### ISSUE TITLE
[Bug] In Alerts Webhook JSON payload "tags" field is always null

### ISSUE THREAD

**Issue by Fiery-Fenix** [grafana/grafana#10046]
- What Grafana version are you using?
Grafana 4.6.2
- What datasource are you using?
InfluxDB 1.3.7
- What OS are you running grafana on?
Ubuntu 16.04.3 LTS
- What did you do?
Create Webhook Notification channel, create chart with proper query including GROUP BY tags, create alert rule in this chart, populate data with tags that triggers alert rule
- What was the expected result?
Tags included in Webhook JSON payload
- What happened instead?
"tags" field is always null

- Details 
InfluxDB request:
```
SELECT sum("errorCount") FROM "jmeter_samples" WHERE ("test_name" = 'Test') AND time >= now() - 30m GROUP BY time(10s), project, test_name fill(0)
```
InfluxDB response (from influx console):
```
name: jmeter_samples
tags: project=test, test_name=Test
time                sum
----                ---
.....data.....
```
Response from Grafana Query Inspector:
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/query",
    "params": {
      "db": "aptp",
      "q": "SELECT sum(\"errorCount\") FROM \"jmeter_samples\" WHERE (\"test_name\" = 'Test') AND time >= now() - 30m GROUP BY time(10s), project, test_name fill(0)",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms"
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "jmeter_samples",
            "tags": {
              "project": "test",
              "test_name": "Test"
            },
            "columns": [
              "time",
              "sum"
            ],
            "values": [....data....]
          }
        ]
      }
    ]
  }
}
```
Grafana Alert Rule:
```
WHEN sum () OF query (A, 5m, now) IS ABOVE 7
```
Grafana Webhook JSON payload:
```
{
  "evalMatches": [
    {
      "value": 10,
      "metric": "errors",
      "tags": null
    }
  ],
  "ruleId": 1,
  "ruleName": "Test",
  "ruleUrl": "https://grafana.host/dashboard/db/dashboard?fullscreen&edit&tab=alert&panelId=1&orgId=1",
  "state": "alerting",
  "title": "[Alerting] Test alert"
}
```

As you can see InfluxDB returns tags, Grafana see that tags, but in JSON I have null. I've tried number of different queries, was trying to rewrite query in different ways, result - tags always null.

**Comment by bergquist** [comment]
Fixed! Available shortly in our nightly builds.

**Comment by josefkorbel** [comment]
@bergquist This is still happening, we just wanted to transition to webhooks but discovered the tags are always empty.
