### ISSUE TITLE
Product Area: Timerange picker takes too much space of dashboard

### ISSUE THREAD

**Issue by tiantangkuohai** [grafana/grafana#103047]
### What happened?

I have some dashboards with quite a few variables in Grafana 11. The timerange picker and variables take too much space of dashboard. 

<img width="1737" alt="Image" src="https://github.com/user-attachments/assets/45acc2ba-aa26-4308-b609-53ae6da08e34" />

### What did you expect to happen?

The variables layout work like old Grafana UI.

### Did this work before?

In old Grafana version, timerange picker and variables are arranged well.

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by yunkaisc** [comment]
+1 to this issue. Now it takes half of the screen to render all the variables in our dashboard.

**Comment by kdilsiz-sc** [comment]
+1 this is one of the biggest customer complaints for our use case as well.

**Comment by yaelleC** [comment]
Fixed by : https://github.com/grafana/grafana/pull/113765

**Comment by kdilsiz-sc** [comment]
When will 12.4.0 be released? We still have this issue on 12.3.0. Thanks.
