### ISSUE TITLE
Nodegraph: Mapping Issue on Variable Change

### ISSUE THREAD

**Issue by iamshreeram** [grafana/grafana#103164]
### What happened?

While working with the NodeGraph plugin to visualize nodes and edges representing service dependencies, I encountered an issue when changing the application details via variables. When I initially load the Grafana panel, the nodes are displayed correctly, and the service mapping is accurate. However, when I modify the variable to select a different application, the nodes continue to display correctly, but the edges become scrambled and do not reflect the proper mapping.

Interestingly, if I completely reload the page after changing the variables, the service mapping displays correctly. This inconsistency suggests there may be an issue with how the plugin processes updates to the variables without a full page refresh.

### What did you expect to happen?

I expected that when changing the application variables, the NodeGraph would automatically update both the nodes and edges to reflect the new data without the need for a full page reload.

### Did this work before?

No

### How do we reproduce it?

1. Load the Grafana panel with the NodeGraph plugin & Datasource as Infinity (Rest API - Backend - JSON ).
2. Select the desired application details using the infinity plugin variables.
3. Observe that the nodes are displayed correctly, and the service mapping is accurate.
4. Change the application variable to a different selection.
5. Notice that the panel loads while the nodes are still correctly displayed, the edges do not reflect the proper mappings and scrambled across.
6. Refresh the entire page, and observe that the nodes and edges are plotted correctly.

Please find the below mapping - 

<img width="171" alt="Image" src="https://github.com/user-attachments/assets/f959f43a-cb45-42dd-a436-df3d6de705dd" />
<img width="140" alt="Image" src="https://github.com/user-attachments/assets/f1160597-72f7-4f25-a175-e13b6f0bff18" />
<img width="177" alt="Image" src="https://github.com/user-attachments/assets/271f0b62-a973-4704-8259-87609b19f07c" />

### Is the bug inside a dashboard panel?

Yes. May be in caching 

### Environment (with versions)?

Grafana: 11.2.2 (Enterprise)
OS: Linux 
Browser: Firefox / Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Infinity 3.2.0

**Comment by ifrost** [comment]
Thanks @iamshreeram for reporting this. Could you please try Grafana 11.6.0? This has likely been fixed by https://github.com/grafana/grafana/pull/100866

**Comment by iamshreeram** [comment]
Hi @ifrost , Thanks for looking into the issue. 

Yes I tested this in 11.6. The issue still persists.  

Thanks

**Comment by ross-paypay** [comment]
I also encounter pretty frequently. The issue is a bit annoying but is resolved by refreshing the page most of the time.

**Comment by ross-paypay** [comment]
I spent some time debugging this. I am far from a React expert, but I think it might be [this](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/nodeGraph/Edge.tsx#L23) `memo` usage.

I can see the `edge` data appears to be in the `NodeGraph` component so it seems likely that there is a memoization issue.

**Comment by ifrost** [comment]
Does it happen only when using Infinity datasource? Could you provide a sample data frame response (from the Query Inspector)?

**Comment by ross-paypay** [comment]
It happens for me when using the Clickhouse datasource. 

I have a reproducible example. (I had to redact some information so hopefully it is still reproducable)

## Before Data

<details><summary>Nodes</summary>

Nodes
```csv
"id","title","nodeRadius","errors","color","icon"
__Start,Start,10,0,green,
service-aRedis,Redis,15,0,#00000000,redis
service-bRedis,Redis,15,0,#00000000,redis
service-c-db,service-c-db,15,0,#00000000,database
other-db,other-db,15,0,#00000000,database
service-c-db,service-c-db,15,0,#00000000,database
service-a,service-a,15,0,#999,
service-b,service-b,15,0,#999,
service-f,service-f,15,0,#999,
service-c,service-c,35,0,#999,
service-d,service-d,15,0,#999,
```


</details> 


<details><summary>Edges</summary>
<p>

```csv
"id","source","target","thickness","errors","color","mainStat","secondarystat"
__Startservice-f,__Start,service-f,3,0,#2563eb,HTTP,
service-bservice-bRedis,service-b,service-bRedis,3,0,#999,Redis,
service-aservice-aRedis,service-a,service-aRedis,3,0,#999,Redis,
service-aother-db,service-a,other-db,3,0,#999,MySQL,
service-cservice-c-db,service-c,service-c-db,3,0,#999,MySQL,
service-cservice-c-db,service-c,service-c-db,3,0,#999,MySQL,
service-fservice-dServer,service-f,service-d,3,0,#2563eb,HTTP,
service-cservice-bClient,service-c,service-b,3,0,#2563eb,HTTP,POST /v1/foo
service-dservice-aClient,service-d,service-a,3,0,#2563eb,HTTP,POST /v2/foo
service-dservice-cClient,service-d,service-c,3,0,#2563eb,HTTP,GET /v1/bar
service-fservice-aServer,service-f,service-a,3,0,#2563eb,HTTP,
```

</p>
</details> 


## After Data

<details><summary>Nodes</summary>

```csv
"id","title","nodeRadius","errors","color","icon"
__Start,Start,10,0,green,
service-aRedis,Redis,15,0,#00000000,redis
service-bRedis,Redis,15,0,#00000000,redis
service-a,service-a,15,0,#999,
service-b,service-b,15,0,#999,
service-e,service-e,15,0,#999,
service-f,service-f,15,0,#999,
service-c,service-c,15,0,#999,
service-d,service-d,15,0,#999,
service-c-db,service-c-db,15,0,#00000000,database
service-c-db,service-c-db,15,0,#00000000,database
```

</details> 

<details><summary>Edges</summary>

```csv
"id","source","target","thickness","errors","color","mainStat","secondarystat"
__Startservice-f,__Start,service-f,3,0,#2563eb,HTTP,
service-bservice-bRedis,service-b,service-bRedis,3,0,#999,Redis,
service-aservice-aRedis,service-a,service-aRedis,3,0,#999,Redis,
service-cservice-c-db,service-c,service-c-db,3,0,#999,MySQL,
service-cservice-c-db,service-c,service-c-db,3,0,#999,MySQL,
service-fservice-dServer,service-f,service-d,3,0,#2563eb,HTTP,
service-dservice-eClient,service-d,service-e,3,0,#2563eb,HTTP,
service-eservice-cClient,service-e,service-c,3,0,#2563eb,HTTP,
service-eservice-bClient,service-e,service-b,3,0,#2563eb,HTTP,POST /v1/foo
service-fservice-aServer,service-f,service-a,3,0,#2563eb,HTTP,
```

</details>
