### ISSUE TITLE
Allow custom mapping of template variable value -> display text

### ISSUE THREAD

**Issue by mbell697** [grafana/grafana#1032]
Use Case: You may store metrics based on an 'ID' property but wish to have the template variable selection UI use a more human friendly label. e.g. You track metrics by domain with an internal domain ID but wish to use the domain's URL in the template variable selector UI. 

@torkelo I can take a cut at implementing this, what are your thoughts on implementation? For my specific use case I would want to be able to provide an arbitrary JS function to perform the value -> text conversion as I need to hit an external service for the lookup. I was thinking an initial implementation could be adding a config value in the dashboard JSON that defines the mapping function. UI support could be added later to handle more trivial mappings with pre built mapping functions (e.g. regex substitutions). 

Also connected to this would be the ability to edit the full dashboard JSON via the UI, although export -> edit -> import would function as a workaround if this proves to be difficult.

**Comment by Iker-Jimenez** [comment]
I too could use at least a simpler version of this. Something like a configured mapping from A -> B

In my scenario I want to select an entity name in the variable dropdown (CustomerName1, CustomerName2, etc.) but use a numeric id internally when it comes to the metric name.
app.requests.$customer1_ID.count

**Comment by timgriffiths** [comment]
+1

**Comment by Krinkle** [comment]
Merging from #3138

> E.g. when creating a custom template variable with values `fooBar` and `baz_quuxInternal`, to be able to have the UI display the checkboxes as "Foo bar" and "Baz".
>
> This is especially common when using repeated rows and a custom variable to reduce duplication, but the top level metrics may not be user-friendly.
>
> One could potentially support this for queried template values (e.g. graphite properties) as well by using a regex (if the replacement is generic). Regex support already exists, but it applies to both the value used and the label. Having it used for the value only would be valuable.
>
> For example, if a graphite query expands `kafka.messagesByTopic.myservice_*` for use in templates, then one may want the user interface to strip the prefix. But when used in the actual panels, the prefix should be included. This can be worked around (in Grafana 2.x and later) now that template variables can be embedded in a metric property, so one could hardcode the prefix in all metrics in all panels and rows, but that's better to avoid.
>
> Once these "label" values exist, it would be useful to be able to access them inside the panels as well. Such when embedding a variable in a Row and/or Panel title. Either we can make it use the label by default (if embedded in a title field), or perhaps with some alternate syntax (e.g. `$$Variable`, or some whatever)

**Comment by bluecmd** [comment]
http://play.grafana.org/dashboard/db/test?editview=templating shows "Variable Label" as an option. Can this be closed?

**Comment by torkelo** [comment]
that is just an option to have a friendly name for the variable, not the variable values

**Comment by malnor** [comment]
+1

**Comment by rjromay** [comment]
+1

**Comment by m4dc4p** [comment]
+1

**Comment by aalleexxeeii** [comment]
+1

**Comment by tboeghk** [comment]
+1

**Comment by GautamGupta** [comment]
+1

**Comment by sbarale** [comment]
What's the status of this ?
Is it possible to do so ?

**Comment by cosmos78** [comment]
Is this possible for the 3.0 final ?
It looks like a feature many people are waiting for. Including me :-)

**Comment by musskopf** [comment]
+1
I normally use part of regular expressions which looks awful for users.

**Comment by redredgroovy** [comment]
+1

**Comment by McStork** [comment]
+1

**Comment by srpatatas** [comment]
+1

**Comment by inbilla** [comment]
+1

**Comment by vincenzomos** [comment]
+1

**Comment by blak3r2** [comment]
+1

**Comment by Daaru00** [comment]
+1

**Comment by lucadistefano** [comment]
+1

**Comment by rasjoy** [comment]
+1

**Comment by ihard** [comment]
+1

**Comment by moises-silva** [comment]
@mbell697 @torkelo 

I've implemented this for an internal service that uses Grafana. As we use uuids for hosts (so a change in hostname does not lose metrics history and a number of other things), it was unacceptable to show those uuids to the user. I did a specific patch for our use case where we detect uuid values and translate them using an http endpoint of our application. That is working well for us but I'd prefer doing something that is generic and accepted upstream.

Would it be acceptable to add a 'variable_translation_url' option that points to a url that can perform the mapping? (with an optional authorization token if needed) or a variable_translation_script that points to javascript src that can be downloaded and hook into templateValuesSrv.js at the points where translation is required (if that option is set) ?

**Comment by ZhuWanShan** [comment]
Can you share you templateValuesSrv.js code? I want try it.

**Comment by moises-silva** [comment]
@ZhuWanShan This is basically it:

https://github.com/sangoma/grafana/commit/fa109c23bc92c3121173579afbd87a04d7e2f523

Note you'll see 2 approaches there. The first was meant to be more general, introducing a new template variable type 'http', with a 'query' property that points to an HTTP url to perform the mapping (see _getHttpVariableOptions). Later I implemented a second method that detects if an option text (display value) matches a UUID regex, and forces mapping of whatever variable is that using a hard-coded HTTP call to /api/v1/nodes/grafana-hosts/ that returns the mapping of all the options. That has worked well so far, just need to have direction as of how to convert this into a generic method.

**Comment by meverett** [comment]
+1

**Comment by linar-jether** [comment]
+1

**Comment by meverett** [comment]
For anyone who is interested I was able to solve my particular use case by using the [Simple JSON Datasource](https://github.com/grafana/simple-json-datasource) plugin.

That said the plugin doesn't presently support template variable queries but I've submitted a [pull request](https://github.com/grafana/simple-json-datasource/pull/36) that fixes the issue.

I also added support to the plugin so that your HTTP endpoint used by Simple JSON Datasource can either just return a list of values or it can return a list of nested text/value objects which allows you to perform a custom alias look up for user-friendly template variable labels while still preserving the underlying raw value.

This may not work in all template variable aliasing scenarios, and it would be great if Grafana supported this natively, but this does allow you to use your own HTTP endpoint to query your own template variables. This includes passing other template variable values to your own HTTP endpoint so that you can do whatever custom processing/mapping/translation/aliasing you'd like and then return the results to Grafana as a template variable query result.

**Comment by peterfisher** [comment]
I am human.

+1

**Comment by daalwr** [comment]
+1

**Comment by mbraeger** [comment]
+1

**Comment by cattt84** [comment]
+1

**Comment by lghamie** [comment]
+1

**Comment by hzhaop** [comment]
+1

**Comment by wokr** [comment]
+1

**Comment by Celibat1** [comment]
+1

**Comment by tereska** [comment]
+2

**Comment by JonathanThorpe** [comment]
Would be immensely useful to have this. In effect, I have a bunch of objects that have both a name and a uuid. I'd like to display the name, but store the uuid in the variable.

It would be great if we could do something like have:

Query (existing): SHOW TAG VALUES FROM "vcd_vm" WITH KEY = "uuid" where "OrgVdc" =~ /^$vDC$/)

Label (new): SHOW TAG VALUES FROM "vcd_vm" WITH KEY = "name" where "uuid" =~ /^$tag$/)

**Comment by 0x62ash** [comment]
+1

**Comment by mahdianpeyman** [comment]
+1

**Comment by rkalicinski** [comment]
+1

**Comment by acky6012** [comment]
+1

**Comment by vaibhavinbayarea** [comment]
+1

**Comment by sdreep** [comment]
+1

**Comment by scharissis** [comment]
+1

Would be great if the 'Custom' template variable took as input both a list of 'values' and a list of 'labels' (essentially, a custom hash/dict)

**Comment by gabrielmocan** [comment]
+1

**Comment by satyashanmuka** [comment]
+1

**Comment by vacri** [comment]
This would be useful for AWS CloudFront data, as exported by the official cloudwatch exporter. Data for CloudFront is displayed by IDs, which no human uses. Much easier for humans looking at graphs to see "foo.example.com; bar.example.com" instead of "EAUUWLGUQEPFWV; EVWWU9PGWIB"...

**Comment by miton18** [comment]
+1

**Comment by svet-b** [comment]
First off, thank you for developing an awesome product and sharing it with the world!

Any indication on what the likelihood is of this being implemented in the coming months? I'm just trying to weigh up to what extent it makes sense to go ahead and implement @meverett's suggested workaround or wait for this.

Implementing this via an HTTP endpoint is a neat solution to a highly generalized version of this problem, but seems like overkill for many of the use cases described here (including mine) where all that's needed is basic static mapping on a modest number of "friendly display name" -> "not friendly database name" pairs.

**Comment by moises-silva** [comment]
@svet-b fwiw, we moved to use @meverett's suggestion and it was painless and clean. Just a few hours to build the datasource plugin.

**Comment by prasanth-thangachi** [comment]
+1

**Comment by anitakrueger** [comment]
+1

**Comment by TommiKetola** [comment]
+1

**Comment by wp3xpp** [comment]
+1

**Comment by jaune-rouge** [comment]
+1

**Comment by feiyuw** [comment]
+1

**Comment by iShift** [comment]
+1

**Comment by sspetebr** [comment]
+1

**Comment by northtree** [comment]
+1

**Comment by royemmerich** [comment]
@meverett thanks very much for adding the template variable mapping feature as discussed here:

https://github.com/grafana/grafana/issues/1032#issuecomment-265263943

I'm just struggling to come up with the correct config settings in my template variable. I'd really appreciate a few tips.

**Comment by Xokker** [comment]
+1

**Comment by sevencastles** [comment]
+1

**Comment by wicol** [comment]
@meverett's workaround works pretty good, but falls short when used with multi value variables because the series can only be labeled with tags from (in my case) influxdb. Any suggestions for workarounds there? :)

**Comment by mcortinas** [comment]
+1

**Comment by bluefish6** [comment]
+1

**Comment by mkue** [comment]
+1

**Comment by Ni-k0** [comment]
+1

**Comment by langerma** [comment]
+1

**Comment by meverett** [comment]
Hey all, since this issue gets bumped pretty regularly I decided to throw together an example Node.js web application that [uses my solution above](https://github.com/grafana/grafana/issues/1032#issuecomment-265263943).

It's pretty basic, but it fully implements the pattern I mention in my original comment. And if you can get by with putting your look-up data into a single JSON file that wouldn't get updated very often, it might just work out-of-box for you.

Otherwise you can use it as a starting point and extend it to access your aliasing data from whatever source you'd like (programmed by you of course) and serve it up through the app in such a way that the SimpleJson datasource plugin can consume it and it can be used to drive template variable aliasing/mapping.

The repository for the example web app is [here](https://github.com/CymaticLabs/GrafanaSimpleJsonValueMapper).

Hope it helps. I've had some requests from time to time asking for more help/explanation setting up the solution.

Cheers

**Comment by inselbuch** [comment]
+1

**Comment by lotysh** [comment]
+1

**Comment by shirakaba** [comment]
Thanks for your makeshift solution, @meverett . I've made a repository with Dockerfile for creating a Docker container to run your solution. It is set up to take a custom `data.json` from alongside the Dockerfile upon build. Hope it helps people:

https://github.com/shirakaba/GrafanaSimpleJsonValueMapper-docker

**Comment by chalene** [comment]
＋1

**Comment by oplehto** [comment]
+1

**Comment by cfstras** [comment]
When you want to +1 this, please keep in mind you will annoy the 74 people that are currently subscribed to this issue and are hoping for someone to step forward and implement a fix.
GitHub added reactions for a reason...

**Comment by sanchomuzax** [comment]
+1

**Comment by nayeemnayyu** [comment]
+1

**Comment by seattle** [comment]
+1

**Comment by YeisonMelo** [comment]
add this woud be great! a have a list of long numeric values but should be much better to show a label human friendly for each one than the value itsef
vairable: myListOfLongs {name: toyota value: 122321312332, name: renault value: 6666666}

**Comment by vl-80** [comment]
+1

**Comment by YeisonMelo** [comment]
+1!

**Comment by darkstar939** [comment]
+1

**Comment by tecmatia-dp** [comment]
+1

**Comment by duxiaofeng-github** [comment]
+111111

**Comment by fjarrett** [comment]
+1

**Comment by wlay** [comment]
+1

**Comment by wolfhong** [comment]
+1, Very much in need of this feature.

**Comment by serggp** [comment]
+1

**Comment by davidohana** [comment]
+1

**Comment by progan** [comment]
+1

**Comment by johnymachine** [comment]
This works for MySql and PostgreSQL:

Another option is a query that can create a key/value variable. The query should return two columns that are named __text and __value. The __text column value should be unique (if it is not unique then the first value is used). The options in the dropdown will have a text and value that allows you to have a friendly name as text and an id as the value. An example query with hostname as the text and id as the value:

`SELECT hostname AS __text, id AS __value FROM my_host`

http://docs.grafana.org/features/datasources/mysql/#query-variable

I would suggest custom variable to be:

```
[{
		"__text": "Server 1",
		"__value": 1
	},
	{
		"__text": "Server 2",
		"__value": 2
	}
]
```

Maybe new type called JSON?

**Comment by MGinshe** [comment]
Thanks @johnymachine! That worked beautifully with the PostgreSQL datasource.

As an extension of this, is there any way to retrieve the `__text` section of the variable? This would be really useful for repeating graphs.

**Comment by johnymachine** [comment]
Hey @MGinshe, this works fine (displays text uses value) for me:

![image](https://user-images.githubusercontent.com/2737699/43568114-11d7b3d6-9634-11e8-94df-61f26fa595a5.png)

**Comment by psarossy** [comment]
@torkelo @nmaniwa

https://github.com/grafana/grafana/pull/12609 seems to implement what most people are asking for here, any reason why that is closed and never got merged?

**Comment by torkelo** [comment]
No, that issue is about something totally different, or did you link to wrong issue?

**Comment by hiddenrebel** [comment]
@dmayan it was answered. You can use this.

> This works for MySql and PostgreSQL:
> 
> Another option is a query that can create a key/value variable. The query should return two columns that are named __text and __value. The __text column value should be unique (if it is not unique then the first value is used). The options in the dropdown will have a text and value that allows you to have a friendly name as text and an id as the value. An example query with hostname as the text and id as the value:
> 
> `SELECT hostname AS __text, id AS __value FROM my_host`
> 
> http://docs.grafana.org/features/datasources/mysql/#query-variable
> 
> I would suggest custom variable to be:
> 
> ```
> [{
> 		"__text": "Server 1",
> 		"__value": 1
> 	},
> 	{
> 		"__text": "Server 2",
> 		"__value": 2
> 	}
> ]
> ```
> Maybe new type called JSON?

**Comment by dmayan** [comment]
I don't use MySQL nor PostgreSQL. This should be a Grafana feature. Not
some sort of hack.

Thanks!

**Comment by wfhu** [comment]
pretty useful feature, If this feature is out there, It could help us a lot here. Because graphite can not store Chinese character. So we have to use English in Graphite, but we would really like to show the Chinese in the grafana dashboard, so the user experience would be much better.

Hope this feature will come true shortly.

**Comment by FdeFabricio** [comment]
I managed to do the ID->name mapping by using two variables. The first variable lists all possible IDs (value) while the second variable lists the name (display text) that matches the ID. It's not the ideal or pretty, but it does the trick.

I reckon it's called [nested variables](http://docs.grafana.org/features/datasources/influxdb/#query-variable).

![](https://user-images.githubusercontent.com/1853854/46375047-b4fa4880-c668-11e8-9a37-3eee41d6af8e.png)

**Comment by CME64** [comment]
> I managed to do the ID->name mapping by using two variables. The first variable lists all possible IDs (value) while the second variable lists the name (display text) that matches the ID. It's not the ideal or pretty, but it does the trick.
> 
> I reckon it's called [nested variables](http://docs.grafana.org/features/datasources/influxdb/#query-variable). And then you can hide one of the variable selectors.
> 
> ![](https://user-images.githubusercontent.com/1853854/46375047-b4fa4880-c668-11e8-9a37-3eee41d6af8e.png)

how did you do it?

**Comment by mixvin** [comment]
+1

**Comment by bassie1995** [comment]
@FdeFabricio You used InfluxDB? Does it automatically update one value when changing the other? How do you do that?

**Comment by FdeFabricio** [comment]
@bassie1995 
> You used InfluxDB?

Yes

>Does it automatically update one value when changing the other?

Yes

> If so, how do you do that?

You create a query type variable that selects the item that matches the already selected value (e.g. `SELECT "name" FROM playlists WHERE ("id" =~ /^$playlist_id$/)`. So now you will have two variables: one with the ID and other with the name.

**Comment by MGinshe** [comment]
@bassie1995 @FdeFabricio You could also do this in reverse:

- A visible variable, which lets you select the playlist name (i.e. Girl Power)
- A hidden variable, which finds the playlist ID from the name (something like `SELECT "id" FROM playlists WHERE ("name" =~ /^$playlist_name$/)`)


This way, your users see an option to select the playlist by its name, but the playlist ID is hidden. You can still access the playlist ID programatically, in order to search for playlist items, etc.


The `__name` and `__value` syntax from the PostgreSQL/MySQL datasource is still ideal though, as it prevents any id->name ambiguity, and reduces the number of database queries required. It should be a base feature IMO.

**Comment by MikeKulls2** [comment]
Using the second variable as in the Girl Power example above only has a very limited use. I can't use it for repeated graphs and it's of no use when multi-select is enabled.

How on earth is this still not an option?? This was raised back in 2014 and IMO is a very basic must have feature. Are there actually plans to add it?

**Comment by thinrope** [comment]
I was just fiddling with that issue and found a somewhat hackinsh workaround...
I needed a hash, that in Perl notation is written as:
````Perl
 %units = (
    'μSv/h' => 1.0,
    'mrem/h' => 0.1 );
````
I created a dashboard variable `Type`:`Custom`,  `Values separated by comma`:`mrem/h, μSv/h` and then edited the `JSON Model` like that:
````JSON
      {
        "allValue": null,
        "current": {
          "tags": [],
          "text": "mrem/h",
          "value": "0.1"
        },
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "units",
        "options": [
          {
            "selected": true,
            "text": "mrem/h",
            "value": "0.1"
          },
          {
            "selected": false,
            "text": "μSv/h",
            "value": "1.0"
          }
        ],
        "query": "mrem/h, μSv/h",
        "skipUrlSync": false,
        "type": "custom"
      }
````

While this does work (for some time), editing the dashboard via the GUI changes it back to non-working state :-|

**Comment by mbell697** [comment]
Another option for working around this if you have another system that can provide the data:

Use a JSON datasource plugin, I'm using: https://grafana.com/plugins/simpod-json-datasource

Implement only the `/` health-check endpoint and the `/search` endpoint in some system that has the needed data. The `/search` endpoint should return JSON that looks like: `[{ "text": "A Human Name", "value": "123456" }, ...]`. The `text` property will be what appears in the variable select drop down and the `value` will be what is used in the metrics query.

Then setup your dashboard variable to query against this new datasource, it's kinda hacky but you can use the `target` field for the datasource to tell the backend what it should return if you have multiple datasets you want to use this with.

**Comment by Sembiance** [comment]
> Then setup your dashboard variable to query against this new datasource, it's kinda hacky but you can use the `target` field for the datasource to tell the backend what it should return if you have multiple datasets you want to use this with.

Could you elaborate on how you set up the variable to query the datasource? I specify a variable type of `Query` and select the data source, but it actually wants a Query and whatever I put in there (empty or even `{}`) just gives an error `Template variables could not be initialized: undefined` so not sure how to get the data from the JSON data source into a dashboard variable.

**Comment by KorkyPlunger** [comment]
+1 on this. I would really like a way to do this, but one that was not backend-dependent (we use graphite).

**Comment by BlackRider97** [comment]
+1 any working solution ?

**Comment by MGinshe** [comment]
@BlackRider97 Please have a look through the comments above - there are several working solutions for PostgreSQL (and probably MySQL, MSSQL, etc).

Solution 1: https://github.com/grafana/grafana/issues/1032#issuecomment-409124505

Solution 2: https://github.com/grafana/grafana/issues/1032#issuecomment-453242766

**Comment by wildekek** [comment]
Implementing the workaround from @thinrope properly would be a really elegant fix imho.
If we could use JSON in a custom variable, or have a variable type "JSON", we could solve this without hacks and I don't see any drawbacks.

**Comment by jlarmstrong** [comment]
+1 any update on this?

**Comment by siegmund42** [comment]
+1

**Comment by yvbondarenko** [comment]
+1

**Comment by couloum** [comment]
This is definitly a must have feature.
I use variables to filter some hosts using regex on hostname. As my servers cotains patterns in hostname, I can have a regex to get the list of all servers of a given group. Instead of showing a ugly regexp, I would like to display a pretty name, like "Servers of group A" as label of the dropdown menu.

The way to enter this in custom value could be as simple as:
`label1:value1, value2, label3:value3, label5:value5`

The label would be optional. If a `:` is present in string, then everything before `:` is the label and everything after is the value.
We should have a way to escape `:` if we need it in label name or value, as we can do for `,` character.

**Comment by mato-s** [comment]
> Another option for working around this if you have another system that can provide the data:
> 
> Use a JSON datasource plugin, I'm using: https://grafana.com/plugins/simpod-json-datasource
> 
> Implement only the `/` health-check endpoint and the `/search` endpoint in some system that has the needed data. The `/search` endpoint should return JSON that looks like: `[{ "text": "A Human Name", "value": "123456" }, ...]`. The `text` property will be what appears in the variable select drop down and the `value` will be what is used in the metrics query.
> 
> Then setup your dashboard variable to query against this new datasource, it's kinda hacky but you can use the `target` field for the datasource to tell the backend what it should return if you have multiple datasets you want to use this with.

I did this implementation and it works for me, but I'm stucked at the labeling the trend (legend)... I get either id (number) or not defined or some other non-sense.
Can you advise?

M

**Comment by giorgiofanecco** [comment]
+1

**Comment by BBQigniter** [comment]
I am also using now the described JSON-hack by @mbell697 in my company's Grafana. But there seems a strange regex problem IMHO.

I set up a small python flask app which is providing me the needed groups for Graphite queries my search data looks like

```
@app.route('/search', methods=['POST'])
def search():
    data = [
        {"text": "fs-servers", "value": "{FS-server-1,FS-server-2,FS-server-3}"},
        {"text": "db-a-servers", "value": "{db-server-1,}"},
        {"text": "db-b-servers", "value": "{db-server-2,db-server-3}"}
    ]
    return jsonify(data)
```
So in the dashboard I created a query variable called "group" using the json-source and then tried to filter for the "fs-servers" group with the regex-field by using `/fs-.*/` - but this is not working as expected - after fiddling around I recognized that the regex is somehow applied to the "value"- and not to the "text"-field. Has anybody maybe some workaround or an idea?

**Comment by alexvaut** [comment]
+1

**Comment by maplewf** [comment]
+1

**Comment by shalstea** [comment]
My take on the requirements for this:

In our case I think of two variants of the same thing. What we would want is essentially alias'es. In both cases, the dashboard owner wants to provide the user with a template variable list that is easy for the end-user to understand. However the value used in the query is the underlying value.

Example 1 - simple one to one name conversions. So in this case we have numeric country codes published as metric values. But know one memorizes the numeric codes. So we want to display "US" or "Canada"

{ "US" == "01" }
{ "Canada" == "02" }

If "Canada" is selected the template variable value passed to any query is "02"

Example 2 - is a one to many mapping. Internally we have stages for deployment, e.g. s0, s1, s2, s3, s4. However end-users may use this as "dev, beta, prod"
So they want to map them as:

{ "dev" == ["s1"] }
{ "beta" == ["s2", "s3"] }
{ "prod" == ["s4", "s5", "s6"] }  or better yet "prod" == s[456]

So if "prod" is selected "s4,s5,s6" is passed to the query

From a query perspective (taking Example 2) where the variable name is stageVar
and the metric tag name is stage:

We don't see so much the need for aliasBy() like calls but more things like:
stage=~${stageVar.value:regex}
alias($stageVar.label)

To filter results by the selected template variable values. It is certainly possible that someone might try and use it in something like an aliasBy() function but if it is a syntax error that is fine. I wouldn't expect you to magically fix a conversion of an array passed to a function that expects a single value.

As for the mappings I think having the user statically define those is sufficient.
Ideally you would have a query to MT to get the list of values that need to be mapped, for you, e.g. "01", "02", "03" and then you would have an easy to add the mappings / aliases. Unmapped values would go into a "default" bucket.

**Comment by ChrisGute** [comment]
+1

**Comment by xuyixin1996** [comment]
+1

**Comment by johnhtodd** [comment]
I'm very surprised this hasn't been included - I spent quite a bit of time trying to figure out how do this "obvious" thing and eventually found my way here to discover it doesn't exist.

The ability to dynamically re-write as described by some above would be fantastic. However, I'd even be happy with a short-term hack (or permanent "easy" model) that is an extended version of the "Custom" field, that statically mapped choices to single or multiple choice results.

Our example is country codes. We often wish to view clusters of systems based on geographic regions, but not by country. But we only store country codes as keys in our Prometheus server. So right now, if I want to view all systems in North America, I have to select US, CA, MX manually from a Query-based list of options out of nearly 100 countries. I can't even tell you how much time I spend selecting every country in Europe, or Asia, or Africa to do analysis. It's almost worth setting up entirely different dashboards for each region, which is absurd but is the only way to solve the problem short of hard-coding graphs. Making an entirely new database with mappings and then doing hidden queries seems also to be very, very far from ideal.

My fever dream:
It would seem that this would be a "Custom List" option as a possible new type of Variable. The Custom List would start empty if selected, but would look very much like the "Custom" model looks today.  An "Add" button would appear. Clicking "Add" would create a two-field input array with "Display Value:" and "Search Value:" where each could be filled in. The "Display Value" would be whatever the user wanted to show in the picklist - in our case, "North America". Then the "Search Value" would be what would be presented in the query - again, in this example for North America it would be "us,ca,mx".  At any time, a "delete" icon (trash can?) would remote individual lines. Clicking the "Add" button again would create a new pairing, until the user had completed their list of options. The "Multi-Value" and "Select all" options would remain, similar to the existing Custom model.

**Comment by MikeKulls2** [comment]
> 
> 
> I'm very surprised this hasn't been included - I spent quite a bit of time trying to figure out how do this "obvious" thing and eventually found my way here to discover it doesn't exist.

I have solved this by creating a MySQL database, I create a table with the items I want in the dropdown, eg Europe, North America etc. In a second field I have a regex that will match the entries I want to match. Then add the MySQL as a datasource and use them to create the variables. It is a hack but actually works quite well. I use it for pretty much the exact thing you are trying to do.

**Comment by johnhtodd** [comment]
I appreciate the clever hack, but for us it's not really a solution. Setting up an entirely new database (we don't use MySQL at all, which means operationally this is impossible) to perform a simple key/value substitution that is quite static seems like a lot of hoops to jump through. 

I was thinking about this a bit more, and there is an even more elegant way of providing this functionality than what I describe above.  I'd call it a "variable macro".  This again looks like a Custom list, except it allows the administrator to specify that when one (or more) of these macros are selected, then the Variables named will be set, and the Values given will be appended to the existing set of values.  This would entirely be a UI-driven model, and would not change the actual variable concept at all - it would just create an auto-completion sugar layer on top of the existing variables.  This makes it backwards-compatible with no additional variables needed for creation or integration into queries.

A macro that sets the variables would allow the user to see the values as they're being selected, and then would allow the user to open up each variable and see/manipulate the selections or data instead of creating a separate variable as my previous comments imply.  This would be much more intuitive.

Example:

So a variable macro called "North America - Primary Cluster" would set my "Country" variables to "us,ca,mx" and would set my "Cluster:" variable to "primary".  Those settings would be visible if I were to pull down each named variable (or not, if they're hidden) so I could add or subtract countries to the Country: list as long as I didn't touch the Macro variable pulldown again. 

Possibly there is a boolean of "clear named variables before setting" so that if a change is made in the picklist for this Macro, then any other settings of the variables specified would be cleared. This could be useful for lists where it's not obvious that you might include something that was previously set.  I suppose that if more than one Variable Macro option were chosen, then the last one in the list to be examined "wins" if there are competing settings of a particular value; no way around that problem.  (it's arguable that this clearing action should be specified on a variable-by-variable basis, but that seems to sound a little cluttered... but is it?)

Here's my hypothetical example again, where I have pre-existing variables of "Country" and "Cluster".

Variable Macro Name: Region

Name1: North America - Primary Cluster
 Clear Named variables before setting: Y
  Variable1: Country
  Value1: us,ca,mx
  Variable2: Cluster
  Value2: primary
  
Name2: Nordics - Secondary Cluster
 Clear Named variables before setting: Y
  Variable1: Country
  Value1: se,fi,no,dk,is
  Variable2: Cluster
  Value2: secondary

**Comment by MikeKulls2** [comment]
> I appreciate the clever hack, but for us it's not really a solution. Setting up an entirely new database (we don't use MySQL at all, which means operationally this is impossible) to perform a simple key/value substitution that is quite static seems like a lot of hoops to jump through.

I was expecting you would say something like this. The reality is you asked for a hack and this hack does solve the problem, it's not difficult to setup and it's not difficult to reverse in the future. I actually find it quite handy having the MySQL there as we keep adding new data sets to it, it's a convenient place to keep track and update them. If you think about it, if you're going to use these data sets in multiple dashboards and want to have them maintained centrally, then they need to be stored somewhere. If your time series database can't store them then you need something setup to store them. So it actually makes perfect sense to have MySQL. The added bonus is its also very easy to automate the population of MySQL.

**Comment by GlennMatthys** [comment]
If you have PostgreSQL, you don't need to create an actual table for the mapping, you can do something like:

```
SELECT *
FROM
(
	VALUES
		('London server 1', 'london_srv_1'),
		('London server 2', 'london_srv_2'),
		('New York server 1', 'ny_srv_1'),
		('New York server 2', 'ny_srv_2')
) AS t (__text, __value)
```

**Comment by crodriguez-cl** [comment]
But it doesn't work with numeric values:

SELECT * FROM (  VALUES ( 'OK', '0'), ( 'ERROR', '1') ) AS t (__text, __value)

When loading dashboard:

![imagen](https://user-images.githubusercontent.com/69485893/89835558-014f2300-db33-11ea-9f31-2aa644107e36.png)

And when selecting another parameter

![imagen](https://user-images.githubusercontent.com/69485893/89835637-19bf3d80-db33-11ea-875e-3126be75a864.png)

When selecting: OK + ERROR

![imagen](https://user-images.githubusercontent.com/69485893/89835728-483d1880-db33-11ea-902d-8ee25609ecab.png)

**Comment by GlennMatthys** [comment]
If you want numeric values you need to remove the single quotes, otherwise it is interpreted as text, ie

`SELECT * FROM ( VALUES ( 'OK', 0), ( 'ERROR', 1) ) AS t (__text, __value)`

**Comment by crodriguez-cl** [comment]
Thanks @GlennMatthys  glenn for the answer, but i already found where the problem occurs.

SELECT * FROM ( VALUES ( 'OK', 0),  ( 'Warning', 1),  ('Critical', 2) ) AS t (__text, __value)

Configuring Multi-value on:

![imagen](https://user-images.githubusercontent.com/69485893/89901310-ecb26f80-dbb2-11ea-87c9-f237be368982.png)

It happens  
![imagen](https://user-images.githubusercontent.com/69485893/89901883-be815f80-dbb3-11ea-8527-7f0751ebe3a4.png)

Selecting 3 states
![imagen](https://user-images.githubusercontent.com/69485893/89901984-dfe24b80-dbb3-11ea-9047-2ae18781eb11.png)

And Multi-value off:

![imagen](https://user-images.githubusercontent.com/69485893/89901782-9abe1980-dbb3-11ea-8738-db1c52862321.png)

**Comment by fitovic** [comment]
GlennMatthys  - your solution is perfect,  many thanks

**Comment by BasvanH** [comment]
For MySQL its:
`SELECT *  FROM ( VALUES row('a', 1), row('b', 2) ) AS t (__text, __value)`

**Comment by radoeka** [comment]
What about Mariadb?  It is not working for me (mariaDB version: 10.5.5)

```
SELECT * FROM ( VALUES row('a', 1), row('b', 2) ) AS t (__text, __value);
ERROR 1064 (42000)..............
```
Or the one before:

```
SELECT * FROM ( VALUES ( 'OK', 0), ( 'Warning', 1), ('Critical', 2) ) AS t (__text, __value);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your 
MariaDB server version for the right syntax to use near '(__text, __value)' at line 1
```

It looks like the Values statement is no longer available...

Or is there something else that I do wrong?

**Comment by GlennMatthys** [comment]
@radoeka For older MariaDB/MySQL

```
SELECT * FROM
(
    SELECT 'London server 1' AS '__text', 'london_srv_1' AS '__value'
    UNION ALL SELECT 'London server 2', 'london_srv_2'
    UNION ALL SELECT 'New York server 1', 'ny_srv_1'
    UNION ALL SELECT 'New York server 2', 'ny_srv_2'
) AS t;
```

**Comment by radoeka** [comment]
@GlennMatthys wow wow wow, what a swift response!  And this works.  
I thought that I was running a rather new version of mariadb, but that is not case (using a linux distribution that is only 2 months old).
Thanks.

**Comment by nickdelnano** [comment]
This seems to not be supported for Prometheus.

**Comment by hugohaggmark** [comment]
Reopening this issue as #27829 only solves this for static data.

**Comment by McPo** [comment]
## Requirements
- Given an ID I wish to display it as a friendly name to the end user
- It must work on all panel types (A Log Panel was used during experimentation)
- The ID may originate from anywhere (ie. We cant rely on having the user select a Dashboard variable with Name->ID mapping)
- The Name may come from any datasource (In my case MYSQL)

Heres how I solved this issue. Gonna list the "Journey" as different solutions might be useful to different people (and hopefully someone can improve on them).

### Attempt #1

#### Problem #1
- Given two CSV lists (ie. `id1,id2,id3` `name1,name2,name3`). Which may originate from Dashboard Variables (ie. `{myids:csv}` `{mynames:csv}`))
- Using https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/ and https://grafana.com/docs/loki/latest/logql/template_functions/#replace-string
- Replace the ids in the id csv with their corresponding names

#### Solution to #1
- We have limited template functions, however if we managed to merge the two lists into a single key-value string we could use regex. (ie. `id1=name1;id2=name2;id3=name3`)
- If we had the above format we could do `{{ regexReplaceAllLiteral \";.*\" (regexReplaceAllLiteral \".*${myids:regex}:\" \"${key_value_string}\" \"\") \"\" }}"`
- It removes everything up to the id (and colon), then removes everything after the semi-colon. This can then be passed to `line_format`.

#### Problem #2
I want to use a datasource to get my key value pairings. so how will I generate the `id1=name1;id2=name2;id3=name3` string?

#### Solution #2
- We could use a Query Dashboard Variable to pull the required information from the DB.
- We could then hide this variable so it isnt shown on the dashboard.
- However the query will return on multiple rows i.e
```
    id1=name
    id2=name
    id3=name
```   
- And we would not be able to access any of the other pairing apart from the first one
- The solution to this is to use `CONCAT` AND `GROUP_CONCAT` i.e
```
SELECT
    GROUP_CONCAT(CONCAT_WS(':', id, name) SEPARATOR ';' )
FROM soloportal_device;
```
- We will have now generated the key-value string into a single row/option, which can be fed into the above regex. However theres a few "edge" cases that need solved

#### Problem #3
- `GROUP_CONCAT` has limited column width, as such the key-value string may be truncated

#### Solution #3
- A quick solution to this (So we can run into the next roadblock quicker) is to create a new hidden Query Dashboard Variable, place it above the key-value query and execute the following query
`SET SESSION group_concat_max_len = ~0`

#### Problem #4
- If the key-value string is too large, you will hit a 414 HTTP error when returning to the Dashboard. This is due to the Query Variable values being added to the URL

#### Solution #4
- Here you might wish to filter the key-value pair to only return the mappings you need depending on the context
- I didn't want to do that
- Another option is to place the key-value string into `__name` and use `{$key_value_string:text}` instead, this way it wont be passed within the URL

_(I only discovered the text filter while writing this issue, for some reason I kept skipping over it in the docs despite looking for it)_

#### Problem #5
- If you clicked "Explore" on the panel, the Explore page would open with a very large regex in the query which isnt ideal

#### Solution #5
- I didn't like the fact we were using Loki to process the Regex, As such (and for all the nasty hackiness so far) I decided it was time to rethink my approach.

### Attempt #2
- Ideally this feature would run after everything else and would simply replace the values within the DOM itself.
- If it worked as such, then we could use all the existing panels (No need to extend each one), we would not have large queries being fed into the datasources, and datasources would not have to implement their own solution.
- As such the only option was JavaScript.

#### Problem #1
- How to get the custom JavaScript to run

#### Solution #1
- I disabled the `disable_sanitize_html` option so that JavaScript could be added to Text Panel using the HTML option.
- Also removed the title from the panel, enabled transparent background, reduced its size as far as it could go and moved it to the top left corner under variables.

#### Problem #2
- How do we get the key-value mapping now?

#### Solution #2
- Initially thought about doing something similar to the above (using template variables).
- However on further inspection Grafana uses a HTTP API to query the datasource, GREAT!
- Created a Table Panel, entered my query, used Chromes Network Inspector, and copied the request as fetch.
- Removed any redundant information in the fetch request (Depending on your setup, it may not be so redundant).
- Created a script that used the fetch command, to return the mapping and using querySelector and Regex, replace the relevant sections of the page (Regex provides considerable performance boost over looping over the array)
- This was then entered into the text/html panel
- The script is below

```
<script>

function fetchDeviceUUIDMappingConfig() {
    return fetch("https://localhost/logs/api/tsdb/query", {
        "method": "POST",
        "headers": {
            "content-type": "application/json",
        },
        "body": JSON.stringify({
                "queries":[
                    {
                        "refId": "MAPPING",
                        "datasourceId": 2,
                        "rawSql": "SELECT id, name FROM mappings",
                        "format": "table"
                    }
                ]
        }),
    })
    .then(data => data.json())
    .then(json => json.results.MAPPING.tables[0].rows)
    .then(rows => rows.reduce((o, row) => ({ ...o, [row[0]]: row[1] }), {}))
    .then(map => ({
        rexp: new RegExp(Object.keys(map).join('|')),
        map
    }));
}

function remapDeviceUUIDPanel(mappingConfig) {
    document.querySelectorAll("#panel-4 tbody tr span").forEach(el => {
        el.innerHTML = el.innerHTML.replace(mappingConfig.rexp, id => mappingConfig.map[id]);
    });
}

// Fetch Remap Config
let deviceUUIDMappingConfig = null;
fetchDeviceUUIDMappingConfig().then(config => deviceUUIDMappingConfig = config);

// Remap On Changes
const obeserveEl = document.querySelector("#panel-4");
const observeConfig = { childList: true, subtree: true };
new MutationObserver(function(mutationsList, observer) {
    observer.disconnect();
    remapDeviceUUIDPanel(deviceUUIDMappingConfig);
    observer.observe(obeserveEl, observeConfig);
}).observe(obeserveEl, observeConfig);

</script>
```

- The script takes into account the panels changing (It will rerun when required).
- Overall the experience is very good, it quickly replaces all values before they are made visible (Im using 6000 key-value mappings, yes its overkill).
- No doubt it could be improved in areas. One improvement would be to wrap it into a generalised function `remap("SELECT id, name FROM mappings", ["#panel-4 tbody tr span"])`

**Comment by phemmer** [comment]
It looks like this feature should be addressed by the functionality that was added in 7.4 for regex captures: https://grafana.com/docs/grafana/latest/variables/filter-variables-with-regex/#filter-and-modify-using-named-text-and-value-capture-groups


For example, for a database source, you can select a column which is a concatenation of key and value, and then use the regex to split it back apart.
**Query:** `SELECT CONCAT(foo, ' ', bar) FROM baz`
**Regex:** `/^(?<text>\S+) (?<value>.*)/`
![image](https://user-images.githubusercontent.com/1826947/133627954-6aa119bb-b787-4040-a407-974f3f1c2600.png)
![image](https://user-images.githubusercontent.com/1826947/133627973-c3418cc9-cfd2-47f3-9037-3208f7bb4701.png)


Are there any data sources where this doesn't work?

**Comment by SudoNova** [comment]
Please reconsider implementing this as it can compensate for Elasticsearch datasource's lack of filters option:
```json
      {
        "allValue": null,
        "current": {
          "selected": true,
          "text": "No",
          "value": "AND NOT _exists_: exception"
        },
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": "Is exception?",
        "multi": false,
        "name": "is_exception",
        "options": [
          {
            "selected": false,
            "text": "Doesn't matter",
            "value": ""
          },
          {
            "selected": false,
            "text": "Yes",
            "value": "AND _exists_: exception"
          },
          {
            "selected": true,
            "text": "No",
            "value": "AND NOT _exists_: exception"
          }
        ],
        "query": "Doesn't matter, Yes, No",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
```

**Comment by Crinon** [comment]
> If you have PostgreSQL, you don't need to create an actual table for the mapping, you can do something like:
> 
> ```
> SELECT *
> FROM
> (
> 	VALUES
> 		('London server 1', 'london_srv_1'),
> 		('London server 2', 'london_srv_2'),
> 		('New York server 1', 'ny_srv_1'),
> 		('New York server 2', 'ny_srv_2')
> ) AS t (__text, __value)
> ```

Thank you very much, I still don't understand why this feature is not built-in

**Comment by miguel-atenea** [comment]
> > If you have PostgreSQL, you don't need to create an actual table for the mapping, you can do something like:
> > ```
> > SELECT *
> > FROM
> > (
> > 	VALUES
> > 		('London server 1', 'london_srv_1'),
> > 		('London server 2', 'london_srv_2'),
> > 		('New York server 1', 'ny_srv_1'),
> > 		('New York server 2', 'ny_srv_2')
> > ) AS t (__text, __value)
> > ```
> 
> Thank you very much, I still don't understand why this feature is not built-in

It is now! (At least for static data), take a look at [this PR](https://github.com/grafana/grafana/pull/27829#issuecomment-780711418)

**Comment by st316** [comment]
> 



> > > If you have PostgreSQL, you don't need to create an actual table for the mapping, you can do something like:
> > > ```
> > > SELECT *
> > > FROM
> > > (
> > > 	VALUES
> > > 		('London server 1', 'london_srv_1'),
> > > 		('London server 2', 'london_srv_2'),
> > > 		('New York server 1', 'ny_srv_1'),
> > > 		('New York server 2', 'ny_srv_2')
> > > ) AS t (__text, __value)
> > > ```
> > 
> > 
> > Thank you very much, I still don't understand why this feature is not built-in
> 
> It is now! (At least for static data), take a look at [this PR](https://github.com/grafana/grafana/pull/27829#issuecomment-780711418)

Excellent!

**Comment by Koriit** [comment]
I found a way to do this with Prometheus. The only limitation is that map keys must be valid Prometheus labels, so characters like `-` are not allowed.

For some reason, `label_join` still adds a separator even if source labels don't exist. Capitalizing on this behavior, we can add labels with values to `vector(0)` like this:

```
label_join(vector(0), "label", "value", "a", "b")
```
And more:
```
label_join(label_join(vector(0), "label", "value", "a", "b"), "label2", "value2", "a", "b")
```
Etc.
![image](https://github.com/grafana/grafana/assets/75976467/dff30859-7603-48ca-ba11-0d20c2d3f02c)


Unfortunately, you can't use Grafana's `label_values` on that, but fortunately, you can use variables in the regex field so you can then choose a value based on a label with this:
```
.*(?<label>${variable_name})="(?<value>.*?)".*
```

---

In my case, I wanted to select an env and for this choice to populate other hidden variables. Tricky.

First, my custom variable. Note that I can't use `.` because it's not accepted in Prometheus labels, so I'm replacing it with `_`, which is accepted.
![image](https://github.com/grafana/grafana/assets/8916393/80a368ca-e78d-42a2-be33-cd8d7eb31865)

Second, my hidden variable. Prometheus query from above needs to be wrapped with Grafana's `query_result(...)`. No new lines are allowed or it won't work. Note how I use my previous variable in regexp.
![image](https://github.com/grafana/grafana/assets/8916393/51eba08a-a6d1-4189-93ea-a6b636c6ac69)

And now I can use the hidden variable which gets automatically chosen when I select value for my first variable:
![image](https://github.com/grafana/grafana/assets/8916393/2bd78be5-a360-49eb-b60b-c4f4cf20bb8a)

**Comment by SudoNova** [comment]
Please! This is a very needed and common request. Suppose that we have naming mismatch for different services in different data sources (e.g. MSSQL: MyService elasticsearch: my_service). We need to map between these two variables in a dynamic fashion (I'm not talking about value mapping in each dashboard, that's a heck of redundant work) .
If we can have this feature then 1to1 mapping of services in different data sources will be possible.
Note this is not feasible with chained variables especially in multi-option scenarios.

**Comment by BBQigniter** [comment]
ok, so those auto-actions are starting here now too :(

**Comment by jan-xyz** [comment]
Especially, since this is the third highest ranking issue by reactions

**Comment by koriit-kontakt** [comment]
I still find this feature missing.

**Comment by BasvanH** [comment]
For sure, this feature should be added. It has high interest.

**Comment by RedShift1** [comment]
@koriit-kontakt @BasvanH Just use the trick as described here: https://github.com/grafana/grafana/issues/1032#issuecomment-652246005

**Comment by yaelleC** [comment]
Closing as completed : https://grafana.com/whats-new/2026-02-06-map-one-variable-to-multiple-values/   🎉

**Comment by radoeka** [comment]
Thanks.
