### ISSUE TITLE
Dashboards: nextgen tables shows "[object Object]" when inspecting value

### ISSUE THREAD

**Issue by lucasRolff** [grafana/grafana#105179]
### What happened?

I query ClickHouse to visualize email history, one of the coulmns is called "symbols" which is effectively a json array with all the symbols coming from the column in Clickhouse.

Something like the following will be the output (a bunch more items but narrowed down here):
```json
[{"Names": "FROM_HAS_DN", "Options": "", "Scores": 1.3}]
```

This works when I use the "original" tables, but if I enable the NextGen tables with `tableNextGen` in the grafana.ini, then it simply returns something like the following:
```
[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

It only happens when I click "Inspect Value" - the actual values listen in the table column is correct and shows the visible json, but obviously the view is limited.

![Image](https://github.com/user-attachments/assets/47c8a2dd-ed5a-4c7a-8473-0072966be747)

And the inspect value:

![Image](https://github.com/user-attachments/assets/5d887964-9d8c-4d3f-9bdb-8be804639a44)

### What did you expect to happen?

It should show the original json string as it does in the column itself

### Did this work before?

N/A - tableNextGen was introduced in Grafana 12

### How do we reproduce it?

1. Ensure `tableNextGen` is enabled in grafana.ini
2. Have a column value of a json string.

### Is the bug inside a dashboard panel?

N/A - cannot be properly anonymized with the results

### Environment (with versions)?

Grafana: Grafana 12.0.0 (4c0e7045f9) // Enterprise
OS: MacOS - Server is Ubuntu 24.04
Browser: Vivaldi 7.3.3635.12 (Stable channel) (arm64)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

ClickHouse v25.4.1.

**Comment by fastfrwrd** [comment]
This was fixed in a recent release.

**Comment by lucasRolff** [comment]
> This was fixed in a recent release.

It's still broken in 12.1.1, so what release are you referring to?

**Comment by fastfrwrd** [comment]
Sorry, needed to go dig up the PR: https://github.com/grafana/grafana/pull/107274

I just went and checked the 12.1.0 and 12.1.1 release tags and confirmed that this commit barely missed the 12.1.0 release cutoff, which explains why you're still seeing the issue despite us fixing this a while ago. 12.2.0 will have this fix.

**Comment by lucasRolff** [comment]
> Sorry, needed to go dig up the PR: [#107274](https://github.com/grafana/grafana/pull/107274)
> 
> I just went and checked the 12.1.0 and 12.1.1 release tags and confirmed that this commit barely missed the 12.1.0 release cutoff, which explains why you're still seeing the issue despite us fixing this a while ago. 12.2.0 will have this fix.

Thank you sir!

**Comment by daniel-lee-sb** [comment]
@fastfrwrd I think this is still broken in v12.2.1... I updated the version but it is still showing [object Object]

**Comment by ntr-switchdin** [comment]
I'm on
```
app.kubernetes.io/version=12.2.1
  grafana_chart_version = "10.1.3"
```

and experiencing the same

**Comment by frwa-enpace** [comment]
Same here, I am on v12.2.1 and I see this issue.
