### ISSUE TITLE
Dashboards:  "Not found" pop up message when Public Dashboards disabled - 12.1.0

### ISSUE THREAD

**Issue by alexostapchuk** [grafana/grafana#108732]
### What happened?

After upgrade Grafana to version 12.1.0 I see "Not found" pop-up when open dashboard.

<img width="429" height="122" alt="Image" src="https://github.com/user-attachments/assets/a3d9364d-5044-4f73-9da3-b748b0551167" />

Grafana returns a 404 response to requests of the form "/grafana/api/dashboards/uid/<uid>/public-dashboards"

This happens when I set

```
[public_dashboards]
enabled = false
```

### What did you expect to happen?

No annoying pop-up

### Did this work before?

Yes

### How do we reproduce it?

Set

```
[public_dashboards]
enabled = false
```

Login to Grafana as admin and open dashboard

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v12.1.0 (ccd7b6ce7e)
OS: Debian 12
Browser: Chrome Version 138.0.7204.101

### Grafana platform?

None

**Comment by elvishsu-kr** [comment]
I have the same issue. What would be the best way to configure the ini file to remove this alerting?

**Comment by alexostapchuk** [comment]
> I have the same issue. What would be the best way to configure the ini file to remove this alerting?

Hello!

This must remove this pop-up

```
[public_dashboards]
enabled = tue
```

**Comment by thanissi** [comment]
same issue, but setting this to true doesn't seem right 

[public_dashboards]
enabled = tue

**Comment by joecanueldd** [comment]
Agreed, is there a way to disable this popup without enabling public_dashboards?

**Comment by mkutlak** [comment]
Looks like it has been fixed already in https://github.com/grafana/grafana/pull/108650

**Comment by HolgerHees** [comment]
I updated to version 12.1.1 but the error still exists. Also the setting "public_dashboards" does not help. I tried it with true and false, without any differences. I get always "404 Not Found"

**Comment by alexostapchuk** [comment]
> I updated to version 12.1.1 but the error still exists. Also the setting "public_dashboards" does not help. I tried it with true and false, without any differences. I get always "404 Not Found"

I can agree - 12.1.1 do not fix this issue

**Comment by ricmano** [comment]
> Looks like it has been fixed already in [#108650](https://github.com/grafana/grafana/pull/108650)

The change has been merged to main branch but new releases do not have the fix

**Comment by 1tft** [comment]
Can confirm, issue still exists with Grafana v12.1.1 (df5de8219b).

**Comment by Proximyst** [comment]
Backported to 12.1.3: https://github.com/grafana/grafana/pull/110144
