### ISSUE TITLE
User sessions: local user session shows as "Generic OAuth" in Auth Provider column

### ISSUE THREAD

**Issue by octal-ip** [grafana/grafana#110388]
### What happened?

When querying a user's sessions using the admin API or when viewing a user's sessions from the Users and Access area, local (i.e. internal Grafana) users will show "Generic OAuth" in the Auth Provider column, even if they are not using any external authentication.

This seems to only happen when other users are logged in with a Generic OAuth provider. If no other users are not logged in, the local user shows nothing under the Identity Provider heading as expected.

### What did you expect to happen?

Local users should not show any external identity provider for their sessions.

### Did this work before?

I don't think so.

### How do we reproduce it?

1. Log in to Grafana with a local user.
2. In a separate browser session, log into Grafana with a Generic OAuth user.
3. View the local user's session information under Administration > Users and Access > Users > Sessions. It will show the "Generic OAuth" label for each session, despite this authentication mechanism not being used by this particular user.

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 12.0.2+security-01
OS: Ubuntu 24.04
Browser: Firefox 142.0.1

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Not specific to a datasource.

**Comment by vtorosyan** [comment]
Thanks for the issue. We have several improvements in session handling and an upgrade to 12.1 should fix this problem. 

If an upgrade is not a possibility, enabling the `improvedExternalSessionHandling` feature toggle should have the same effect. Let us know if this works please.

**Comment by octal-ip** [comment]
Thanks for your help with this. Since the initial bug report I've upgraded to Grafana 12.2.0, and can confirm that the issue still exists. This only seems to happen when other actual Generic OAuth users are logged in, so I'm guessing the sessions are being mixed up.
