### ISSUE TITLE
Add Variables to a dedicated Row or Collapsible section.

### ISSUE THREAD

**Issue by n8ores** [grafana/grafana#113718]
**Why is this needed**:

Dashboards with lots of variables do not display well on narrow screens (such as tablets, phones etc). Even on large screens, dashboards with lots of variables still take up all the screen real-estate with the variables instead of the charts (which is what the user loaded the page to see).

<img width="764" height="800" alt="Image" src="https://github.com/user-attachments/assets/3c16aaf6-cdc0-41b6-9000-176e43e7bc9a" />

**What would you like to be added**:

I think we should add Variables into a collapsible section that can be minimized (similar or can even utilize the Rows feature). This will allow user's to see the graphs/charts when the page loads, instead of a long list of variable inputs.

Here is a mockup.

<img width="733" height="793" alt="Image" src="https://github.com/user-attachments/assets/8e7fbef1-e3f5-4158-9890-a3e79d5b38c5" />

**Who is this feature for?**
Everyone.

**Comment by yaelleC** [comment]
Hi @n8ores 👋 ,

Not quite the solution you propose here, but we just merged https://github.com/grafana/grafana/pull/113765 to make better use of the space available below the time picker. 

Would you say that solves your problem?

**Comment by n8ores** [comment]
This may have solved the issue, but it still occuring as of version 12.3.0 has it been merged into a minor release yet?

<img width="827" height="964" alt="Image" src="https://github.com/user-attachments/assets/2f2cd412-ff4a-4868-a95c-d3f7b1816033" />

**Comment by yaelleC** [comment]
Good call, It is currently being backported to 12.3, it should become available in the next release (Dec 16th)
