### ISSUE TITLE
Table cell inspection: Columns of type JSON View are formatted as string and not json after upgrading to 12.3.0

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#114821]
### What happened?

After upgrading to 12.3.0 columns of json type are rendered as strings in cell inspection

https://github.com/user-attachments/assets/38b46fbe-aa71-442c-8696-bcf42a85bf73

### What did you expect to happen?

the cells to be treaded as jons and formatted as such

### Did this work before?

yes - in 12.2

### How do we reproduce it?

1. Create new table panel 
2. set Cell type to `JSON view`
3. toggle on the Cell value inspect
4. add a query that returns jsons
5. try inspecting the individual cells

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | table @ 12.3.0 |
| Grafana | Grafana v12.3.0 (20051fb1fc) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "type": "table",
      "title": "Reproduced with embedded data",
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "auto",
            "footer": {
              "reducers": []
            },
            "cellOptions": {
              "type": "json-view"
            },
            "inspect": true,
            "hideFrom": {
              "viz": false
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          }
        },
        "overrides": []
      },
      "pluginVersion": "12.3.0",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": []
        }
      ],
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "options": {
        "showHeader": true,
        "cellHeight": "sm"
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >table @ 12.3.0</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-clickhouse-datasource]</td>\n    </tr>\n    \n    <tr><th>Data</th><td>Loading 0 frames, 0 fields, 0 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana v12.3.0 (20051fb1fc) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 1,\n  \"type\": \"table\",\n  \"title\": \"New panel\",\n  \"gridPos\": {\n    \"x\": 0,\n    \"y\": 0,\n    \"h\": 8,\n    \"w\": 12\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"align\": \"auto\",\n        \"footer\": {\n          \"reducers\": []\n        },\n        \"cellOptions\": {\n          \"type\": \"json-view\"\n        },\n        \"inspect\": true,\n        \"hideFrom\": {\n          \"viz\": false\n        }\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          },\n          {\n            \"color\": \"red\",\n            \"value\": 80\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      }\n    },\n    \"overrides\": []\n  },\n  \"pluginVersion\": \"12.3.0\",\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"grafana-clickhouse-datasource\",\n        \"uid\": \"f14e4dc2-fcce-4d7b-8d6e-884b90429729\"\n      },\n      \"editorType\": \"sql\",\n      \"format\": 1,\n      \"meta\": {\n        \"builderOptions\": {\n          \"columns\": [],\n          \"database\": \"\",\n          \"limit\": 1000,\n          \"mode\": \"list\",\n          \"queryType\": \"table\",\n          \"table\": \"\"\n        }\n      },\n      \"pluginVersion\": \"4.11.2\",\n      \"queryType\": \"table\",\n      \"rawSql\": \"/* App Analytics vitalyb@wix.com */\\nSELECT\\ndata\\nFROM logs_db.app_logs\\nWHERE timestamp >= toDateTime(1764815398) AND timestamp <= toDateTime(1764836998)\\nAND artifact_id IN ('com.wixpress.achievements.challenge-service-web')\\nand data != ''\\nORDER by timestamp DESC\\nLIMIT 100\",\n      \"refId\": \"A\"\n    }\n  ],\n  \"datasource\": {\n    \"type\": \"grafana-clickhouse-datasource\",\n    \"uid\": \"f14e4dc2-fcce-4d7b-8d6e-884b90429729\"\n  },\n  \"options\": {\n    \"showHeader\": true,\n    \"cellHeight\": \"sm\"\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: New panel // 2025-12-04 11:02:07",
  "tags": [
    "debug",
    "debug-table"
  ],
  "time": {
    "from": "2025-12-04T03:00:27.017Z",
    "to": "2025-12-04T09:00:27.017Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 12.3.0
OS: mac
Browser: Chrome

### Grafana platform?

Docker

**Comment by dlucredativ** [comment]
The issue exists in 12.3.0 but is fixed in 12.3.1, even though the changelog does not explain where.

**Comment by tomas-stary-work** [comment]
Hi, I would like to add to this issue. I am also encountering this problem, and unfortunately, the update to 12.3.1 did not resolve it for me. 

I have my data source set to Loki. I have logs in the table. When I want to view the inspect json data, it is formatted the same as in the video. Unfortunately, it is not in json format.

**Comment by dlucredativ** [comment]
> Hi, I would like to add to this issue. I am also encountering this problem, and unfortunately, the update to 12.3.1 did not resolve it for me.

Please check if this also happens when creating a new dashboard or panel. The following screenshot is a `Grafana v12.3.1 (0d1a5b4420)`

<img width="859" height="317" alt="Image" src="https://github.com/user-attachments/assets/2a9eff40-f3fd-420d-874b-d077ded8523d" />

**Comment by tomas-stary-work** [comment]
Hi, unfortunately, it still doesn't work. I tried importing the old dashboard. I tried creating a completely new dashboard and graph. However, the result is still the same. It's still not formatted as JSON. And it was before the update. I tried deploying both versions of Grafana, v12.1.1 and v12.3.1. In the older version, the data is formatted as JSON, but in the newer version, it isn't.

**Comment by tomas-stary-work** [comment]
Hi, I have tried the newly released version 12.3.2, and the problem persists. Can anyone please address this? Thank you

**Comment by tomas-stary-work** [comment]
Hi, I have now tested version 12.4.0, and the problem persists. Can someone please look into this?

**Comment by tomas-stary-work** [comment]
Hi, I solved the problem, maybe it will help someone too. You need to change the type for a column where it was not formatted json.

<img width="545" height="116" alt="Image" src="https://github.com/user-attachments/assets/a2656e80-fbab-4a8e-99b4-e1ba4e29b700" />
