### ISSUE TITLE
Request for decimal precision

### ISSUE THREAD

**Issue by Sybsw** [grafana/grafana#1253]
Hi,
The new way that Grafana automatically tries to put decimal points in or round small numbers if necessary is messing up a lot of my graphs. I would like the ability to choose a "X.XX" (or X number of decimal places) number format so that it doesn't keep rounding my values.

Thanks

**Comment by bouthors** [comment]
Same issue with temperatures, I would like to see at least one decimal.
![grafana](https://cloud.githubusercontent.com/assets/553073/5592481/09687722-91d2-11e4-907c-76b155c274b8.png)
On the other hand, the pressure (Pression) in hPa should be displayed without decimal : 1033 instead of 1.03300 K.

**Comment by infinitydon** [comment]
Hi,

Am also having this issue, some graphs show decimal points while it rounds off some to integer values, the previous version works well with the decimal numbers...

Any help on this?

**Comment by torkelo** [comment]
The previous version did not work so well in many other cases (as it was hard coded to only 2 decimals in all scenarios). I will try to solve this when I have time. The decimal precision (especially when scaling units, ns -> ms -> s -> min, or K -> Mil -> Bil) is so complex that it is tricky to get all scenarios right.

**Comment by infinitydon** [comment]
Ok...No prob then..

I appreciate the good work. Many thanks

**Comment by henkye** [comment]
+1
it's basically last issue keeping us from deploying Grafana at production.
![grafana-problem](https://cloud.githubusercontent.com/assets/4472325/6621803/ff66c5a6-c8d8-11e4-9087-eecea313390a.png)

**Comment by torkelo** [comment]
@henkye well if you put it like that I guess I just have to fix it, which I just did :) 

Both singlestat and graph panel now have a decimal override option, works with all unit formats. 

![image](https://cloud.githubusercontent.com/assets/10999/6625287/75582b86-c8ef-11e4-8363-d479157ea1b8.png)

Only fixed in develop branch (Grafana 2.0)

**Comment by Sybsw** [comment]
That's awesome, thank you.

**Comment by henkye** [comment]
@torkelo great, looks like I'm VIP :-)
Thank you and happy graphing! We at stable.cz appreciate your work.

**Comment by ireun** [comment]
Where is this option now? I cannot find the graph precision setting..

**Comment by peckrob** [comment]
Seconding @ireun's question. I'm using 3.3.1 and I don't see this option anywhere on graph settings.

**Comment by phemmer** [comment]
Thirding the question. I'm on 3.1.1 (a lowly peasant can don't have time travel capabilities to get 3.3.1 :-P)

**Comment by ireun** [comment]
Quadding the question. I also found it a while ago, anyway, thank You. ;)

**Comment by peckrob** [comment]
<img width="760" alt="2016-08-06_0750" src="https://cloud.githubusercontent.com/assets/500950/17456848/8b5b1b9c-5baa-11e6-8954-814e28e5b7b9.png">
Sorry, fat fingered the version number. It's 3.1.1.

For me that works on the legend but not on the axis, though. At least not when I zoom

**Comment by ireun** [comment]
@peckrob How do you check which version of grafana are you using? Honestly, I have no idea which one am I using.

And yes, it only sets the precision of the legend, not te axis. Though it shows the graph with as high precision as possible, if that's necessary. I'm using grafana to show data from my weather sensors, and I'm using moving_avarage()  function of InfluxDB, to smooth the graph and add values between the readings..

![image](https://cloud.githubusercontent.com/assets/695818/17456872/fb60769a-5be5-11e6-8603-1d090cdc38d8.png)

**Comment by Corbyn** [comment]
It would be very helpful to have the decimal precision override option also for the y axis! If the value stays constant over a long time (like it is often with disk usage) Grafana always puts in as many decimals as possible and that messes up the graphs...
![2016-09-06 17_12_23-grafana - os_linux_disk](https://cloud.githubusercontent.com/assets/8446952/18279249/22fd660e-7455-11e6-8524-1a1cd6d79174.jpg)

**Comment by sunfaces** [comment]
met the same bug with Corbyn, y axis precision need to be overrided too!

**Comment by rende2005** [comment]
Same issue here for the unexpected y-axis lable display. Eager to see the fix/enhancement.  Thanks!

**Comment by torkelo** [comment]
should be fixed/improved in v4.0

**Comment by tomekit** [comment]
Facing similar issue, +1 bump :)

**Comment by mrqwer88** [comment]
Hello!
Unfortunately looks like not fixed for y-axis label display in v4.1.1
```
grafana-server -v
Version 4.1.1 (commit: v4.1.1)
```
from 4.1.1-1484211277 deb package.

Avg, max in legend looks ok after set "Decimals".
But y-axis with "Decimals" 2 in legend looks - 
![looks_not_fixed_in_v4 0](https://cloud.githubusercontent.com/assets/7100008/22316227/54c94bc2-e385-11e6-8eba-6825d29cd241.png)

**Comment by iankittomar** [comment]
Hello All,
@torkelo 

I am using  Prometheus 2.3.2 and Grafana 5.2.2 Versions, I have created ActiveMQ Message Alert Rules, I am getting Alerts I decimals(value=1.048) when I crossed checked with Grafana panel(value=2) and in Prometheus, it's in Integer(Value=2). It's a message so it won't be in Decimal.
Can anyone tell me please how to figure it out this problem?  

Its Imp to solve :(

thanks

**Comment by Murthidn** [comment]
Folks under Axes you can select the value whichever you want, even i had same issue, after checking this helped me:

![image](https://user-images.githubusercontent.com/30889242/61947927-160e5680-afc4-11e9-8459-0b3ce8871633.png)
