### ISSUE TITLE
Template variables error after upgrade to 5.3.0

### ISSUE THREAD

**Issue by picolu** [grafana/grafana#13692]
### What Grafana version are you using?
5.3.0
### What datasource are you using?
Postgresql
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
Upgrade from 5.2.4, using working dashboard (on 5.2.4)
### What was the expected result?
Smoothly upgrade
### What happened instead?
Got error as shown in the second screenshots

The dashboard uses 2 template variables:
The first one seems to work properly.
![screenshot 1](https://user-images.githubusercontent.com/44204889/47027279-7637b880-d167-11e8-9e9f-92fddbb6b12a.png)

The second variable depends from the previous one and, when I try to change any property, I got an error:
![screenshot 2](https://user-images.githubusercontent.com/44204889/47027456-c9117000-d167-11e8-92ad-66254031cebc.png)
I got similar error when I try to open the dashboard. The second variable in the panel does not contain any values.

**Comment by marefr** [comment]
Duplicate of #13628

**Comment by marefr** [comment]
Fix included in v5.3.1 which was just released

**Comment by picolu** [comment]
I am sorry to say that I just upgraded to 5.3.1 but the problem is still there. 
Plase note that I edited my comment on the second screenshot to clarify better the situation.

**Comment by marefr** [comment]
@picolu please use chrome developer tools and check console tab - please include any related error logged here. Also check network tab and find the request related to second template variable query and include the request/response. Reopening this. Thanks

**Comment by picolu** [comment]
It seems to me that there is no second template variable query, I see the first one only.

Chrome console shows:
```
warning rootScope onAppEvent called without localscope
grafana_app.ts:86 warning rootScope onAppEvent called without localscope
history_srv.ts:33 Templating init failed TypeError: Cannot read property 'queryModel' of undefined
    at datasource.ts:108
    at Qt (lodash.js:639)
    at Function.Ka [as map] (lodash.js:9553)
    at e.interpolateVariable (datasource.ts:106)
    at e.formatValue (template_srv.ts:119)
    at template_srv.ts:247
    at String.replace (<anonymous>)
    at e.replace (template_srv.ts:218)
    at e.metricFindQuery (meta_query.ts:22)
    at e.metricFindQuery (query_variable.ts:172)

```
This is the firefox console output:
```
commitChanges	http://localhost:3000/public/build/app.09796ed34e70bee7294e.js:1:67617
l 		http://localhost:3000/public/build/app.09796ed34e70bee7294e.js:1:68545
eval 		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:99313
apply 		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:99537
l 		http://localhost:3000/public/build/app.09796ed34e70bee7294e.js:1:68525
dispatch 	http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:124:37882
handle 		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:124:35947

Templating init failed TypeError: "a is undefined"
interpolateVariable	http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:260504
Qt		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:9:5768
Ka		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:9:40614
interpolateVariable	http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:260482
formatValue	http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:52532
replace		http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:54032
replace		http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:53764
metricFindQuery	http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:261835
metricFindQuery	http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:65725
updateOptionsFromMetricFindQuery	http://localhost:3000/public/build/5.09796ed34e70bee7294e.js:10:65383
l		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:92198
l		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:92043
digest		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:97575
apply		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:99590
r		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:99735
h		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:33036
n		http://localhost:3000/public/build/vendor.09796ed34e70bee7294e.js:130:34396  

```

Thanks,
Pino

**Comment by marefr** [comment]
Thanks @picolu would it be possible for you to include your full dashboard JSON?

**Comment by picolu** [comment]
[NRFG Telemetry-1539269269888.zip](https://github.com/grafana/grafana/files/2486847/NRFG.Telemetry-1539269269888.zip)
Here is the dashboard.

**Comment by marefr** [comment]
@picolu thanks was able to reproduce it now

**Comment by marefr** [comment]
@picolu fix will be included in Grafana v5.3.2

**Comment by picolu** [comment]
Just upgraded to 5.3.2.
My problem has been fixed, thank you very much.

**Comment by padrian** [comment]
@marefr i am running grafana version 5.3.2 i still get a similar error when i run a traefik dashboard
this is displayed in the google chrome console, same error as

```
 warning rootScope onAppEvent called without localscope

Templating init failed TypeError: Cannot read property '1' of null
    at Object.stringToJsRegex (kbn.ts:237)
    at e.metricNamesToVariableValues (query_variable.ts:184)
    at query_variable.ts:153
    at angular.js:17051
    at angular.js:17095
    at c.$digest (angular.js:18232)
    at c.$apply (angular.js:18531)
    at angular.js:18832
    at h (angular.js:6362)
    at angular.js:6642
```

this is by json for the traefik dashboard
[https://gist.github.com/padrian/a951d11ee0e888db835563878d4d2236](url)

**Comment by marefr** [comment]
@padrian you seem to have an error in Regex for the `Node` variable. `/([^:]+):.*/*` is not a valid regular expression, it must end with a slash.

**Comment by padrian** [comment]
@marefr thanks for your response.
that is strange though, since the dashboard has been working just fine.
i actuallly got it from > https://grafana.com/dashboards/6293
Nevertheless, i made the change, but i still get the error above.
`Templating init failed, Cannot read property '1' of null`
