### ISSUE TITLE
ipv6 mysql datasource address parse error

### ISSUE THREAD

**Issue by denghuancong** [grafana/grafana#13711]
base info
grafana version: 5.1.3
datasource mysql
running in centos 7.4
----------------------------------------
#### our grafana.ini 
```
[database]
type = mysql
host = [2003:da8:2004:1000:0a30:7eea:1600:1232]:6033
name = grafana_db
user = root
password = dbpw
ssl_mode = disable

[paths]
provisioning = /data/monitor/1/grafana/conf

[auth.anonymous]
enabled = true
org_role = Viewer
```
===========================================
#### the error log :
```
2018-10-17 12:31:37 Starting to extract config info
2018-10-17 12:31:37 Extracted db_name=grafana_db, db_host="2003:da8:2004:1000:0a30:7eea:1600:1232":6033, db_user=root, db_pw=dbpw from provided /etc/grafana/grafana.ini
2018-10-17 12:31:37 Built conn string: mysql -uroot -pdbpw -h"2003 -Pda8:2004:1000:0a30:7eea:1600:1232":6033
2018-10-17 12:31:37 show databases like 'grafana_db';
2018-10-17 12:31:37 Unknown suffix 'd' used for variable 'port' (value 'da8:2004:1000:0a30:7eea:1600:1232":6033') mysql: Error while setting value 'da8:2004:1000:0a30:7eea:1600:1232":6033' to 'port'
2018-10-17 12:31:37 DB exists already, sleep 150s to make sure the other node has complete import operations
2018-10-17 12:33:16 Starting to extract config info
2018-10-17 12:33:16 Extracted db_name=grafana_db, db_host=[2003:da8:2004:1000:0a30:7eea:1600:1232]:6033, db_user=root, db_pw=dbpw from provided /etc/grafana/grafana.ini
2018-10-17 12:33:16 Built conn string: mysql -uroot -pwakandapw -h[2003 -Pda8:2004:1000:0a30:7eea:1600:1232]:6033
2018-10-17 12:33:16 show databases like 'grafana_db';
2018-10-17 12:33:16 Unknown suffix 'd' used for variable 'port' (value 'da8:2004:1000:0a30:7eea:1600:1232]:6033') mysql: Error while setting value 'da8:2004:1000:0a30:7eea:1600:1232]:6033' to 'port'
2018-10-17 12:33:16 DB exists already, sleep 150s to make sure the other node has complete import operations
```

**Comment by ellisvlad** [comment]
#15051

**Comment by marefr** [comment]
Fixed by #15051

**Comment by denghuancong** [comment]
@maage  The ipv6 binding problem is not fixed 
we using the version：
```
/bin # grafana-server -v
Version 6.0.0 (commit: 3789b35, branch: master)
```

our grafana.ini db setting
```
[database]
type = mysql
host = "[2003:da8:2004:1000:c0a8:0004:1600:0036]:6033"
name = grafana_db
user = root
password = xxxpw
ssl_mode = disable
```

error log：
```
2019-03-08 08:31:06 Starting to extract config info
2019-03-08 08:31:06 Extracted db_name=grafana_ucloud, db_host="[2003:da8:2004:1000:c0a8:0004:1600:0036]:6033", db_user=root, db_pw=xxxpw from provided /etc/grafana/grafana.ini
2019-03-08 08:31:06 Built conn string: mysql -uroot -pxxxpw -h"[2003 -Pda8:2004:1000:c0a8:0004:1600:0036]:6033"
2019-03-08 08:31:06 show databases like 'grafana_db';
2019-03-08 08:31:06 Unknown suffix 'd' used for variable 'port' (value 'da8:2004:1000:c0a8:0004:1600:0036]:6033"') mysql: Error while setting value 'da8:2004:1000:c0a8:0004:1600:0036]:6033"' to 'port'

```

**Comment by marefr** [comment]
Thanks. Seems like there's some weirdness going on with the port. It's weird though since we have test cases: 

https://github.com/grafana/grafana/blob/f9e3c33ebdffbd930ddcc776753a76c4254c72b2/pkg/services/sqlstore/sqlstore_test.go#L18-L67

Tried your ipv6 address in test and that works as expected:
```go
{
	name:          "MySQL IPv6",
	dbType:        "mysql",
	dbHost:        "[2003:da8:2004:1000:c0a8:0004:1600:0036]:6033",
	connStrValues: []string{"tcp([2003:da8:2004:1000:c0a8:0004:1600:0036]:6033)"},
},
```

What you could try is to use the [url config instead](http://docs.grafana.org/installation/configuration/#url) - does that work for you?

**Comment by denghuancong** [comment]
@marefr  I follow you tips to change the config file
```
[database]
#  mysql://user:secret@host:port/database
url= mysql://root:dbpw@[2003:da8:2004:1000:c0a8:0004:1600:0036]:6033/grafana_db

[paths]
provisioning = /data/monitor/1/grafana/conf

[auth.anonymous]
enabled = true
org_role = Viewer

```

the error log 
```
ERROR 2005 (HY000): Unknown MySQL server host '-P' (-2)
2019-03-11 03:51:43 Starting to extract config info
2019-03-11 03:51:43 Extracted db_name=, db_host=, db_user=, db_pw= from provided /etc/grafana/grafana.ini
2019-03-11 03:51:43 Built conn string: mysql -u -p -h -P
2019-03-11 03:51:43 show databases like '';
2019-03-11 03:51:43 ERROR 2005 (HY000): Unknown MySQL server host '-P' (-2)
ERROR 2005 (HY000): Unknown MySQL server host '-P' (-2)

```

**Comment by marefr** [comment]
@denghuancong think you've used the wrong format. Try

```ini
url = root:dbpw@tcp([2003:da8:2004:1000:c0a8:0004:1600:0036]:6033)/grafana_db?collation=utf8mb4_unicode_ci&allowNativePasswords=true
```
