### ISSUE TITLE
Bars for timeseries with only one datapoint are too wide

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#14130]
Use a datasource that only returns one datapoint, and does not fill the rest of the range with null values, e.g., https://github.com/grafana/influxdb-flux-datasource

In a bar chart that single datapoint's bar is excessively wide. 

Not really sure if this is the DS who is at fault for not returning empty datapoints for the whole range, or if the graph panel should catch this case.

![screenshot 2018-11-19 at 18 15 19](https://user-images.githubusercontent.com/859729/48723566-42005d80-ec27-11e8-8d68-155512781b2a.png)
 
Original issue in external DS: https://github.com/grafana/influxdb-flux-datasource/issues/11

**Comment by yesoreyeram** [comment]
Is anyone working on this issue ?

**Comment by davkal** [comment]
No, go for it! @yesoreyeram

**Comment by gopalakrishnan-subramani** [comment]
<img width="1433" alt="Grafana" src="https://user-images.githubusercontent.com/354710/55668274-4b602e80-5885-11e9-9c4b-b4d6bb7b5b67.png">

+1, facing same issues, the customer wants to aggregate and show data for every hour, till we complete the first hour, it fills the entire chart [The actual point to full right side of the graph].

**Comment by speed2002** [comment]
same here, should be fixed :)

**Comment by fsmp125** [comment]
+1

**Comment by 2019-05-10** [comment]
Still the same issue with SQL as described by @gopalakrishnan-subramani.
Where/in what version is it fixed?

**Comment by bodschut** [comment]
Same issue here with stackdriver datasource. Can someone have a look at this please?

![image](https://user-images.githubusercontent.com/1922169/76750303-4f2b4f00-677e-11ea-9b75-cc42883ec14f.png)

**Comment by gopalakrishnan-subramani** [comment]
@bodschut 

This issue cannot be fixed, the workaround is to generate data point every hour/missing plots.
It goes like this, this is time series, when you select date input on the top right, there is start and end time. 

If that returns only one input even with right timestamp, Grafana   mistakenly pick whole range as single series, instead of having bar width. 

The workaround we do is fill the 0/default values for every hour,  when the data is not present.

**Comment by bodschut** [comment]
Thanks for the info @gopalakrishnan-subramani. I'm quite new to grafana, how do you go about filling those missing values as 0? The stackdriver metrics simply return no data besides the one datapoint, so the graph option 'null as zero' doesn't work for me...

**Comment by asorokoumov** [comment]
Same issue here. @gopalakrishnan-subramani , could you please show the way you fill values with 0, when data is not present.
Thanks a lot!

**Comment by jehutywong** [comment]
+1 Same here

My Grafana version is 7.1.0. Bars with one data point use 100% width, no matter what Null value is selected

**Comment by perebf** [comment]
+1 Still happening in v7.3.1!!

**Comment by SimoPk** [comment]
+1 same here in v8.0.0

**Comment by mrthehud** [comment]
+1, can confirm still present in 8.4.3 unfortunately.

**Comment by isaccavalcante** [comment]
Setting "No value = 0" did not work for me

**Comment by taleena** [comment]
Posting here in case it helps...
This may be fixed by change this line to anything other than infinity:
https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/packages/grafana-ui/src/components/uPlot/config/UPlotSeriesBuilder.ts#L216

**Comment by leeoniya** [comment]
@taleena agreed.

https://github.com/grafana/grafana/pull/48021 clamps max width to 200px.

![Peek 2022-04-20 22-37](https://user-images.githubusercontent.com/43234/164367827-87fe608e-742e-49e3-b973-dfa21d72b63d.gif)

**Comment by Kasperdelasopa** [comment]
Hello, can i configure the " barMaxWidth = ..." value also for a allready build version?

I'm allready running Grafana and im not able to build a version by myself. I would like to configure it in a config file.

Is that possible?
