### ISSUE TITLE
Autoheight issue in 5.4.3

### ISSUE THREAD

**Issue by dukoo** [grafana/grafana#14971]
Today I upgraded from 5.2.1 to 5.4.3. Right now I'm working on integration of Grafana with iOS App and I found out that graph view seems to scale wrong right now - cut legend (no code changes on our side). I still have both installation of Grafana and when I switch between them problem appears and disappears, so it's definately related to this particular version. 
I'm running MacOS version. 
Below, there are 3 printscreend from my iPad (the first is view from Safari web browser, the second one is view from my iOS App with version 5.4.3 and the third is version 5.2.1

Safari:
![img_0040](https://user-images.githubusercontent.com/8033825/51477689-80caa500-1d89-11e9-8027-5d26a930dc09.PNG)

My app in combination with Grafana 5.2.1:
![img_0041](https://user-images.githubusercontent.com/8033825/51477717-9770fc00-1d89-11e9-8049-cb1141c53ae8.PNG)

My app in combination with Grafana 5.4.3:
![img_0044](https://user-images.githubusercontent.com/8033825/51477722-9b048300-1d89-11e9-9292-6820017e7909.PNG)

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/14744 

This is fixed in master and nightly build

**Comment by dukoo** [comment]
I applied this fix you mentioned locally on my PC and problem still exists...

**Comment by torkelo** [comment]
How did you do that?

**Comment by torkelo** [comment]
no, you need to rebuilt the frontend
