### ISSUE TITLE
Explore: Cannot go from dashboard to explore (or via url) 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#15015]
* Change data source to Loki in explore
* Go to a dashboard with a Graph with Prometheus data source (or any data source)
* Use panel menu to go to explore. Loki data source still selected. 

Seems like the URL state data source cannot change the last local storage saved data source (a guess).

**Comment by hugohaggmark** [comment]
Have a hard time solving this issue.
In explore.ts line 87 this is easily fixed by substituting state with left instead.
``url = renderUrl('/explore', { state: exploreState });`` 

But this is only part of the problem, if you've already "intialized" an Explore.ts then trying to "intializing" it again causes an infinite UpdateLocation loop randomly which has taken the whole day to solve.

Maybe someone more familiar with the Explore code can solve this.

**Comment by torkelo** [comment]
So I solved the issue with infinite UpdateLocation it was caused by a mistmatch between url encoding between angularjs and our redux url state. 

fixed by this PR #15071 

But that fix does not solve this issue as Explore does not ever reinitialize after it has been loaded once. So you can never change data source from Url. this initialized is set to true and will stop any initialization. 

https://github.com/grafana/grafana/blob/master/public/app/features/explore/Explore.tsx#L122

thoughts @davkal? 

Might be related to other issues in explore after redux migration, like not recovering from a data source set error (can not set any other data source after that) and that the same query is set when you go back to explore after leaving it (might be a good thing though)

**Comment by hugohaggmark** [comment]
Awsome work @torkelo 

As a temporary fix, we could supply an extra param in url when called from outside of Explore and "reinitialize" Explore when that extra param is supplied.
