### ISSUE TITLE
Grafana 6 leaks memory

### ISSUE THREAD

**Issue by narqo** [grafana/grafana#15731]
### What Grafana version are you using?

`Grafana v6.0.0 (34a9a62)`

### What datasource are you using?

Graphite

### What OS are you running grafana on?

Linux Raspbian running on Pi 3 Model B+ (1GB RAM)

### What did you do?

We have 3 dashboards in kiosk mode, one per Chromium tab, rotated via Chrome Revolver extension, once per 1 minute (*no tabs reload on rotate*). Chromium is the only application running (excluding system services and ssh daemon).

Each dashboard has 3 to 8 line graphs (graphite datasounce), all graphs from 2 dashboards draw about 10+ datapoints each, the thirds one has 3 graphs each draws <300 datapoints (e.g. `sortByMaxima(groupByNode(*.svc.label.*.success, 3, 'sum'))`).

The dashboards have refresh rate set to 5 minutes.

We use Pi's default Chromium `Version 65.0.3325.181 (Official Build) Built on Raspbian , running on Raspbian 9.8 (32-bit)`

### What was the expected result?

After updating to Grafana 6, system was expected to run in the described configuration as it was with 5.4.

### What happened instead?

Chromium crashes tabs with Grafana after running it for ~6hrs.

I did a simple experiment measuring the amount of memory chromium tabs consume during a period of time after OS restart, checking the output from `htop(1)`.

After running it for 2 hours, memory consumption of the biggest dashboard (3rd from the description above) increased from 200M to 280M and continue to grow slowly.

Note, I've tried to get the memory numbers between tabs rotation and graph refresh calls. Right after a tab rotation happens, memory usage jumps to +40M but decreases within several seconds.

**Comment by xlson** [comment]
Thanks for reporting this issue.

**Comment by ryantxu** [comment]
We once had similar issues, but using the playlists feature helped fix memory issues:
![image](https://user-images.githubusercontent.com/705951/53656256-9bedc780-3c07-11e9-8132-ef9c4c35d962.png)

Carete a playlist with the three panels, and grafana will cycle them for you.  The page refresh lets chrome release its memory.

That is likely unrelated to any core changes since 5.4, but may help your immediate needs

**Comment by narqo** [comment]
We've tried Playlists, but, unfortunately, reloading the page every N minutes is very disturbing and brings additional visual noise to the office space.

**Comment by ssiergl** [comment]
I can second this. We have same memory problems on our raspberry pi since release of version 6.0.0 running on chromium

**Comment by ntting** [comment]
We had the similar issues,  the chrome will crash  after open dashboard 3 hours, we use the V5.3.2, and test 6.0.0 have the same issue.

**Comment by torkelo** [comment]
What OS and browser are you using? Unable to find any big memory leak on Ubuntu & Chrome 72

**Comment by narqo** [comment]
We use Raspbian Linux 4.14.98-v7+ and Pi's default Chromium `Version 65.0.3325.181 (Official Build) Built on Raspbian , running on Raspbian 9.8 (32-bit)` (have updated the issue description).

One note, last week I did another set of experiments (with the original setup, described above):

1. Increased tab rotation interval from 1 to 5 minutes. Wanted to check if Grafana returned the memory to OS, that was allocated on tab rotation. Didn't see any difference: the tab with the biggest dashboard crashed after 6-10hrs.

2. Excluded the biggests dashboard from rotation. So far everything looks fine. 

Could it be that one huge dashboard (*3 graphs, each draws <300 datapoints with lines*, see the issue description) caused the visible leak?

**Comment by ssiergl** [comment]
We are using FullPageOS with latest chromium. Only 2 Boards medium heavy. We tried it with 6.0.0 and 6.0.1....both are running into memory issues and freezes after 1-2 hours. Reverting back to 5.4.3 solves the problem immediately. Low memory footprint and all is running well for days as usual.

Any hint what we need to debug or which information you guys need to debug it?

**Comment by ntting** [comment]
we  use in win7  64bit , chrome version is: 72.0.3626.121（64 bit）  , we add 30 Graph in one dashboard, the chrome memory increase and chrome crashed after 3 hours

**Comment by torkelo** [comment]
One panels do you use on these dashboards? And what datasources?

**Comment by ntting** [comment]
> One panels do you use on these dashboards? And what datasources?

30 Graph panels,   datasource  is simplejson datasource .

**Comment by Atem18** [comment]
Hi, does it still exists on the version 6.2 ?

**Comment by torkelo** [comment]
Anyone still having issue with this? We have no other reports of memory leaks in recent releases.

**Comment by Atem18** [comment]
@torkelo I did the upgrade 7 days ago anyway to test. No crash so far and no one complained, so I would say that the issue is solved.

**Comment by stephen8339** [comment]
> Anyone still having issue with this? We have no other reports of memory leaks in recent releases.

We still have the out of memory to crash the browser on the version 6.6.1

**Comment by AndyBehr** [comment]
this issue still exists in the current version. any news?

**Comment by dpithon** [comment]
@AndyBehr 

I guess we have similar issues :

Ubuntu 18.04.4 LTS / Mozilla Firefox 73.0.1
Grafana Dashboard : grid of 6x6 StatusPanel + Clock

WebContent process (firefox tab) use up to 1.5Gb. Sometime the screen freeze
It seems to be the same on IE/Edge/Chrome.

**Comment by badcrc** [comment]
Hi,

I've been WFH since the end of March, we have a grafana playlist displayed on a 4k TV via a RPI4 (2GB Edition). Grafana runs on a separate server. We have been using the same playlist for months.

I've updated grafana from grafana-6.4.4 (working correctly) to 6.7.2 when at home and after coming this week to the office I've noticed that usually the playlist crashes. 

In the RPI I can see that the linux OOM killed chromium.

I've updated the RPI and continues to happen. I have tried Firefox with the same results, every now and them:

```
[ 9041.391373] Out of memory: Kill process 9548 (chromium-browse) score 355 or sacrifice child
[ 9041.391420] Killed process 9548 (chromium-browse) total-vm:575776kB, anon-rss:96904kB, file-rss:38764kB, shmem-rss:21812kB
```

**Comment by badcrc** [comment]
Just a follow up, updated to Grafana 7.0 and I'm still having this problem.

The playlist is set to 2 minutes in each dashboard (graphite backend) and as you can see in this netdata graph, every two minutes there is a spike and the rams, little by little, goes up.

![Screen Shot 2020-06-08 at 15 19 45](https://user-images.githubusercontent.com/663985/84035179-aa469980-a99b-11ea-982c-f6d801e35067.png)

The RPI is updated. And it happens with Chromium, Firefox and Midori.

The playlist is inside an iFrame if that matters.

**Comment by skydiablo** [comment]
one year later and we have still the same problem here. we have tried Pi3, Pi4, NUC (Ubuntu 22.04), chromium, chrome, disable hardware acceleration,  and so on... nothing helps, RAM is going up from time to time :/
we use all the time the latest versions beginning from the OS, over the chrome engine, till grafana itself, nothing helps. any new hints to solve this problem?
