### ISSUE TITLE
Cloudwatch data source does not properly support multiple variables in dimension field

### ISSUE THREAD

**Issue by unaiur** [grafana/grafana#15900]
**What happened**:
There is a dashboard with multiple queues with a country code and a queue name. For example: US-activations, CA-activations, US-updates, CA-updates and so on.

The country code is selected by a custom variable called $country, which is visible and must be changed manually. The queue name is another custom variable $queueName that is hidden.

There is a row configured to repeat on $queueName and inside that queue a cloudwatch single-stat panel that shows the max-age of the queue $country-$queueName (dimension).

But the panels do not show any information because it says that there is multiple rows to show.

**What you expected to happen**:
I expect to see a row per queue name (activations, updates) containing a single-stat panel showing the max-age.

**How to reproduce it (as minimally and precisely as possible)**:
The scenario above is the minimum I've been able to reproduce.

**Anything else we need to know?**:
Reading the source code, I think I've found the source of the problems: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/cloudwatch/datasource.ts#L446

This method (expandTemplateVariable) duplicates the dimensions field for all values of queueName, querying both US-activations and US-updates even if the queueName variable is scoped to a single value. The reason is that:
* L451 only checks for scoped variables in the first variable it finds (country, which is not scoped)
* L463 does not pass the scoped variables to getExpandedVariables.

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: CloudWatch (integrated)
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox & Crome
- Grafana plugins: Only integrated ones
- Others: N/A

**Comment by unaiur** [comment]
I've tested replacing lines [L454-L466](https://github.com/grafana/grafana/blob/cfea8bdcae0ef392f7d83fa119a18c1a4b04f565/public/app/plugins/datasource/cloudwatch/datasource.ts#L454-L466) with ```return [target];``` and the issue is fixed.

**Comment by mtanda** [comment]
@unaiur Is it still happen?
If so, would you share query inspector output?

**Comment by justinTM** [comment]
@torkelo  @mtanda We are still experiencing this bug; multi-value dropdowns inside the Dimensions portion of a CloudWatch query are returning no metrics.
