### ISSUE TITLE
UID ignored when creating notification via API

### ISSUE THREAD

**Issue by JohnONeill** [grafana/grafana#16372]
**What happened**: When creating a new notification through the API, the "uid" field is ignored:

![image](https://user-images.githubusercontent.com/306122/55502415-80b51400-561a-11e9-98bf-760e141fe418.png)

**What you expected to happen**: According to [the docs](http://docs.grafana.org/http_api/alerting_notification_channels/#identifier-id-vs-unique-identifier-uid), it should be possible to specify a "uid" when creating a notification channel:

>The unique identifier (uid) of a notification channel can be used for uniquely identify a notification channel between multiple Grafana installs. It’s automatically generated *if not provided when creating a notification channel*. [Emphasis mine.] The uid allows having consistent URL’s for accessing notification channels and when syncing notification channels between multiple Grafana installs...

In the above example / screenshot, I would expect the `uid` of the final alert channel to be `"manuallyadded9"` (the original `uid` provided) not `"vW3vqB6mk"`.

**How to reproduce it (as minimally and precisely as possible)**:

POST request to http://localhost:3001/api/alert-notifications with basic authorization and the following JSON in the body of the request:

```
{
  "name": "new alert notification 9",
  "uid": "manuallyadded9",
  "type":  "email",
  "isDefault": false,
  "sendReminder": false,
  "settings": {
    "addresses": "test@example.com"
  }
}
```

**Anything else we need to know?**:

The issue seems different than https://github.com/grafana/grafana/pull/16219 but perhaps that might help resolve it? If so, I can try updating my grafana version.

Thanks in advance!

**Environment**:
- Grafana version: 6.0.1
- Data source type & version: Graphite / 1.1.5
- OS Grafana is installed on: Behavior reproducible on macOS 10.13.6 & debian 8 (jessie) installs
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you try 6.1.0, think this is fixed in 6.1.0

**Comment by JohnONeill** [comment]
Thanks @torkelo. Unfortunately, even with an install of `6.1.0` (confirmed new version on login page) I'm still seeing the same behavior.

For some context, we're provisioning our dashboards through json files (thanks for that btw 🎉) and we're hoping to reference specific notification channels within those json configurations.

**Comment by torkelo** [comment]
That is not supported yet

**Comment by torkelo** [comment]
But this issue is about uid in api?

**Comment by JohnONeill** [comment]
Yup, our automated deployment of grafana goes something like:

1. Create notification channel via API
2. Include [dashboard JSON](http://docs.grafana.org/administration/provisioning/#dashboards) file that references the notification UID's inside the alerts
3. Restart Grafana

For example, in step 1 if we create a notification channel with `uid` of `notification-channel-1`, that `uid` gets ignored and replaced with a randomly generated `uid`. That prevents us from provisioning alerts with predetermined notification channel UID's like so:
```
"alert": {
  ...,
  "notifications": [
     {"uid": "notification-channel-1"}
  ]
}
```

From the docs it seems like the UID should carry through when creating the notification channel, but maybe that's not expected behavior? And/or perhaps the above deployment pattern is discouraged?

**Comment by josephcf** [comment]
Thanks @torkelo, Thanks @JohnONeill this was a good one,  we had the requirement of linking uid to dashboards, as we had multiple grafana installs
