### ISSUE TITLE
Mysql creation/migration hang

### ISSUE THREAD

**Issue by mag009** [grafana/grafana#1643]
Hi ,

I just updated the latest build of grafana 2.0 this morning and there is a bug with the creation or migration of a mysql db.

2015/03/25 12:16:36 [I] Starting Grafana
2015/03/25 12:16:36 [I] Version: 2.0.0-prebeta2, Commit: e31a3a6, Build date: 2015-03-25 11:27:33 +0000 UTC
2015/03/25 12:16:36 [I] Config: Loaded from /etc/grafana/grafana.ini
2015/03/25 12:16:36 [I] Database: mysql, ConnectionString: gl_grafana:aNwHgMKhTbBU@tcp(db-gli:3306)/grafana?charset=utf8
2015/03/25 12:16:36 [I] Migrator: Starting DB migration
2015/03/25 12:16:36 [I] Migrator: exec migration id: create migration_log table
2015/03/25 12:16:36 [I] Migrator: exec migration id: create user table
2015/03/25 12:16:36 [I] Migrator: exec migration id: add unique index user.login
2015/03/25 12:16:36 [I] Migrator: exec migration id: add unique index user.email
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index UQE_user_login - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index UQE_user_email - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: Rename table user to user_v1 - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create user table v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_user_login - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_user_email - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: copy data_source v1 to v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: Drop old table user_v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create star table
2015/03/25 12:16:36 [I] Migrator: exec migration id: add unique index star.user_id_dashboard_id
2015/03/25 12:16:36 [I] Migrator: exec migration id: create org table v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_org_name - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create org_user table v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index IDX_org_user_org_id - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_org_user_org_id_user_id - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: copy data account to org
2015/03/25 12:16:36 [I] Migrator: skipping migration id: copy data account to org, condition not fulfilled
2015/03/25 12:16:36 [I] Migrator: exec migration id: copy data account_user to org_user
2015/03/25 12:16:36 [I] Migrator: skipping migration id: copy data account_user to org_user, condition not fulfilled
2015/03/25 12:16:36 [I] Migrator: exec migration id: Drop old table account
2015/03/25 12:16:36 [I] Migrator: exec migration id: Drop old table account_user
2015/03/25 12:16:36 [I] Migrator: exec migration id: create dashboard table
2015/03/25 12:16:36 [I] Migrator: exec migration id: add index dashboard.account_id
2015/03/25 12:16:36 [I] Migrator: exec migration id: add unique index dashboard_account_id_slug
2015/03/25 12:16:36 [I] Migrator: exec migration id: create dashboard_tag table
2015/03/25 12:16:36 [I] Migrator: exec migration id: add unique index dashboard_tag.dasboard_id_term
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index UQE_dashboard_tag_dashboard_id_term - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: Rename table dashboard to dashboard_v1 - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create dashboard v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index IDX_dashboard_org_id - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_dashboard_org_id_slug - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: copy dashboard v1 to v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop table dashboard_v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create data_source table
2015/03/25 12:16:36 [I] Migrator: exec migration id: add index data_source.account_id
2015/03/25 12:16:36 [I] Migrator: exec migration id: add unique index data_source.account_id_name
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index IDX_data_source_account_id - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index UQE_data_source_account_id_name - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: Rename table data_source to data_source_v1 - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create data_source table v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index IDX_data_source_org_id - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_data_source_org_id_name - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: copy data_source v1 to v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: Drop old table data_source_v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create api_key table
2015/03/25 12:16:36 [I] Migrator: exec migration id: add index api_key.account_id
2015/03/25 12:16:36 [I] Migrator: exec migration id: add index api_key.key
2015/03/25 12:16:36 [I] Migrator: exec migration id: add index api_key.account_id_name
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index IDX_api_key_account_id - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index UQE_api_key_key - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: drop index UQE_api_key_account_id_name - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: Rename table api_key to api_key_v1 - v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create api_key table v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index IDX_api_key_org_id - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_api_key_key - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_api_key_org_id_name - v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: copy api_key v1 to v2
2015/03/25 12:16:36 [I] Migrator: exec migration id: Drop old table api_key_v1
2015/03/25 12:16:36 [I] Migrator: exec migration id: create dashboard_snapshot table v4
2015/03/25 12:16:36 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_key - v4
2015/03/25 12:16:37 [I] Created default admin user: admin

from the migration_log : 
          id: 61
migration_id: create dashboard_snapshot table v4
         sql: CREATE TABLE IF NOT EXISTS `dashboard_snapshot` (
`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL
, `name` VARCHAR(255) NOT NULL
, `key` VARCHAR(255) NOT NULL
, `dashboard` TEXT NOT NULL
, `expires` DATETIME NOT NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET UTF8 ;
     success: 1
       error: 
   timestamp: 2015-03-25 12:16:36
*************************** 62. row ***************************
          id: 62
migration_id: create index UQE_dashboard_snapshot_key - v4
         sql: CREATE UNIQUE INDEX `UQE_dashboard_snapshot_key` ON `dashboard_snapshot` (`key`);
     success: 1
       error: 
   timestamp: 2015-03-25 12:16:36

show tables;
+--------------------+
| Tables_in_grafana  |
+--------------------+
| api_key            |
| dashboard          |
| dashboard_snapshot |
| dashboard_tag      |
| data_source        |
| data_source_v1     |
| migration_log      |
| org                |
| org_user           |
| star               |
| user               |
+--------------------+

seem to jam at data_source_v1

**Comment by torkelo** [comment]
thanks for reporting this, will take a investigate asap.

**Comment by torkelo** [comment]
btw, I did not see any evidence of hanging, just that the migration did not clean up data_source_v1 correctly (fixed now).

**Comment by mag009** [comment]
Migrator: Starting DB migration
2015/03/25 13:17:05 [I] Migrator: exec migration id: Drop old table data_source_v1 #2


now it's stuck at this line

**Comment by mag009** [comment]
Yes you are right it wasn't the issue.. but I still have issue : 

2015/03/25 13:44:07 [I] Starting Grafana
2015/03/25 13:44:07 [I] Version: 2.0.0-prebeta2, Commit: 9c5e116, Build date: 2015-03-25 13:14:45 +0000 UTC
2015/03/25 13:44:07 [I] Config: Loaded from /etc/grafana/grafana.ini
2015/03/25 13:44:07 [I] Database: mysql, ConnectionString: gl_grafana:aNwHgMKhTbBU@tcp(db-gli:3306)/grafana?charset=utf8
2015/03/25 13:44:07 [I] Migrator: Starting DB migration

Nothing on the myslq I get a connection but it's sleeping thats it.

**Comment by torkelo** [comment]
@mag009 how did you solve this issue? What was the cause? I think I remember you saying it was a config issue?

**Comment by mag009** [comment]
@torkelo  yes it was an issue with my config ( missing the auth google etc) I wasn't using the default.ini when I did the upgrade.
