### ISSUE TITLE
Error when switching visualization to Gauge

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#16534]
**What happened**:
Switching any Singlestat graph to Gauge results in an error:
undefined is not iterable (cannot read property Symbol(Symbol.iterator))

Attempted to load the Query Inspector, but just got "Loading query inspector..." Loads fine when not set to Gauge.

**What you expected to happen**:
Gauge to display some data,

**How to reproduce it (as minimally and precisely as possible)**:
For me it is reproducible on any data format with any visual switched to Gauge

**Environment**:
- Grafana version: 6.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10, Chrome

**Comment by torkelo** [comment]
Tried to switch a bunch of Singlestats to Gauge without any error. Query Inspector is also working fine. 

Test on master (v6.2-pre) and latest stable release v6.1.3

Can you replicate here?
https://play.grafana.org/d/000000006/new-features-in-v1-9?tab=visualization&orgId=1&fullscreen&edit&panelId=17

**Comment by mskorge** [comment]
I'm seeing the same thing. First detected when switching from graph to gauge, but also when just adding a new gauge widget. 
Using InfluxDB as backend.
Tried simplifying the query but didn't help:
`SELECT last("rt:activeUsers") FROM "analytics" WHERE ("webStore" = 'example.com') AND $timeFilter`

Getting the following in the browser console:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.l (tslib.es6.js:108)
    at Ls (SingleStatEditor.tsx:10)
    at Object.t.getProcessedValues (PieChartPanel.tsx:34)
    at new t (SingleStatValueEditor.tsx:17)
    at ui (react-dom.production.min.js:132)
    at Mo (react-dom.production.min.js:167)
    at Fo (react-dom.production.min.js:180)
    at Va (react-dom.production.min.js:232)
    at qa (react-dom.production.min.js:233)
    at Ls (react-dom.production.min.js:249)

**Comment by torkelo** [comment]
Still unable replicate, but found another issue: https://github.com/grafana/grafana/issues/16546 

Can you show the raw response from your query in Query Inspector?

**Comment by MelonSmasher** [comment]
I'm experiencing the same issue on Grafana v6.1.3 (9504db8).

The query inspector does not load any results wen the Gauge visualization is selected, it spins on `Loading query inspector...` . I've pasted the query inspector results from the Single Stat visualization results. This may be related, I have the panel set to repeat for each `$location` tag value from influx.

Hope this helps.

Query:
```sql
SELECT distinct("value") FROM "autogen"."nest" WHERE ("key" = 'temperature' AND "location" =~ /^$location$/) AND $timeFilter GROUP BY time($__interval) fill(null)
```

Single Stat Results:
```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/2/query",
    "params": {
      "db": "nest",
      "q": "SELECT distinct(\"value\") FROM \"autogen\".\"nest\" WHERE (\"key\" = 'temperature' AND \"location\" =~ /^Basement$/) AND time >= now() - 1h GROUP BY time(1m) fill(null)",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms"
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "nest",
            "columns": [
              "time",
              "distinct"
            ],
            "values": [
              [
                1555108740000,
                65.425982
              ],
              [
                1555108800000,
                65.425982
              ],
              [
                1555108860000,
                65.425982
              ],
              [
                1555108920000,
                65.425982
              ],
              [
                1555108980000,
                65.425982
              ],
              [
                1555109040000,
                65.425982
              ],
              [
                1555109100000,
                65.425982
              ],
              [
                1555109160000,
                65.425982
              ],
              [
                1555109220000,
                65.425982
              ],
              [
                1555109280000,
                65.425982
              ],
              [
                1555109340000,
                65.425982
              ],
              [
                1555109400000,
                65.425982
              ],
              [
                1555109460000,
                65.425982
              ],
              [
                1555109520000,
                65.425982
              ],
              [
                1555109580000,
                65.425982
              ],
              [
                1555109640000,
                65.425982
              ],
              [
                1555109700000,
                65.425982
              ],
              [
                1555109760000,
                65.425982
              ],
              [
                1555109820000,
                65.425982
              ],
              [
                1555109880000,
                65.425982
              ],
              [
                1555109940000,
                65.425982
              ],
              [
                1555110000000,
                65.425982
              ],
              [
                1555110060000,
                65.425982
              ],
              [
                1555110120000,
                65.425982
              ],
              [
                1555110180000,
                65.425982
              ],
              [
                1555110240000,
                65.425982
              ],
              [
                1555110300000,
                65.425982
              ],
              [
                1555110360000,
                65.425982
              ],
              [
                1555110420000,
                65.425982
              ],
              [
                1555110480000,
                65.425982
              ],
              [
                1555110540000,
                65.425982
              ],
              [
                1555110600000,
                65.425982
              ],
              [
                1555110660000,
                65.425982
              ],
              [
                1555110720000,
                65.425982
              ],
              [
                1555110780000,
                65.425982
              ],
              [
                1555110840000,
                65.425982
              ],
              [
                1555110900000,
                65.425982
              ],
              [
                1555110960000,
                65.425982
              ],
              [
                1555111020000,
                65.425982
              ],
              [
                1555111080000,
                65.425982
              ],
              [
                1555111140000,
                65.425982
              ],
              [
                1555111200000,
                65.425982
              ],
              [
                1555111260000,
                65.425982
              ],
              [
                1555111320000,
                65.425982
              ],
              [
                1555111380000,
                65.425982
              ],
              [
                1555111440000,
                65.425982
              ],
              [
                1555111500000,
                65.425982
              ],
              [
                1555111560000,
                65.425982
              ],
              [
                1555111620000,
                65.425982
              ],
              [
                1555111680000,
                65.425982
              ],
              [
                1555111740000,
                64.435982
              ],
              [
                1555111800000,
                64.435982
              ],
              [
                1555111860000,
                64.435982
              ],
              [
                1555111920000,
                64.435982
              ],
              [
                1555111980000,
                64.435982
              ],
              [
                1555112040000,
                64.435982
              ],
              [
                1555112100000,
                64.435982
              ],
              [
                1555112160000,
                64.435982
              ],
              [
                1555112220000,
                64.435982
              ],
              [
                1555112280000,
                64.435982
              ]
            ]
          }
        ]
      }
    ]
  }
}
```

<img width="1316" alt="Screen Shot 2019-04-12 at 7 35 50 PM" src="https://user-images.githubusercontent.com/1491053/56071162-7271a100-5d5a-11e9-810a-caea657c4778.png">
<img width="1290" alt="Screen Shot 2019-04-12 at 7 36 15 PM" src="https://user-images.githubusercontent.com/1491053/56071164-77365500-5d5a-11e9-8ef3-2b09e2f7ff2b.png">

**Comment by LeVeloute** [comment]
Same problem. Got this error with fresh install a just create a Gauge panel :(

**Comment by torkelo** [comment]
This should be fixed in the nightly build, can anyone test?  hope to release this fix today in v6.1.4,  but no 100% sure as I got a different error

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/issues/16546 (I think)

**Comment by Aqualie** [comment]
Running 6.2.0 I'm still having this same message trying to create a gauge panel.

**Comment by PeggyFree** [comment]
I upgraded to 6.1.4 yesterday, and I get the same error when creating a new gauge. My old gauges still work. When I created this new gauge, the first error I got is the "interval not valid blah". Now I get the "undefined is not iterable" error.

Influxdb updated yesterday
Grafana 6.1.4
Windows

**Comment by torkelo** [comment]
There is still an open issue for this: https://github.com/grafana/grafana/issues/16762
