### ISSUE TITLE
Beta: New opentsdb alias patterns don't seem to work with multiple metrics

### ISSUE THREAD

**Issue by alienth** [grafana/grafana#1733]
A bit hard to explain, so let me just include some pretty pictures:

As you can see below, I have two metrics defined. The upper one is an aggregate, and the lower one is a breakdown of all of the site tags. I have an alias defined for the aggregate.
![image](https://cloud.githubusercontent.com/assets/218431/7057991/a2596716-de08-11e4-95a5-6f8ea3f31321.png)

The result of the above is as follows:

![image](https://cloud.githubusercontent.com/assets/218431/7058075/7903b848-de09-11e4-847d-b6984417a3ff.png)

(I added the black bars added over axis and values)

As you can see, the alias from the first metric has somehow applied to all of the tags from the second metric. Adding a specific alias to the second metric doesn't resolve the issue.

I should note that this issue just started with the new beta. In alpha, the above metric layout worked as expected (however a reversed ordering of the metrics did not work properly, which was another bug).

**Comment by alienth** [comment]
Just realized a similar problem happens with two metrics each having a specified tag. The top alias will always override the lower alias.

**Comment by torkelo** [comment]
Fixed in master and latest beta2 build (http://grafana.org/download/builds)
https://github.com/grafana/grafana/commit/1bd238191c49517032de43d1ed27db3cb5783a80

**Comment by alienth** [comment]
This appears to address the second case, where I have two metrics with different aliases each having a specified tag. However the first case I which I screenshotted is still occurring: the alias from the first metric is applying to all of the tags from the second metric.

**Comment by torkelo** [comment]
That is fixed

**Comment by agaoglu** [comment]
I see a somewhat similar issue in beta3. I use the same metric, no tags but with different aggregators (max, avg, min). Then i was using fill-below-to, it was OK in 1.9.

**Comment by torkelo** [comment]
@agaoglu hm.. damit, so hard to solve this issue (matching query to returned series, this needs to be solved in OpenTSDB!)

**Comment by agaoglu** [comment]
agreed, response contains aggregateTags but does not tell how they are aggregated. workaround maybe?

**Comment by agaoglu** [comment]
Found the issue

https://github.com/OpenTSDB/opentsdb/issues/438
