### ISSUE TITLE
remote_cache: redis: invalid expire time in setex

### ISSUE THREAD

**Issue by gjcarneiro** [grafana/grafana#17377]
**What happened**:

After #17375, I tried to work around by using redis as remote_cache.  I added this config:

```
    [remote_cache]
    type = redis
    connstr = redis:6379
```

Now I see these errors in logs:

```
t=2019-05-30T16:20:26+0000 lvl=eror msg="auth proxy: failed to store user in cache" logger=context message="failed to store user in cache" error="ERR invalid expire time in setex"
t=2019-05-30T16:20:26+0000 lvl=eror msg="failed to store user in cache" logger=context error="ERR invalid expire time in setex"
```

**Also** there is this other bug: documentation is wrong: it says
> Redis example config: `addr=127.0.0.1:6379,pool_size=100,db=grafana`

But if I put `addr=redis:6379`  as connection string it says it cannot find host `addr=redis`, so it tries to use `addr=redis` as hostname, I assume.  I had to remove the `addr=` part.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
    [remote_cache]
    type = redis
    connstr = redis:6379
```

Where `redis` is the hostname of a redis server

**Anything else we need to know?**:

redis_version:3.2.12

**Environment**:
- Grafana version: 6.2.1
- Data source type & version:
- OS Grafana is installed on: official docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment]
Should be fixed by the above two commits

**Comment by gjcarneiro** [comment]
Switch the `latest` and still get:

```
t=2019-06-18T11:05:41+0000 lvl=eror msg="auth proxy: failed to store user in cache" logger=context message="failed to store user in cache" error="ERR invalid expire time in setex"
t=2019-06-18T11:05:41+0000 lvl=eror msg="failed to store user in cache" logger=context error="ERR invalid expire time in setex"
```

**Comment by gjcarneiro** [comment]
Oh, yes, I've since been told, `latest` points to 6.2.2, not 6.2.3, that will explain why it's not fixed :(

**Comment by kylebrandt** [comment]
@gjcarneiro Sorry for the confusion. 6.2.4 is being worked on now and should be out today.

**Comment by gjcarneiro** [comment]
Indeed.  I've already deployed 6.2.4 and can confirm that this bug is fixed.  Thanks!
