### ISSUE TITLE
Tables with NaN or absent values sort incorrectly

### ISSUE THREAD

**Issue by VictorGavrish** [grafana/grafana#17752]
**What happened**:

I have three columns in a table. One is the total time a single endpoint was processing requests, one is the number of times the endpoint is hit, and the third is the average time an endpoint took to process a request. The third is calculated by dividing the first by the second.

This works, but when I try to sort a table on the third column, the values come out in seemingly random order:

![image](https://user-images.githubusercontent.com/11678899/60090239-d517ed80-974a-11e9-9575-010275a5e4f5.png)

This happens if any of the counts are 0, making the division return `NaN`. The same thing happened when a value was simply missing for a column, but there is data for other columns.

**What you expected to happen**:

I expected the missing values to be sorted to the end of the table, or at least an option somewhere to map NaN to 0 or something. So far I've found no workaround.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure what's the easiest way to reproduce this, but I'll talk about the setup.

I'm not sure if my backend is relevant, but it is Prometheus for my case. In order to reproduce, have Prometheus record a single Histogram metric, which includes a `_sum` and a `_count` field. Let's call them `request_duration_sum` and `request_duration_count`. The metric has an `endpoint` tag. Then configure a table with three inputs:

```prometheus
sum(increase(request_duration_sum[1h])) by (endpoint)
sum(increase(request_duration_count[1h])) by (endpoint)
sum(increase(request_duration_sum[1h])) by (endpoint) / sum(increase(request_duration_count[1h])) by (endpoint)
```

![image](https://user-images.githubusercontent.com/11678899/60091356-10b3b700-974d-11e9-8a24-cd16a459a163.png)

If then Prometheus then has data for an endpoint, but it hasn't been hit in the relevant timeframe, sorting by the third column becomes meaningless.

**Environment**:
- Grafana version: v6.2.2 (07540df)
- Data source type & version: Prometheus 2.3.2
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10, Firefox 67.0.2
- Grafana plugins: Nothing relevant

**Comment by dprokop** [comment]
@VictorGavrish thanks for reporting! Can you also please share your panel data with us?

**Comment by torkelo** [comment]
Can you show the output from query inspector?

**Comment by VictorGavrish** [comment]
I can't show the full output of query inspector (it's from my job, so I have to edit the names of endpoints, and the actual output has 7199 results that I'd have to go through), but I've created a reduced version with only the results that show up as the first four (preserved in the order that they were in the original file) here:

```json
{
    "xhrStatus": "complete",
    "request": {
      "method": "GET",
      "url": "api/datasources/proxy/29148/api/v1/query?query=sum(increase(request_duration_sum%5B1h%5D))%20by%20(endpoint)%20%2F%20sum(increase(request_duration_count%5B1h%5D))%20by%20(endpoint)&time=1561547899"
    },
    "response": {
      "status": "success",
      "data": {
        "resultType": "vector",
        "result": [
          {
            "metric": {
              "endpoint": "/request4"
            },
            "value": [
              1561547899,
              "4540.869676762092"
            ],
            "values": [
              [
                1561547899,
                "4540.869676762092"
              ]
            ]
          },
          {
            "metric": {
              "endpoint": "/request3"
            },
            "value": [
              1561547899,
              "NaN"
            ],
            "values": [
              [
                1561547899,
                "NaN"
              ]
            ]
          },
          {
            "metric": {
              "endpoint": "/request1"
            },
            "value": [
              1561547899,
              "1073.709211765576"
            ],
            "values": [
              [
                1561547899,
                "1073.709211765576"
              ]
            ]
          },
          {
            "metric": {
              "endpoint": "/request2"
            },
            "value": [
              1561547899,
              "5"
            ],
            "values": [
              [
                1561547899,
                "5"
              ]
            ]
          }
        ]
      }
    }
  }
```

The first items that show up like this:

![image](https://user-images.githubusercontent.com/11678899/60176264-8176d400-981e-11e9-8479-d286088343bb.png)

**Comment by ryantxu** [comment]
For sure we should fix this in:
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/utils/processSeriesData.ts#L185

but that will only fix the react table (and everything else using series data)

**Comment by dprokop** [comment]
For this particular case (Table panel) the fix should be done in https://github.com/grafana/grafana/blob/master/public/app/core/table_model.ts#L41

**Comment by hawran** [comment]
> For this particular case (Table panel) the fix should be done in https://github.com/grafana/grafana/blob/master/public/app/core/table_model.ts#L41

I think the problem is still here:
![Screenshot_2019-12-03_17-25-54 table sort-issue NaN](https://user-images.githubusercontent.com/25924718/70070036-29c16d80-15f3-11ea-9803-52b17c0026f8.png)
`Grafana v6.4.4 (NA)`

**Comment by paulnickerson-shadowhealth** [comment]
Has anyone found a workaround for this?

**Comment by hugohaggmark** [comment]
Hi @VictorGavrish I'm looking into this and I can confirm that this was a bug in 6.2.2 of Grafana but if I upgrade to version 7 of Grafana and use the `Labels to Fields` transform,  I'm no longer able to reproduce this using the data provided.

Closing this issue because I can't repro it in 7.0. We can always reopen this issue if there are additional facts that point in that direction.
