### ISSUE TITLE
Panel Rendering: Handle longer query times better

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#1933]
There seems to be a bug in the "direct link rendered image" - every time i click it (on any of a our dashboards) I get an image of the blank dashboard with the loading icon.

![image](https://cloud.githubusercontent.com/assets/12067107/7454078/502fa8d4-f23e-11e4-9e17-03561ff6e530.png)

**Comment by torkelo** [comment]
strange, how long does the query take to execute? If it is very long it could be that the phantomjs rendering code timeouts (it is waiting for the canvas/graph element to show), but timeout after a while.

**Comment by agaon** [comment]
I think I narrowed down the conditions a little bit - it seems to only happen now when the dashboard has many metrics (or wildcards) or many function. the query seems to execute at around the same time though, no matter what the results are.

**Comment by torkelo** [comment]
you mean when the graph has many metrics? How long does the metric request take for this graph?

**Comment by agaon** [comment]
the initial load (from selecting the dashboard until it is displayed) takes ~15 sec

**Comment by torkelo** [comment]
@agaon WOW, what the heck kind of query is that? Metric requests with graphite are usually arround 50ms - 500ms

**Comment by torkelo** [comment]
what data source are you using and what does the query look like, how much data is returned?

**Comment by agaon** [comment]
We monitor our production environment, so this query is looking at hundreds of servers....  it is getting a simple metric (disk partition used), offsetting it and showing only a subset of the results ("currentbelow")

**Comment by torkelo** [comment]
@agaon I see

currently the phantomjs render code will capture an image as soon as the canvas element is added, and will timeout and capture the image anyway after 1.2 seconds. Currently it is not possible to change this timeout

**Comment by elnappo** [comment]
Same issue here, can't render two series with 10s resolution over one month with InfluxDB.

**Comment by torkelo** [comment]
@elnappo of course not! you have to roll up your data, a query like that should take 150ms if you had the right roll ups. This is o ly an issue with InfluxDB users (they don't use roll ops and get slow queries). 

If you metric query takes more than 1 second you are using your TSDB WRONG. 

But anyway will fix this so the timeout is more dynamic :)

**Comment by tuxinaut** [comment]
+1

**Comment by mgravlin** [comment]
+1 same issue here

**Comment by srfraser** [comment]
I'm also having this issue, using InfluxDB. However, I'm using rolled up queries, and using 'curl' to get the data from InfluxDB takes 100-200ms for each metric on the graph. There are two such queries for the graph I'm having intermittent trouble with.

Examining the queries using the browser developer tools, the queries take around 700ms to respond when loading the graph in grafana. 

It'd be easier if the renderer produced an error if the timeout was reached, as then I'd know to retry.

**Comment by thenayr** [comment]
+1 this issue, graphite user here.

**Comment by trinitronx** [comment]
Also seeing this on a Graphite-backed Grafana graph which has 60 `graph-legend-series` metrics in it.  Lots of metrics on a single Graphite query may be a good way to reproduce this (e.g.: `foo.bar.*.metric.name`)

**Comment by christianchristensen** [comment]
I'm seeing this same problem - it appears inconsistent; but when saving to a link for example, the timeout looks to be hard coded to 4s: [shareSnapshotCtrl.js#L35-L48](https://github.com/grafana/grafana/blob/59fc72d37e252a3b848ce5b891c017cdc87974d0/public/app/features/dashboard/shareSnapshotCtrl.js#L35-L48)

Bumping this up by hand verifies that longer queries (that are re-run on the snapshot button press).

Interestingly - one use case of this feature is to take a relatively complicated query and visual setup, snapshot it, so the penalty or retention policy is not a problem for other users it's shared with.

**Comment by charlesg3** [comment]
Hi!

I'm using ElasticSearch as our backend and I'm seeing the same issue, though the graphs show data on the regular dashboard. I see no mention of phantomjs errors in the log.

**Comment by torkelo** [comment]
this is fixed in master (I think)

**Comment by balrogthane** [comment]
Hello, I am still seeing this issue with our Grafana instance. We're using InfluxDB and a simple query, and usually the graph generates in well under a second. But intermittently it takes longer, and sometimes that gives us the loading screen snapshots. I think the ultimate culprit is probably the InfluxDB instance, as whenever we get a loading snapshot we get them across all our rendering code at the same time, but it's definitely still happening occasionally.

**Comment by tokudan** [comment]
I seem to face this issue as well since I upgraded to grafana 3. With 2.6 everything was working, but with version 3 only one of the two images we currently use is successfully generated.
This generated image works:
https://statistik.hamburg.freifunk.net/render/dashboard-solo/db/freifunk-ubersicht?panelId=1&fullscreen&var-region=ffhh&theme=light&width=530&height=332&from=now-3d

This image seems to fail:
https://statistik.hamburg.freifunk.net/render/dashboard-solo/db/freifunk-knoteninfo-knoten-id?panelId=1&fullscreen&var-region=ffhh&var-knoten=14cc20b4c774&theme=light&width=530&height=332&from=now-3d
The base graph sitting behind this can be found here and it does not seem to take long to load:
https://statistik.hamburg.freifunk.net/dashboard/db/freifunk-knoteninfo-knoten-id?panelId=1&fullscreen&var-region=ffhh&var-knoten=14cc20b4c774&theme=light&width=530&height=332&from=now-3d

Is there any way of increasing the timeout?

**Comment by balrogthane** [comment]
It looks like the file [render.js](https://github.com/grafana/grafana/blob/master/vendor/phantomjs/render.js) returns a valid PNG if:

1. The panel(s) actually render
2. The hardcoded number of checks (1000 at one per 10 ms, or 10 seconds) is reached

It would be great if an error could be thrown if the timeout is reached, instead of just rendering anyway and passing the result back. I am familiar with JavaScript and somewhat familiar with PhantomJS, but don't know Go at all so I can barely make sense of [renderer.go](https://github.com/grafana/grafana/blob/master/pkg/components/renderer/renderer.go), much less suggest modifications.
