### ISSUE TITLE
Table columns rearrange when query is run

### ISSUE THREAD

**Issue by cstyan** [grafana/grafana#19448]
**What happened**:
We have a dashboard with a table panel that contains resource usage for k8s pods. I wanted to sort the table by memory usage, so I clicked on the column heading. The next time Grafana executed the query (the dashboard has 10s refresh) the columns reordered, and the column I was trying to look at now was now on the opposite side of the table.

**What you expected to happen**:
Table columns to stay in the same place even with a page refresh.

**How to reproduce it (as minimally and precisely as possible)**:
Load a dashboard with a table panel, use the refresh button in the top right and watch the columns reorder.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.5.0-pre (commit: a3008ff)
- Data source type & version: prometheus
- User OS & Browser: linux, firefox

**Comment by torkelo** [comment]
This does not look like a new issue but due the fact that Prometheus issues each query separately and the combined result is not sorted. Each query result is sorted (as Prometheus returns series in non-deterministic order). 

But the total combined series list is not sorted so the result given to the panel will differ depending on when queries finish.

**Comment by torkelo** [comment]
Not sure what the solution is here as we now always return query results as they come there is no opportunity to add sorting in the data source and Grafana usually leaves sorting up the query/data source as it can handle that much better. 

ideas @davkal  ?

**Comment by bswinnerton** [comment]
Is it possible this was resolved by f9611250eaada546b9b24429dc010c4969d48c28? Pinning Grafana to [`v6.3.6`](https://github.com/grafana/grafana/tree/v6.3.6) has temporarily resolved this problem until a new release is cut.

**Comment by weeco** [comment]
@torkelo @cstyan The problem seems to be resolved (along with reandomly switching label colors) after updating Grafana from 6.4.1 to 6.4.2

**Comment by ivanahuckova** [comment]
This issue was fixed in 6.4.2 by #19597.

**Comment by orena1** [comment]
@ivanahuckova  I think the problem is back now with grafana 7 can you please verify?
Thanks

**Comment by orena1** [comment]
Problem re-emerged in 7.0 and is fixed:
https://github.com/grafana/grafana/pull/24705
