### ISSUE TITLE
Data link URL field turns read-only for graph panels

### ISSUE THREAD

**Issue by filippog** [grafana/grafana#19477]
**What happened**:

While testing data links in graph panel, the URL field turns read-only (can't click on it to edit) after clicking on the time series in the graph to preview what the data link will look like. The workaround I found is to change "card" on the left say to "general" and then go back to "visualization", after that the data link URL field is editable again.

**What you expected to happen**:
The URL field keeps being editable after testing by left-clicking on a time serie in the graph.

**How to reproduce it (as minimally and precisely as possible)**:
- fill in a graph panel data link title and URL
- click one of the series in the graph to preview what the data link will look like
- URL field isn't editable anymore

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.0-beta2
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this @filippog we'll take a look!

**Comment by torkelo** [comment]
unable to replicate this. Do you still get this on 6.4.2 ?

**Comment by filippog** [comment]
@hugohaggmark @torkelo thanks for taking a look! Confirmed I can replicate this on 6.4.2 too (with chrome 77 at least). I'm able to minimally reproduce with these steps:

* `docker run --network host grafana/grafana:6.4.2`
* login as admin, create a new dashboard an add a graph panel
* scroll down to data links and add one, title/url can be arbitratry
* click on "A-series" in the graph to preview what the newly added data link will look like
* the url field for the datalink now has turned read-only (i.e. can't click on it to edit)
* changing tab to e.g. "queries" and switching back to "visualization" makes the data link url editable again

Hope that helps!

**Comment by aocenas** [comment]
This should be fixed by https://github.com/grafana/grafana/pull/19883

**Comment by dprokop** [comment]
@aocenas just tested this on master and this is not fixed unfortunately

**Comment by aocenas** [comment]
So seems like I cannot reproduce this, while @dprokop and @peterholmberg can. No idea why so far.

**Comment by aocenas** [comment]
So this only happens for me when I click into title, then into the graph and then into the url input. Still no idea why though.

**Comment by aocenas** [comment]
@dprokop So I got far enough that it seems this is not an issue of the Slate component. The title input has an onBlur and it seems that because of that onBlur and then clicking into the Graph it somehow captures the native window selection in a way that you cannot actually select anything else afterwards. Even if you remove the slate editor from the page, if you click into the title, then into the graph, you cannot select event normal selectable text on the page anymore.

**Comment by filippog** [comment]
Fantastic! Thanks for working on this
