### ISSUE TITLE
Pie charts not rendered

### ISSUE THREAD

**Issue by pbuentam** [grafana/grafana#19507]
**What happened**:

Pie charts are not been rendered if there are several panels in the dashboard before them. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

A templated dashboard with 72 panels (graph and single stat) before 20 pie chart panels (version 1.3.8) 

![Captura](https://user-images.githubusercontent.com/38005863/65888274-88722d00-e39f-11e9-8058-60e8c089fb5b.PNG)

If I put all the panels, but the piecharts, inside a row and colapse it, they render properly.
 
![Captura](https://user-images.githubusercontent.com/38005863/65888565-07676580-e3a0-11e9-824c-e74690e78b32.PNG)

**Anything else we need to know?**:
The datasource is an elasticsearch

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Elasticsearch 
- OS Grafana is installed on: RedHat 7.4
- User OS & Browser: Windows 7, IE 11, firefox 69, Chrome 77
- Grafana plugins: Datatable panel, Diagram, Discrete, plotly, singlestat math, status panel, status dot
- Others:

**Comment by torkelo** [comment]
update pie chart plugin, should fix it

**Comment by pbuentam** [comment]
Just upgraded it from 1.3.8 to 1.3.9 the issue is still there. Tomorrow I will upgrade Grafana to 6.3.6, just in case.

**Comment by pbuentam** [comment]
I have tried upgrading grafana to 6.3.6 and 6.4.0 but the issue persists

Kind regards

**Comment by torkelo** [comment]
maybe it's one of your other plugins that is causing it? can you try adding them one by one (on a dashboard)

**Comment by pbuentam** [comment]
I have found the plugin that is broking it. I was not aware that someone has used Graph Compare Panel. A panel plugin that is not published on Grafana site. I will look for an alternative for its functionality using an elasticsearch datasource.
