### ISSUE TITLE
Grafana TestData DB bug

### ISSUE THREAD

**Issue by Mixajlo14** [grafana/grafana#19769]
**What happened**: 
I tried to add some test data on Grafana for Scenario **Manual Entry**. When I use current time everything works fine, when I try to change time problem happen. Tried to add some value for days in the past and future.

**What you expected to happen**:
To add value for the timestamp from the past or in the future.

**How to reproduce it (as minimally and precisely as possible)**:
- select Test DB as Datasource
- select Manual Entry Scenario
- Change time parameter (set some date from the past)
- Set value (We used integer value)
- Click on Add button

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3 and 6.4.2
- Data source type & version: TestData DB
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 10 Firefox
- Grafana plugins:
- Others:
  * Also can be reproduced on https://play.grafana.org (version 6.4.1)
  * Error from the log file
```
t=2019-10-10T15:20:27+0200 lvl=eror msg="Request error" logger=context userId=15 orgId=1 uname=m.djordjevic error="interface conversion: interface {} is string, not json.Number" stack="/usr/local/go/src/runtime/iface.go:248 (0x414965)\n/go/src/github.com/grafana/grafana/pkg/tsdb/testdata/scenarios.go:172 (0x117c211)\n/go/src/github.com/grafana/grafana/pkg/tsdb/testdata/testdata.go:34 (0x117a5fe)\n/go/src/github.com/grafana/grafana/pkg/tsdb/request.go:17 (0xa90aa9)\n/go/src/github.com/grafana/grafana/pkg/api/metrics.go:49 (0x12404b3)\n/usr/local/go/src/reflect/value.go:447 (0x491bf0)\n/usr/local/go/src/reflect/value.go:308 (0x491673)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x8a4806)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8a40fb)\n/go/src/github.com/grafana/grafana/pkg/api/common.go:37 (0x126336d)\n/usr/local/go/src/reflect/value.go:447 (0x491bf0)\n/usr/local/go/src/reflect/value.go:308 (0x491673)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x8a4806)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8a40fb)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x8a58b9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xbae9be)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xbae9b1)\n/usr/local/go/src/reflect/value.go:447 (0x491bf0)\n/usr/local/go/src/reflect/value.go:308 (0x491673)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x8a4806)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8a40fb)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x8a58b9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xbae1dc)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xbae1c7)\n/usr/local/go/src/reflect/value.go:447 (0x491bf0)\n/usr/local/go/src/reflect/value.go:308 (0x491673)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x8a4806)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8a40fb)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x8a58b9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xbae0f5)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:147 (0xbae0e3)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x8a5760)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x8a44c0)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x8a41ea)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x8a58b9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0xbab60b)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xbab5f6)\n/usr/local/go/src/reflect/value.go:447 (0x491bf0)\n/usr/local/go/src/reflect/value.go:308 (0x491673)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x8a4806)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x8a40fb)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x8a58b9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x8b6c66)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:294 (0x8b167d)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x8aa90c)\n/usr/local/go/src/net/http/server.go:2774 (0x6f13b7)\n/usr/local/go/src/net/http/server.go:1878 (0x6ed0a0)\n/usr/local/go/src/runtime/asm_amd64.s:1337 (0x4680e0)\n"
```

**Comment by marefr** [comment]
Fixed by #19409. Will be included in Grafana v6.5 and is available in nightly builds now.

**Comment by Mixajlo14** [comment]
Hi @marefr, this bug still exists, I tested it on versions 6.5.2 and 6.6.1. When I try to change Date and Time for **TestDB Manual Entry** Scenario, I am getting **invalid date** error, and in DB instead of timestamp staying **null**.

**Comment by marefr** [comment]
@Mixajlo14 works for me using for example "Fri Feb 28 2020 11:15:09 GMT+0100" as timestamp

**Comment by Mixajlo14** [comment]
@marefr It works for current time, but when you try to change for example to set "Fri Feb 01 2020 00:00:09 GMT+0100"

Even when I set **time** parameter as a string ( Feb 01 2020 00:00:09 GMT+0100) or timestamp(1580511609000) , this error occurs. I tried this on https://play.grafana.org.

![TestFromPlayGrafana](https://user-images.githubusercontent.com/24840317/75540978-64ce1400-5a1d-11ea-9f3e-66d9606d9758.PNG)

**Comment by marefr** [comment]
@Mixajlo14 I guess the user experience could be better here, but you'll need to include the weekday `Fri` as I did. The current date and time are pre-filled so important to use the same format.

**Comment by Mixajlo14** [comment]
@marefr Thanks for trying to help me, I saw just now that in last comment I forget to add weekday.
But we still have some misunderstandings about this issue, I'll try to write all steps that I am doing, so you can reproduce same issue that I am getting.

1. Open any graph on https://play.grafana.org
2. Change Data source for that graph to **Grafana TestData**
3. Set Scenario **Manual Entry**
4. Set any **alias** that you want eg. **test**
5. Add some integer as **New value** eg. **123**
6. Update **Time** parameter, for example: **Decrease hours for one, set 11.**
7. And try to add that value

In this case I am getting error Invalid date. Hope this will help you to reproduce this issue.

Kind regards for all your help

**Comment by marefr** [comment]
Thanks, was able to reproduce that. We're not currently planning to work on this, but anyone that wants to help out is welcome to contribute.

**Comment by Mixajlo14** [comment]
Hi @marefr , after some research I figure out that this problem can be solved only with changing default format of time parameter. 
When I use time format which is used in previous versions of Grafana `2020-01-01 11:31:29` instead of `Wed Jan 01 2020 11:31:29 GMT+0100` everything works as expected. 
Also this format is works fine `2019-05-09T08:25:22+00:00`. 

Probably is this issue related with this line and ISO 8601:

https://github.com/grafana/grafana/blob/e2038e061488aa001ed0ef17ea66f69f5e68450c/packages/grafana-data/src/datetime/datemath.ts#L62

**Comment by torkelo** [comment]
This manual entry scenario in the test data source will probably be removed, replaced with google sheets data source (and the csv input data source)
