### ISSUE TITLE
github enterprise login_oauth , failed to exchange token

### ISSUE THREAD

**Issue by williamjoy** [grafana/grafana#1995]
Hi, I can pass oauth authentication step but after this, grafana use the token to fetch user info failed.

I was unable to debug the payload sent to https://github.XXXXX.net/api/v3/user as it is encrypted, can you help on this? If debug log can be enabled it can help a lot :)
```
2015/05/14 14:07:44 [I] Completed / 302 Found in 71.395943ms
2015/05/14 14:08:10 [I] Completed /login/github 302 Found in 1.132814ms
2015/05/14 14:09:17 [I] Completed /login/github 302 Found in 746.366µs
2015/05/14 14:13:28 [T] login.OAuthLogin(Got token)
2015/05/14 14:13:28 [login_oauth.go:48 OAuthLogin()] [E] login.OAuthLogin(get info from github): Get https://github.XXXXX.net/api/v3/user: oauth2: token expired and refresh token is not set
2015/05/14 14:13:28 [I] Completed /login/github 500 Internal Server Error in 1.880940348s
```

**Comment by williamjoy** [comment]
not sure if the api_url is correct for grafana, but I can use curl to fetch user info successfully like below

```
curl -v  -d '{"scopes":["user:email"], "note": "hello world"}' https://test-account:password_XXXX@github.XXXXX.net/api/v3/user
```

**Comment by torkelo** [comment]
did you specify api url in config?

**Comment by williamjoy** [comment]
yes, all urls start with same domain
```
scopes = user:email
auth_url = https://github.XXXXX.net/login/oauth/authorize
token_url = https://github.XXXXX.net/login/oauth/access_token
api_url = https://github.XXXXX.net/api/v3/user
# Uncomment bellow to only allow specific email domains
```

**Comment by torkelo** [comment]
ping  @williamjoy any idea of what could be wrong?

**Comment by williamjoy** [comment]
I can't see github api response so not clear about this. I just guess maybe github enterprise disabled the api if using token ?

I am just a github enterprise user I don't know if this requires config in github server side.

I tried to and some debug log to see the api response which should contain the error reason but failed to build from  the grafana code . to many go package decencies :)

**Comment by torkelo** [comment]
@williamjoy but you specified client_id and client_secret?

**Comment by williamjoy** [comment]
Yes,  I did

**Comment by torkelo** [comment]
but it was you who implemented this feature, did you not test it before submitting your PR? I do not have a github enterprise server to test this against, 

https://github.com/grafana/grafana/pull/1782

**Comment by mgravlin** [comment]
I am experiencing the *exact* same problem with Github Enterprise. It does not seem to work.

**Comment by torkelo** [comment]
Someone with github for enterprise will have to debug and troubleshoot it

**Comment by williamjoy** [comment]
Sorry @torkelo , I failed at `go build` and didn't test it. 
Finally I got the reason, https://github.com/slackhq/slack-api-docs/issues/18#issuecomment-72201873
:)
oauth golang lib does send client_secret in post data but in Header, white from github official doc, it says require this is required as post parameter, https://developer.github.com/v3/oauth/#parameters-1

Just add `client_secret` in post parameter then I see got my github login and email from log
```
diff --git a/Godeps/_workspace/src/golang.org/x/oauth2/oauth2.go b/Godeps/_workspace/src/golang.org/x/oauth2/oauth2.go
index 0c6a1ed..87dc32e 100644
--- a/Godeps/_workspace/src/golang.org/x/oauth2/oauth2.go
+++ b/Godeps/_workspace/src/golang.org/x/oauth2/oauth2.go
@@ -23,6 +23,7 @@ import (
        "time"
 
        "golang.org/x/net/context"
 )
 
 // NoContext is the default context you should supply if not using
@@ -305,11 +306,13 @@ func retrieveToken(ctx context.Context, c *Config, v url.Values) (*Token, error)
                return nil, err
        }
        v.Set("client_id", c.ClientID)
+       v.Set("client_secret", c.ClientSecret)
        bustedAuth := !providerAuthHeaderWorks(c.Endpoint.TokenURL)
        if bustedAuth && c.ClientSecret != "" {
                v.Set("client_secret", c.ClientSecret)
        }
        req, err := http.NewRequest("POST", c.Endpoint.TokenURL, strings.NewReader(v.Encode()))
```

```
2015/05/17 16:07:50 [T] login.OAuthLogin() HTTP 200 OK, [access_token=e333f3c684a3d556d758cbfd9868577b6514be66&scope=user%!A(MISSING)email&token_type=bearer]
2015/05/17 16:07:50 [T] login.OAuthLogin(Got token) [&{e333f3c684a3d556d758cbfd9868577b6514be66 bearer  0001-01-01 00:00:00 +0000 UTC map[access_token:[e333f3c684a3d556d758cbfd9868577b6514be66] scope:[user:email] token_type:[bearer]]}]
2015/05/17 16:07:51 [T] login.OAuthLogin(social login): &{245 williamwei william.wei@demonware.net  }
2015/05/17 16:07:51 [I] Completed /login/github 302 Found in 3.57159297s
```

**Comment by torkelo** [comment]
I know there has been some updated to golangs oauth2 package, maybe it has been fixed

**Comment by torkelo** [comment]
strange that github public api is having a different oauth2 implementation than github for enterprise

**Comment by williamjoy** [comment]
@torkelo looks like not yet, refer to https://github.com/golang/oauth2/issues/111

**Comment by cjs** [comment]
With the GitHub Enterprise [2.3.4 release](https://enterprise.github.com/releases/2.3.4/notes), the OAuth2 implementation has been made more compliant with the spec and should work with the standard Go libraries without change.  You should no longer need to customize the Go OAuth libraries to authenticate Grafana against GitHub Enterprise.

**Comment by bergquist** [comment]
I'm closing this since it's solved in github enterprise.

**Comment by williamjoy** [comment]
Finally I can verify this feature after our github enterprise upgraded. works well !
thanks!

**Comment by chrisfelix82** [comment]
OK so prior to 2.3 it fails?  I am on GHE 2.8 and it still fails for me :(

**Comment by suresh1209** [comment]
@williamjoy @bergquist  we still have the same issue :(

**Comment by cjs** [comment]
@suresh1209 @chrisfelix82 If you're still having problems contact GitHub Enterprise Support and it will be looked into.
