### ISSUE TITLE
2.1.0-pre1: dashboard templating: checkmark of current value is off by +1

### ISSUE THREAD

**Issue by pret79** [grafana/grafana#2028]
Hi,

Looks like that the checkmark marking the currently used templating value is of by +1. In the screenshot the office-build03 server is shown in the dashboard but the next value (office-build05) is marked with the checkmark. The lowest entry in the dropdown box is always marked correctly:

![grafana](https://cloud.githubusercontent.com/assets/999153/7732564/2a05ed60-ff29-11e4-8cd5-e093406cfc81.png)

BTW: Awesome progress on the InfluxDB 0.9 metrics selector - thanks for that! :)

Greetings,
Markus

**Comment by torkelo** [comment]
that is very strange. Cannot replicate it. Please run "grunt css" to rebuild the css to rule out that it is not just a visual css layout thing (maybe the check gets pushed down one level).

**Comment by pret79** [comment]
I've installed the grafana-2.1.0-pre1.x86_64.rpm (19.5.2015 08:44:50) rpm file so that I'm not sure how to run "grunt css" on top of that. Before installing the latest build I've deleted the previously installed rpm.

**Comment by torkelo** [comment]
ok, then maybe its a browser issue, what os and browser are you using?

**Comment by pret79** [comment]
First screenshot was done with Firefox 37.0.2 (Fedora 20). Konqueror and Chrome shows a different behaviour for the last drop box element:
![grafana_chrome](https://cloud.githubusercontent.com/assets/999153/7745986/688ce3aa-ffaf-11e4-9f23-e9302b9894f5.png)
Firefox shows the last element as as active, Konqueror and Chrome add a new blank line at the end that's marked as active.

**Comment by torkelo** [comment]
Try updating to latest 2.1-pre1 build , I think this is fixed in latest build. Changed the how the checkbox is positioned 2-3 days ago, http://grafana.org/download/builds.html

**Comment by pret79** [comment]
I've just updated to grafana-2.1.0-pre1.x86_64.rpm (5/21/2015, 9:25:22 AM), still the same on all three browsers (I've cleared the caches as well).

**Comment by torkelo** [comment]
very strange, fail to replicate with chrome or firefox (linux)

**Comment by pret79** [comment]
To make sure I didn't had any leftovers from previous Grafana installations I've just deleted all Grafana resources from my server and did a fresh installation - still the same problem after importing the earlier exported dashboard. Anything else I can do to track this down?

**Comment by torkelo** [comment]
If you create a new dashboard from scratch do you get the same behavior?

**Comment by pret79** [comment]
Yes, I can reproduce this with a new dashboard:
![grafana1](https://cloud.githubusercontent.com/assets/999153/7818189/73e71e76-03da-11e5-93a4-c8b881d40a77.png)
![grafana2](https://cloud.githubusercontent.com/assets/999153/7818190/73e7f33c-03da-11e5-9c27-6516f701d9ac.png)
![grafana3](https://cloud.githubusercontent.com/assets/999153/7818191/73e83036-03da-11e5-9013-72cf0ac3b663.png)
![grafana4](https://cloud.githubusercontent.com/assets/999153/7818192/73e8a502-03da-11e5-8855-6a032880d25e.png)
It doesn't matter if the values are defined as a custom list or if queried from InfluxDB. Firefox was used while taking those screenshots.

**Comment by torkelo** [comment]
Solved in 2.1
