### ISSUE TITLE
Alerts Notification Test Works but actual Alerts are not sent to Notification Channels - context deadline exceeded

### ISSUE THREAD

**Issue by bzon** [grafana/grafana#20736]
**What happened**:

Alerts are not sent to the target Notification. I'm seeing context deadline exceeded errors from logs.

**What you expected to happen**:

Alerts are sent to the target Notification.

**How to reproduce it (as minimally and precisely as possible)**:

* Grafana version 6.5.0
* Grafana is configured in HA mode with postgresql database
* Create any kind of slack alerts
* Create a sample alerting graph

**Anything else we need to know?**:

When using Slack, and "Send Test" is clicked, the Test alert is sent successfully.

When alerting from a Graph dashboard, Grafana logs the following errors:

```
prometheus-grafana-6479967497-vrlmf grafana t=2019-11-28T11:07:18+0000 lvl=eror msg="Failed to send alertmanager" logger=alerting.notifier.prometheus-alertmanager error="context deadline exceeded" alertmanager=AlertManager
prometheus-grafana-6479967497-vrlmf grafana t=2019-11-28T11:07:18+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=J5K8bXxWz error="context deadline exceeded"
prometheus-grafana-6479967497-vrlmf grafana t=2019-11-28T11:07:18+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=J5K8bXxWz error="context deadline exceeded"
```

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: prometheus
- OS Grafana is installed on: Kubernetes using the grafana helm chart
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by bzon** [comment]
Issue is now fixed. The context deadline exceeded was cause by a failed image upload to GCS which I had to fix first. 

```
prometheus-grafana-6479967497-6ccjf grafana t=2019-11-28T11:18:46+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"```

**Comment by europemaster** [comment]
After upgrading from 6.3.2 to 6.5.2 we started to experience this error. Upgrading to 6.5.3 did not solve the issue.
Testing rule sends notification, while actual rule doesn't send anything.
From Grafana logs:
```
t=2020-01-20T12:36:48+0000 lvl=info msg="Notifying Pagerduty" logger=alerting.notifier.pagerduty event_type=resolve
t=2020-01-20T12:36:48+0000 lvl=eror msg="Failed to send notification to Pagerduty" logger=alerting.notifier.pagerduty error="context deadline exceeded"
```

Version: 6.5.3
OS: Ubuntu 16.04 LTS
Data source: Prometheus 2.7.1

**Comment by europemaster** [comment]
Downgrading from 6.5.3 to 6.3.7 fixed the issue, so I am positive that there is issue with 6.5.x version.

**Comment by marefr** [comment]
Please refer to https://github.com/grafana/grafana/issues/21018#issuecomment-575579432
