### ISSUE TITLE
Fix grafana 6.6 app plugin types

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [grafana/grafana#21390]
Grafana AppPlugIn seems to be having issue with   .setRootPage(ExampleRootPage) as this React page is not loaded by Grafana. However .addConfigPage worked fine, along with ConfigCtl, Readme files are loading into grafana fine.

Also the navigation menus for AngularExamplePage is not working through routing, all we could see is a blank page. 

I have followed code sample from,

https://github.com/grafana/grafana/tree/master/public/app/plugins/app/example-app

**Environment**:
- Grafana version: 6.6 pre build 
- Data source type & version:
- OS Grafana is installed on: Mac OS, Compiled from source
- User OS & Browser: Mac OS
- Grafana plugins: https://github.com/grafana/grafana/tree/master/public/app/plugins/app/example-app
- Others:

**Comment by gopalakrishnan-subramani** [comment]
Facing Below error while mounting a React Page


Plugin component error Error: [$injector:unpr] Unknown provider: propsProvider <- props
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=propsProvider%20%3C-%20props
    at angular.js:116
    at angular.js:4887
    at Object.getService [as get] (angular.js:5047)
    at angular.js:4892
    at getService (angular.js:5047)
    at injectionArgs (angular.js:5072)
    at Object.invoke (angular.js:5098)
    at $controllerInit (angular.js:11076)
    at nodeLinkFn (angular.js:9926)
    at compositeLinkFn (angular.js:9248)


`
{
  "type": "app",
  "name": "Simple app",
  "id": "simple-react-app",
  "routes": [],


  "info": {
    "description": "Simple React App",
    "author": {
      "name": "Your Name"
    },
    "keywords": ["Simple"],
    "logos": {
      "small": "img/logo.svg",
      "large": "img/logo.svg"
    },
    "links": [
      {"name": "Website", "url": "https://github.com/grafana/simple-react-panel"},
      {"name": "License", "url": "https://github.com/grafana/simple-react-panel/blob/master/LICENSE"}
    ],
    "screenshots": [],
    "version": "%VERSION%",
    "updated": "%TODAY%"
  },
 

  "includes": [
    {
      "type": "page",
      "name": "Angular Page",
      "component": "AngularExamplePageCtrl",
      "addToNav": true,
      "role": "Viewer"
    },
    {
      "type": "page",
      "name": "React Page",
      "component": "Page",
      "addToNav": true,
      "role": "Viewer"
    },
    {
      "type": "dashboard",
      "name": "Streaming Example",
      "path": "dashboards/streaming.json",
      "addToNav": true
    },
    {
      "type": "dashboard",
      "name": "Lots of Stats",
      "path": "dashboards/stats.json"
    },
    {
      "type": "panel",
      "name": "Anything -- just display?",
      "addToNav": false
    }
  ],

  "dependencies": {
    "grafanaVersion": "6.5.x",
    "plugins": []
  }
}

`


module.ts file 

`
import { ExampleRootPage } from './ExampleRootPage';
import { ExamplePage2 } from './ExamplePage2';
import { ExamplePage1 } from './ExamplePage1';
import { AppPlugin } from '@grafana/data';
import { ExampleConfigCtrl } from './legacy/config';
import { AngularExamplePageCtrl } from './legacy/angular_example_page';

import { Page } from './Page';
import { ExampleAppSettings } from './types';

export { ExampleConfigCtrl as ConfigCtrl, AngularExamplePageCtrl, Page };

export const plugin = new AppPlugin<ExampleAppSettings>()
  .setRootPage(ExampleRootPage)
  .addConfigPage({
    title: 'Page 1',
    icon: 'fa fa-info',
    body: ExamplePage1 as any,
    id: 'page1',
  })
  .addConfigPage({
    title: 'Page 2',
    icon: 'fa fa-user',
    body: ExamplePage2 as any,
    id: 'page2',
  });

plugin.angularPages = ['AngularExamplePageCtrl'];
`

**Comment by ryantxu** [comment]
Now reproducible in:
https://github.com/grafana/simple-app-plugin

the plugin embedded in grafana core does not have strict type checking so builds ok but as a plugin you cant :(

**Comment by ryantxu** [comment]
The issue (I think) is with the typing on:
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/plugin.ts#L135

```
export class GrafanaPlugin<T extends PluginMeta = PluginMeta> {
  // Meta is filled in by the plugin loading system
  meta?: T;
  ...
  // Show configuration tabs on the plugin page
  configPages?: Array<PluginConfigPage<GrafanaPlugin>>;

  // Tabs on the plugin page
  addConfigPage(tab: PluginConfigPage<GrafanaPlugin>) {
  ...
```

Rather than `PluginConfigPage<GrafanaPlugin>` it needs to be something like `PluginConfigPage<GrafanaPlugin<T>>`, but that seems to fail 🤷‍♂

**Comment by gopalakrishnan-subramani** [comment]
There are two problems that needs to be investigated.

1. Angular pages is not always consistently displayed, it appears, sometime it doesn't
2. React pages is not appearing. 

configuration pages are fine, only pages to be fixed

**Comment by gopalakrishnan-subramani** [comment]
@ryantxu are you planning fix for 6.6 release? 

1. Kindly check to Bring React pages
2. Kindly check to bring angular pages consistently [it works like random behaviour]

**Comment by ryantxu** [comment]
@gopalakrishnan-subramani check https://github.com/grafana/simple-app-plugin against master grafana.  I think it is all sorted now

**Comment by gopalakrishnan-subramani** [comment]
I see that Grafana page(s) has two type of functionalities.

1. Config Page [ as demonstrated below]

.addConfigPage({
    title: 'Page 1',
    icon: 'fa fa-info',
    body: ExamplePage1,
    id: 'page1',
  })
  .addConfigPage({
    title: 'Page 2',
    icon: 'fa fa-user',
    body: ExamplePage2,
    id: 'page2',
  });

and module.ts export as ConfigCtrl

export {
  ExampleConfigCtrl as ConfigCtrl,
}

---
2. The another part is purely the pages, as defined in plugin.json

 "includes": [
    {
      "type": "page",
      "name": "Angular Page",
      "component": "AngularExamplePageCtrl",
      "role": "Viewer",
      "addToNav": true,
      "defaultNav": true
    },
]

Can you give how to use React in the place of Angular? For example,    
Below Angular component, 
   
"component": "AngularExamplePageCtrl",

can be a ReactPageCtrl?

I could not find any references on internet, how to do the ReactPage in Grafana App.

Config and Pages are quite different purpose, IMHO. Config is all about configuring application, pages that are for end users or role based.

**Comment by ibrahimtan93** [comment]
Hi @ryantxu, is this fixed in 6.6.0 stable?
if its possible can you notify me?

**Comment by toussa** [comment]
I still have the same issue with grafana v6.6.1 (21bf8b71bc) :
React pages are not appearing.
Configuration pages are fine, only pages to be fixed

**Comment by papagian** [comment]
@ryantxu @dprokop 
People report that still have this issue can you have a look?

**Comment by jpmcb** [comment]
We are also seeing this issue when attempting to deploying a data source plugin after using the [grafana-toolkig](https://www.npmjs.com/package/@grafana/toolkit). Are there any work arounds? Please let me know if there's any more information I can provide!

**Comment by ryantxu** [comment]
@jpmcb and @toussa -- are you able to reproduce your errors using https://github.com/grafana/simple-app-plugin

I am testing against master now, and everything seems to load and run OK

**Comment by toussa** [comment]
I tried with docker image `grafana/grafana:master` and master branch of simple-app-plugin and have the same problem: impossible to display content of root page.

In console, I cannot see the angular error anymore, but I see:
```
plugin_component.ts:265 Plugin component error 
message: "Failed to find exported plugin component for app-page-yourorg-simple-app-root-page-react"
```

**Comment by toussa** [comment]
Ok, I succeeded to display the react root page.
Based on `plugin.json`, the page has `a/yourorg-simple-app/ `as path.
Going to `http://127.0.0.1:3000/a/yourorg-simple-app/` works and display the page without warnings.

However, all the links in the left nav bar or in the "Include" section of the plugin config page are misformed to :
```
http://127.0.0.1:3000/plugins/yourorg-simple-app/page/root-page-react
http://127.0.0.1:3000/plugins/yourorg-simple-app/page/root-page-tab-b
...
```
Going through those links, it displays the right page-header but nothing inside the page body, with the warning message I wrote above:

> plugin_component.ts:265 Plugin component error 
> message: "Failed to find exported plugin component for app-page-yourorg-simple-app-root-page-react"

**Comment by jpmcb** [comment]
I've tried the simple app as well and get the same message in the console with nothing displaying in the actual page. 

```
message: "Failed to find exported plugin component for app-page-yourorg-simple-app-root-page-react"
```

We were able to get this to work with our datasource plugin by performing
```
yarn dev
```

and moving the subsequent build. Now, the datasource plugin works as expected. Could there be a dev dependency that the rest of the normal build depends on?

**Comment by ryantxu** [comment]
> However, all the links in the left nav bar or in the "Include" section o

Correct -- that is not yet supported.  I hope to fix that with https://github.com/grafana/grafana/pull/22428

With this issue I was mostly worried about the not loading and type conflicts

**Comment by ryantxu** [comment]
#22428 is now merged into master... with that you can specify links using "path":
```
 {
      "type": "page",
      "name": "Root Page (tab B)",
      "path": "/a/yourorg-simple-app/?tab=B",
      "role": "Viewer",
      "addToNav": true
    },
```

I'll close this issue -- but open a new one if there are other problems with app plugins we should fix before 6.7
