### ISSUE TITLE
role_attribute_path does not handle hard-coded strings in quotes

### ISSUE THREAD

**Issue by gboor** [grafana/grafana#21667]
**What happened**:
While testing some issues with keycloak (apparently resolved recently), I tried the following config to see if role assignment works at all;

`role_attribute_path = 'Admin'`

**What you expected to happen**:
If I put `'Admin'` into jmespath.org, it always returns `"Admin"`, regardless of the input. So I expect all users who log in to be automatically Admin, instead everyone was Viewer.

**How to reproduce it (as minimally and precisely as possible)**:
Set `role_attribute_path = 'Admin'` on the oauth_generic config, then log in.

**Environment**:
- Grafana version: 6.5.2
- OS Grafana is installed on: Kubernetes on GKE
- User OS & Browser: Windows 10 + Chrome, Mac + Chrome, Ubuntu + Chrome
- Grafana plugins: None

**Comment by Quicksy** [comment]
Same issue. Еried to set default permission for private gitlab oauth - looks like it just ignores ```role_attribute_path = 'Admin'``` setting.

**Comment by marefr** [comment]
Please use the [auto_assign_org_role](https://grafana.com/docs/grafana/latest/installation/configuration/#auto-assign-org-role) for this status use case. Could also be related to a bug we had in 6.5.x which we've fixed in 6.6 so suggests trying that out.

**Comment by zoftdev** [comment]
true||'Admin' solve this issue.

**Comment by RubenGarcia** [comment]
I used 

role_attribute_path = true||'Admin' 

in grafana 7.1.5 and it does not work for me. I still get 

t=2020-09-08T11:13:40+0200 lvl=dbug msg="User info result" logger=oauth.generic_oauth result="&{Id: Name: <my name> Email:<my email> Login:<my email> Company: Role: Groups:[]}"
t=2020-09-08T11:13:40+0200 lvl=info msg="Successful Login" logger=http.server User=<my email>
t=2020-09-08T11:13:41+0200 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=2 orgId=1 uname=<my email> dashId=10 action=View
t=2020-09-08T11:13:41+0200 lvl=dbug msg="User denied access to execute action" logger=dashboard.permissions userId=2 orgId=1 uname=<my email> dashId=10 action=Edit
t=2020-09-08T11:13:41+0200 lvl=dbug msg="User denied access to execute action" logger=dashboard.permissions userId=2 orgId=1 uname=<my email> dashId=10 action=Edit
t=2020-09-08T11:13:41+0200 lvl=dbug msg="User denied access to execute action" logger=dashboard.permissions userId=2 orgId=1 uname=<my email> dashId=10 action=Admin

**Comment by pjamenaja** [comment]
Just for the people who reach here later, the below works for me.

> role_attribute_path = to_string('Editor')

**Comment by zhtaihao** [comment]
@pjamenaja You're a saint for writing this down. After googling around for over an hour this solution finally worked for me.
