### ISSUE TITLE
[BUG][6.6.0] - Alert Images not rendering for Prometheus/Victoriametrics datasources

### ISSUE THREAD

**Issue by xandr2** [grafana/grafana#21912]
**What happened**:
Alert image doesn't render if datasource are Prometheus/Victoriametrics (maybe some more, not tested all). Image hosted on S3.
Error in console:
`t=2020-02-04T10:59:27+0000 lvl=dbug msg="Phantomjs output" logger=rendering renderer=phantomJS out="Loading a web page: http://localhost:3000/d-solo/UbpDfwPZk/prometheus-2-0-stats-copy_test?orgId=1&panelId=3&render=1 status: success 15000\n"
t=2020-02-04T10:59:27+0000 lvl=dbug msg="Phantomjs error" logger=rendering renderer=phantomJS error="signal: killed"
t=2020-02-04T10:59:27+0000 lvl=info msg="Rendering timed out" logger=rendering renderer=phantomJS
t=2020-02-04T10:59:27+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=32 error="Timeout error. You can set timeout in seconds with &timeout url parameter"`

When I tested alerts on other dashboards with ElasticSearch or Cloudwatch datasources everything works fine and image rendered and sent with alert.

**What you expected to happen**:
Image should render without errors.

**How to reproduce it (as minimally and precisely as possible)**:
Use alarm with DS Prometheus/Victoriametrics and check error logs.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.6.0
- Data source type & version:
Prometheus Victoriametrics
- OS Grafana is installed on:
Docker
- User OS & Browser:
MacOS, Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
@dprokop this should have been fixed by #21657 included in v6.6.0 stable, right? 

@xandr2 would suggest trying https://grafana.com/grafana/plugins/grafana-image-renderer. We've deprecated PhantomJS and will remove it in future version.

**Comment by dprokop** [comment]
@marefr correct

**Comment by eloo** [comment]
Hi, 
we are also affected by this bug. Using V6.6.0 so it looks like this is not fixed.
I've teared down this bug to be introduced between 6.4.5 and 6.5.0
Maybe this information help to fix this.

Thanks

**Comment by marefr** [comment]
@eloo would suggest trying https://grafana.com/grafana/plugins/grafana-image-renderer. We've deprecated PhantomJS and will remove it in future version.

@xandr2 any updates from your side?

**Comment by eloo** [comment]
i did this already, see https://github.com/grafana/grafana-image-renderer/issues/48

at the moment its impossible to use a higher version as 6.4.5 :/

**Comment by xandr2** [comment]
@marefr We tried that variant in Docker but container with Image Renderer have another issue https://github.com/grafana/grafana-image-renderer/issues/97
For now we are upgrading to 6.6.1 just for try.

**Comment by xandr2** [comment]
6.6.1 the same problem...

**Comment by xandr2** [comment]
@marefr How we can help you with investigating process?

**Comment by Quicksy** [comment]
Updated to 6.6.0 and run into the same issue with Prometheus DS and Telegram as alert service. Do we have any news on this issue fix? Image Renderer plugin doesn't work for us either.

**Comment by xandr2** [comment]
@marefr @eloo Guys, can you help us with that issue, we can provide additional information if you need just write what we need to do, that's critical for us.

**Comment by marefr** [comment]
Sorry, it have taken me some time to come back to this. @xandr2 have requested more information in grafana/grafana-image-renderer#97 - seems like a configuration error to me.

Too all of you having problems. Can you provide a dashboard json using a panel with Prometheus query (up metric?) and/or panel from the Prometheus 2.0 stats dashboard which fails to render using Panel context menu -> Share -> Direct link rendered image. Also please include Grafana version and image renderer plugin/docker image version and on what platform you run Grafana/image renderer.

Thanks in advance

**Comment by eloo** [comment]
@marefr 
Hi i tried to increase the timeout like this:
GF_ALERTING_NOTIFICATION_TIMEOUT_SECONDS: 60
but it still fails with timeout and i still see the that the timeout for the renderer is `timeout=30`
So it looks like this configuration is not changing the timeout for phantomjs.
Okay, just checked this again. and it looks like the timeout for the renderer is the half of the notification timeout. I've tested timeout 300 which results in a renderer timeout of 150. 
But I still get an timeout

The panel itself can be rendered in my browser without any issues:
(d-solo/_9F9kHOWz/test-dashboard?orgId=1&panelId=3&render=1)

When i use the "direkt link to rendered image" i get a 504 gateway timeout.
But with a Grafana instance 6.4.5 the same link is working as expected!!!
So maybe we got here a problem.
I've also tried to use a smaller timeframe for rendering. it still not working with only 5 minutes timeframe for the image to be rendered.
So it looks like there is something else broken with the renderer for prometheus data.

I've also checked the CPU and memory usage but i can't see any issues.. 
CPU usage is around 30% max when the renderer is going to start. After a few seconds phantomjs is going down to around 6%.
Memory usage is also fine, around 25% when the renderer starts.

I hope this will help fixing this issue.
Thanks

**Comment by marefr** [comment]
Was able to reproduce this using PhantomJS on v6.6.1. Will try to fix and include in v6.6.2

**Comment by marefr** [comment]
PhantomJS issue fixed by #21677. Will be included in upcoming v6.6.2 release.

For further discussion about Grafana Image Renderer please continue that in https://github.com/grafana/grafana-image-renderer/.

**Comment by eloo** [comment]
@marefr 
Sounds good. Thank you!

**Comment by xandr2** [comment]
Fixed for me in version 6.6.2! Thank you very much!
