### ISSUE TITLE
Alert reminders not working post upgrade.

### ISSUE THREAD

**Issue by tiagomeireles** [grafana/grafana#22370]
**What happened**:
Upgraded to v6.5.2 from v6.4.2. Alert reminders are not working.

**What you expected to happen**:
Alert reminders to work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The notification channel is slack with  `Send reminder every` set to `10m`
**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Prometheus 2.15.2
- OS Grafana is installed on: Alpine
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tiagomeireles** [comment]
Fixed in #21536. Upgrading to 6.6.2 resolved it.

**Comment by candranapits** [comment]
I have been upgrade to 6.6.2, but grafana still cannot send notification to slack and no error in logging grafana.
datasource prometheus 2.3.2
