### ISSUE TITLE
Verify that grafana/grafana:latest Docker manifest is multiarch

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#22765]
**What happened**:
According to a user, grafana/grafana:latest Docker manifest is no longer multiarch, only amd64/linux.

```
    $ docker run --rm mplatform/mquery grafana/grafana
    Image: grafana/grafana
     * Manifest List: No
     * Supports: amd64/linux
```

Also make sure that beta release pipeline doesn't update the grafana/grafana:latest tag.

**Comment by andrasg** [comment]
Indeed no multiarch in `latest`. Watchtower updated my Grafana docker and now it won't run on a rpi due to architecture mismatch.
Would be nice to either have a `latest-arm` tagged or ensure that `latest` is multi-arch.

**Comment by marefr** [comment]
@aknuds1 latest shouldn't have been tagged for v6.7.0-beta1, only stable releases.

**Comment by marefr** [comment]
@andrasg please use a different tag than latest for now. You can see which OS/ARCH is supported by tag here https://hub.docker.com/r/grafana/grafana/tags

**Comment by aknuds1** [comment]
> @aknuds1 latest shouldn't have been tagged for v6.7.0-beta1, only stable releases.

@marefr Thanks, I'll try to fix it.

**Comment by andrasg** [comment]
> @andrasg please use a different tag than latest for now. You can see which OS/ARCH is supported by tag here https://hub.docker.com/r/grafana/grafana/tags

Thanks, I was able to fix it by pulling `:6.6.2`. Will keep monitoring to see when I can go back to `:latest`.

**Comment by aknuds1** [comment]
The bug is fixed in our release pipeline, but I haven't been able to restore the current grafana/grafana:latest as a multi-arch manifest :/ It should be fixed with our next release though.

**Comment by andrasg** [comment]
I see that this issue is still present. Still no ARM version in latest.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/10730249/78470614-3c77ba80-772b-11ea-9be8-9e0007725f06.png">

**Comment by aknuds1** [comment]
@andrasg I've pushed multi-arch _latest_ manifests, can you please have another look? Thanks!

**Comment by andrasg** [comment]
> @andrasg I've pushed multi-arch _latest_ manifests, can you please have another look? Thanks!

Looks good now. Question is, can I now rely on `latest` tag for my updates? Meaning, is it expected that `latest` will always contain arm images as well?

**Comment by aknuds1** [comment]
@andrasg Our release pipelines are now supposed to push a multi-arch manifest also for the _latest_ tag; we just fixed this for the v6.7.x line also, although we will have to wait until v6.7.3 before we see if that actually works (we don't have a good way right now to test this logic).

**Comment by andrasg** [comment]
@aknuds1 thanks for confirming!

**Comment by aknuds1** [comment]
You're welcome @andrasg.
