### ISSUE TITLE
unable to use spacebar in template variables

### ISSUE THREAD

**Issue by daldoyle** [grafana/grafana#23825]
**What happened**:
I have a template variable based on query. When I click the variable the dropdown appears and I can type to filter (helpful with long dropdowns). In 6.7.2 when I type a space character the dropdown closes and uses whatever I have typed so far, as if I had hit the return key. This makes searching for a term with a space in it impossible. This worked in 6.3.5 and appears to have changed behavior somewhere along the way when we upgraded. The dashboards themselves haven't changed at all.

**What you expected to happen**:
I expect the dropdown to let me enter "foo <space> bar" and then filter the list for "foo bar". As noted earlier, this was the behavior in earlier versions of Grafana.

**How to reproduce it (as minimally and precisely as possible)**:
Have a template variable that has several options, including ones with spaces such as "My Test" and "My Other Test". Open the template variable dropdown and type "My <space> Other" and the template dropdown will close and select the first match for just "My".

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: N/A, happens with any datasource as best I can tell
- OS Grafana is installed on: CentOS7
- User OS & Browser: MacOS 10.15.3, Chrome 80.0.3987.163, also happens in Safari
- Grafana plugins: N/A
- Others:

**Comment by marefr** [comment]
Are you referring to [this feature](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-5/#dynamic-typeahead-support-in-query-variables)?

**Comment by daldoyle** [comment]
I don't believe so - I have tested this using an Elastic datasource and one from an in house datasource, both behave as I described above. The feature you referenced states it only applies to Graphite, MySQL, and Postgres. It looks like that is maybe implementing server side filtering, which is good to know but not what I am describing here.

What I'm trying to say is that as a user (as in while trying to use the dashboard, not the variable creation page), I cannot filter by a term with a space character in it because entering a space closes the template variable as if I had hit the return key.

In 6.3.5 (note the term I'm filtering by has a space in it, looking for "Indiana University"):
![image](https://user-images.githubusercontent.com/7233444/80213586-5fe5a500-8607-11ea-9a9f-b34ddfc42940.png)

in 6.7.2 when I enter a space after "Indiana" the template variable closes and selects whatever the first entry was, like I had hit return. 

I also tested this in the most recent 6.7.3, behavior seems to be the same as 6.7.2.

**Comment by torkelo** [comment]
Seems fixed in 7.0 
<img width="356" alt="Screen Shot 2020-05-28 at 19 46 54" src="https://user-images.githubusercontent.com/10999/83175333-05ff6000-a11c-11ea-8f1e-4d4e01ab17bc.png">

**Comment by Grrrolf** [comment]
This issue is back in Grafana 7.3.6. I have not checked any of the versions in between 7.0 and 7.3.6.

**Comment by marcuzh** [comment]
I'm also getting very similar behaviour in Grafana 7.5.3 when using either Chrome or Edge.
In my case the data source for the template variables is MySQL, displaying a list of FirstName/LastName whitespace separated.
I can type the firstname and it starts to filter the list - but hitting the space bar is ignored. It doesn't _close_ the dropdown for me, which seemed to be what @daldoyle was experiencing
