### ISSUE TITLE
v7.0.0-beta1: Graph x-axis labels showing "MM/DD" rather than actual date

### ISSUE THREAD

**Issue by societymartingale** [grafana/grafana#24063]
**What happened**:
Upgraded Grafana from version 6.7.3 to 7.0.0-beta1. The x-axes on our graph panels began displaying "MM/DD" rather than the actual date. After downgrading to 6.7.3, dates are back to normal. Please see screenshot from v7.0.0-beta1:
![Screen Shot 2020-04-29 at 1 58 59 PM](https://user-images.githubusercontent.com/22607854/80630047-a4b37680-8a21-11ea-8c98-81cddf409278.png)

**What you expected to happen**:
Month and day to appear on x-axis, e.g. "04/29"

**Environment**:
- Grafana version: 6.7.3 upgraded to 7.0.0-beta1
- Data source type & version: Postgres
- OS Grafana is installed on: Alpine (Docker)
- User OS & Browser: Mac OS, Chrome

**Comment by mjuopperi** [comment]
I have this same issue with InfluxDB. The tooltip does show the correct values though.

**Comment by mckn** [comment]
I get the feeling that this has to do with a caching issue. If you do a hard refresh of the browser do you still get the same issue? @mjuopperi @societymartingale ?

**Comment by societymartingale** [comment]
I tried doing a hard refresh in the browser and am still seeing this issue. (Also tried it from a couple browsers in private/incognito mode.)

**Comment by mckn** [comment]
> I tried doing a hard refresh in the browser and am still seeing this issue. (Also tried it from a couple browsers in private/incognito mode.)

Hmm, interesting. Can you try to see if any of the following helps:

- Try run Command + r.

or

- Open developer console (option + command + j). Go to network tab and check the "Disable cache" checkbox.

**Comment by societymartingale** [comment]
I tried both Command + r and disabling cache in the developer console network tab, and it still happens. 

Here is a screenshot of some of the time series data coming back from the query: 
![Screen Shot 2020-05-04 at 9 02 42 AM](https://user-images.githubusercontent.com/22607854/80977485-cb432a00-8df2-11ea-9d82-87b9ca1ff705.png)

**Comment by mckn** [comment]
@societymartingale okay, thanks for the proper testing. Then we can rule out the caching issue. Currently I have problems reproducing this issue but will see if I can manage to do it in some way.

**Comment by societymartingale** [comment]
Thanks! I will see if I can find a simpler way to reproduce this issue.

**Comment by mckn** [comment]
@societymartingale what settings do you have below 'edit panel' -> 'display' -> 'x-axis'?

**Comment by mckn** [comment]
@societymartingale also, do you get any errors in the console?

**Comment by societymartingale** [comment]
@mckn x-axis settings are: (1) "Show" toggled to on and (2) "Mode" = Time

In the console tab, I'm not seeing any errors, just a warning: "onmozfullscreenerror is deprecated."

**Comment by societymartingale** [comment]
When I create a new panel on a new dashboard, the x-axis times show HH:mm. Then when I save it, it still shows HH:mm. However, after refreshing after save, the times appear. Here are a couple screenshots.

After adding a new panel (default data source with random walk test data):
<img width="699" alt="Screen Shot 2020-05-04 at 12 22 25 PM" src="https://user-images.githubusercontent.com/22607854/80988996-4fe97480-8e02-11ea-85d9-747c47c1a4a2.png">

After saving AND refreshing:
<img width="707" alt="Screen Shot 2020-05-04 at 12 22 54 PM" src="https://user-images.githubusercontent.com/22607854/80989095-73acba80-8e02-11ea-8137-9a44b1660a0c.png">

**Comment by societymartingale** [comment]
Issue does not occur when running a local docker container: `docker run -p 3000:3000 grafana/grafana:7.0.0-beta1`, which lends credence to theory that this is somehow caching related.

**Comment by mckn** [comment]
@societymartingale would be awesome if you can test the following:

1. Copy the link from the browser to the file below. You can filter on `vendors~app`.
2. Run the following command `curl -s <insert_url>|sha1sum` example `curl -s https://play.grafana.org/public/build/vendors~app.62a3fe02209bb31bd997.js|sha1sum`

What is the output you get from the command?

**Comment by societymartingale** [comment]
@mckn sorry for the delay. Here is the output from that command:
```
8384485b9797654b14bd191baa9c201c81d2768b  -
```

**Comment by mckn** [comment]
@societymartingale awesome, thanks! That looks correct. 

The instance that you ran that command against. Can you still reproduce the issue in that instance?

**Comment by societymartingale** [comment]
@mckn , yes, this instance is still showing `MM/DD` on the x-axis.

**Comment by mckn** [comment]
@societymartingale super! thanks - will continue to look into this issue.

**Comment by mckn** [comment]
thanks for reporting this issue and for all the help debugging. It is now fixed and will be included in the next beta release.

**Comment by societymartingale** [comment]
Thanks for being so responsive and fixing this quickly! Can't wait to try out all the new version 7 features.

**Comment by societymartingale** [comment]
I'm still seeing this issue on some panels after upgrading to 7.0 beta 2. Tried it in different incognito sessions with network caching turned off.

![Screen Shot 2020-05-07 at 2 50 26 PM](https://user-images.githubusercontent.com/22607854/81333747-05226380-9073-11ea-9add-f94841214773.png)

**Comment by torkelo** [comment]
What other panel types do you have on the dashboard?

**Comment by societymartingale** [comment]
Single stat, pie chart, and tables

**Comment by torkelo** [comment]
We identified that it was the pie chart that caused this, maybe the fix did not make it into beta2 , we will investigate tomorrow

**Comment by societymartingale** [comment]
Just following up: this issue is definitely fixed after upgrading to Grafana v7.0.0-beta3 and Piechart panel v1.5.0. Now seeing the dates on the x axis as expected.
