### ISSUE TITLE
Stacking series not always showing up

### ISSUE THREAD

**Issue by ITDebicki** [grafana/grafana#2413]
I am using influxDB as a datasource and I originally tried using a single query to fetch all the data I need. However, it then stacked the values I wanted in the incorrect way.

I made a work around which involves sending two queries, one for the value I want on top of the stack, and another for all of the other values.
The queries I use are:
```
SELECT last(value) FROM "ceph-ceph_value" WHERE "host" =~ /$Monitor$/ AND "instance" = 'pg' AND "type_instance" = 'active+clean' AND $timeFilter GROUP BY time($interval), "type_instance" fill(0)
```
and this to fetch everything else
```
SELECT last(value) FROM "ceph-ceph_value" WHERE "host" =~ /$Monitor$/ AND "instance" = 'pg' AND "type_instance" <> 'active+clean' AND $timeFilter GROUP BY time($interval), "type_instance" fill(0)
```

However, the second query does not always return a series, as all of the objects can be in the first state. This causes influxDB to not return any series for the second query.

When this happens, Grafana states that there are no datapoints for the graph, and does not display anything.

**Comment by torkelo** [comment]
I fixed a similar issue this morning, can you try updating to latest build?

**Comment by torkelo** [comment]
also make sure you use fill(0) when using stacking as each series must have a value for stacking to work

**Comment by ITDebicki** [comment]
I tried running the [latest build](http://grafana.org/download/builds) from today, and I am still getting the same error, even when the graphs aren't stacked. I used fill(0) in both queries on both occasions.

**Comment by torkelo** [comment]
Can you open chrome dev tools and show me the json response from influxdb? (in network tab)

**Comment by ITDebicki** [comment]
![screenshot from 2015-07-30 16 48 04](https://cloud.githubusercontent.com/assets/8769605/8987884/23e03352-36db-11e5-85fd-9b3e58265809.png)

As you can see the first object is empty, whilst the second contains valid data points

**Comment by torkelo** [comment]
can you great a gist with the response json? I might be able to replicate the issue then

**Comment by ITDebicki** [comment]
https://gist.github.com/ITDebicki/4b4203ff5aef96392a4e#file-pg_state_response

**Comment by torkelo** [comment]
have you tested with a recent build?

**Comment by ITDebicki** [comment]
Yes just tested with the build form 11/08/2015 and I still do not see the series when both queries are on, but if I turn on just the one that does return points, the graph shows up. No errors about invalid syntax
