### ISSUE TITLE
Transforms: column order in reduce is not same as the user created

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#24207]
1. Create a new dashboard
2. Add a new panel
3. Add Test Data as data source
4. Choose CSV Metric Values and keep default values
5. Copy the above row 2 times
6. Change to Transforms tab
7.  Add Reduce transform, Max is default => switch graph to table 
![image](https://user-images.githubusercontent.com/562238/80937432-6a592900-8dd5-11ea-8b35-8d7ac1da0c25.png)
8. Shows Max value for first series, expected it to show Max for all 3 series [NOT OK]
9. Add Last column, expect Last column to appear to the right of Max [OK]
10. Add First column, expect First column to appear to the right of Last but Last is now first column and First is the last column [NOT OK]
![image](https://user-images.githubusercontent.com/562238/80937532-cd4ac000-8dd5-11ea-952a-c79fcbf81a4b.png)
11. Column pills are sorted alphabetical [NOT OK]
![image](https://user-images.githubusercontent.com/562238/80937624-30d4ed80-8dd6-11ea-9be5-e5f7f38fc544.png)
12. Add Mean column, expect Mean column to appear to the right of First but First is now the second column and Mean is the last column [NOT OK]
![image](https://user-images.githubusercontent.com/562238/80937668-709bd500-8dd6-11ea-9b59-b3145e054bcb.png)
13. Exit panel edit with back arrow
14. All series are now shown, [OK]
![image](https://user-images.githubusercontent.com/562238/80937721-9d4fec80-8dd6-11ea-902d-40ba6eb71a17.png)
15. Edit panel again via panel menu
16. ~~Columns and data are flipped and looks weird [NOT OK]~~ FIXED

**Comment by ryantxu** [comment]
Mostly fixed in:
https://github.com/grafana/grafana/pull/23978

**Comment by torkelo** [comment]
The second issue fixed in https://github.com/grafana/grafana/pull/24211  We used already transformed data when going back into edit mode

**Comment by hugohaggmark** [comment]
> The second issue fixed in #24211 We used already transformed data when going back into edit mode

Which second issue are you referring to @torkelo I did a second pass on current master 9b1c0455c455c73807f863bd57f8c9999e470f79 and it fixes only point 16 above (I'll remove that point). I still can't see all the series without clicking on the refresh button and the pills and columns are still sorted alphabetically.

**Comment by torkelo** [comment]
>  I still can't see all the series without clicking on the refresh button 

Is this not related to the fact duplicate query does not issue it right away?

The select multi-value mode sorting looks to be the issue here. Am I right? or there sorting going on the table display?

**Comment by hugohaggmark** [comment]
Yes, both the multi-select and columns are ordered alphabetically. I think they should be in the order the user adds them?

**Comment by hugohaggmark** [comment]
I'll have a look and see if there is an easy way to fix this.
