### ISSUE TITLE
ng-blur event will trigger twice request

### ISSUE THREAD

**Issue by HallsHalls** [grafana/grafana#2429]
I get some problem when I use the ng-blur on the input label. I found that will trigger twice query requests. thanks

By the way, I have a lot of data show on the one graph, and too many lines show in the views, like that
![2015-08-03 11 28 06](https://cloud.githubusercontent.com/assets/9986416/9030272/e6d72b6e-39d2-11e5-9022-115c3438615d.png)
I made some function filter the line number.According to the user's choice such as (shuffle ,random, highest Average ,lowest Average etc.) and line limit number.

**Comment by HallsHalls** [comment]
I am so sorry ,I poor of my English :(
but i try my best to express my mind;

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by HallsHalls** [comment]
@torkelo  
I am sorry. The last time, I haven't expressed clear.
When i use the OpenTSDB to add a new graph ,and write the metrics name if I click the 
Drop-down box, and will trigger twice request . I found that the Drop down box will send the request. If  I haven't use drop down box , input direct will trigger a request.

![2015-08-24 16 25 45](https://cloud.githubusercontent.com/assets/9986416/9456013/b7f37e4a-4b04-11e5-8bd4-c52d1fa35b57.png)
![2015-08-24 16 29 06](https://cloud.githubusercontent.com/assets/9986416/9456036/ffb094b6-4b04-11e5-812b-379649130219.png)
![2015-08-24 16 27 15](https://cloud.githubusercontent.com/assets/9986416/9456079/948b919e-4b05-11e5-81b6-9d06eac65ffd.png)
![1111](https://cloud.githubusercontent.com/assets/9986416/9456088/b9ab090a-4b05-11e5-8e0f-ef002492e173.png)

**Comment by torkelo** [comment]
@HallsHalls fixed in https://github.com/grafana/grafana/commit/6e8d5cd8732d5a674dc8ef3ebc9f7da071ba9adc

**Comment by HallsHalls** [comment]
it doesn't work. But I try to use last time change

````html
<input type="text" class="input-large tight-form-input ng-valid ng-dirty ng-valid-parse ng-touched" ng-model="target.metric" spellcheck="false" bs-typeahead="suggestMetrics" placeholder="metric name" data-min-length="0" data-items="100" ng-model-onblur="" ng-change="targetBlur()" data-provide="typeahead">
````
that will be work.

***
On the other hand, if I have already added tag and try to modify metrics name , will click drop-down-box will trigger the error query 
![222](https://cloud.githubusercontent.com/assets/9986416/9483497/c3250fc0-4bd3-11e5-9b06-39d0be0e3774.png)

query request:
![333](https://cloud.githubusercontent.com/assets/9986416/9483507/f4c35b40-4bd3-11e5-86c9-d7c922dd1fbe.png)

**Comment by HallsHalls** [comment]
@torkelo thanks you very much ,but it doesn't work. 

***
On the other hand, if I have already added tag and try to modify metrics name , will click drop-down-box will trigger the error query 
![222](https://cloud.githubusercontent.com/assets/9986416/9483497/c3250fc0-4bd3-11e5-9b06-39d0be0e3774.png)

query request:
![333](https://cloud.githubusercontent.com/assets/9986416/9483507/f4c35b40-4bd3-11e5-86c9-d7c922dd1fbe.png)

***


I found the reason why will send twice request , because    'on-model-blur'  directive will be trigger when we  click drop-down box(there was the first request). After click ,the input value will be changing,and will be send the others request. 


I try to fix this by add time out 
That will be work.
````html
query.editor.html 

<input type="text" class="input-large tight-form-input ng-valid ng-dirty ng-valid-parse ng-touched" ng-model="target.metric" spellcheck="false" bs-typeahead="suggestMetrics" placeholder="metric name" data-min-length="0" data-items="100" ng-model-onblur="" ng-change="targetBlur()" data-provide="typeahead">
````

```html
queryCtrl.js  line:27

$scope.targetBlur = function() {
      $scope.target.errors = validateTarget($scope.target);
      // this does not work so good
      $timeout.cancel($scope.timer);
      $scope.timer = $timeout(function() {
        if (!_.isEqual($scope.oldTarget, $scope.target) && _.isEmpty($scope.target.errors)) {
          $scope.oldTarget = angular.copy($scope.target);
          $scope.get_data();
        }
      }, 250);

    };
```

**Comment by torkelo** [comment]
are you running a build with in 6e8d5cd? I fixed the line you pasted yesterday (in the commit I mentioned)

**Comment by HallsHalls** [comment]
I have already build the lastest .But still doesn't work. At the beginning I thought is my fault ,because I change a lot. And I try to download the zip from GitHub , build it and run it , it doesn't work yet.
And the 'ng-blur'  must be touch  out of the input space , to user unfriendly   :(

**Comment by torkelo** [comment]
sorry, was sure it was working but tested again and got duplicated query calls, did another fix :)

**Comment by HallsHalls** [comment]
thank for your fix , I think it was something problem in my project.
I think if  have a timeout controller  would be great for the database.Will reduce many query . yeah!
