### ISSUE TITLE
Templating init failed e.current is undefined

### ISSUE THREAD

**Issue by carlospeon** [grafana/grafana#24323]
**What happened:**
Error loading snapshot:

```
Templating init failed
e.current is undefined
```

Only first graphs are drawn. If I scroll down, next graphs are blank.

```
TypeError: "e.current is undefined"
    value variable_srv.ts:316
    value interval_variable.ts:64
    value variable_srv.ts:253
    value interval_variable.ts:95
    value variable_srv.ts:119
    Angular 6
        f
        f
        $digest
        evalAsync
        p
        n
```
```
TypeError: "this.variable.current is undefined"
    value value_select_dropdown.ts:270
    link value_select_dropdown.ts:350
    Angular 11
        ht
        Tt
        It
        it
        St
        f
        f
        $digest
        evalAsync
        p
        n
 <value-select-dropdown ng-if="variable.type !== 'adhoc' &amp;&amp; variable.type !== 'textbox'" dashboard="ctrl.dashboard" variable="variable" on-updated="ctrl.variableUpdated(variable)">
```

**Environment:**
RHEL7: grafana-6.7.3-1.x86_64

**Comment by dprokop** [comment]
Fixed by https://github.com/grafana/grafana/pull/24261

**Comment by carlospeon** [comment]
Hello @dprokop, I've backported the fix to 6.7.x but the bug is still present.

Regards.
