### ISSUE TITLE
Grafana 7 new Table wont format timestamp as time

### ISSUE THREAD

**Issue by yurividal** [grafana/grafana#24917]
**What happened**:
On Grafana 6, if i set a column on a table to Unit "Time", it would correctly format my timestamp that comes from Elasticsearch. After updating to Grafana 7, and using the new Table, the column does not change to a userfriendly time format.

![image](https://user-images.githubusercontent.com/8555749/82427586-33477080-9a81-11ea-8e17-f58634d9e190.png)

**What you expected to happen**:
Column has value 2020-05-20T02:10:24.798Z, even after adding Overide to treat that column as Date/Time

![image](https://user-images.githubusercontent.com/8555749/82427713-5eca5b00-9a81-11ea-9368-c6a498249ad0.png)

Expected to see a cleaner Time format, like the old Table plugin would do.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0:latest
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker on Rancher
- User OS & Browser: Chrome/Firefox

**Comment by yurividal** [comment]
it looks like processing the elasticsearch fields is not possible in the new table panel.

We’ve been able to do this with the raw-data option in the table-panel in previous grafana version.
But It doesnt seem to be possible in 7.0

**Comment by matteoseppi** [comment]
We have more or less the same problem using InfluxDB 1.8.0.
In Grafana 6.7 we could use DD MMMM YYYY as Time format (es. 22 May 2020). Now with Grafana 7.0 it doesn't work properly. Infact, using DD MMMM YYYY as Time format
![image](https://user-images.githubusercontent.com/65722009/82662578-6844f600-9c2e-11ea-8305-d868e4b1dd2e.png)
The result is the following one:
![image](https://user-images.githubusercontent.com/65722009/82662691-9aeeee80-9c2e-11ea-9496-f006339d54d7.png)
So, new 'Table Panel' in Grafana 7.0 can use only YYYY-MM-DD HH:mm:ss as Time format

**Comment by therealcodlord** [comment]
I can confirm this is also an issue with Prometheus and MySQL data sources. Setting a date format override has no effect.

**Comment by matteoseppi** [comment]
So, this is a bug in new "Table Panel". I hope it'll be fixed in the upcoming Grafana 7.1

**Comment by ghayne** [comment]
I have the same problem in 7.01 using InfuxDB as the source.

**Comment by ghayne** [comment]
The same problem in 7.02.

**Comment by Rayn0r** [comment]
On 7.0.3 I am trying to display Time coming from an InfluxDB in the form of "1591135200000000000" with a custom Date-String. As you can see from the screenshot, it does not seem to work...
![Screenshot_2020-06-12 - Grafana3](https://user-images.githubusercontent.com/4147858/84477669-47e9e380-ac90-11ea-95c0-3a8ef7ef62b9.png)

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/25195

**Comment by dp106** [comment]
Should this be closed because as far as I can tell the fix has not yet been implemented?  I've just installed 7.0.4 and still cannot format datetime columns in any way

**Comment by Rayn0r** [comment]
Commit #25195 is included in 7.0.4.
See here: https://github.com/grafana/grafana/compare/v7.0.3...v7.0.4

Custom date format is working here on my 7.0.4 installation of Grafana.
Make sure to  type:
```
time: YYYY-MM-DD
```
The prefix `time: ` is required for it to work.
See screenshot below:
![image](https://user-images.githubusercontent.com/4147858/85784949-17428900-b729-11ea-956f-c463256a3578.png)

**Comment by lucianosb** [comment]
Agree with @dp106. The issue seems to persist on tables.

**Comment by Rayn0r** [comment]
I did a quick test on a table and and re-formated the date according to my liking.
It is working here as well:
![image](https://user-images.githubusercontent.com/4147858/85790266-46102d80-b730-11ea-8002-01c34b9f30f0.png)

**Comment by dp106** [comment]
Tried formatting it with time: but still doesn't change the format 
![image001](https://user-images.githubusercontent.com/29710771/85801495-e10e0500-b73a-11ea-8a1c-636d5a68985d.png)

**Comment by Rayn0r** [comment]
I'm using data from an InfluxDB Backend.
Opening the Query Inspector and looking at the query shows the time in the following format.
![image](https://user-images.githubusercontent.com/4147858/85825948-d7f55600-b783-11ea-9f62-cb95eae1dcdb.png)

What backend are you using? 
What's is the date string format?

**Comment by Rayn0r** [comment]
@dp106 
can you try to run a SELECT like this:
`SELECT Status, RunDateTime as time, RunDuration FROM ...` and then try to reformat column "time" via overrides?

**Comment by dp106** [comment]
@Rayn0r The backend I am using is MS SQL Server.  As you suggested I can get around the issue by reformatting the date in the SQL query: FORMAT([RunDateTime], 'dd/MM/yyyy HH:mm:ss').

My original statement still stands though, the issue has not been fixed.

**Comment by therealcodlord** [comment]
@dp106 With MySQL I now have to do the following to get date formatting to work with the new table panel:

`select UNIX_TIMESTAMP(datetime)*1000 as 'Date/Time' from...`

So I don't know if there is an equivalent function in MS SQL Server to return dates as UTC `seconds since` values?

And then either choose one of the pre-defined date/time formats or enter a custom format with the `time:` prefix like:
`time: DD/MM/YYYY` 

You didn't have to do either of those things with on the old table panel for date formatting to work but I don't know if that means there are bugs here or if the above is now just the way it is.

**Comment by dp106** [comment]
> @dp106 With MySQL I now have to do the following to get date formatting to work with the new table panel:
> 
> `select UNIX_TIMESTAMP(datetime)*1000 as 'Date/Time' from...`
> 
> So I don't know if there is an equivalent function in MS SQL Server to return dates as UTC `seconds since` values?
> 
> And then either choose one of the pre-defined date/time formats or enter a custom format with the `time:` prefix like:
> `time: DD/MM/YYYY`
> 
> You didn't have to do either of those things with on the old table panel for date formatting to work but I don't know if that means there are bugs here or if the above is now just the way it is.

Unfortunately in the version of SQL  are on there is no built in function to do that.

**Comment by gadol** [comment]
The override feature doesn't work on elastic's date/time field if the group by @timestamp is set to Terms and not Date Histogram causing setting a custom date format still doesn't work

**Comment by Ilium77** [comment]
I don't understand why this issue is closed since it's still not working with an Elasticsearch datasource. I tried a lot of time:<custom format> combination with no luck.

**Comment by erezacohen** [comment]
Still not working with Grafana 7.1.5 with Postgres DB :/

**Comment by yurividal** [comment]
Not working on MySQL with 7.1.5 either

**Comment by iordachelm** [comment]
> Commit #25195 is included in 7.0.4.
> See here: [v7.0.3...v7.0.4](https://github.com/grafana/grafana/compare/v7.0.3...v7.0.4)
> 
> Custom date format is working here on my 7.0.4 installation of Grafana.
> Make sure to type:
> 
> ```
> time: YYYY-MM-DD
> ```
> 
> The prefix `time: ` is required for it to work.
> See screenshot below:
> ![image](https://user-images.githubusercontent.com/4147858/85784949-17428900-b729-11ea-956f-c463256a3578.png)

This really works !

**Comment by torkelo** [comment]
try latest master of 7.2, fixed by https://github.com/grafana/grafana/pull/26879

**Comment by mieseprem** [comment]
I know this is already closed but only to have it logged: I don't get this working. Even with "time: YYYY-MM-DD".
To be honest, I used "time: DD.MM.YYYY" (*) (and Grafana 7.1.5 and MYSQL datasource). Good for me, by DATE_FORMAT() I can do this independently from table overrides.

*) I didn't found something like "Date (System/Browser configured format)"

**Comment by torkelo** [comment]
Try latest beta release

**Comment by kvn-tylr** [comment]
Just upgraded to 7.2 beta.  Went to my table panel and attempted to apply a custom override so I could display milliseconds on my timestamp.  I can't get any custom datetime formatting to work.  You to select one of the presents or nothing, and none of the presets give you milliseconds.

I'm completely willing to accept an answer of "you're doing it wrong."  Please feel free to correct me.

Using InfluxDB 2.0 OSS (only supports Flux) as the backend.

**Comment by torkelo** [comment]
Yea the build in ones do not have milliseconds , you can define a custom one using time:HH:mm:ss.SSS (ie any format with SSS)

**Comment by kvn-tylr** [comment]
Thanks for the reply.  time:HH:mm:ss.SSS works.  I didn't realize I needed to add "time:" to be able to do custom formats for datetimes.

time: YYYY-MM-DD HH:mm:ss.SSS gives me what I need.

Thanks again.

**Comment by jameskirsop** [comment]
Landed here because I'm developing a plugin that's receiving formats from an external source as `YYYY-MM-DDTHH:MM:SSZ`.

This seems like a pretty standard date format that isn't currently supported (in the Table plugin)?

**Comment by haraldkoch** [comment]
I still cannot get this to work with Prometheus (Alertmanager) timestamps in Grafana 7.2.0. The Time column returned by the datasource ( camptocamp / grafana-prometheus-alertmanager-datasource) is in ms, but Grafana refuses to format it with any of the overrides. If I copy it to another field using a Transform, then I can format the copied field. This is very strange behaviour?

**Comment by zoltanbedi** [comment]
Hi @jameskirsop, I've checked and this is working for me. Don't forget to add time: before your format. This should look like this `time:YYYY-MM-DDTHH:MM:SSZ`

**Comment by MarkoBursic** [comment]
Installed 7.2, the table works correctly:

![image](https://user-images.githubusercontent.com/7830293/94267269-97040d80-ff3b-11ea-96b2-d3db678179fe.png)

But the panel doesn't:

![image](https://user-images.githubusercontent.com/7830293/94267386-cca8f680-ff3b-11ea-8bd9-6214e3eda825.png)


Also table inspector and export to CSV doesn't:

![image](https://user-images.githubusercontent.com/7830293/94267493-f9f5a480-ff3b-11ea-99f7-34afbfab5036.png)

**Comment by amnonh** [comment]
As It still does not work for me with the alertmanager plugin, is it possible that there is an issue with the legacy format?

**Comment by kt-256** [comment]
Still have an issue on latest 7.3.5 (Open Source Edition)

:-(

Any Ideas?

My time format is like this: 1607718101319 on a table from Prometheus AlertManager Plugin

![Screen Shot 2020-12-12 at 2 19 08 PM](https://user-images.githubusercontent.com/75909966/101993082-bf232300-3c85-11eb-86e9-22bcb65b869a.png)

**Comment by amnonh** [comment]
@kt-256 see my previous comment I believe it's  a combination of alertmanager plugin still using the older reporting format with a probable bug in tables
I think the chagne should be in alertmanager

**Comment by kak-tus** [comment]
Notice about needed transformation for alertmanager plugin:
![Снимок экрана в 2021-01-05 15-49-12](https://user-images.githubusercontent.com/3152421/103648353-cdefb380-4f6d-11eb-9b6c-370f6ff9f6de.png)

Works only with "*1" operation, but not with "+0".

**Comment by firslien** [comment]
timestamp can't  format to date string in table.
![time column](https://user-images.githubusercontent.com/11465112/110059323-f691ff00-7d9e-11eb-9307-0051cceeb4ea.png)
![override](https://user-images.githubusercontent.com/11465112/110059310-f1cd4b00-7d9e-11eb-8660-5545b996e987.png)

**Environment:**
Grafana version: 7.4.3
Data source: Prometheus AlertManager 0.0.8
Grafana is installed on: Docker
Grafana Pannel: table

**Comment by gorSign** [comment]
Same problem on Grafana v7.5.3:

![image](https://user-images.githubusercontent.com/81162782/117149332-6b8daf00-adb7-11eb-915f-c750357568e3.png)

![image](https://user-images.githubusercontent.com/81162782/117149451-86602380-adb7-11eb-9e29-0679d75a0fe6.png)


Environment:
Grafana version: 7.5.3
Data source: Prometheus AlertManager 0.0.8
Grafana is installed on: Docker
Grafana Pannel: table

Want to use new table pannel because of function: possible left/right scrolling of column header.

Is any solution or workaround for it?

**Comment by amnonh** [comment]
The problem is with Alertmanger plugin (it's probably a combination of the newer grafana and old plugin format)
Upgarde to the latest alertmanger plugin and it will be solved

**Comment by gorSign** [comment]
Should Grafana provide update for it?
In git there is v1.0.0. alert manager plugin (released 12.2.), Grafana v7.5.3. doesn't provide it:

![image](https://user-images.githubusercontent.com/81162782/117152329-36369080-adba-11eb-81e5-434c76d3bf29.png)

**Comment by gorSign** [comment]
...looks like it is not in some plugin DB, grafana start with alert manager v1.0.0 plugin fails (container restarting).

**Comment by gorSign** [comment]
and I get container log:
{"log":"Error: ✗ could not find the version you're looking for\n","stream":"stdout","time":"2021-05-12T14:11:07.242976888Z"}
{"log":"Error: ✗ could not find the version you're looking for\n","stream":"stdout","time":"2021-05-12T14:11:07.96128262Z"}
{"log":"Error: ✗ could not find the version you're looking for\n","stream":"stdout","time":"2021-05-12T14:11:08.737194476Z"}
{"log":"Error: ✗ could not find the version you're looking for\n","stream":"stdout","time":"2021-05-12T14:11:09.880264365Z"}
{"log":"Error: ✗ could not find the version you're looking for\n","stream":"stdout","time":"2021-05-12T14:11:11.330510348Z"}
{"log":"Error: ✗ could not find the version you're looking for\n","stream":"stdout","time":"2021-05-12T14:11:13.578600612Z"}
{"log":"Error: ✗ could not find the version you're looking for\n","stream":"stdout","time":"2021-05-12T14:11:17.495565738Z"}

When will be alertmanager data source plugin v1.0.0 available in Grafana?

**Comment by Husnain51** [comment]
any update on this issue still facing same error even in v8.1.3 :/ 
![grafana issue](https://user-images.githubusercontent.com/66380322/133081724-e5dcdd5f-948d-47c4-a134-e256be5cef70.PNG)

![grafana issue](https://user-images.githubusercontent.com/66380322/133079654-6ef16f70-3a2a-4958-9079-dfef2f6abe76.PNG)

**Comment by mahob** [comment]
I was facing the same issue, but I could solve it with the help of the Grafana docs I found here: https://grafana.com/docs/grafana/latest/panels/standard-options/#custom-units.
The article led me here: https://momentjs.com/docs/#/displaying/

What you have to do is: add a field override using a custom time format that includes the _Fractional Second_ portion: `time:yyyy-MM-DD HH:mm:ss.SSS`

![field-override-with-custom-time-format](https://user-images.githubusercontent.com/1625103/133462574-17468789-3a86-4cb4-9851-d6613343b5df.png)

This is the result:

![the-result](https://user-images.githubusercontent.com/1625103/133462677-a06335ed-db21-41c9-b810-6e8d242cd013.png)

**Comment by sach3000** [comment]
Hi,
Grafana 8.3.2
Problem with override time format still exists:
![image](https://user-images.githubusercontent.com/1357433/151563675-58aa49a6-0654-49f1-a1ab-7365722ffe0b.png)

**Comment by leo4life2** [comment]
Grafana 8.5.2 and having same issue as sach3000. The solution doesn't work for me.

**Comment by davide1995** [comment]
Grafana 9.3.1 and having problem for which "Unit" just update the label but not the real data
<img width="804" alt="Screenshot 2023-01-17 at 02 08 42" src="https://user-images.githubusercontent.com/21131407/212742592-4f59040d-8d33-4693-a33d-53be13c87f88.png">
<img width="788" alt="Screenshot 2023-01-17 at 02 08 56" src="https://user-images.githubusercontent.com/21131407/212742601-c13786dc-f7dc-44f5-897b-0a3fd6fee881.png">

**Comment by kale1d0code** [comment]
I Have this issue on 11.6.0
I can't format a datetime to only show the date
