### ISSUE TITLE
DataLinks: Links cause full page reload when linking to other dashboards or same dashboard

### ISSUE THREAD

**Issue by nickebbitt** [grafana/grafana#25115]
**What happened**:
We have a dashboard panel that uses a table to represent some metrics. One of the columns has a data link to the same dashboard with different template variables set (the same problem occurs with or without variables).

When clicking the link the URL in the browser updates but the page panels don't refresh with the new template variables.

Links to other dashboards work fine, but self links don't seem to work.

**What you expected to happen**:
A data link should be followed when clicked.

**How to reproduce it (as minimally and precisely as possible)**:
The problem occurs with the following panel JSON.

```
{
      "columns": [],
      "datasource": null,
      "description": "This panel shows a breakdown of the services running on the cluster which are calling $namespace.  ingress-nginx-internal, if present, represents all services on-prem making requests to $namespace.",
      "fontSize": "100%",
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 5
      },
      "hideTimeOverride": false,
      "id": 30,
      "links": [],
      "options": {},
      "pageSize": 5,
      "repeatDirection": "v",
      "scroll": true,
      "showHeader": true,
      "sort": {
        "col": 3,
        "desc": true
      },
      "styles": [
        {
          "alias": "Service",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "link": true,
          "linkTargetBlank": false,
          "linkTooltip": "$__cell dashboard",
          "linkUrl": "/d/at-application-health/service-health?orgId=1&var-namespace=$__cell_2&var-workload=$__cell_1",
          "pattern": "source_workload",
          "preserveFormat": false,
          "sanitize": false,
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "Ops",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "pattern": "Value #A",
          "thresholds": [
            ""
          ],
          "type": "number",
          "unit": "ops"
        },
        {
          "alias": "P95",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 0,
          "pattern": "Value #B",
          "thresholds": [],
          "type": "number",
          "unit": "s"
        },
        {
          "alias": "P50",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 0,
          "link": false,
          "pattern": "Value #C",
          "thresholds": [],
          "type": "number",
          "unit": "s"
        },
        {
          "alias": "P90",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 0,
          "pattern": "Value #D",
          "thresholds": [],
          "type": "number",
          "unit": "s"
        },
        {
          "alias": "P99",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 0,
          "pattern": "Value #E",
          "thresholds": [],
          "type": "number",
          "unit": "s"
        },
        {
          "alias": "Success",
          "align": "auto",
          "colorMode": "cell",
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 3,
          "pattern": "Value #F",
          "thresholds": [
            "0.95",
            "1.00"
          ],
          "type": "number",
          "unit": "percentunit"
        },
        {
          "alias": "",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "pattern": "Time",
          "thresholds": [],
          "type": "hidden",
          "unit": "short"
        },
        {
          "alias": "Implied",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 0,
          "mappingType": 1,
          "pattern": "Value #G",
          "thresholds": [],
          "type": "hidden",
          "unit": "s"
        },
        {
          "alias": "",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "source_workload_namespace",
          "thresholds": [],
          "type": "hidden",
          "unit": "short"
        }
      ],
      "targets": [
        {
          "expr": "sum(istio_requests_total:rate1m{source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\"}) by (source_workload, source_workload_namespace)",
          "format": "table",
          "hide": false,
          "instant": true,
          "interval": "30s",
          "intervalFactor": 1,
          "legendFormat": "{{ source_workload  }}",
          "refId": "A"
        },
        {
          "expr": "(\nsum(istio_request_duration_milliseconds_bucket:rate1m{percentile=\"50\", source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\"}) by (source_workload, source_workload_namespace) / 1000\n)\n> 0",
          "format": "table",
          "hide": false,
          "instant": true,
          "interval": "30s",
          "intervalFactor": 1,
          "legendFormat": "{{ source_workload }}",
          "refId": "C"
        },
        {
          "expr": "(\nsum(istio_request_duration_milliseconds_bucket:rate1m{percentile=\"90\", source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\"}) by (source_workload, source_workload_namespace) / 1000\n)\n> 0",
          "format": "table",
          "hide": false,
          "instant": true,
          "interval": "30s",
          "intervalFactor": 1,
          "legendFormat": "{{ source_workload }}",
          "refId": "D"
        },
        {
          "expr": "(\nsum(istio_request_duration_milliseconds_bucket:rate1m{percentile=\"95\", source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\"}) by (source_workload, source_workload_namespace) / 1000\n)\n> 0",
          "format": "table",
          "hide": false,
          "instant": true,
          "interval": "30s",
          "intervalFactor": 1,
          "legendFormat": "{{ source_workload }}",
          "refId": "B"
        },
        {
          "expr": "(\nsum(istio_request_duration_milliseconds_bucket:rate1m{percentile=\"99\", source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\"}) by (source_workload, source_workload_namespace) / 1000\n)\n> 0",
          "format": "table",
          "hide": false,
          "instant": true,
          "interval": "30s",
          "intervalFactor": 1,
          "legendFormat": "{{ source_workload }}",
          "refId": "E"
        },
        {
          "expr": "  1 -\n  (\n    (\n      sum(increase(istio_requests_total:rate1m{source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\", response_code=~\"5.*|0\"}[5m])) by (source_workload, source_workload_namespace)\n      or\n      (count(count(istio_requests_total:rate1m{source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\"}) by (source_workload, source_workload_namespace) > 0) by (source_workload, source_workload_namespace) -1)\n    )\n    /\n    (sum(increase(istio_requests_total:rate1m{source_workload!=\"unknown\", destination_workload_namespace=\"$namespace\", destination_workload=\"$workload\"}[5m])) by (source_workload, source_workload_namespace) > 0)\n  ) <= 100",
          "format": "table",
          "hide": false,
          "instant": true,
          "interval": "30s",
          "intervalFactor": 1,
          "legendFormat": "{{ source_workload }}",
          "refId": "F"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Source Services",
      "transform": "table",
      "type": "table"
    }
```

**Anything else we need to know?**:
The same dashboard works in 6.6.2.

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana docker image
- User OS & Browser: Mac OSX Catalina 10.15.4 & Chrome 81.0.4044.138
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Works when I test here (check the second column link): https://play.grafana.org/d/27c0IFkGk/data-link-with-dashboard-variable?orgId=1&var-variable=asd

**Comment by torkelo** [comment]
I can replicate the problem that links cause a full page reload:

the target defaults to _self , it should not do that
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldOverrides.ts#L370

**Comment by Stono** [comment]
@torkelo - that's not quite what we're seeing so we're a little confused.  We don't even see full page reloads.

I'm more than happy to screen share with you to demonstrate the problem?

**Comment by nickebbitt** [comment]
@torkelo hi, this issue has been renamed to suggest that links cause full page reloads, this is not the case for the issue I reported.

As @Stono has clarified, when clicking a data link in a table the URL updates on the browser however the template variables do not and the data in the panels on the page is not refreshed with the new data.

Are you able to recreate this scenario in the playground? It would be unfortunate for this issue to not solve the actual problem that was raised.

**Comment by nickebbitt** [comment]
As a temp workaround enabling `Open in new tab` ensures the link works however we lose some of the user experience we'd like by remaining in the same tab.

Something I spotted that may be relevant, the diff after enabling `Open in new tab` shows the panel type `"type": "table-old"`.

**Comment by torkelo** [comment]
Fixed in master

**Comment by jaspreetm1221** [comment]
I think we need to reopen this issue since, this is still not working in version v7.1.5.

As a work around I open links in a new tab.

**Comment by nickebbitt** [comment]
It was fixed, so maybe a regression. We're running 7.1.3 and links are opening correctly within the same browser window. I'll check if it's not working for us either with 7.1.5.

**Comment by matthubb** [comment]
> I think we need to reopen this issue since, this is still not working in version v7.1.5.
> 
> As a work around I open links in a new tab.

I've currently have drill down links working without page reloads on v7.1.5. The data link format has to include the dashboard slug, which is an inconvenience and I've an enhancement request open about that.
e.g. field override data link url =  `/d/${__dashboard.uid}/cpu-stats-by-host?var-host=${__data.fields[host]}&${__url_time_range}`

**Comment by nickebbitt** [comment]
yeah it's working for us with 7.1.5 also

**Comment by iridos** [comment]
I still (or again) see the behavior, that a variable does not update in a table, although the new variable content is correctly shown on top of the dashboard. 
Pressing "refresh" to load new data into the tables changes to the correct variable value in the table.

**Comment by j9archer** [comment]
> I still (or again) see the behavior in grafana 11.4, that a variable does not update in a table, although the new variable content is correctly shown on top of the dashboard. Pressing "refresh" to load new data into the tables changes to the correct variable value in the table.
> 
> I adjusted the link to be similar to the one from matthubb just above: `https://host/grafana/d/${__dashboard.uid}/usage?orgId=1&var-user=${__data.fields.user}&${__url_time_range}`

I have the same issue in grafana 11.3.0. The data link updates the panel it was called from, but not the other panels in the same dashboard. I need to do a page reload to force an update for these.

**Comment by theok-nice** [comment]
I am getting the similar behavior but I think the cause has to do with dashboard name:
https://github.com/grafana/grafana/issues/100274

**Comment by iridos** [comment]
Don't think that is related to what I see. When I remove all spaces (actually any special chars) from the dashboard name, the problem still persists
