### ISSUE TITLE
Bar gauge: Names/Alias disappear after Update from 6.x to 7.x

### ISSUE THREAD

**Issue by valcryst** [grafana/grafana#25283]
**What happened**:
Names of the Bar gauge metrics disappear after upgrade to Grafana 7.x

![image](https://user-images.githubusercontent.com/12711020/83505943-c98a8600-a4c6-11ea-8664-d5b711876335.png)

**What you expected to happen**:
Names do not disappear
**How to reproduce it (as minimally and precisely as possible)**:
Upgrade Grafana 6.x to 7.x with Bar gauges that have Aliases
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: InfluxDB 1.8.0-1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Firefox & Chrome
- Grafana plugins: none
- Others:

**Comment by peterholmberg** [comment]
should be fixed via https://github.com/grafana/grafana/pull/24829

**Comment by valcryst** [comment]
@peterholmberg Is this fix is included in 7.0.3 because i still have the same issue on latest.
