### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by restlessankyyy** [grafana/grafana#25319]
An unexpected error happened
Details
TypeError: Cannot read property '1' of undefined

    in t
    in div
    in t
    in div
    in r
    in u
    in div
    in div
    in div
    in e
    in t
    in div
    in t
    in t
    in div
    in div
    in t
    in d
    in div
    in t
    in div
    in t
    in t
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in t
    in div
    in div
    in div
    in e
    in t
    in div
    in div
    in t
    in d
    in n
    in Unknown
    in p
    in Unknown
    in Unknown
    in t
    in t
    in d

**What happened**: While opening grafana dashboard edit tab

**What you expected to happen**: I should be able to edit the dashboard

**How to reproduce it (as minimally and precisely as possible)**: Install grafana 6.6.2 and use apica data source

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6
- Data source type & version: Apica
- OS Grafana is installed on: Docker container
- User OS & Browser: Google Chrome
- Grafana plugins: Apica
- Others:

**Comment by peterholmberg** [comment]
Can't find the Apica plugin, has it been updated recently? 

Is upgrading your grafana version (to 7.0.x) an option ?

**Comment by restlessankyyy** [comment]
Nope.

**Comment by restlessankyyy** [comment]
is seems to be a react js error.

**Comment by peterholmberg** [comment]
where can I find the apica plugin?

**Comment by restlessankyyy** [comment]
https://apica-kb.atlassian.net/wiki/spaces/ASMDOCS/pages/4631616/On-Premise+Grafana+Servers

Please use this link.

**Comment by restlessankyyy** [comment]
It is happening for some influxdb datasource as well.

**Comment by restlessankyyy** [comment]
Please let us know if you need more details on it.

**Comment by marefr** [comment]
@restlessankyyy feels like a bug we've already fixed. Can you try a later version like 6.6.2, 6.7.4 or 7.0.3?

**Comment by restlessankyyy** [comment]
we are using 6.6.2, I am still getting this. Do I need to upgrade it to 6.7.4.

**Comment by aknuds1** [comment]
@restlessankyyy I would try v6.7.4, v7.0.3 to see if it's fixed.

**Comment by Sup3rlativ3** [comment]
I'm on 7.0.3 and I'm getting the same error consistently.

**What happened:** 
* Added a new dashboard
* Added a panel (doesn't matter which)
* Started to build the query (I can trigger with just win_cpu)
* Set the Format As to table
* Error

**What you expected to happen:** 
I should be able to edit the dashboard

**How to reproduce it (as minimally and precisely as possible):** 
As per above

**Anything else we need to know?:**
* It seems that if I never try to use the Status Panel Panel I'm much less likely to encounter the error

**Environment:**
* Grafana version: 7.0.3
* Data source type & version: InfluxDB 1.7.8
* OS Grafana is installed on: Windows Server 2016 DataCenter
* User OS & Browser: Edge Chromium

**Comment by marefr** [comment]
@Sup3rlativ3 sounds like a problem with [Status Panel plugin](https://grafana.com/grafana/plugins/vonage-status-panel). Any chance this is the [issue](https://github.com/Vonage/Grafana_Status_panel/issues/168) you're facing?

**Comment by Sup3rlativ3** [comment]
@marefr That looks to be it, thank you. I'll try to make the change today but as suggested in the first thread, I might need to move away from using that panel altogether if it's not being maintained.

**Comment by marefr** [comment]
Thanks. Closing this for now. We'll consider reopen this if it's a problem in Grafana.
