### ISSUE TITLE
7.0 Gauge / Bar Gauge does not show term labels.

### ISSUE THREAD

**Issue by i5okie** [grafana/grafana#25343]
Bar Gauge or Gauge for that matter does not show term labels. Changing orientation/other options makes no difference, labels do not show up. (does not matter which style/orientation)
![image](https://user-images.githubusercontent.com/2119240/82613267-bc41d300-9b79-11ea-8169-e9eb50bf45ee.png)
![image](https://user-images.githubusercontent.com/2119240/82613284-c5cb3b00-9b79-11ea-82e0-1981d5112889.png)

Expected behavior (downgraded to 6.7.3 shows as expected):
![image](https://user-images.githubusercontent.com/2119240/82614988-0dec5c80-9b7e-11ea-8bdc-83e5a47f086b.png)

This is against Elasticsearch datasource. Have not tried others.

**Comment by i5okie** [comment]
Just upgraded to 7.0.3. Looks like this has been fixed. closing

**Comment by fluegra** [comment]
We are facing the same issues since upgrading to version 7(.0.1). An update to 7.5 didn't solve it. So I guess this issue still exists.

**Comment by i5okie** [comment]
> We are facing the same issues since upgrading to version 7(.0.1). An update to 7.5 didn't solve it. So I guess this issue still exists.

Yeah, if you follow the progress, it looks like there was a bigger issue uncovered which affects other parts of Grafana too if I understand it correctly. I’m just not upgrading until this is resolved, because we need this to work.

**Comment by torkelo** [comment]
This is resolved, no open issue like this

**Comment by torkelo** [comment]
unable to replicate this in 7.1.5
https://play.grafana.org/d/VaeQyXDMz/elastic-gauge-labels?orgId=1&from=now-5m&to=now

**Comment by torkelo** [comment]
will re-open if this is still a problem, but then include panel json, and raw query results
