### ISSUE TITLE
TimeSeries & Graph: Disable add annotation context menu  

### ISSUE THREAD

**Issue by roman-tiukh** [grafana/grafana#25580]
I want disable annoying "Add annotation" popup
![image](https://user-images.githubusercontent.com/38906004/84596730-1297ee00-ae68-11ea-8c35-4ab10f6b77f0.png)

**Steps to reproduce**:
click to chart

**Actual Result**:
annoying popup

**Expected Result**
if annotations disabled, popup not showing

**Environment**:
- Grafana version: 7.0.3

**Comment by sakjur** [comment]
It makes sense that it would be hidden if the "Annotations & Alerts" annotation source isn't enabled.
The graph panel is facing an impending migration from Angular to React #14789. I don't think this will be fixed before that is done, but it's good input for that process 🙂

**Comment by ptitou** [comment]
Interested by this functionnality too, if user not authorized (guest access), don't show the popup.

**Comment by xieziqiang** [comment]
+1 on this!

**Comment by castillo92** [comment]
@sakjur @xieziqiang 

Please, thumbs up the first post

**Comment by thisisobate** [comment]
Hi @castillo92 @roman-tiukh 

You can use the new Timeseries panel without experiencing this issue. I would recommend you try it out and see if it solves your problem.

Hope this helps!

**Comment by castillo92** [comment]
> 
> 
> Hi @castillo92 @roman-tiukh
> 
> You can use the new Timeseries panel without experiencing this issue. I would recommend you try it out and see if it solves your problem.
> 
> Hope this helps!

It's true, the new Timeseries panel does not show the "Add annotation" popup. Thanks you very much!

But, because this panel is in beta step, it could be implemented in a future? What happend with the alarms in this panel?

**Comment by allomorphy** [comment]
> > Hi @castillo92 @roman-tiukh
> > You can use the new Timeseries panel without experiencing this issue. I would recommend you try it out and see if it solves your problem.
> > Hope this helps!
> 
> It's true, the new Timeseries panel does not show the "Add annotation" popup. Thanks you very much!
> 
> But, because this panel is in beta step, it could be implemented in a future? What happend with the alarms in this panel?

👋
Is this not because annotations are simply not _yet_ implemented in the shiny new TimeSeries 😞

**Comment by kkevvai** [comment]
The 'Add annotation' popup appears to be disabled for users with 'Viewer' privileges and when a dashboard is configured as 'Read-only'. This, of course, is only helpful in a limited set of use cases. Tested with Time-series panels on Grafana 8.1.5.

**Comment by castillo92** [comment]
Yes... it still be there.... It is very anoying in touch screens, like all UI

**Comment by melvanderwal** [comment]
Adding my vote.  A primary use case is mobile devices, and the Add Annotation popup sometimes obscures the graph popup. And sometimes you simply don't want annotation to be an option.

**Comment by TTLucian** [comment]
Yup. Very annoying!

**Comment by rparol** [comment]
Very annoying! Please fix the issue.
When I long-touch the screen then it is not appearing - kind of workaround :)

**Comment by EtiolEhomba** [comment]
It's very annoying on mobile devices. Could you pls change priority to medium or high?

**Comment by rvk01** [comment]
After almost 2 years this hasn't even been assigned yet. Very discouraging.

**Comment by justlep** [comment]
As a quick & dirty solution for Docker image `grafana/grafana:8.5.2-ubuntu`, I ended up altering the dark theme css directly in the running container:
```sh
docker exec -u0 grafana sh -c 'echo "body .css-m2xj9h{display:none}" >> /usr/share/grafana/public/build/grafana.dark.b208037f6b1954dc031d.css'
```
Both CSS filename and "Context menu" DIV's class name are specific to that image, of course, but should be easy to determine for other builds as well. Not beautiful at all, but problem solved for me.

**Comment by amirmd76** [comment]
Please please please fix this, it's SOOOOO ANNOYING.

**Comment by MarcoH2O** [comment]
is there anything new?

**Comment by castillo92** [comment]
> Hi @castillo92 @roman-tiukh
> 
> You can use the new Timeseries panel without experiencing this issue. I would recommend you try it out and see if it solves your problem.
> 
> Hope this helps!

Today, "add annotation" button is in the new Time Series panel... and we still cant disable it. Using it in mobiles is very annoying

**Comment by maumi** [comment]
For me, the only real "fix" is actual to set the dashboard read only and log in as viewer, as already said here. 
But it's still annoying if you want to make changes

**Comment by pango** [comment]
+1 
This annotation Popup is fucking anoying. I'm using grafana on a mobile device and the stupid implementation hinders me to interact with Diagramms as originaly intended. See yourself in this short video:

https://user-images.githubusercontent.com/148268/191262400-d3b6c057-76af-42e8-82e1-305d31501cc3.mp4

 If there would be an Option to completely dissable annotations for my grafana instance I would imediatly make use of it.

**Comment by sseypt** [comment]
> +1 This annotation Popup is fucking anoying. I'm using grafana on a mobile device and the stupid implementation hinders me to interact with Diagramms as originaly intended. See yourself in this short video:
> 
>  Record_2022-09-20-14-44-59.mp4 
> If there would be an Option to completely dissable annotations for my grafana instance I would imediatly make use of it.

Great Video. I can feel the pain 🙈 Same here. The charts could just as well be static images. It would not make any difference.

Did you try https://github.com/grafana/grafana/issues/25580#issuecomment-1141341267?

**Comment by sauvant** [comment]
Same here. Incredible low feedback for this high impact GUI issue. That should be VERY easily solvable. Come on Grafana developers, you can do better...

**Comment by tclausing** [comment]
A variation on @justlep's CSS hack above that moves popup menus to the bottom right corner of the screen so they don't cover the data tooltip. Writes to all css theme files. Selects all popups using `[role=menu]` instead of the generated class since the class changes with each build.

```sh
docker exec -u0 grafana sh -c 'echo "[role=menu]{left: auto !important; top: auto !important; right: 10px; bottom: 10px;}" | tee -a /usr/share/grafana/public/build/grafana.*.css'
```

![image](https://user-images.githubusercontent.com/7464100/197268092-c226bb4e-8b3b-4c07-aac6-13ea5a22315e.png)

**Comment by leeoniya** [comment]
we just merged a commit that fixes the original issues (disabling Annotation datasource should disable Add annotation popover).

the mobile/tooltip overlap aspect will be tracked in https://github.com/grafana/grafana/issues/57565

**Comment by leeoniya** [comment]
update: the mobile situation should improve in upcoming v10.2, once https://github.com/grafana/grafana/pull/76492 is merged.

**Comment by castillo92** [comment]
> update: the mobile situation should improve in upcoming v10.2, once #76492 is merged.

Sadly does not improve a lot for me, but appreciate the updates and I give thanks first. Using Safari and touching Time Series panel, "Add annotation" popup still appear, hiding some metrics, a couple of second after, it disappear.

The upper bar of Grafana, search , user, and location of dashboard, plus navigation bar, use near of 40% of the screen in portrait screen
