### ISSUE TITLE
Grafana v7.0.3 login loop

### ISSUE THREAD

**Issue by redbaron4** [grafana/grafana#25758]
**What happened**: After upgrade to v7.0.3 I can no longer login to Grafana. After inputting the correct usernames/ password, the green tooltip ("Logged In") flashes and I am redirected to next page, but the page again redirects to login. Before this I was using v6.7.3 and it was working oerfectly

**What you expected to happen**: On entering correct password, login should be successful

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: Grafana is running behind a reverse proxy and is accessed using subpath `/grafana`
The Nginx config is

```
location /grafana/ {
        proxy_pass http://grafana/;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass_header Access-Control-Allow-Origin;
        proxy_pass_header Access-Control-Allow-Methods;
        proxy_hide_header Access-Control-Allow-Headers;
        add_header Access-Control-Allow-Headers 'X-Requested-With, Content-Type';
        add_header Access-Control-Allow-Credentials true;
}
```

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Graphite - 1.1.7
- OS Grafana is installed on: Centos7
- User OS & Browser: Firefox 68.3 esr on CentOS 6
- Grafana plugins: None
- Others: NA

The grafana logs have the following entry

```
t=2020-06-23T10:54:50+0530 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2020-06-23T10:54:50+0530 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2020-06-23T10:54:50+0530 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2020-06-23T10:54:50+0530 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=XX.XX time_ms=1 size=37 referer=https://xxx/grafana/login
t=2020-06-23T10:54:50+0530 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
```

**Comment by marefr** [comment]
Duplicate of #25444

**Comment by marefr** [comment]
Please read the [upgrade notes](https://grafana.com/docs/grafana/latest/installation/upgrading/#cookie-path). Clearing the cookies should resolve the problem

**Comment by joyceliaoxy** [comment]
I have the same issue, though I clear the cookies, this problem still here.
Grafana version: 7.0.3
Data source type & version: Graphite - 1.1.7
OS Grafana is installed on: Centos7
User OS & Browser: Firefox 60.6.1 on CentOS 7
Grafana plugins: None
Others: NA

**Comment by marefr** [comment]
@joyceliaoxy please try Grafana v7.0.5 if that makes any difference. If that doesn't help, please open a new issue and include detailed information about your configuration, logs and possibly screenshots. Thanks

**Comment by surajavail** [comment]
Go to Grafana Home->conf -> Defaults
Change cookiesamesite = disabled

**Comment by ShadowBr0ther** [comment]
Hello. 
I installed a docker image of grafana on a outsourced server.
I tried to integrate my dasboard into my local home Assistant installation, but what ever I try, I keep getting this login loop.
It only doesn't work on Chrome based browsers. Firefox is working fine.

Settings: 
- GF_SECURITY_ALLOW_EMBEDDING=true
- GF_SECURTIY_COOKIE_SECURE=false
- GF_SECURITY_COOKIE_SAMESITE=disabled

Grafana version: 8.3.3
Docker Image:  grafana/grafana-enterprise
Chrome version: 96.0.4664.93
Home Assistant Version: 2021.12.1

In my browser console is no error. 
Is there a known issue?
