### ISSUE TITLE
Nested LDAP Groups

### ISSUE THREAD

**Issue by tmalkowski** [grafana/grafana#2582]
I'm trying to tie in AD authentication via LDAP, and wanted to use nested groups (so our department groups are members of the various Grafana groups, as opposed to individual membership in the groups).

I'm hoping it's just a matter of getting filter strings passed correctly to the underlying LDAP library, but haven't done much digging into the code yet. It's also possible I'm just doing it wrong. :)

Here's what I was hoping to get working: (Obviously the final implementation would include groups for admins and editors as well)

> search_filter = "(&(CN=%s)(memberof:1.2.840.113556.1.4.1941:=CN=Grafana-Users))"

Would also require nested groups for group_dn, so really I could get away with not using them in the search_filter.

e.g. for Admin role:
> group_dn = "memberof:1.2.840.113556.1.4.1941:=CN=Grafana-Admins"

Any chance that's already possible in newer builds? I'm running the latest stable version currently, 2.1.2-1

**Comment by torkelo** [comment]
You will have to explain what limitation with the current ldap group to membership mapping you are having. I do not understand much of what your proposing in this issue :)

**Comment by tmalkowski** [comment]
Apologies, I'll try to explain a bit more thoroughly. (I'll probably get too pedantic, but hopefully I'll be able to express the idea more clearly.)

We use nested groups to define role-based access with our Active Directory implementation. So, for example, our System Team group is actually a member of the Grafana-Users group, instead of individually adding each team member. (At least, assuming we can get this working.) For grafana1.x, this wasn't a problem, as we were able to use Apache's authz-ldap module to accomplish this.

Here's some basic output from ldapsearch: (I simplified command params just to make it more clear)

$ ldapsearch CN=Grafana-Users|grep ^member:
member: CN=System Team,OU=User Groups,OU=Groups,DC=example,DC=com
member: CN=mrbuttons,OU=Users,DC=example,DC=com

Here's my config in ldap.toml:

```
[[servers.group_mappings]]
org_role = "Editor"
group_dn = "CN=Grafana-Editors,OU=App Groups,OU=Groups,DC=example,DC=com"
```

So, with the above configuration, the "mrbuttons" user has the Editors role successfully applied, but anyone who inherits membership by way of nested groups does not. (Specifically, users who are members of the "System Team" group.)

I expected to be able to use a nested group filter similar to the following, but haven't been successful:

```
group_dn = "memberof:1.2.840.113556.1.4.1941:=CN=Grafana-Editors,OU=App Groups,OU=Groups,DC=example,DC=com"
```

This may very likely be an issue with the underlying LDAP module, but I'm not familiar with Go and unfortunately haven't found the time to read through the code to see if something jumps out at me.

Sorry it took so long to respond, go figure, the work life of a sysadmin is a hectic one. I can provide more examples if it'll help.

**Comment by tmalkowski** [comment]
I'm no Go developer but hacked up a copy of example_test.go in the upstream go-ldap/ldap repo. From my initial testing, it looks like the library doesn't support this syntax for searches, so there may be quite a bit involved in making this happen.

FYI, I created an issue there: https://github.com/go-ldap/ldap/issues/28

After looking at more of grafana2's ldap code, it looks like you're matching groups that show up in LDAP attributes for a user, as opposed to using membership filters to determine a list of users that match. Unfortunately if that's the case, it sounds like it's the opposite direction I was expecting, meaning it might not be practical to implement this without a serious overhaul of the LDAP lookup code. Then again, I'm no Go developer, so...

**Comment by tmmukunn** [comment]
The issue i believe is resolved in go-ldap #28.  With the current code in grafana it is possible to hack something by using the POSIX search.  However, instead of using the samaccountName to login, you'd have to use the CN instead.  The POSIX search that grafana setup uses whatever is used for the user name.  For the search filter, you would do something like group_search_filter = "(member:1.2.840.113556.1.4.1941:=CN=%s,OU=[Organization Unit],DC=[Domain Component])"  
The reason you have to use CN is because the Member/Member Of extension only works with the Distinguished name of the group/user.

This will work with no change to grafana, but we can't use the samAccountName as the username.

Now if there was a way we can specify which attribute grafana uses in the user name for the group search after it retrieves the user info, that would make it way easier :).

**Comment by tmmukunn** [comment]
ldap-go 2.2 has been released that has the support for extensible match.

**Comment by Alph4d0g** [comment]
Is there any possibility we you could update the underlying ldap-go to version 2.2, or did this already happen ?
In our company we also use samAccountName as the user and have our LDAP built with AGDLP scheme [Wikipedia AGDLP](https://en.wikipedia.org/wiki/AGDLP)

**Comment by tmmukunn** [comment]
Still interested in this as well.

**Comment by Alph4d0g** [comment]
*monthly bump*

**Comment by dccsp92** [comment]
Agree...I am running into the exact same issue.  If in addition to passing back the login username in the %s variable it could pass back the full CN for the user in say a %cn variable then there would not be any issues looking up the group memberships in active directory ldap I think.

**Comment by phemmer** [comment]
Also running into this. because of the fore-mentioned issue with `%s` being substituted with the value of the configured `username` property (such as `samAccountName`) instead of the CN, I don't see how the linked PR (#4401) helps any with this.

**Comment by tpoindessous** [comment]
Hi,

can we re-open this issue ?

Thanks !

**Comment by provenvelocity** [comment]
Per @tmalkowski comments on on Sep 9, 2015 the real issue of memberOf only showing the child level groups and not the nested parent level ldap group issue can be resolved.  I am working on a branch that has a fix I amusing in my company. The fix is to add a ldap config and some code to add to memberOf showing which parent group authorized the user. This allows role-based access from LDAP with nested groups.  Should have it up later this week. I have worked in private companies and this will be my first pull on Github to give back is there a document I should read up on and follow?

**Comment by tmalkowski** [comment]
See response from @tmmukunn on Nov 23, 2015 — this was a go-ldap bug which has been resolved for years.

You don't want to overload the behavior of the memberOf function, since memberOf should literally return memberOf, and not memberOf+other stuff. That would not be a proper ldap implementation.

I don't understand the problem you're having; since this bug was fixed I've had my ldap.toml configuration working fine:

`
group_search_filter = "(member:1.2.840.113556.1.4.1941:=%s)"
group_search_filter_user_attribute = "distinguishedName"
group_search_base_dns = ["OU=App Groups,DC=domain,DC=org"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "distinguishedName"
email =  "mail"

[[servers.group_mappings]]
group_dn = "CN=Grafana-Admins,OU=App Groups,DC=domain,DC=org"
org_role = "Admin"
`

From the ldap perspective, only groups are members of the Grafana groups:

`
dn: CN=Grafana-Admins,OU=App Groups,DC=domain,DC=org
member: CN=Linux Team,OU=User Groups,DC=domain,DC=org
member: CN=Windows Team,OU=User Groups,DC=domain,DC=org
`

And yet, through the magic of member:1.2.840.113556.1.4.1941:, it all works fine.

**Comment by provenvelocity** [comment]
I can start a new thread then if needed, but yes the member:1.2.840.113556.1.4.1941 fix's the nested search but does not fix the memberOf chain return issue that is still present.

The only setting I don't have is this and I will try that today is this one.

group_search_filter_user_attribute = "distinguishedName"

This may fix my existing iMemberOf Chain issue in the most recent release of grafana as I will explain below.

With a working ldap toml and the LDAP_MATCHING_RULE_IN_CHAIN turned on this is the result I get.

toml:

group_search_filter = "(&(|(mail=%s)(sAMAccountName=%s)(userPrincipalName=%s))(|(memberOf:1.2.840.113556.1.4.1941:=CN=grfana-admin,OU=Groups,OU=Managed,DC=corp,DC=company,DC=com)(memberOf:1.2.840.113556.1.4.1941:=CN=grfana-users,OU=Groups,OU=Managed,DC=corp,DC=company,DC=com)))"
search_base_dns = ["ou=Users,ou=Managed,dc=company,dc=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "CN=grfana-admins,OU=Groups,OU=Managed,DC=company,DC=com"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "CN=time-machine,OU=Groups,OU=Managed,DC=company,DC=com"
org_role = "viewer"

[[servers.group_mappings]]
group_dn = "*"
org_role = "editor"

ldap data:
group: grfana-admins
     user: bill
     group: most-excellent 
          user: ted
group: grfana-users
     user: nufus
     group: time-machine
         user: napoleon

Ldap return in grafana with debug on.

user: bill 
     memberOf=[CN=grfana-admins,OU=Groups,OU=Managed,DC=company,DC=com]
user: ted 
     memberOf=[CN=most-excellent,OU=Groups,OU=Managed,DC=company,DC=com]
user: Rufus 
     memberOf=[CN=grfana-users,OU=Groups,OU=Managed,DC=company,DC=com]
user: Napoleon 
     memberOf=[CN=time-machine,OU=Groups,OU=Managed,DC=company,DC=com]

I can log in with all users.  wowo

user rights in grafana:
bill: admin
ted:Editor
rufus:Editor
napoleon: editor

Not the right user rights: sad

The issue is that AD does not return the parent groups in memberOf only the last group in the chain that was used to authenticate. It is a known flaw in AD ldap and has never been fixed to the best of my knowledge. 

I wrote some code in ldap.go to take the groupDN in server group mappings and find out the group used to auth the user at login and add to the user's memberOf as follows.

same ldap data

user: bill 
     memberOf=[CN=grfana-admins,OU=Groups,OU=Managed,DC=company,DC=com]
user: ted 
     memberOf=["CN=grfana-admins,,OU=Groups,OU=Managed,DC=company,DC=com","CN=most-excellent,OU=Groups,OU=Managed,DC=company,DC=com"]
user: Rufus 
     memberOf=[CN=grfana-users,OU=Groups,OU=Managed,DC=company,DC=com]
user: Napoleon 
     memberOf=["CN=time-machine,OU=Groups,OU=Managed,DC=company,DC=com","CN=grafana-users,OU=Groups,OU=Managed,DC=company,DC=com"]

User rights in grafana:
bill: admin
ted: admin
rufus:Editor
napoleon: viewer

As said this is a known flaw with AD and if your fix above fix's it for me then great but otherwise I have a fix if wanted.
