### ISSUE TITLE
Alerts not working (on 7.0.2), dashboards save not working (on 7.0.2), due to notification id to uid translation issues

### ISSUE THREAD

**Issue by kali-brandwatch** [grafana/grafana#25970]
**Update**:
After testing 7.0.5 I can confirm that the main issues (alerts not sent, save dashboard not working) are *solved*.

The log file still gets filled up with warning messages:
```
t=2020-07-01T15:28:25+0000 lvl=eror msg="Unable to translate notification id to uid" logger=alerting.testnotification error="Alert notification [ Id: 3, OrgId: 1 ] not found" dashboardId=103 alertId=4 panelId=1 notificationId=3
```
but that shuold be acceptable

**What happened**:
- After upgrade from 6.5.4 to 7.0.2 we noticed some alerts were no longer notified.
- When we tried to save a change on an affected dashboard, the save process would fail giving the following message:
```
Validation failed
Alert validation error: Unable to translate notification id to uid, Alert notification [ Id: 3, OrgId: 1 ] not found PanelId: 1 DashboardId: 157
```

- The underlying issue seems to be removed alert notification channels from the UI, while still in Grafana 6.x
- Grafana log shows the following:
```
t=2020-06-17T07:05:17+0000 lvl=eror msg="Could not build alert model for rule" logger=alerting.ruleReader ruleId=41 error="Alert validation error: Unable to translate notification id to uid, Alert notification [ Id: 3, OrgId: 1 ] not found AlertId: 41 PanelId: 9 DashboardId: 157" 
```

**What you expected to happen**:
- Alert notifications already defined before the upgrade keep processing when a notification channel id to uid translation fails, so other notification channels get the alert sent.
- Saving changes to the dashboard work. Possibly offending notification id's get removed automatically from the json model, or at least safely ignored and only logged.

**How to reproduce it (as minimally and precisely as possible)**:
1- In Grafana 6.x, define a notification channel. 
2- Go to a dashboard and create an alert rule, and set it to send notifications to several channels, including the one created on step 1
3- Remove notification channel defined in step 1. You still receive alerts on the other configured channels
4- Upgrade to Grafana 7
5- Alerts are no longer sent to the valid notification channels, and grafana will log the errors described in this bug ticket.

**Anything else we need to know?**:
- I would expect that removing an alert notification would also remove any reference to it from any alert and dashboard configuration.
- This seems to not affect notifications defined in Grafana 7.x but only an issue for alerts defined while on 6.x once 7.x is running.
- I believe this is somewhat related to this commit: https://github.com/grafana/grafana/commit/44b7f3ea1c31af9587702d5dbe1138211ed0a8f6

**Environment**:
- Grafana version: 7.0.2
- Data source type & version: any
- OS Grafana is installed on: Debian Linux 9 (stretch)
- User OS & Browser: not relevant
- Grafana plugins: not relevant

**Comment by kali-brandwatch** [comment]
For further detail, this was the (relevant part of the) json model config when the issues were observed:
```
"notifications":[{"id":3},{"id":49}]}
```
After manually removing the offending `id` from the json model in the database (I suspect editing the json model from the UI under `dashboard settings` would do as well) I could proceed and save changes on the dashboard.

For alerts, I got them solved similarly, replacing 
```
[{"id":3},{"id":49}]
```
by
```
[{"id":49}]
```
in the `settings` field of the relevant rule row under `alerts` table.

**Comment by aknuds1** [comment]
Does this also fail in v7.0.5?

**Comment by aknuds1** [comment]
From what I hear, this _should_ be fixed in 7.0.3.

**Comment by kali-brandwatch** [comment]
I can't say for sure, I need to upgrade. I have not tested because I did not see any relevant mention to this on the changelog. I will check tomorrow and report back here

**Comment by kali-brandwatch** [comment]
Actually I could test just now....
I can confirm, on Grafana 7.0.5 the *save dashboard* issue is fixed.
But log still gets filled with these:
```
t=2020-07-01T15:18:41+0000 lvl=eror msg="Unable to translate notification id to uid" logger=alerting.testnotification error="Alert notification [ Id: 3, OrgId: 1 ] not found" dashboardId=103 alertId=4 pan```

**Comment by aknuds1** [comment]
I think the fix basically is to be tolerant versus these errors. I guess we can close the issue?

**Comment by aknuds1** [comment]
Can you please edit your issue, removing what you found actually works in v7.0.5?

**Comment by kali-brandwatch** [comment]
I am testing now if the alerts are being sent despite the warning in the log, will modify the issue accordingly with all the info once gathered

**Comment by kali-brandwatch** [comment]
I can also confirm that the notifications work properly on 7.0.5 despite the error messages in the logfile.

I will update the OP and I would understand this bug becoming a non-bug.

Thanks for your help

**Comment by aknuds1** [comment]
Can we just close the issue?

**Comment by kali-brandwatch** [comment]
I'm fine with closing the issue as it became a non issue really. But it would be nice to get these non-translateable id's removed automatically on dashboard save? Maybe turn it into a feature request?
It would also be nice that removing a notification channel from the UI would trigger cleanup of its references in notification settings

**Comment by kali-brandwatch** [comment]
Closing since it's already solved on 7.0.5

**Comment by aknuds1** [comment]
I'm not sure what the intention is with regards to the log messages, maybe they're desirable in order to indicate that the causes should be cleaned up? I wasn't involved in the fix, so don't know the thought behind.

**Comment by kali-brandwatch** [comment]
I find it a reasonable request because there is no way to solve the issue from logging unless you have access to the database and manually remove the offending `id` from the notification table entry.
The dashboard json model is editable via the grafana UI but the issue in the dashboard is no longer an issue as it now allows saving the dashboard (while keeping the offending `id` though). However, for the alert rule, there is no way in the UI to change the settings and I had to manually run some SQL `UPDATE`s with `REPLACE` clauses. Will maybe open another one and link to this one.
