### ISSUE TITLE
Provision folders structure from filesystem to Grafana does not work

### ISSUE THREAD

**Issue by eesperi** [grafana/grafana#26223]
**What happened**:
I attempted to provision folders and files using my file system, but the folder does not get created. The dashboard is provisioned, but under the General folder. 

[Link to documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#provision-folders-structure-from-filesystem-to-grafana)

/etc/grafana/provisioning/dashboards/provisioner.yaml
```
apiVersion: 1

providers:
 - name: dashboards
   type: file
   updateIntervalSeconds: 30
   options:
     path: /var/lib/grafana/dashboards/dashboards
     foldersFromFilesStructure: true
```

I have an empty dash to test folder provisioning.

/var/lib/grafana/dashboards/dashboards/TestFolder/sample_dash.json
```
{
    "id": null,
    "uid": null,
    "title": "Provisioning Test Dashboard...",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0
}
```

**What you expected to happen**:
I expect the folder TestFolder to be provisioned in Grafana, and the test dashboard to be under TestFolder. 

**How to reproduce it (as minimally and precisely as possible)**:
Please view above. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.1 (ef5b586d7d)
- Data source type & version: Prometheus
- OS Grafana is installed on: VM
- User OS & Browser: Chrome
- Grafana plugins: Sysdig
- Others:

**Comment by sc250024** [comment]
Having the exact same issue on Grafana 7.0.5. I also note that even though `allowUiUpdates` is set to `true`, I still get the error message saying that Grafana cannot save to the local filesystem.

Here's the relevant files:

<details>
<summary>docker-compose.yaml</summary>

```yaml
services:
  grafana:
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
      GF_SECURITY_ADMIN_PASSWORD: secret
    image: docker.io/grafana/grafana:7.0.5
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    volumes:
    - ./rootfs/etc/grafana/provisioning:/etc/grafana/provisioning:rw
    - ./dashboards:/etc/dashboards:rw
version: '3.4'
```

</details>

<details>
<summary>dashboardproviders.yaml</summary>

```yaml
apiVersion: 1
providers:
- allowUiUpdates: true
  disableDeletion: true
  editable: true
  name: my-dashboards-local
  options:
    foldersFromFilesStructure: true
    path: /etc/dashboards
  orgId: 1
  type: file
```

</details>

**Comment by arvin495** [comment]
Having the same issue on grafana 7.0.6. It's not creating folders but dashboards are created under general folder.

/etc/grafana/provisioning/dashboards/all.yml
`apiVersion: 1

providers:
- name: 'dashboards'
  type: file
  updateIntervalSeconds: 30
  options:
    path: /etc/grafana/provisioning/dashboards
    foldersFromFilesStructure: true`

my folder structure is as  follows
`.
├── all.yml
├── dev
│   └── home_co.json
└── test
    └── home_co.json`

**Comment by ByJacob** [comment]
This feature is included in version 7.1.0-beta3.

https://github.com/grafana/grafana/commit/810ec4c5f8ec5bf028d2de015fbb1779ff8fd94d

**Comment by jmichalek132** [comment]
> This feature is included in version 7.1.0.
> 
> [810ec4c](https://github.com/grafana/grafana/commit/810ec4c5f8ec5bf028d2de015fbb1779ff8fd94d)

In that case it should be highlighted in the documentation section [describing](https://grafana.com/docs/grafana/latest/administration/provisioning/#provision-folders-structure-from-filesystem-to-grafana) it as is in case of this [feature](https://grafana.com/docs/grafana/latest/administration/provisioning/#plugins) available from 7.1.0.

**Comment by ByJacob** [comment]
![image](https://user-images.githubusercontent.com/23155811/87678785-a6b4e800-c77b-11ea-9cdc-e4de1accb07b.png)

I did not notice it before, on the top right side you can choose which version of Grafana the documentation is presented for.

https://grafana.com/docs/grafana/v6.7/administration/provisioning/

**Comment by eesperi** [comment]
> ![image](https://user-images.githubusercontent.com/23155811/87678785-a6b4e800-c77b-11ea-9cdc-e4de1accb07b.png)
> 
> I did not notice it before, on the top right side you can choose which version of Grafana the documentation is presented for.
> 
> https://grafana.com/docs/grafana/v6.7/administration/provisioning/

I was viewing documentation for latest, that being v7.0. If this feature is only in v7.1, then it shouldn't be in the doc for the version I was viewing.

**Comment by paulojmdias** [comment]
I have the same issue in 7.1.0 that is released yesterday. All dashboards are provisioned on `General` folder.

```
apiVersion: 1

providers:
- name: dashboards
  type: file
  updateIntervalSeconds: 30
  options:
    path: /etc/grafana/dashboards
    foldersFromFileStructure: true
```

**Comment by jmichalek132** [comment]
> I have the same issue in 7.1.0 that is released yesterday. All dashboards are provisioned on `General` folder.
> 
> ```
> apiVersion: 1
> 
> providers:
> - name: dashboards
>   type: file
>   updateIntervalSeconds: 30
>   options:
>     path: /etc/grafana/dashboards
>     foldersFromFileStructure: true
> ```

The name of the default folder is general, change the name and it should work

**Comment by paulojmdias** [comment]
> > I have the same issue in 7.1.0 that is released yesterday. All dashboards are provisioned on `General` folder.
> > ```
> > apiVersion: 1
> > 
> > providers:
> > - name: dashboards
> >   type: file
> >   updateIntervalSeconds: 30
> >   options:
> >     path: /etc/grafana/dashboards
> >     foldersFromFileStructure: true
> > ```
> 
> The name of the default folder is general, change the name and it should work

Isn't make sense since `folder` and `folderUid` need to be empty for this works.

https://github.com/grafana/grafana/pull/23117/files#diff-21bb6cab0207495bb263495c098a22dcR52-R55

**Comment by jmichalek132** [comment]
> > > I have the same issue in 7.1.0 that is released yesterday. All dashboards are provisioned on `General` folder.
> > > ```
> > > apiVersion: 1
> > > 
> > > providers:
> > > - name: dashboards
> > >   type: file
> > >   updateIntervalSeconds: 30
> > >   options:
> > >     path: /etc/grafana/dashboards
> > >     foldersFromFileStructure: true
> > > ```
> > 
> > 
> > The name of the default folder is general, change the name and it should work
> 
> Isn't make sense since `folder` and `folderUid` need to be empty for this works.
> 
> https://github.com/grafana/grafana/pull/23117/files#diff-21bb6cab0207495bb263495c098a22dcR52-R55

I ran into the same issue. It helped me, I think it causes issue because the name of the default folder is general.

**Comment by paulojmdias** [comment]
If I use the configuration below, only the folder `General` has renamed to `Test`, so the issue will be the same.

```
apiVersion: 1

providers:
- name: dashboards
  type: file
  folder: 'Test'
  folderUid: 'Test'
  updateIntervalSeconds: 30
  options:
    path: /etc/grafana/dashboards
    foldersFromFileStructure: true
```

**Comment by paulojmdias** [comment]
> > > > I have the same issue in 7.1.0 that is released yesterday. All dashboards are provisioned on `General` folder.
> > > > ```
> > > > apiVersion: 1
> > > > 
> > > > providers:
> > > > - name: dashboards
> > > >   type: file
> > > >   updateIntervalSeconds: 30
> > > >   options:
> > > >     path: /etc/grafana/dashboards
> > > >     foldersFromFileStructure: true
> > > > ```
> > > 
> > > 
> > > The name of the default folder is general, change the name and it should work
> > 
> > 
> > Isn't make sense since `folder` and `folderUid` need to be empty for this works.
> > https://github.com/grafana/grafana/pull/23117/files#diff-21bb6cab0207495bb263495c098a22dcR52-R55
> 
> I ran into the same issue. It helped me, I think it causes issue because the name of the default folder is general.

If I use the configuration below, only the folder `General` has renamed to `Test`, so the issue will be the same.

```
apiVersion: 1

providers:
- name: dashboards
  type: file
  folder: 'Test'
  folderUid: 'Test'
  updateIntervalSeconds: 30
  options:
    path: /etc/grafana/dashboards
    foldersFromFileStructure: true
```

**Comment by jmichalek132** [comment]
> > > > > I have the same issue in 7.1.0 that is released yesterday. All dashboards are provisioned on `General` folder.
> > > > > ```
> > > > > apiVersion: 1
> > > > > 
> > > > > providers:
> > > > > - name: dashboards
> > > > >   type: file
> > > > >   updateIntervalSeconds: 30
> > > > >   options:
> > > > >     path: /etc/grafana/dashboards
> > > > >     foldersFromFileStructure: true
> > > > > ```
> > > > 
> > > > 
> > > > The name of the default folder is general, change the name and it should work
> > > 
> > > 
> > > Isn't make sense since `folder` and `folderUid` need to be empty for this works.
> > > https://github.com/grafana/grafana/pull/23117/files#diff-21bb6cab0207495bb263495c098a22dcR52-R55
> > 
> > 
> > I ran into the same issue. It helped me, I think it causes issue because the name of the default folder is general.
> 
> If I use the configuration below, only the folder `General` has renamed to `Test`, so the issue will be the same.
> 
> ```
> apiVersion: 1
> 
> providers:
> - name: dashboards
>   type: file
>   folder: 'Test'
>   folderUid: 'Test'
>   updateIntervalSeconds: 30
>   options:
>     path: /etc/grafana/dashboards
>     foldersFromFileStructure: true
> ```

The configuration above is invalid, docs:
Note. folder and folderUid options should be empty or missing to make foldersFromFilesStructure work.

**Comment by paulojmdias** [comment]
> The name of the default folder is general, change the name and it should work

I know, but with your comment, I understand to use the `folder` with a different value to use.

> The name of the default folder is general, change the name and it should work

**Comment by jmichalek132** [comment]
> > The name of the default folder is general, change the name and it should work
> 
> I know, but with your comment, I understand to use the `folder` with a different value to use.
> 
> > The name of the default folder is general, change the name and it should work

No you cannot use folder and foldersFromFilesStructure at the same time.

**Comment by nabokihms** [comment]
Hello. First of all, thanks for using this feature and giving feedback about it.

@paulojmdias looks like you missed the letter `s` in the option name.
Please change it like this `foldersFromFileStructure` -> `foldersFromFilesStructure` and check it one more time 🙏

**Comment by paulojmdias** [comment]
> Hello. First of all, thanks for using this feature and giving feedback about it.
> 
> @paulojmdias looks like you missed the letter `s` in the option name.
> Please change it like this `foldersFromFileStructure` -> `foldersFromFilesStructure` and check it one more time 🙏

Hi @nabokihms,

Many thanks for the head's up, I have seen the configuration example on the PR below, and I didn't see that typo sorry 🤦 

https://github.com/grafana/grafana/pull/23117/files#diff-dbd9cb7d903817ba9cc81e845e44fd9dR300

Issue solved 🙏

**Comment by eesperi** [comment]
> Hello. First of all, thanks for using this feature and giving feedback about it.
> 
> @paulojmdias looks like you missed the letter `s` in the option name.
> Please change it like this `foldersFromFileStructure` -> `foldersFromFilesStructure` and check it one more time 🙏

I got a little farther after upgrading to Grafana v7.1. I can now create folders and some dashboards from file system. The problem I'm facing now is that I cannot delete dashboards that where provisioned under the General folder, and since I can't delete these dashboards from the General folder they aren't provisioned under the intended folder. How do I go about deleting provisioned dashboards?

```
apiVersion: 1

providers:
  - name: dash
    type: file
    disableDeletion: false
    editable: true
    allowUiUpdates: true
    updateIntervalSeconds: 30
    options:
      path: /some/path/to/dash
      foldersFromFilesStructure: true
```

**Comment by nabokihms** [comment]
@eesperi Could you also provide files structure of  `/some/path/to/dash`? It's hard to determine where is the problem without it. Grafana logs will help too (if there is something unusual).

**Comment by desolatorxxl** [comment]
It's seems to work with Grafana 7.1.5.

**Comment by marefr** [comment]
Sounds like issues are resolved so I'll close this. Let us know if you don't agree and what's missing and we'll consider reopen it. Thanks

**Comment by mmchougule** [comment]
Anyone else still facing this issue? We are using Grafana 7.5.6, copied dashbord folders to `provisioning/dashboard` directory.  Structure something like this:
```$ tree /etc/grafana/provisioning/dashboards
/etc/grafana/provisioning/dashboards
└── Folder1
    ├── component1.json
    ├── component2.json
└── General
    ├── alerts.json
    ├── system.json
└── dashboards.yml
```

Grafana is deployed to AWS ECS with 2 tasks pointing to one Postgresql database. The issue is random, If I move `alerts.json` file to `Folder1` then the provisioning doesn't apply properly, it stays in the same folder. I checked the database and the folder_id is still 0. When I try this locally on my machine, it works. Anyone have an idea?

**Comment by ohofherr** [comment]
Just tried this feature. unfortunately it is not working for nested folders. only one folder level is supported.

**Comment by nabokihms** [comment]
In grafana, at a time feature was released, there were no nested folders. Are there any now?

**Comment by ohofherr** [comment]
yes, now there are nested folders
