### ISSUE TITLE
Inspect: Table decimals on Inspect doesn't respect configuration 

### ISSUE THREAD

**Issue by avelo** [grafana/grafana#26398]
**What would you like to be added**:
In a table with Decimals set to 3 in Standard Options and overrides for two parameters set to 2 decimals,
when inspecting, Table shows 1 or 0 decimals by default, which is inconsistent.
Activating "Apply field configuration", works as expected, with the correct number of decimals.

My suggestion is to always apply field configuration by default, as is the expected.

**Why is this needed**:
Precision and number of decimals is very relevant for many uses. Using Inspect and exporting data without carefully reviewing the options (to activate "Apply field configuration") generates a csv file with a loss of decimals, which is very problematic.

**Comment by torkelo** [comment]
This is by design, as inspect and csv Download is mainly about accessing and exporting the raw data

**Comment by dprokop** [comment]
@torkelo I was thinking about this, and TBH we are not displaying the raw data - as the display processor is executed and the decimals count is calculated resulting. I think we should display real raw data by default, meaning no display processor involved until field config is applied.

**Comment by avelo** [comment]
> @torkelo I was thinking about this, and TBH we are not displaying the raw data - as the display processor is executed and the decimals count is calculated resulting in decimals being dropped. I think we should display real raw data by default, meaning no display processor involved until field config is applied.

Exactly, as you said, you get decimals lost with default options, not the raw data.
Having raw data as default and the options switch for specific conf. would be the expected

**Comment by torkelo** [comment]
> I was thinking about this, and TBH we are not displaying the raw data - as the display processor is executed and the decimals count is calculated resulting in decimals being dropped. I think we should display real raw data by default, meaning no display processor involved until field config is applied.

I am confused, the field config is not enabled by default, so doing what this issue request is the opposite to what you suggest

**Comment by avelo** [comment]
> > I was thinking about this, and TBH we are not displaying the raw data - as the display processor is executed and the decimals count is calculated resulting in decimals being dropped. I think we should display real raw data by default, meaning no display processor involved until field config is applied.
> 
> I am confused, the field config is not enabled by default, so doing what this issue request is the opposite to what you suggest

In a sense may seems opposite, but is not. The real issue are decimals being dropped by default, and the proper solution, to just display raw data (with full decimals) by default.
My suggestion to apply the field config by default was only avoid the lost in precision, without being aware that the table should already show raw data.

You can see that in table here: https://co2.iim.csic.es/monitoring/d/f15S3qMGk/durafet-ecimat
pH with 3 decimals and temperature with 2. Panel defined with global set to 3 decimals and overrides cutting to 2 for temperature.
If you go to Inspect>Data you have the export table with 1 decimal for pH and 0 for temperature, so losing precision to being unusable.

**Comment by torkelo** [comment]
Strange, wonder why the decimals are lost

**Comment by torkelo** [comment]
Not sure what to do here, not a bug per say

**Comment by avelo** [comment]
My guess is that it probably should be considered bug as, by default, results in decimals lost, so losing data

**Comment by torkelo** [comment]
they are there in the csv download

**Comment by ukkathva** [comment]
This is a critical issue , When the latitude/ longitude values are exported , Hope this gets resolved soon  ,

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/27306 in v7.2 

The inspect table & csv now uses the formatting options by default, you can disable that to get raw data in the table and csv

**Comment by Hvitnov** [comment]
I think I am still seing this issue in grafana 7.5.7 when using inspect > data.
The datasource is postgresql.

The Decimal setting for both axes as well as legend is at 3.
I cant see any options under the field or overrides tabs to set decimal points.
The data is displayed with three decimal points in the graph and legend:
![billede](https://user-images.githubusercontent.com/7369842/119484032-e95d2e80-bd55-11eb-8205-b8d666d097b3.png)

When using inspect -> data the column only displays one decimal by default (with Data options -> Formatted Data enabled). This is also the case in the downloaded .csv file.
![billede](https://user-images.githubusercontent.com/7369842/119484130-fed25880-bd55-11eb-9d1d-3d2d90e9988a.png)


With Data options -> Formatted Data disabled the three decimal places are displayed (probably because the raw data has 3 decimal points), and the formatting on the time column is of and the raw unix epoch is shown.
![billede](https://user-images.githubusercontent.com/7369842/119484175-0a258400-bd56-11eb-823f-3d70cc53acab.png)


Am I missing some formatting option for decimal points related to the time series?

**Comment by Newsheriff** [comment]
The issue seems to be still present at Grafana 8.0.3
Here is the data from a dashboard
![image](https://user-images.githubusercontent.com/40631175/140538696-5cb4e47d-933e-4069-ad43-75c9df0bffa3.png)
And here is it in Inspect Data:
![image](https://user-images.githubusercontent.com/40631175/140538812-ff91b16e-459b-4109-9f83-ac0a04c2604f.png)
