### ISSUE TITLE
Flux QL - not all data points are shown

### ISSUE THREAD

**Issue by spacejay01** [grafana/grafana#26484]
Hello,

I'm using Influxdb 1.8.1 and Grafana 7.1.0 and try to use the influxdb with the new Flux QL. Therefore I'm created a new datasource and have created a query to get the same graph I already created with the normal Influx QL, what worked out fine witout any problems.

The problem is, when I now change the time range to e.g. last 24 hours, the graph based on Flux QL does not show all data points. 

![image](https://user-images.githubusercontent.com/68586421/88051030-409fda80-cb58-11ea-9be8-eea9febf4631.png)
(1st query is wiht Influx QL, 2nd with Flux QL)

My assumption is that this behavoiur is related to the "Max Data Points" value, which is empty, but in gray the value of the possible points are mentioned.

![image](https://user-images.githubusercontent.com/68586421/88051106-5f05d600-cb58-11ea-9a9b-53466f4a04f4.png)

When I check the result with the Query Instpector, I get more than the mentioned 1810 values. When I change now the "Max Data Points" value to the value I get with the Query Inspector I get all data points. 

![image](https://user-images.githubusercontent.com/68586421/88051167-7a70e100-cb58-11ea-85af-e17066eddf6d.png)

![image](https://user-images.githubusercontent.com/68586421/88051310-adb37000-cb58-11ea-8cc1-426840ccc8e7.png)

**Environment**:
- Grafana version: 7.1.0 
- Data source type & version: InfluxDB 1.8.1 
- OS Grafana is installed on: Raspbian GNU/Linux 9 (stretch)
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: Flux QL
- Others:

**Comment by ivanahuckova** [comment]
@ryantxu this is another recent issue related to Flux and max data points. Could it be related to  https://github.com/grafana/grafana/issues/26431?

**Comment by coussej** [comment]
If you manually set the Max data points to a higher number, you will get the complete result.

**Comment by lephisto** [comment]
I can report the same Issue with Grafana 7.3.1 in conjunction with InfluxDB 2.0.0 OSS (f46a3bd).

MD is lower then the amount of Data my Flux queries produce.

This in fact is a showstopper and keeps me pinned on Grafana 6 for some IIoT Projects.

**Comment by lephisto** [comment]
Might this be related? https://github.com/grafana/influxdb-flux-datasource/blob/87b7c464277666a00b5284b91c4e752523bdd1a2/pkg/influx/executor.go#L25

**Comment by ryantxu** [comment]
The current implementation will stop returning results after 1.5*max data points.

What is the expected behavior?  Perhaps we should add a warning to the response that says "write a query with interval, or increase max data points)?

**Comment by FortDigital** [comment]
Does that line up with how Max Data points is used in other data sources? (I genuinely don't know) My understanding of Max Data points is that its used to calculate the Interval ($__interval) that should be used to return the number of datapoints specified, If you choose not to use the Interval Variable shouldn't it just return the entire dataset without any early truncation? IE remove the direct connection between Max Data points and expected response?

**Comment by ryantxu** [comment]
> If you choose not to use the Interval Variable shouldn't it just return the entire dataset without any early truncation?

It is a good question.  The real problem with ignoring it is how easy it is to write queries that return LOTS of data (enough to crash the server and browser).  Influx has a model where they keep writing data until you stop reading -- that is great if it is intentional, but not so great if you are just exploring the dataset. 

> Does that line up with how Max Data points is used in other data sources? (I genuinely don't know)
The behavior varies widely :frowning_face: but yes, many datasources will clip data beyond maxDataPoints.  We currently stop after %150, but maybe could should make that larger?  %250?

**Comment by FortDigital** [comment]
I must confess I don't personally suffer from this issue, Its very rare I would write a query without an Interval, as generally I don't need to preserve super-high levels of precision, but I can see why people might want to be able to.

I'm not too sure what the 'Right' solution would be here, Having the Cut off at 1.5xMax Data Points is potentially Confusing i guess since having a MDP of 600 Actually Means 900, So an argument could be made that you should really stop returning data after 600 and honour the MDP Value. For this particular use case though it just makes things worse. 

Being able to set MDP to 'Infinite' for high precision use cases might be an option? But probably comes with a hefty disclaimer around system stability, Especially if you don't have Query timeouts configured for long running queries....

**Comment by FortDigital** [comment]
does this interaction differ between the flux and influxql query types? the origional issue suggests that influxql will return all datapoints and only flux truncates, should the behaviours be different?

**Comment by nsteinmetz** [comment]
Hi there,

To check if it's linked with https://github.com/influxdata/influxdb/issues/20162

Do you see such a line in influxdb logs when query on grafana side is executed ?

```
Nov 24 08:38:44 crnt-d10-monitoring influxd[4578]: ts=2020-11-24T07:38:44.702783Z lvl=info msg="Error writing response to client" log_id=0Qav6bVG000 handler=flux error="csv encoder error: write tcp 127.0.0.1:8086->127.0.0.1:59186: write: broken pipe"
```

**Comment by nsteinmetz** [comment]
If I change Max Data Points from 2100 to 10000, it works as expected and the error is no longer present.

**Comment by R-Studio** [comment]
I have the same issue and I think this is a Major Bug!
@ryantxu is there any news on this?

Informations about my environment:
Grafana: v7.3.5
InfluxDB: v2.0.2
QL: Flux

**Comment by lephisto** [comment]
This is still an issue. Big Showstopper for going on Grafana 7x in some cases where I early adopted Fluxlang.

**Comment by lephisto** [comment]
Still an issue in 7.3.7

**Comment by R-Studio** [comment]
@spacejay01: **It looks like this is resolved in Grafana 7.4.1!**
Can anyone confirm this?

**Comment by nsteinmetz** [comment]
@R-Studio 

Tested very quickly in a few charts: seems indeeds it's fixed - just remove my previous 8400 or 10.000 forced values and I see no differences in charts.

**Comment by nsteinmetz** [comment]
I may have spoken too fast - issue is still there :-(

But now you have a warning and a message: 

```
returns too many points for a series: <number>
```

**Comment by davkal** [comment]
@nsteinmetz could you please help us debug this some more?

- do you run 7.4.1?
- What's the screen width?
- How many datapoints are you requesting? (time range divided by data resolution)
- Are you using `aggregateWindow()`? What value for `v.windowPeriod` is used in the request (see query inspector)?
- What's the maxDataPoints that was calculated?

**Comment by nsteinmetz** [comment]
@davkal of course I can.

* Yes, I run on 7.4.1
* 25" with a 2560x1440 resolution
* Last 6 hours / what do you mean by data resolution ?
* For this case, no query is:

```
from(bucket: "comptaonline")
  |> range(start: 2021-02-15T08:41:51Z, stop: 2021-02-15T14:41:51Z)
  |> filter(fn: (r) => r["_measurement"] == "mysql")
  |> filter(fn: (r) => r["_field"] == "connections" or r["_field"] == "queries" or r["_field"] == "questions")
  |> filter(fn: (r) => r["host"] == "cod10r1")
  |> derivative(unit: 30s, nonNegative: false)
  |> yield(name: "derivative")
```
Error message is:

> returned too many points in a series: 1598

Default value is 2110 for maxDataPoints for this panel.

What is weird is that it partially works: 
* when I load the dashboard: it fails with message above
* if I go in the panel, edit it (do nothing) and go back, it's complete
* or if I view the panel (only this panel) and click on refresh button from Grafana, it will work then

When it works I can see, it has 2159 rows

**Comment by philomory** [comment]
@nsteinmetz  Data resolution is how many data points your store has per unit time. That is, if you are requesting 1 hour's worth of data, you'll get very different results if you've got 1 data point per minute vs 1 data point per millisecond.

**Comment by nsteinmetz** [comment]
@philomory I understand the concept of data resolution - I was just looking around where to get this value from grafana.

> Also, the default maxDataPoints depends on the width of the graph, so it actually changes when you open it in edit view, since that makes the graph take up (basically) the whole width of the screen. You can see the actual "max data points" if you switch the view in the editor from "fill" mode to "exact" mode, and then click the little "refresh" button.

Thanks, didn't know about it. In this case, MaxDataPoints is 825 and now the message is:

```
returned too many points in a series: 1650
```

> Ultimately unless they radically change the way the Max Data Points is handled for the Flux input, you're pretty much obligated to use aggregateWindow in every Flux query to explicitly pass the desired data resolution, just like you're obligated to use range to explicitly pass the time range

I copy/pasted queries from Influx 2.0.x editor to Grafana - so I wonder why would `aggregateWindow` be required in a Grafana context but not in InfluxDB one. In some of my queries, I can see the use of this function when it seems required. But adding it to all grafana panels may not make sense :thinking: 

Is it stated/explained somewhere on Grafana's side about this requirement (if confirmed) ?

**Comment by philomory** [comment]
> @philomory I understand the concept of data resolution - I was just looking around where to get this value from grafana.
I don't think Grafana displays this information anywhere; it will vary with your source data. There's not really a good flux function to calculate it either, although you _can_ easily get the final value he was asking for ("how many data points are you requesting?") by adding `|> count()` to the end of your existing query (and proably switching to a Stat or Table panel to make the answer easier to read).

> I copy/pasted queries from Influx 2.0.x editor to Grafana - so I wonder why would `aggregateWindow` be required in a Grafana context but not in InfluxDB one. In some of my queries, I can see the use of this function when it seems required. But adding it to all grafana panels may not make sense 🤔
The reason it's not required in the Influx 2.0 editor is that the Influx 2.0 editor doesn't enforce any maximum number of data points returned. In Grafana, if you run a query that returns a billion datapoints, it'll cut you off at whatever `maxDataPoints` evaluates to; in the InfluxDB 2.0 UI it'll pretty much just try to get all the datapoints, and if that makes the request time out or your browser run out of RAM then the request times out or your browser runs out of RAM (actually InfluxDB may also impose some cap on the number of records a single query can return, but if there is one I can't find it documented offhand).
 
> Is it stated/explained somewhere on Grafana's side about this requirement (if confirmed) ?

I doubt it; the Flux support in Grafana is fairly new, explicitly "beta", occasionally buggy, and very lightly documented as yet.

**Comment by nsteinmetz** [comment]
> I doubt it; the Flux support in Grafana is fairly new, explicitly "beta", occasionally buggy, and very lightly documented as yet.

hmm from my point of view, flux support is out of beta from grafana 7.1 - https://grafana.com/docs/grafana/latest/datasources/influxdb/#flux-support

**Comment by philomory** [comment]
> hmm from my point of view, flux support is out of beta from grafana 7.1 - https://grafana.com/docs/grafana/latest/datasources/influxdb/#flux-support

Right you are! Well, personally, from my perspective that was a mistake on Grafana's part; it's still _pretty_ buggy.

**Comment by davkal** [comment]
To shed some light onto this: The fix #31025 raises the number of series and also makes it configurable. That same fix also now surfaces the error message that per-series datapoints were reached. The "issue" is hence not fixed, but at least Grafana is now telling you what is happening. I fully realize that an unfounded hard limit is confusing and interrupting. We're working on a new fix to raise the limit considerably (we have to have some limit to protect Grafana itself), but hopefully it will not be triggered in practice (and if it's triggered, it will tell you to use `aggregateWindow()` to reduce the number of datapoints).

**Comment by spacejay01** [comment]
I can understand the need to protect grafana, but the question for me is, why all datapoints are shown in grafana when I do the request with influxQL, but not with FluxQL. The datasource is the same.

________________________________
Von: David <notifications@github.com>
Gesendet: Wednesday, February 17, 2021 2:01:34 PM
An: grafana/grafana <grafana@noreply.github.com>
Cc: spacejay01 <spacejay@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [grafana/grafana] Flux QL - not all data points are shown (#26484)


To shed some light onto this: The fix #31025<https://github.com/grafana/grafana/pull/31025> raises the number of series and also makes it configurable. That same fix also now surfaces the error message that per-series datapoints were reached. The "issue" is hence not fixed, but at least Grafana is now telling you what is happening. I fully realize that an unfounded hard limit is confusing and interrupting. We're working on a new fix to raise the limit considerably (we have to have some limit to protect Grafana itself), but hopefully it will not be triggered in practice (and if it's triggered, it will tell you to use aggregateWindow() to reduce the number of datapoints ).

**Comment by gabor** [comment]
@spacejay01 the reason is technical, the InfluxQL queries and the FluxQL queries are handled by different code-paths, so there are differences how exactly the limits are applied. in general, the max-data-points value is used together with the current time-selection to feed the aggregate-functions used in the queries, the fluxql/influxql handling is consistent in that regard. i recommend using an aggregate-function, when possible.

i merged a change that should improve the situation, it increases the "tolerance" -factor (we now allow 10times more points than in the max-data-points setting), so you should meet the error-message less often, and the error-message itself was improved to give more info about what happened.

**Comment by holmesb** [comment]
This is still happening in grafana v7.5.1.  In my Flux panels, I have manually set Max Data Points to a large, hard-coded value that accommodates the longest time series that can be selected.  Be good if Grafana could figure this out itself.  Without this, we get the 
![image](https://user-images.githubusercontent.com/5072156/113475868-b2fae580-946f-11eb-86f1-edfddd677a14.png)
"returned too many points in a series: ###" error.

**Comment by gabor** [comment]
@holmesb could you use `aggregateWindow` to make sure the number is always suitable?

**Comment by holmesb** [comment]
Yes adding line:
```|> aggregateWindow(every: v.windowPeriod, fn: mean)```
fixed, thanks @gabor
