### ISSUE TITLE
Updating variable value using LocationSrv.update takes considerable time and produces error

### ISSUE THREAD

**Issue by Jim-Rouse** [grafana/grafana#26558]
**What happened**:
Using the following to update a dashboard variable:
`getLocationSrv().update({query: {'var-enterpriseservice_id':serviceId.toString()}});`

After the code is ran it takes about 10-15 seconds to return, the data is updated but  the following error is produced: 
`app.5e3a92e1d96185a124d4.js:2 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at n (actions.ts:23)
    at app.5e3a92e1d96185a124d4.js:2
 
9app.5e3a92e1d96185a124d4.js:2 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at n (actions.ts:253)
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:271)`

**What you expected to happen**:
Expect the data to return with in 1-3 seconds, and no error.  (similar timing to what occurs if the user changes the variable on the screen)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I believe that updating variables using the locationserver was to be fixed in this issue: https://github.com/grafana/grafana/pull/25192

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: 7.1.0
- OS Grafana is installed on: Docker container
- User OS & Browser: Chrome current version
- Grafana plugins: (custom plugin)

**Comment by torkelo** [comment]
Is the variable a multi value variable (in the options), if that is the case it should be an array value

**Comment by Jim-Rouse** [comment]
Variable type is "Text box"

**Comment by marcusolsson** [comment]
Confirmed on 

- Grafana 7.1.5
- @grafana/runtime 7.1.5

1. Create a new variable of type **Text Box**.
1. Add the following to a panel plugin:

   ```tsx
   <button
     onClick={() => {
       getLocationSrv().update({
         query: {
           'var-instance': 'foo',
         },
         replace: true,
         partial: true,
       });
     }}
   >
     Click me
   </button>
   ```

1. Grafana hangs.
1. On page refresh, I get:

   ```
   Uncaught (in promise) InternalError: too much recursion
   ```

**Comment by dprokop** [comment]
@marcusolsson did a quick repro session. My observation:

1. This is indeed a problem in 7.1.5 version - I can replicate it using 7.1.5 packages & Grafana
2. Can't reproduce on master - can you please confirm? Will try to dig into what change might have fixed that issue sine 7.1.5

**Comment by marcusolsson** [comment]
Indeed it seems like it's been fixed in master 👍

**Comment by polovmak** [comment]
@marcusolsson @dprokop I have installed 7.1.5 version for grafana and @grafana/runtime but the error is still there. Any suggestions ?

**Comment by hugohaggmark** [comment]
> @marcusolsson @dprokop @hugohaggmark I have installed 7.1.5 version for grafana and @grafana/runtime but the error is still there. Any suggestions ?

I think the fix was in `master` and not in 7.1.5 can you check that is correct @polovmak

**Comment by polovmak** [comment]
@hugohaggmark Yes, thank you, it is fixed in master!

**Comment by hugohaggmark** [comment]
Great @polovmak then we just need to figure out what that is :)
