### ISSUE TITLE
Alias patterns for multiple metrics on the same graph erroneous

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#2687]
The `$tag_<alias>` feature works as expected when we have only one metric query per graph. However, if we add a second metric query with its own alias, then only the first metric is correctly expanded.

We are using openTSDB, so this might be a bug in #1344.
OpenTSDB 2.1
Grafana 2.0

Here are some illustrative screenshots.
First with no aliases:
![fpbyteshandled-noalias](https://cloud.githubusercontent.com/assets/8266640/9714479/85da728e-5558-11e5-84c5-8ea319d2e61f.png)
Second, with two aliases, the tagk 'file' first. In this case '$tag_input' alias of the second metric is ignored and the first metric '$tag_file' is applied to both metrics.
![fpbyteshandled-tagfilefirst](https://cloud.githubusercontent.com/assets/8266640/9714482/8a1942bc-5558-11e5-83c5-e1e87f3a5797.png)
Second, with two aliases, the tagk 'input' first. In this case '$tag_file' alias of the second metric is ignored and the first metric '$tag_input' is applied to both metrics.
![fpbyteshandled-taginputfirst](https://cloud.githubusercontent.com/assets/8266640/9714483/8c59b502-5558-11e5-9f88-b9ff59bcf8a6.png)

**Comment by torkelo** [comment]
This is due to an OpenTSDB query limitation (no way to match query to returned series). 

This is fixed in next version of OpenTSDB (2.2), where they have a queryId field so you can know which series came from which query. 

https://github.com/grafana/grafana/issues/1876

**Comment by IzakMarais** [comment]
Excellent, thanks for the feedback.

**Comment by githubu1** [comment]
We just upgraded to OpenTSDB (2.2) from 2.1.3 
Our graphana is 2.6.0 

The issues mentioned in the ticket is still exists.

**Comment by utkarshcmu** [comment]
@githubu1 Check this issue https://github.com/grafana/grafana/issues/1876

**Comment by githubu1** [comment]
We dont have any pipe separator , for the issue #1876 I could not able to conclude the issue is resolved or going to be in next version.

But the issue still exists in OpenTSDB(2.2) 

The query is very simple 

Q1 Average of Metric on individual hosts
Aggregator Avg & tags datacenter=DC1 and host_name=* Alias is $tag_host_name

Q2 Average of Metric for all the Hosts 
Aggregator Avg & tags datacenter=DC1 Alias is Average 

The results are Ok for Q1 but for Query 2 the Alias name is showing as $tag_host_name

**Comment by torkelo** [comment]
you can only use $tag_host_name in the alias field if you group by the tag

**Comment by githubu1** [comment]
For the first query we are using $tag_host_name for alias there is no issues ,
But the issue is for the second Query which just gets an average for the given tag.

If i use individual query for each host then there is no issue ( for example i have 12 hosts and used 12 queries and the 13th query is average )
![graphan_tag_issues](https://cloud.githubusercontent.com/assets/16827421/13335309/5220af3c-dbc5-11e5-9a92-a77fb8af47e1.png)

**Comment by githubu1** [comment]
In the above graph the issue is on the Query B where we are not using any tag , Instead of displaying Average it is displaying the Query A's Alias

**Comment by torkelo** [comment]
Ah yes,  this is an OpenTSDB issue, they need to return a query id do Grafana can match what series returned came from which query

**Comment by githubu1** [comment]
Thanks , Do you have a ticket no to track this issue

**Comment by torkelo** [comment]
there is a search feature on github :) just search OpenTSDB alias match

**Comment by ericdwhite** [comment]
https://github.com/OpenTSDB/opentsdb/issues/438
