### ISSUE TITLE
After Clicked Show context, context panel is too small .

### ISSUE THREAD

**Issue by github-yxb** [grafana/grafana#27262]
**What you expected to happen**:
When i clicked show context, i can't view newest log in context panel if log is first or last record, just can view old log.

![image](https://user-images.githubusercontent.com/7059300/91546198-a734c700-e954-11ea-947d-ef508224a9df.png)

**Environment**:
- Grafana version: Grafana v7.1.5 (9893b8c53d)
- Data source type & version: 1.6.1
- OS Grafana is installed on: Centos5.6 x86_64
- User OS & Browser: MacOs 10.15.6 Chrome 84.0.4147.135
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Not sure I understand, can you describe this a bit more? the screenshot is not clear

**Comment by github-yxb** [comment]
![image](https://user-images.githubusercontent.com/7059300/91627042-e01d7c00-e9e6-11ea-9de4-f296846f5cbc.png)
**No problem like this.**

![image](https://user-images.githubusercontent.com/7059300/91627087-59b56a00-e9e7-11ea-86f7-d3a337a68f76.png)
In second image, i can't "Load 10 more".

Sorry about my english, I tried my best.

**Comment by torkelo** [comment]
Are you sure there are entries above the last result?

**Comment by aocenas** [comment]
I think the issue is a problematic overflow behavior, where because of the nesting and scrolling containers the context windows cannot overflow the main logs window which on edges creates this behavior. I think this also depends on the line wrapping (not sure if wrapping off or on produces this behavior).

This should be a duplicate in that case cause it is know thing and we are working on redesign of the context but have to find the issue.

**Comment by github-yxb** [comment]
> Are you sure there are entries above the last result?

Yes, I have confirmed many times.

![image](https://user-images.githubusercontent.com/7059300/91826744-947e0300-ec70-11ea-92eb-9256846511e6.png)
In another case, the same problem  when there is only one entry.

**Comment by aocenas** [comment]
can't find the duplicate query so keeping this in the Observability backlog

**Comment by ivanahuckova** [comment]
In the past, we were able to turn off logs wrapping and users were able to see the context, however in 8 we have moved to Custom scrollbar and now this hacky solution won't work either. I am changing priority to important soon as this feature is currently not usable for first ~10 lines of logs and last ~10 lines of logs.

**Comment by ivanahuckova** [comment]
This/Similar issue was fixed for the Portal, but we don't use portal for the context. Maybe we could and this wouldn't be an issue anymore.

**Comment by zswanson** [comment]
I can confirm this still occurs in 8.x. It seems to mostly show up when the number of log lines returned is fairly small or you're trying to get context of an item at the very top or bottom of the scroll pane.

**Comment by ivanahuckova** [comment]
@zswanson I am currently working on this bug. I hope to have this fixed in 8.1 stable. 🤞
