### ISSUE TITLE
Query parameter drop-downs not working for custom cloudwatch metrics

### ISSUE THREAD

**Issue by chrs-myrs** [grafana/grafana#28510]
**What happened**:
Every time I try to create a dashboard with a new custom metric I run into several problems adding metrics and dimensions.  I normally have to enter the namespace, metric name and dimension keys manually.

Cloudwatch often does not have the dimension keys or values.  It also does not show some of the dimensions that are clearly available in the cloudwatch console.

Also when turning on exact match the data often does not appear, despite matching the parameters.  This would work with AWS metrics fine, and some other custom metrics.

Also turning on exact match often creates a 400 error and shows no data (not sure if this is another bug or related)

See attached GIF of the process...

**What you expected to happen**:
1. Metric Names to show
2. Dimension Names to show
3. Exact match to show matching series

**How to reproduce it (as minimally and precisely as possible)**:
Not sure, but think you need a recently created metric.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.2.1
- Data source type & version: CloudWatch
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: Ubuntu Firefox
- Grafana plugins: Standard only
- Others:

**Comment by chrs-myrs** [comment]
Failed query `{
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1602864805161",
      "to": "1603469605161",
      "queries": [
        {
          "intervalMs": 600000,
          "maxDataPoints": 1275,
          "datasourceId": 12,
          "type": "timeSeriesQuery",
          "namespace": "Test-API Cache by Day",
          "metricName": "RequestCount",
          "expression": "",
          "dimensions": {
            "EndpointCategoryLevel1": [
              "CLM"
            ],
            "EndpointCategoryLevel2": [
              "*"
            ]
          },
          "region": "eu-west-1",
          "id": "",
          "alias": "",
          "statistics": [
            "Sum"
          ],
          "period": "86400",
          "refId": "A",
          "matchExact": true,
          "datasource": "Prod"
        }
      ]
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "ValidationError: Invalid SEARCH parameter: {Test-API Cache by Day,\"EndpointCategoryLevel1\",\"EndpointCategoryLevel2\"} MetricName=\"RequestCount\" \"EndpointCategoryLevel1\"=\"CLM\"\n\tstatus code: 400, request id: c1b68370-ff7e-4797-862b-b8fd8cdba44d",
        "refId": "A",
        "series": null,
        "tables": null,
        "dataframes": null
      }
    },
    "message": "ValidationError: Invalid SEARCH parameter: {Test-API Cache by Day,\"EndpointCategoryLevel1\",\"EndpointCategoryLevel2\"} MetricName=\"RequestCount\" \"EndpointCategoryLevel1\"=\"CLM\"\n\tstatus code: 400, request id: c1b68370-ff7e-4797-862b-b8fd8cdba44d"
  }
}`

**Comment by chrs-myrs** [comment]
![Peek 2020-10-23 15-35](https://user-images.githubusercontent.com/2414664/97028101-915a1180-1553-11eb-98ff-18308937942f.GIF)

**Comment by wbrowne** [comment]
Hey @chrs-myrs, thanks for raising this issue. This should be fixed with Grafana 7.2.2 (see relevant PR for the fix: https://github.com/grafana/grafana/pull/28391)

There was also an original issue for this bug [here](https://github.com/grafana/grafana/issues/28075) so will close this duplicate.

**Comment by chrs-myrs** [comment]
@wbrowne This is still not working for me, using 7.3.1, I'm going to open a new issue

**Comment by chrs-myrs** [comment]
Sorry it is working, getting mixed up between problems.  Have opened https://github.com/grafana/grafana/issues/29109 instead
