### ISSUE TITLE
Error: e.replace is not a function - after creating data link in field override

### ISSUE THREAD

**Issue by Tommie15** [grafana/grafana#28714]
**What happened**: after creating a link an error message appears: e.replace is not a function

**What you expected to happen**: creating a link

**How to reproduce it (as minimally and precisely as possible)**: please see the executed steps in the gif

**Anything else we need to know?**: I'm using Elasticsearch as source and a complete fresh install. I'm using an ad-hoc filter variable

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Elasticsearch 7.9.3
- OS Grafana is installed on: Windows 10
- User OS & Browser: Vivaldi | 3.1.1929.45 (Stable channel) (64-bits)
-- | --

- Grafana plugins:
- Others:

![GrafanaError](https://user-images.githubusercontent.com/73750017/97783438-14084f80-1b98-11eb-9b1e-eb64947e5bae.gif)

**Comment by marefr** [comment]
Not able to reproduce. Can you please use Chrome Developer Tools or similar and check the console when your error occurs and include the details of it. Can you please include the query inspector response?

**Comment by Tommie15** [comment]
I hope the attached screenshots are what you're looking for.
If you need any other information, please ask.

![GR_Chrome](https://user-images.githubusercontent.com/73750017/97901220-2a4f1080-1d3c-11eb-9bea-f5a578e7e8e2.jpg)
![GR_QueryInspector](https://user-images.githubusercontent.com/73750017/97901225-2cb16a80-1d3c-11eb-9b97-03abcb16a077.jpg)

**Comment by marefr** [comment]
Thanks. Based on the error message seems like it maybe fails to parse the URL you're using. Have you tried manually inputting the URL and not paste it (in case there's some extra character included when pasting)?

**Comment by Tommie15** [comment]
![ES_Error](https://user-images.githubusercontent.com/73750017/97911534-b1f04b80-1d4b-11eb-80da-039882fdc658.gif)

When I try to copy the URL of the 'destination' page another error occurs.

**Comment by marefr** [comment]
Not able to reproduce the bug. I noticed you're using the Vivaldi browser. Can you please try if you can reproduce it using a different browser? Thanks

**Comment by Tommie15** [comment]
My last post and recorded session was while using Chrome.
Is there anything else I can do to help you?

**Comment by marefr** [comment]
Will ask another team to help out investigating this.

**Comment by mckn** [comment]
> My last post and recorded session was while using Chrome.
> Is there anything else I can do to help you?

Thanks @Tommie15 for reporting this. Can you verify that you do not have a cached version of the js-bundle or are running an older version of Grafana? 

This issue should have been resolved in the following PR: https://github.com/grafana/grafana/pull/28226

**Comment by mckn** [comment]
I will close this issue for now with the comment that we can't reproduce it and it should be fixed in the following PR: #28226.

**Comment by KeithTt** [comment]
Same problem here.

Grafana v6.4.3 (3a2bfb7)

Hi @mckn , how to resolve this problem in old version?

**Comment by marcosRandulfe** [comment]
It still happend it´s something in the panel Node Exporter Full with another panels there aren´t problem

**Comment by mckn** [comment]
Lets have another look at it

**Comment by mckn** [comment]
> It still happend it´s something in the panel Node Exporter Full with another panels there aren´t problem

What version of Grafana are you currently running?

**Comment by marcosRandulfe** [comment]
Latest version i just install it last week

**Comment by mckn** [comment]
> Latest version i just install it last week

OK ok, super! Can you provide some data and panel json so we can try to reproduce the error on our side?
