### ISSUE TITLE
DashboardQueryEditor of PanelEditor not rendering "Link to Graph in Prometheus" variable when datasource "Prometheus" template variable used to select actual datasource

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#29768]
**What happened**:
Panel editor has button for launching Prometheus with specific query parameters. Feature is very useful for debugging purpose, often it is easier to fine tune the query in Prometheus or modify to query when problem is not shown (No link to launch built in explorer either).

When datasource is used to select the actual datasource the DashboardQueryEditor of PanelEditor prometheus link expanding is not working, empty link is returned which href convert to Grafana own address like localhost:13000 when running in local machine.

Often the same dashboard needs to work with multiple different environment like development, test, production where each environment has own TSDB collector like Prometheus.

The standard solution is to define template variable type datasource, and then select the actual datasource per environment.

If in Panel editor direct datasource is selected and dashboard saved then rendering works correctly when dashboard is reloaded.

Inspecting Panel JSON show that datasource is promsource 

 "datasource": "$promsource",

Seems that value is not resolved when panel is opened or when datasource is changed. Thus changing datasource to fixed datasource will not fix the link until even dashboard is closed and opened. Link only works if dashboard is saved with direct datasource config and dashboard is reloaded.

![image](https://user-images.githubusercontent.com/19704268/101889558-34202b00-3ba8-11eb-8972-933e3ad1e98d.png)

![image](https://user-images.githubusercontent.com/19704268/101895937-e1973c80-3bb0-11eb-866b-e7363980e53a.png)

**What you expected to happen**:
Link should work like it did in early Grafana 6.x.
Grafana 6.4.1 already had some regression with link, but toggling instance query on/off resolved the issue. In 7.x the link has never worked.

**How to reproduce it (as minimally and precisely as possible)**:
Just create any dashboard where template variable promsource is used.
Attached example dash 
[promlinknotworking.txt](https://github.com/grafana/grafana/files/5678862/promlinknotworking.txt)
board.

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows 10 and Linix
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
think this is fixed by https://github.com/grafana/grafana/pull/29543

**Comment by jtorkkel** [comment]
I tested 7.4.0.8542pre but unfortunately issue was not fixed.
