### ISSUE TITLE
Support microsecond time axis ticks / steps in graph panel

### ISSUE THREAD

**Issue by pfennema** [grafana/grafana#3035]
We are currently investigating Grafana together with InfluxDB. As we are measuring network traffic which have nanoseconds resolution in the timestamp we need to zoom in on the individual measurement points on nanosecond level. What we now see is that the timescale on the x-axis only supplies second resolution while we need to have the ability to zoom in on at least a scale of 1 microsecond. Currently InfluxDB supports timestamps with nanosecond resolution, hence we need this as well in Grafana. Any thoughts how to get the data for the individual measurements?

Thanks, Paul

**Comment by torkelo** [comment]
Grafana support microsecond resolution metrics when used with InfluxDB. Nanosecond resolution is not supported

**Comment by pfennema** [comment]
I probably did not write the issue properly, what I mean is that the display resolution is on 1 second resolution and we want to zoom in on the individual messages which have a timestamp resolution of nanoseconds. If we can see the individual messages (max 1000 in one microsecond, in reality about 1-5) that would really be quite helpful. So effectively if the timeline has microsecond resolution it would be ok. Can't find that how to achieve this however.

**Comment by torkelo** [comment]
the timeline will n

**Comment by pfennema** [comment]
Hi Torkel, do you know whether this issue will be picked up? I will check in the code what I can do about it but will take quite a while I'm afraid.

**Comment by laurentlap** [comment]
Torkelo, Pfennema,

I'm also interested by this feature. Microsecond granularity would be perfect. Torkelo, any suggestions of workaround / alternative solutions in the meantime ?

**Comment by torkelo** [comment]
@laurentlap not that I know :(

**Comment by timgriffiths** [comment]
+1

**Comment by vitorboschi** [comment]
+1

**Comment by discoduck2x** [comment]
+1

**Comment by Stuermer** [comment]
+1

**Comment by PaulKuiper** [comment]
+1

**Comment by joaogb** [comment]
+1

**Comment by nmosafi** [comment]
+1

**Comment by glucose1016** [comment]
+1

**Comment by Sykkro** [comment]
+1

**Comment by filipedgb** [comment]
+1

**Comment by kalifed** [comment]
+1

**Comment by ruiner3141** [comment]
+1

**Comment by chilambaba** [comment]
+1

**Comment by lkcole** [comment]
+1

**Comment by nunocmalmeida** [comment]
+1

**Comment by qed-** [comment]
+1

**Comment by joaogb** [comment]
@torkelo Any news on when this issue will be picked up?

**Comment by a-pritzel** [comment]
+1

**Comment by brachiel** [comment]
+1

**Comment by tmramalho** [comment]
+1

**Comment by m-lal** [comment]
+1

**Comment by AdamKielczewski** [comment]
+1

**Comment by aschumilin** [comment]
+1 
In the mean time, has anybody explored any alternatives for similar task as OP described? Chronograph is a candidate but it is far from ready for productive use.

**Comment by alacx** [comment]
+1

**Comment by sergiuionescu** [comment]
+1

**Comment by poikilotherm** [comment]
Things are moving at Influx, see https://github.com/influxdata/chronograf/pull/2127 and https://github.com/influxdata/chronograf/issues/1449.

Maybe that can be a source of inspiration?

**Comment by multiple1** [comment]
@torkelo you wrote that Grafana supports **micro**second resolution with InfluxDB. Is this a typo? I could only get **milli**second resolution working.

>Grafana support microsecond resolution metrics when used with InfluxDB. Nanosecond resolution is not supported

**Comment by torkelo** [comment]
yes, I meant millisecond

**Comment by hidai** [comment]
+1

**Comment by digrich** [comment]
+1

**Comment by kaspergrubbe** [comment]
+1

**Comment by OTL** [comment]
+1

**Comment by mhfrantz** [comment]
Chronograf uses its own fork of Dygraphs for rendering its graphs. Here's the commit where millisecond resolution was added: https://github.com/influxdata/dygraphs/commit/69f7d2a0a5d044b21a45c8e03d91bb5b1e52d6ff

The Dygraphs library appears to be limited by JavaScript's `Date` resolution, which is milliseconds. Thus, supporting microseconds is likely to be a bigger undertaking than it was for milliseconds.

**Comment by alex00971** [comment]
+1

**Comment by Chawoot** [comment]
+1

**Comment by patricksferraz** [comment]
+1

**Comment by comcomservices** [comment]
nanosecond (ns) or microsecond (us) time scales would be extremely useful. An example of this is for power monitoring where we record oscillograms of AC power quality.   

@mhfrantz https://www.npmjs.com/package/nano-date is almost a drop-in replacement for the built-in Date method which is limited to millisecond resolution. From there it would take some re-writing of the dygraph library and then a small fix to grafana.

![graphing1](https://user-images.githubusercontent.com/13089993/67244189-0ad59600-f40e-11e9-8ded-53a2be509cf6.png)

**Comment by comcomservices** [comment]
$1,000.00 if anyone wants to update grafana to support ns timescale resolution.  Our use case requires importing graph data from influxdb and displaying it. uS would be considered too but nS prefered

Contact me if interested, work must be professional with pull requests for all changes needed

**Comment by aocenas** [comment]
@torkelo As I understand this is more of an issue with the graph support so assigning it to platform backlog.

**Comment by torkelo** [comment]
yes, this is a platform issue! actually worked on a branch poc for this years ago to add this to flot but never completed it

**Comment by leeoniya** [comment]
i think the route here would be to dynamically switch away from a calendar-aware x that relies on javascript's Date and to a treat x as numeric with a predefined starting position.

alternatively, use 2 charts that switch from a calendar-aware one to a numeric one at high zoom levels. i did a prototype/discussion of this a while ago in https://github.com/leeoniya/uPlot/issues/111, which would likely work for Flot as well.

**Comment by bijwaard** [comment]
Dear all,
Micro/nanosecond resolution would be essential for digital fault recording of electric signals, i.e. where based on a trigger condition a signal trace is written to the database, and would be visualized in grafana graph panel. When I currently do this in influxdb-python 5.3.0, I can only zoom to 10ms resolution, which is not enough to inspect the fault in detail. And furthermore, there still seems to be conversion problems in influxdb-python, which would hopefully go away when [directly using the epoch timestamps ](https://github.com/influxdata/influxdb-python/issues/880)
I.e. the trace with gnuplot from CSV file with seconds on x-axis since last hour: 
![image](https://user-images.githubusercontent.com/6523124/111636914-37efc900-87f9-11eb-828f-bd6bf7dfaf47.png)

The trace in grafana graph panel from influxdb datasource:
![image](https://user-images.githubusercontent.com/6523124/111637065-5eadff80-87f9-11eb-9c97-5b04a671c2c2.png)

Kind regards,
Dennis Bijwaard, [grafana blog post](https://grafana.com/blog/2021/01/06/how-using-grafana-and-plugins-gave-a-jolt-to-smart-state-technology-a-company-advancing-technology-for-energy-infrastructures/)

**Comment by bijwaard** [comment]
Hi,
I just found that ms-resolution is possible by dividing the influxdb query interval itself ($__interval/10), but this is not so efficient since it also happens uses this when not zoomed in to subseconds. Looks like the 10ms minimum resolution is hardcoded somewhere.
![image](https://user-images.githubusercontent.com/6523124/124575166-72827d80-de4b-11eb-89d0-aac48bf9052e.png)

Kind regards,
Dennis

**Comment by aocenas** [comment]
@leeoniya I assume this is still a feature request for the new graph? I am asking to know if there is anything influxdb specific here that needs to be done because from my understanding not really.

**Comment by bijwaard** [comment]
Hi leeoniya,
Not sure if this is influxdb specific, the main issue is that the automatic time interval ($__interval) in the query stops at 10ms instead of 1ms.
Kind regards,
Dennis

**Comment by gabor** [comment]
> Hi leeoniya, aaocenas,
> Not sure if this is influxdb specific, my main issue is that the automatic time interval ($__interval) in the query stops at 10ms instead of 1ms. Support for microsecond precision would also be welcome.
> Kind regards,
> Dennis

hi @bijwaard , that problem is tracked in a separate issue if you are interested ( https://github.com/grafana/grafana/issues/7533 ) , and also seems to be a generic (non-influxdb specific) problem.

**Comment by tskarhed** [comment]
I left a comment in regards to nanosecond support on #6252, but this is also relevant.

**Comment by oscarkilhed** [comment]
Some of these use cases could possibly be solved with the XY chart. It’s not a perfect solution, but would allow for visualization of the data.

**Comment by bijwaard** [comment]
This issue is still relevant for most of us, guess ticket got closed because there is no involvement from the Grafana developers.

**Comment by Slach** [comment]
@torkelo useless and stupid bot usage decision, your software delivery process is completelly broken =(
