### ISSUE TITLE
GraphNG: Context series color is different than series color

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#30626]
**What happened**:

https://user-images.githubusercontent.com/13729989/105819916-23414280-5fb9-11eb-9ced-9ec26ec9ede3.mp4

**Comment by torkelo** [comment]
think this is fixed

**Comment by zoltanbedi** [comment]
This is still an issue 
![Screenshot 2021-04-07 at 13 48 11](https://user-images.githubusercontent.com/13729989/113861835-f2933b80-97a7-11eb-82a1-5271d91d9426.png)

**Comment by zoltanbedi** [comment]
This is fixed now.
