### ISSUE TITLE
Plugin "Dashboard list" shows folder "all" as the selected folder 

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#31158]
The plugin Dashboard List is not showing the selected and saved folder but always shows "all" as the selected folder. But the content of the list is referring to the right folder. The same thing happens on all the plugin "Dashboard list" I use. 

![image](https://user-images.githubusercontent.com/8969659/107743157-ac25e100-6d10-11eb-8a4e-327e54d01d15.png)

This is is the original setting and saved but when edditing the Plugin it returns to "All"

![image](https://user-images.githubusercontent.com/8969659/107743720-b3012380-6d11-11eb-98c3-f5c397eb4586.png)

**Environment**:
- Grafana version: 7.4.0
- OS Grafana is installed on: Azure
- User OS & Browser: Windows / Edge
- Grafana plugins: Dashboard list

**Comment by torkelo** [comment]
thanks for reporting this, fixed in https://github.com/grafana/grafana/pull/31160

**Comment by HenrikRolandHansen** [comment]
Sorry if it was already reported, I'm a noop to find existing issues.

**Comment by torkelo** [comment]
no it was not! I just fixed it right away after reading you issue

**Comment by HenrikRolandHansen** [comment]
ok thanks for info and glad to assist

**Comment by Leletir** [comment]
Hello,

I'm still having the problem on 7.4.2, There is only on folder displayed.

**Comment by krzd7** [comment]
I'm having the same issue as @Leletir, can only see the "General" folder. Is there an extra config I'm missing?
