### ISSUE TITLE
Can't edit panel in Chrome

### ISSUE THREAD

**Issue by memoir** [grafana/grafana#31374]
**What happened**:
Clicking the triangle next to the panel title doesn't open a menu in Chrome.

**What you expected to happen**:
That it opens a menu, as it does in Firefox.

**Environment**:
- Grafana version: 7.4.2 (29e75ad97b)
- OS Grafana is installed on: Docker container on Ubuntu
- User OS & Browser: Windows 10, Chrome 88.0.4324.182

**Comment by torkelo** [comment]
Can you try in incognito mode? maybe a chrome extension interfering?  Do you get this always or sometimes?

**Comment by memoir** [comment]
Hmm OK, it seems to be a problem with my Chrome installation. Yes, I also have the problem in incognito mode, and yes, I get it always. However, I just tried in a fresh installation of Chrome in a VM (also Windows 10), and there it works.

**Comment by yorikya** [comment]
I am also using Chrom `Version 88.0.4324.182 (Official Build) (x86_64)` on my mac to browse the Grafana but I am failing to edit the dashboards as well, In the `Safari` the issue isn't reproduced.  

Grafana version: 7.0.3

**Comment by memoir** [comment]
@yorikya OK, so it's not just me. It's still annoying not to be able to see the menu, but a workaround for editing is to use the keyboard shorcut, i.e. press `e` while your cursor is over the panel you want to edit.

**Comment by yorikya** [comment]
Thanks, @memoir workaround works for me 👍

**Comment by jonathan-mothership** [comment]
Same issue, started happening within the last week. Workaround works.

**Comment by mwk1963** [comment]
Same issue, just noticed it today 2-24-2021
doesn't work running Version 88.0.4324.192 on OSX Mojave
tried incognito mode does NOT work 
using e key workaround does work 
DOES work running Version 88.0.4324.190 on Windows 2016
co worker running same version of Chrome on OSX doesn't have the issue

**Comment by ingshtrom** [comment]
> Thanks, @memoir workaround works for me 👍

Did you run a VM or do a fresh install on Mac? I tried doing a fresh install on Mac and I guess I didn't clean something up because it is still happening.

**Comment by jonathan-mothership** [comment]
Upgraded to Grafana 7.4.3 and issue went away.

**Comment by ying-jeanne** [comment]
@memoir Hi, thanks for reporting the issue, could you install Grafana 7.4.3 and see whether the issue persists.

**Comment by memoir** [comment]
> @memoir Hi, thanks for reporting the issue, could you install Grafana 7.4.3 and see whether the issue persists.

Unfortunately yes, I still have the problem on v7.4.3 (010f20c1c8).

**Comment by hugohaggmark** [comment]
@memoir do you experience the same issue on Grafana v7.4.0 or v7.4.1? I also have issue with opening the Panel Edit menu but I've discovered that's because of my Mouse on MacOS. If I use the builtin track pad on my Mac, everything works.

**Comment by fangdaidai** [comment]
I am also

**Comment by memoir** [comment]
> @memoir do you experience the same issue on Grafana v7.4.0 or v7.4.1? I also have issue with opening the Panel Edit menu but I've discovered that's because of my Mouse on MacOS. If I use the builtin track pad on my Mac, everything works.

Yes, same on v7.4.0 and still on v7.4.3. I can, however, open the menu on v7.3.7.

**Comment by mattpr** [comment]
Grafana v7.3.3 
Chrome Version 89.0.4389.82
Extensions disabled (only had 1password).
MacOS Mojave

Safari works, chrome doesn't.
Neither built-in trackpad (macbook pro) or bluetooth mouse work in chrome.  Both work in Safari.

**Both** safari and chrome are registering the mousedown...because I see the `react-draggable-dragging` class added to the `react-draggable` panel wrapper if I hold mousedown.

However post-click safari has the dropdown element added (see screenshot) but chrome does NOT (ie the dropdown menu element is not in the dom in chrome where it is in safari).  So this isn't a style/css issue.

Running the following in both chrome and safari (trying to see if there is a difference in the event listener) doesn't show any difference....but I am probably looking at the wrong element for the event listener for the drop-down.  

```javascript
var panelTitles = document.querySelectorAll('.panel-title-container'),
    firstOne = panelTitles.length > 0 ? panelTitles[0] : false,
    clickHandler;

if (firstOne) {
    clickHandler = getEventListeners(firstOne).click[0];
    console.log(''+clickHandler.listener);
}
else console.log('Could not find panel title.')

//outputs: VM2928:7 function Fr(){}
```

I've never used jQuery so I don't know anything about debugging jQuery event handlers but I can reproduce this every time so if someone from Grafana wants to tell me how to debug this particular event handler, I'm happy to do that.

![image](https://user-images.githubusercontent.com/1196252/110949218-a2f55780-8342-11eb-8e81-7bb3b7bd11b1.png)

**Comment by duoonp** [comment]
I have several Grafanas on different projects, same behaviour on all of them. But panel editing menu on https://play.grafana.org/ works great.

**Comment by julienlafont-tabmo** [comment]
I've the same issue with Chrome 89.0.4389.90 on macOS 11.2.1, but it **works fine with the latest Chrome Canary** (91.0.4454.0)

**Comment by riobard** [comment]
Same issue with Safari 14.0.3 on macOS 11.2.3. Clicking the triangle causes the panel to flash. Multiple clicks will (seemly randomly) show the edit menu.

**Comment by bigHave** [comment]
@memoir thx, work around works for me

**Comment by riobard** [comment]
Update: It's an issue with using a Magic Mouse. The Magic Mouse is on a softer-than-normal mouse pad. Due to the structure of the Magic Mouse (not recommended to say the least), clicking slightly harder seems to cause the mouse cursor to drift a tiny little bit, which (I think) makes the panel think that I intend to move it around. If I click very carefully to hold the Magic Mouse still, or use a trackpad, the issue goes away.

Not sure if there has been any recent changes in how macOS recognizes mouse events, or any changes in tolerance in the Grafana JavaScript. Maybe you guys could dig around deeper to see why.

**Comment by bigHave** [comment]
@riobard I have the issue when I use touch pad , IMHO this is not a hardware issue

**Comment by mattpr** [comment]
I have the issue with different mice (usb, bluetooth) as well as touchpad on macbook pro...so I also don't think this is hardware related especially since different browser with same hardware doesn't have the problem.

**Comment by qixiaobo** [comment]
I think just chrome team make a big change! After upgrading  to  89.0.4389.90 .
Nearly forget to say mojava.

**Comment by qixiaobo** [comment]
I need more evidence

**Comment by nata7che** [comment]
also not working for me after updating to Chrome Version 89.0.4389.90.
working on MacOs Catalina v.10.15.7 and Grafana v6.7.3

**Comment by bigHave** [comment]
seems like a issue related to Chrome version?

**Comment by nvolker** [comment]
Same issue for me. Here are some specs if it's useful to anyone:
- Chrome: `Version 89.0.4389.90 (Official Build) (x86_64)`
- macOs: `Catalina Version 10.15.7 (19H524)`
- Grafana: `v7.3.1 (6668161a88)`

https://user-images.githubusercontent.com/45795784/112613960-60934680-8e29-11eb-88e6-54b401409ff6.mov

**Comment by noahleal** [comment]
Same issue for me for several days. With touchpad or mouse, makes no difference. The only way to access panel menus currently is with `e` hotkey

* Chrome: `Version 89.0.4389.90 (Official Build) (x86_64)`
* macOs: `Big Sur 11.1`
* Grafana: `v7.2.1 (72a6c64532)`

**Comment by Haesmen** [comment]
Helped by removing adblock and reinstalling the browser
Grafana v7.0.6 (9f4a172a76)
Version 89.0.4389.90 (Official Build), (64 бит)
Linux Mint 20.1 Cinnamon

**Comment by oscarkilhed** [comment]
Been trying to reproduce this issue on Windows and Linux on different chrome versions, but no success so far.

**Comment by bigHave** [comment]
several colleagues of mine encounterd the same issue, all with chrome version ```89.0.4389.90```

**Comment by MrYueQ** [comment]
Hi, I also encountered this problem. My version information is as follows.
```yaml
os: macos 11.1 (20C69)
chrome: 版本 89.0.4389.90（正式版本） (x86_64)
grafana: Grafana v7.0.3 (00ee734baf)
```
thanks

**Comment by enggal17** [comment]
Hi, I'm also having the same issue.
os: Windows
chrome: Version 89.0.4389.90 (Official Build) (64-bit)
grafana: Grafana v7.3.4 (14c494085e)

thanks

**Comment by mattpr** [comment]
Enough people seem to be running into this I took another look.  

The issue is that the click/mousedown event in chrome is giving fractional pixels now.  

So the `isClick` check in `onMenuToggle` returns false in chrome and the menu is not toggled.

### Chrome devtools

![image](https://user-images.githubusercontent.com/1196252/112805123-7eed8200-9075-11eb-8d35-481d1554c321.png)

![image](https://user-images.githubusercontent.com/1196252/112805226-9b89ba00-9075-11eb-82a4-e15fa5d3b3bc.png)

### Safari for comparison

![image](https://user-images.githubusercontent.com/1196252/112805335-c3791d80-9075-11eb-98db-3ce9664e36da.png)

**Comment by oscarkilhed** [comment]
> The issue is that the click/mousedown event in chrome is giving fractional pixels.
> 
> So the `isClick` check in `onMenuToggle` returns false in chrome and the menu is not toggled.

Good catch @mattpr, I'll look into this asap!

**Comment by oscarkilhed** [comment]
@mattpr I looks like that specific problem was fixed in 7.3.5 by this PR #29544
But there seems like there is another issue causing the same symptom. Upgrading to at least 7.3.5 could possibly help, unless you run into this second unknown problem as well.

**Comment by mattpr** [comment]
Great to hear.  This is a fairly recent Grafana deploy (Nov 2020) but `<7.3.5`.

Just deployed an update to `7.5.1` and I can confirm that this issue is resolved (for me).

I think we can assume this issue is resolved unless there is anyone on `>=7.3.5` that can still report this issue.

@memoir [reports](https://github.com/grafana/grafana/issues/31374#issuecomment-792613116) that they have this issue on `7.4.x`...but it sounds like this could be [a second issue](https://github.com/grafana/grafana/issues/31374#issuecomment-792523977) related to magic mouse...which might have to do with the same code-path (pixel coordinate checking).

**Comment by memoir** [comment]
Yes, I still can't open the menu on v7.5.1. I do not have a magic mouse, though.

**Comment by oscarkilhed** [comment]
> Yes, I still can't open the menu on v7.5.1. I do not have a magic mouse, though.

@memoir Do you get the blue border around the panel as visible in the video @nvolker posted? It indicates that a panel drag event has fired. I'm thinking it might have to do with the fractional pixels, but related to the drag event. 

Are you using a high dpi monitor?

**Comment by memoir** [comment]
Yes, I do get the blue border.
No, I am not using a high dpi monitor.

**Comment by mattpr** [comment]
Hey @memoir, perhaps you can do a little quick check to see if this is the pixel issue or not.

I made a screencapture showing how to open up dev tools, pick the right file, beautify it, find the right spot and add a breakpoint.  After you add the breakpoint in the right spot you click on the panel to try and open the menu and the breakpoint should stop execution and show you the variable values at that point in the script.  If the breakpoint doesn't hit that is useful info too.

If you can make a screenshot of what you see when the javascript execution stops at that break point it might shed some light on what is going on.

While you have chrome dev tools open, if you can check the "console" tab to see if there are any errors/messages there that would also be good.

https://www.youtube.com/watch?v=fQ1SonHV8oc

**Comment by memoir** [comment]
@mattpr I would gladly do that, but I can't get to the Dashboards page. Whatever I do, it takes me to my default dashboard, and I can't find any button or setting that would take me to the Dashboards page.

**Comment by memoir** [comment]
Oh no wait, got it.
OK, so I'm not seeing any variables, i.e. the debugger doesn't pause at all. Nothing in the console, either.
Just to be clear: After setting the breakpoint, all I do is click the title of the Dashboards panel, right?
![image](https://user-images.githubusercontent.com/2774225/112829148-fbda2500-9090-11eb-8f9f-057a45212023.png)

**Comment by memoir** [comment]
I clicked another panel and got this:
![image](https://user-images.githubusercontent.com/2774225/112829353-4c518280-9091-11eb-9378-f693397b8e0c.png)

**Comment by mattpr** [comment]
Okay so you aren't having a fractional pixel problem because `clicked == current`.
So just to be clear on that last case when you clicked on the PANEL title when the breakpoint hit...normally this does not open the menu. 
The breakpoint will stop the menu from opening but if you don't have the breakpoint set, clicking the same spot does not open any menu, right?

What about the "console" tab in dev tools.  Any errors/messages there?

**Comment by mattpr** [comment]
Aside from checking the devtools console for messages/errors (send screenshots please)... here is the next thing to test...

- disable the breakpoint you set earlier in the sources tab.

![image](https://user-images.githubusercontent.com/1196252/112830563-01d10580-9093-11eb-831a-f7c6d311b96e.png)

**Comment by memoir** [comment]
I was just about to say yes, but then decided to try again.
Actually, that particular menu can be accessed by clicking the little triangle. It's the "Welcome to Grafana" panel. As I said, clicking the title of the Dashboards panel doesn't pause.
So I went into one of my dashboards and deleted the title of one of the panels, and now I can access that menu as well, so the issue affects only panels that have a title.

**Comment by memoir** [comment]
The console is empty.
When I click a panel title, no menu div appears.
When I click the triangle on a title-less panel, it does.

**Comment by mattpr** [comment]
Interesting... going back to the breakpoint from earlier... 

That breakpoint stops execution when I click on either the title text and on the icon.  
It appears to be the same handler for both...so strange that one would work and the other would not...like event bubbling is not working properly or `stopPropagation` is being called on the event.

Can you set the breakpoint and try again clicking on three cases:
- the title text
- the down-arrow icon next to title text
- the title bar (ie to the right or left of the title text/arrow).  your mouse cursor should change to move icon.

Then in devtools expand the event object on the right-hand side and make the devtools window big enough to screenshot the event details.  For each screenshot please note where you clicked and whether you had set the title text to empty or not.

See my examples...


### Panel title TEXT

![image](https://user-images.githubusercontent.com/1196252/112832448-9dfc0c00-9095-11eb-8b6a-17f8f5bdbccb.png)


### Panel menu icon (down arrow)

![image](https://user-images.githubusercontent.com/1196252/112832470-a6ecdd80-9095-11eb-99c2-c9312978a61f.png)


### panel menu bar (move mouse icon...but just click)

![image](https://user-images.githubusercontent.com/1196252/112832615-db609980-9095-11eb-8888-5a1d1f39a348.png)

**Comment by mattpr** [comment]
> The console is empty.

By the way...I find that a bit strange as I am also running 7.5.1 and my console is NOT empty.  Maybe reload the page and check again?  Also in the devtools network tab, check the "disable cache" checkbox...just to make sure this isn't some strange caching issue.

While we are at it, can you double check in chrome://extensions that all extensions are disabled?
I assume you haven't been playing with chrome's browser flags/experiments either or you would mention it.
Just going through the list of things that could potentially result in the app working differently in your browser than in mine.

![image](https://user-images.githubusercontent.com/1196252/112832906-41e5b780-9096-11eb-9126-1aa2fb78f64a.png)

**Comment by memoir** [comment]
When the panel has a title, execution is not paused and the Scope area in the Dev Tools is empty, no matter where I click.
When the panel has no title…
…clicking on the down arrow
![image](https://user-images.githubusercontent.com/2774225/112833472-12837a80-9097-11eb-9c88-570904720a07.png)
…clicking on the title bar
![image](https://user-images.githubusercontent.com/2774225/112833510-1fa06980-9097-11eb-8d3f-8a607be11336.png)

**Comment by memoir** [comment]
This is my console with the Home page open (clicking on panel titlebars (with without a title) doesn't add anything):
![image](https://user-images.githubusercontent.com/2774225/112834360-2e3b5080-9098-11eb-9d23-8521c144f356.png)
This is my console with a dashboard open (again, clicking on panel titlebars (with without a title) doesn't add anything):
![image](https://user-images.githubusercontent.com/2774225/112834435-427f4d80-9098-11eb-9793-0e07be5d8bad.png)

**Comment by memoir** [comment]
Extensions are disabled.
I did have non-default options on these flags:
![image](https://user-images.githubusercontent.com/2774225/112834902-dbae6400-9098-11eb-930b-5e61a5fb8c6e.png)
However, resetting them doesn't change anything.

**Comment by oscarkilhed** [comment]
Can you try resizing your chrome window to make it very narrow before clicking? Change it so that the dashboard is using the responsive design for mobile (you'll see the panels jump when you've made it narrow enough)

**Comment by memoir** [comment]
😮 that works, @oscarkilhed

**Comment by nata7che** [comment]
nice hack @oscarkilhed works for me also!

**Comment by oscarkilhed** [comment]
@memoir @nata7che thanks for your patients. Can you try one more thing for me? Can you go to https://react-grid-layout.github.io/react-grid-layout/examples/0-showcase.html and click the boxes in the grid? Does the entire box you click flash red?

**Comment by nata7che** [comment]
@oscarkilhed only when trying to resize or move.

**Comment by memoir** [comment]
@oscarkilhed @nata7che For me, they also flash red when I just click inside.

**Comment by oscarkilhed** [comment]
This could be an issue with #[react-grid-layout](https://github.com/react-grid-layout/react-grid-layout) then. I was able to reproduce this issue both in grafana and on the react-grid-layout demo page only while using microsoft teams to present the specific chrome window.

**Comment by keycodez** [comment]
> Can you try resizing your chrome window to make it very narrow before clicking? Change it so that the dashboard is using the responsive design for mobile (you'll see the panels jump when you've made it narrow enough)

@oscarkilhed I also tried this, but the issue persists.

**Comment by oscarkilhed** [comment]
@shaharb-hs @keycodez Are you running grafana 7.3.5 or later?

**Comment by keycodez** [comment]
> @shaharb-hs @keycodez Are you running grafana 7.3.5 or later?

No, I have 7.1.5 deployed here. Is the only solution to upgrade?

**Comment by oscarkilhed** [comment]
@keycodez Yes, you need to upgrade, it is likely you are running into the issue fixed by #29544
Chrome changed the position in the mouse event to use fractions of a pixel, so with newer chrome versions old versions of grafana will have this issue.

**Comment by bettinabenli** [comment]
Chrome version 89.0.4389.90
Grafana version: v7.3.1

Same with setup ad my colleague next to me. But for him it works for me not. Same Grafana, same OS version same Chrome version.

**Comment by mattpr** [comment]
@bettinabenli 
> Same with setup ad my colleague next to me. But for him it works for me not. Same Grafana, same OS version same Chrome version.

This fractional pixel issue may impact some users and not other due to monitor or other configuration that is not obvious.

What we know... the fractional pixel issue is fixed in Grafana 7.3.5, so you would need to update to at least 7.3.5 (or later) and test again.   If you still have the issue after updating to Grafana >7.3.5, report back.

**Comment by bigHave** [comment]
expect a fix, too. we are currently using v6.7.4 in prod env and update  to 7.x may cause unpredicted issues.

**Comment by pytimer** [comment]
Upgrade chrome 89.0.4389.114 from 88.0.4324.182, it works well.

**Comment by gtskaushik** [comment]
Chrome version: 89.0.4389.90
Grafana version: 7.1.0
I have the same issue. I upgraded my Chrome to 89.0.4389.114 and still have the same issue

**Comment by hugohaggmark** [comment]
> Chrome version: 89.0.4389.90
> Grafana version: 7.1.0
> I have the same issue. I upgraded my Chrome to 89.0.4389.114 and still have the same issue

@gtskaushik thank you for reporting, but as several people already said, the fix is in Grafana 7.3.5. and you wrote version 7.1.0 Can you please try to upgrade and report back if you're still experiencing the issue? Thank you 🙏

**Comment by ethirolle** [comment]
One more data point... I am doing some tests to see if I can reproduce the issue by enabling some of the Chrome experimental features (as discussed in https://github.com/grafana/grafana/issues/25018). I am on Chrome version 89.0.4389.114 (Official Build) (64-bit), and testing on various versions of Grafana from 7.3.4 to 7.5.2.

I enabled **Experimental JavaScript** and **Experimental Web Platform features**, and no luck reproducing the issue.

**Comment by oscarkilhed** [comment]
Possible root issue: https://github.com/react-grid-layout/react-grid-layout/issues/1441

**Comment by rileyhun** [comment]
I started experiencing this issue suddenly yesterday. Incognito mode doesn't work either. I am on Chrome Version 89.0.4389.114 (Official Build) (x86_64). I am using the "e" keyboard shortcut as a workaround.

**Comment by torkelo** [comment]
What version of Grafana?

**Comment by SatyaaDixit** [comment]
I too started experiencing the same issue all sudden one week back also Incognito mode doesn't work either. Grafana and Chrome version respectively are v7.3.3 (2489dc4d3a) and 89.0.4389.114 (Official Build) (32-bit). As a workaround "e" is working for me but if anyone could help with permanent fix for this?

**Comment by hugohaggmark** [comment]
> I too started experiencing the same issue all sudden one week back also Incognito mode doesn't work either. Grafana and Chrome version respectively are v7.3.3 ([2489dc4](https://github.com/grafana/grafana/commit/2489dc4d3a6b8d26dfa6ef90c49f3a040f8dd433)) and 89.0.4389.114 (Official Build) (32-bit). As a workaround "e" is working for me but if anyone could help with permanent fix for this?

@SatyaaDixit  thank you for reporting, but as several people already said, the fix is in Grafana 7.3.5. and you wrote version 7.3.3 Can you please try to upgrade and report back if you're still experiencing the issue in 7.3.5? Thank you 🙏

**Comment by risoms** [comment]
I'm seeing the same issue as well. In some cases upgrading Grafana can be risky for teams using it, especially if upgrading is producing another set of breaking changes.
Chrome: 89.0.4389.114
Grafana: v7.3.3
OS: Mac OS X 10.15

**Comment by hugohaggmark** [comment]
> I'm seeing the same issue as well. In some cases upgrading Grafana can be risky for teams using it, especially if upgrading is producing another set of breaking changes.
> Chrome: 89.0.4389.114
> Grafana: v7.3.3
> OS: Mac OS X 10.15

Thanks for reporting this @risoms, we know that this is an issue < 7.3.5 Grafana. What would help us solve this issue is if you could upgrade to Grafana 7.3.5 and report back if that works or not? Thank you.

**Comment by iamstarkov** [comment]
@hugohaggmark didnt OG reporter mentioned their Grafana version being `7.4.2 (29e75ad)`

**Comment by risoms** [comment]
> Thanks for reporting this @risoms, we know that this is an issue < 7.3.5 Grafana. What would help us solve this issue is if you could upgrade to Grafana 7.3.5 and report back if that works or not? Thank you.

@hugohaggmark That won't be possible. As I mentioned, alot of people use our dashboard, and to introduce an update has to be well-tested before it's done. Can this issue be fixed on all supported versions of Grafana?

**Comment by oscarkilhed** [comment]
@risoms the fix is two patch versions away from the version you use. Those versions contain additional bug fixes and security updates. I don’t think patches released, for every patch version, is a reasonable expectation.

**Comment by SiddAjriY2Jaccount** [comment]
I am using grafana version 7.5.3 and while I was able to edit dashboard panels freely initially, all of a sudden I was unable to see a dropdown when I clicked on the down arrow next to the panel title, the edit option was just frozen. I checked and reset my permissions over and over to no avail. However, a few hours later, I was able to edit the panels once again. 

So it seems like the issue appears at random in later versions as well. I installed grafana using the zip file on Windows 10 Enterprise edition system, and use Chrome Version 89.0.4389.114

**Comment by flitjoe** [comment]
We're having an issue editing Grafana tiles in Chrome & Edge (Chromium) ONLY when screensharing in MS Teams. We've done working sessions with stakeholders via zoom but today when trying in MS teams, clicking the title drop-down carrot to try and edit, does nothing. If you stop sharing that particular browser window, you can then edit. Is it worth making a new ticket or is it related to this issue? We have a video recording that is rendering that I can attach once done and cropped.

**Comment by gidhap** [comment]
same here, using 7.1.5, Chrome, Win10. It worked since it was released. Since a couple of days I can no longer edit. Pull down menu with triangle not available. This happens randomly. Sometimes it takes minutes until it works, sometimes after hours. Best workaround for me is to use Firefox.

**Comment by gitman0** [comment]
I've been using Chrome 88 since early February and and Grafana 7.2.0 since Oct 1st 2020. Only within the past 2-3 weeks has the pull down menu stopped working. Very strange...

**Comment by da-blok** [comment]
Same for me with Chrome 90.0.4430.72 (Mac OS), in Safari it is working.

**Comment by Ma3oBblu** [comment]
same issue Chrome 90.0.4430.72 (Mac OS), Safari is good with this

**Comment by oscarkilhed** [comment]
@gidhap @gitman0 @da-blok @Ma3oBblu
There is an issue with the same symptom as this, related to a change in chromes behavior. Upgrading to at least Grafana 7.3.5 will fix that issue. If you're already using a later version of Grafana, please report back.

**Comment by Ma3oBblu** [comment]
> @gidhap @gitman0 @da-blok @Ma3oBblu
> There is an issue with the same symptom as this, related to a change in chromes behavior. Upgrading to at least Grafana 7.3.5 will fix that issue. If you're already using a later version of Grafana, please report back.

thanks, we are using 7.0.3, will try to upgrade

**Comment by gidhap** [comment]
@Ma3oBblu Upgraded to 7.5.4 following the instructions for Debian https://grafana.com/docs/grafana/latest/installation/upgrading/
Worked right away. Will report back if issues occur again.

**Comment by adsche** [comment]
I'm on 7.5.4 (Centos; via yum repo) and the issue described here now occurs (yes, only **after** the upgrade). I am using a magic mouse, macOS 10.15.7, Firefox 87.0.
Previous ('good') version was 7.3.6.
The issue only occurs with the magic mouse, not with the touchpad. It occurs both on the internal (retina) display and an external (non-retina) display.
Grafana always interprets the click as if I was moving the mouse (starts to move the dashboard as if I was clicking+dragging anywhere else on the titlebar).

**Comment by oscarkilhed** [comment]
@adsche do you mind testing out these two sandboxes to see if they work or not?

https://codesandbox.io/s/sparkling-frost-b5ozq?file=/package.json

https://codesandbox.io/s/modest-hamilton-rqi9f?file=/package.json

**Comment by adsche** [comment]
@oscarkilhed sure thing! I'm not sure what is supposed to happen / what I'm supposed to do but:

On your first link, when I click boxes, ~3/4 of times they turn red briefly and nothing further happens. I can reorder them by dragging, which is followed by an alert ("success"). But ~1/4 of the time, they move a tiny bit and the alert is displayed even when only clicking (I don't see the mouse cursor move even a pixel).

On your second link, every click (no matter if dragging or not) causes the alert.

**Comment by oscarkilhed** [comment]
@adsche it's probably related to this then https://github.com/react-grid-layout/react-grid-layout/issues/1441

**Comment by bigHave** [comment]
update to newest chrome version ```90.0.4430.85```  has solved this problem.

**Comment by memoir** [comment]
> update to newest chrome version `90.0.4430.85` has solved this problem.

not for me

**Comment by oscarkilhed** [comment]
@memoir do you mind testning the two sandboxes i posted earlier?

**Comment by memoir** [comment]
> @memoir do you mind testning the two sandboxes i posted earlier?

1st link: Success only on "static" boxes
2nd link: Success on all boxes

**Comment by gitman0** [comment]
Upgrading to google-chrome-stable-90.0.4430.85-1.x86_64 has resolved the issue for me.

**Comment by qixiaobo** [comment]
> Upgrading to google-chrome-stable-90.0.4430.85-1.x86_64 has resolved the issue for me.

Me too

Google Chrome 已是最新版本
版本 90.0.4430.85（正式版本） (x86_64)

**Comment by da-blok** [comment]
> Upgrading to google-chrome-stable-90.0.4430.85-1.x86_64 has resolved the issue for me.

Same applies for me. Chrome version 90.0.4430.85

**Comment by Phil1pp** [comment]
> 
> 
> @adsche do you mind testing out these two sandboxes to see if they work or not? You should get a success alert when you click the boxes.
> 
> https://codesandbox.io/s/sparkling-frost-b5ozq?file=/package.json
> 
> https://codesandbox.io/s/modest-hamilton-rqi9f?file=/package.json

I am on Grafana v7.5.4 (615c153b3a) and Chrome Version 90.0.4430.85 and have this issue too.
First link doesn't show success. Second one does.

**Comment by christianbookpwood** [comment]
I'm also having this issue with Grafana 7.2.1. However, Chrome 90.0.4430.85 has not fixed the issue for me as it has with others. No issues in Firefox.

**Comment by Phil1pp** [comment]
Now with latest Chrom Update Version 90.0.4430.93 it's working fine.
Also both codesandbox links showing success on every click.

**Comment by Ma3oBblu** [comment]
fixed after updating Chrome to 90.0.4430.85 version (MacOS/Intel)

**Comment by nata7che** [comment]
Fixed after updating to the latest Chrome: 90.0.4430.85

**Comment by memoir** [comment]
Oh, it works for me, too, now on Chrome 90.0.4430.93 and Grafana 7.5.5.

**Comment by forgitit** [comment]
Same issue for me on Chrome Version 91.0.4472.77 and Grafana v7.5.7. Cleared cache/restarted no change. The dropdown click detects as moving the panel, instead of presenting the dropdown.

Works on Firefox.

**Comment by memoir** [comment]
> Same issue for me on Chrome Version 91.0.4472.77 and Grafana v7.5.7. Cleared cache/restarted no change. The dropdown click detects as moving the panel, instead of presenting the dropdown.
> 
> Works on Firefox.

Indeed, it's back :(

**Comment by krisavi** [comment]
Same issue on Grafana 8.0.2

**Comment by risoms** [comment]
I'm seeing the same issue after updating to 8.0.1 and 8.0.2.

**Comment by redlegoman** [comment]
I have just installed grafana 8.0.3 in docker, I am running Chrome 91.0.4472.114 on Windows 10 and I too am getting this error out-of-the box. I also have no issues with Firefox. I know this "me too" isn't particularly helpful, but just to let you know it seems to be a problem. I get the same issue on the Brave and Microsoft Edge browsers, which I understand are also Chromium based.

**Comment by lux4rd0** [comment]
Was about to open a new ticket and found this quite similar issue. Running on Mac Chrome Version 91.0.4472.114 (Official Build) (x86_64) - With Grafana 8.0.3 - but upgraded to Grafana v8.0.4 (81fef5b4b4) - when clicking on the drop-down the entire panel flashes once, twice, sometimes three times before being presented. Keyboard shortcuts work just fine.

**Comment by Alloc86** [comment]
Having the same issue.
Chrome 96.0.4664.45 on Windows 10
Grafana 8.2.2 and 8.2.5 (just updated to see if that fixes it)

Making the window pretty narrow "fixes" it (not seeing what exactly the difference is, the Grafana menu sidebar is still visible, when the first of the dashboard buttons on the top right of the page moves into a second row it still has the issue but it starts working *before* the second button moves into the second row).

First sandbox from @oscarkilhed works only for static boxes, second one on every box.

**Comment by BeePerNet** [comment]
Same issue with version 8.2.5

**Comment by koitsu** [comment]
Seeing this on a brand new installation of official `grafana/grafana-oss:8.3.4` Docker image. Issue starts happening after periodic use of Grafana (editing panels, etc.). A full browser relaunch works around the problem (closing/reopening the tab does not), or using keyboard shortcuts as previously described. What triggers the problem I have not been able to determine. Issue happens without any extensions installed as well. Chrome Version 97.0.4692.99 (Official Build) (64-bit).

**Comment by kernelphr34k** [comment]
I'm also seeing this issue on Brave browser: 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit)

If I open a private window, login I can edit a panel. Once I save and apply I can no longer edit the panel. A pop-up does not show. I must close the private browser window and login again to edit the panel. Refreshing the page does nothing.

**What happened:**
Clicking the triangle next to the panel title doesn't open a menu in Chrome.

**What you expected to happen:**
That it opens a menu, as it does in Firefox 96.0.3 (64-bit

Server: 
Ubuntu 20.04.3 LTS (Focal Fossa), Kernel: 5.4.0-96-generic 
Prometheus Version: prometheus-2.33.0-rc.1.linux-amd64
Grafana Version: grafana-enterprise_8.3.4_amd64
Node Exporter:  node_exporter-1.3.1.linux-amd64.

**Comment by BeePerNet** [comment]
It seems that the mouse drag&drop is taking over before the mouse release to call the click event. I have to press and release the mouse very fast without moving the mouse at all to bypass the problem, pretty difficult, but doable. It seems the under laying header drag&drop is taking over the button drop down click functionality.

**Comment by BeePerNet** [comment]
It seems to be fixed on version 8.4.2.

**Comment by kernelphr34k** [comment]
Confirmed working in 8.4.4 on Ubuntu 20.04.4 LTS.

**Comment by limabing** [comment]
Having the same issue(Can't edit panel).
edge 114.0.1823.79 and google chrome 114.0.5735.199 on Windows 11 
Family Chinese Version 22000.2176
Grafana 8.2.0.oh my god,please help me!

**Comment by Randommmm** [comment]
Exact same issue, Grafana v10.2.2.

**Comment by yylbfyl** [comment]
Exact same issue, Grafana v11.3.0, some panel have no edit option.
![Image](https://github.com/user-attachments/assets/572712f8-3f73-460f-8dbf-be80be50995a)
