### ISSUE TITLE
Node Graph: Error: ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#31599]
**What happened**:
From Sentry (3150 times):
`Error: ResizeObserver loop limit exceeded`
`at ? (https://play.grafana.org/d/Pbk2rfBGz/node-graph?orgId=1&editPanel=2:0:0)`

**Comment by Elfo404** [comment]
FYI I did some research in the past for this, and the conclusion was to simply ignore this error.

tracing back to some discussions on the web, it feels like the error shouldn't be an error but a warning. 

some references:
- https://github.com/WICG/resize-observer/issues/38#issuecomment-422126006
- https://github.com/w3c/csswg-drafts/issues/5023

**Comment by hilts-vaughan** [comment]
> tracing back to some discussions on the web, it feels like the error shouldn't be an error but a warning.

Finding this hot off the heels of dealing with another issue that was similar; peeking at your code you are doing some manipulation on item. However, in your case you are generating dozens of these per second (in the above example run `window.onerror = (e) => console.log(e)` and you can see it), so you have some self-referential stuff to deal with it. If this is intentional, perhaps you would benefit from a flag or something to let the browser know it's WAI -- the above proposals talk about if you want to chime in.

**Comment by aocenas** [comment]
This is already fixed sort of accidentally in https://github.com/grafana/grafana/pull/31521 (issue was an inline function for a component ref, which created some feedback loop with a hook that used ResizeObserver). But that PR is a feature that will be part of v8. Considering this is mostly a slight perf issue in a visualisation that is still beta state I think it is ok to leave this for v8.

**Comment by bradenhs** [comment]
For what it's worth I still see this issue in 8.2.5. You may want to consider reopening this.

**Comment by bradenhs** [comment]
Here's a gif demonstrating the issue in 8.2.5. The error appears when hovering the "State timeline" and "Time series" visualizations. I wasn't able to see the error when using other visualization types. Additionally, the error doesn't make it to the browser console for some reason. I had to add a window error event listener to pick it up so this issue likely has flown under the radar b/c of that. The main problem I'm encountering here is that this is filling our remote error logs with a bunch of irrelevant errors.

![resizeObserver](https://user-images.githubusercontent.com/22484684/145085852-16bbfeea-3d1b-4cb6-9b7b-0c19254940a3.gif)

**Comment by ivanahuckova** [comment]
@bradenhs Thank you for bringing this up! Would you mind creating separate issue for State timeline and Time series as this one was for Node Graph where the issue was remove. 🙏
