### ISSUE TITLE
When write text directly to a variable input field, then press enter not work

### ISSUE THREAD

**Issue by msober** [grafana/grafana#31879]
**What happened**:
When write text directly to a variable input field, if the text not in the defalult value list, then press enter will throw an Error.

For example:
![image](https://user-images.githubusercontent.com/1792217/110728603-56cde880-8258-11eb-8998-13a884826e62.png)

After press enter, report an error:
![image](https://user-images.githubusercontent.com/1792217/110729010-f12e2c00-8258-11eb-9865-a3e6423d089b.png)

**What you expected to happen**:

After press enter, the input text as the value of the variable 

**Environment**:
- Grafana version: 7.3.5
- Data source type & version:
- OS Grafana is installed on: mac os
- User OS & Browser: Chrome 
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
looks like it's fixed in 7.4.x 
https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&var-app=backend&var-server=backend_03&var-interval=1h

**Comment by dessen-xu** [comment]
hello! The bug stills exists。

https://user-images.githubusercontent.com/41524013/110887240-e5a83700-8324-11eb-9501-2d5ed8fbf61a.mov

**Comment by dessen-xu** [comment]
Hello! The bug stills exists. Type "appName", then press enter, then throw an error

https://user-images.githubusercontent.com/41524013/110899632-6e7e9d00-833c-11eb-917c-1006c0138f9c.mov

**Comment by dessen-xu** [comment]
@torkelo please look at it
