### ISSUE TITLE
Latest Github/Docker Tag Messed Up!

### ISSUE THREAD

**Issue by jag3773** [grafana/grafana#32134]
About an hour ago @xlson pushed 6.7.6 as the `latest` tag in Docker Hub, see screenshot.  This pushes everyone back a major release!  Please update to point at the actual latest, 7.4.5.

<img width="338" alt="Screen Shot 2021-03-18 at 14 21 18" src="https://user-images.githubusercontent.com/107731/111677315-7b483880-87f5-11eb-9e3b-a23579ccfdad.png">

**Comment by jag3773** [comment]
Looks like this is an issue with the Github tags too, Docker is following the "latest" Github tag, which points at 6.7.6.

**Comment by xlson** [comment]
Thanks for reporting, it has been fixed now.

**Comment by jag3773** [comment]
Thanks for fixing Docker! The issue still exists in Github:
<img width="280" alt="Screen Shot 2021-03-18 at 16 43 59" src="https://user-images.githubusercontent.com/107731/111695318-552c9380-8809-11eb-9851-270a7f503033.png">

**Comment by james-callahan** [comment]
> Thanks for fixing Docker! The issue still exists in Github:

It's not wrong: 6.7.6 is the most recent release....
7.4.5 was released chronologically before 6.7.6.
