### ISSUE TITLE
Loki: Log Browser stuck at "Loading labels ..." when Loki is the default data source

### ISSUE THREAD

**Issue by tonychoe** [grafana/grafana#32565]
**What happened**:

The Log Browser stuck with "Loading labels..." message when you visit Explore and the Loki is the default data source. This issue won't happen if you first get to the non-Loki data source and then switch to Loki.

**What you expected to happen**:

The Log Browser should complete loading and display "Log browser title".

**How to reproduce it (as minimally and precisely as possible)**:

0. Configure the Loki datasource as default.
1. Go to Explore. You see Log Browser works well.
    <img width="1051" alt="step1" src="https://user-images.githubusercontent.com/12507518/113337108-2c61cf00-92dc-11eb-902a-4357ce682754.png">
2. Go to somewhere else like Dashboard
    <img width="1070" alt="step2" src="https://user-images.githubusercontent.com/12507518/113337121-31bf1980-92dc-11eb-903a-79c9aa297eca.png">
3. Go back to Explore. Loki data source comes up with the "Loading labels..." message.
    <img width="1027" alt="step3" src="https://user-images.githubusercontent.com/12507518/113337802-1ef91480-92dd-11eb-921d-fa00046f7bd7.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: Loki
- OS Grafana is installed on: RHEL7
- User OS & Browser: MacOS Catalina & Brave (Chrome)
- Grafana plugins: 
- Others:

**Comment by Elfo404** [comment]
Hi @tonychoe, thanks for the issue!

I'm not able to reproduce this, can you please check your dev tools to see if there's some error in the browser console and/or in the network panel? that would hugely help!

**Comment by tonychoe** [comment]
Hi @Elfo404 Thanks for investigating this issue. I came up with the better reproducing steps and the screenshot of the browser console.

**Comment by yongzhang** [comment]
similar issue:
https://github.com/grafana/grafana/issues/32528

**Comment by gabor** [comment]
i can reproduce this in 7.5.2, but not in 7.5.3 anymore. this probably got fixed by https://github.com/grafana/grafana/commit/81d34a9efa3fe66a484048ca80ec4d3eba6849ec .

**Comment by yongzhang** [comment]
My issue may be a different one  https://github.com/grafana/grafana/issues/32528, I still have the issue in 7.5.6.

**Comment by gabor** [comment]
@yongzhang  strange... i reopened https://github.com/grafana/grafana/issues/32528 for now.
