### ISSUE TITLE
Time Series issue on Grafana 8 (Cannot read property ‘scale’ of undefined)

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#34693]
**What happened**:
After update Grafana from 7.5.7 to 8.0.0-beta2, Time Series plugin doesn't show correctly chart

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/73607094/119602321-2d4e4300-bdeb-11eb-975c-6d0a03fdc57c.png)
When I click table view option then shows me correctly data
![image](https://user-images.githubusercontent.com/73607094/119602353-3f2fe600-bdeb-11eb-8e1d-d08f80b6c59e.png)

**Environment**:
- Grafana version: 8.0.0-beta2
- Data source type & version:
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome, Firefox, Edge
- Grafana plugins: Time Series
- Others: n/a

**Comment by leeoniya** [comment]
this specific error will probably be solved by https://github.com/leeoniya/uPlot/pull/519 (in 8.0.0-beta3)

however, this tells me that somehow the time series panel is ending up with 0 series to render. which means it does not properly filter the necessary fields.

can you provide the query response data and your dashboard config so we can try to reproduce this?

**Comment by deejayluk** [comment]
this is code from MS SQL Database:
```
With Bs as (
    select distinct [t$date] from [Operations].[dbo].[BAAN] 
    where [t$date]>= dateadd(hour,1,$__timeFrom()) and [t$date]< dateadd(hour,1,$__timeTo())
)
select
    convert(float,sum(case when substring(t.status,0,3)='OK' then 1 else 0 end))/count(t.status)*100 OTD,b.[t$date] time
from
    Bs b
        inner join
    [Operations].[dbo].[BAAN] t
        on
            b.[t$date] >= t.[t$date]
            where t.[t$date]>= dateadd(hour,1,$__timeFrom()) and t.[t$date]< dateadd(hour,1,$__timeTo())
            and ([t$nama] like (case when '[[CUSTOMER]]' = '_WSZYSTKIE_' then '%' else N'[[CUSTOMER]]' end)
    and [t$buyr] like (case when '[[BUYER]]' = '_WSZYSTKIE_' then '%' else N'[[BUYER]]' end)
    or
     [t$nama] like (case when '[[CUSTOMER]]' = '_WSZYSTKIE_' then '%' else N'[[CUSTOMER]]' end)
    and [t$buyr] is null and '[[BUYER]]' = '_WSZYSTKIE_'
    )
group by
    b.[t$date]
	order by b.[t$date]
```
I took last week data, only four lines and problem is still the same
![image](https://user-images.githubusercontent.com/73607094/119604657-b8313c80-bdef-11eb-979b-f9611074b051.png)

**Comment by deejayluk** [comment]
If I change the columns, first will be time, second will be data and I change the format to a table, this shows the graph :)
![image](https://user-images.githubusercontent.com/73607094/119605399-07c43800-bdf1-11eb-9525-7eb6862efb53.png)
but when I change again to Time Series
![image](https://user-images.githubusercontent.com/73607094/119605563-4e199700-bdf1-11eb-94a1-36d4aa5b35b6.png)

maybe this information help you to find problem

**Comment by deejayluk** [comment]
Next issue:
version 7.5.7
![image](https://user-images.githubusercontent.com/73607094/119809081-0a07be80-bee5-11eb-8baf-e609232ff0f4.png)
version 8.0.0-beta2
![image](https://user-images.githubusercontent.com/73607094/119809196-23a90600-bee5-11eb-9318-340c2bdd8dc7.png)

version 8.0.0-beta2 show always the same day and results, every bar show me 2021-05-27 but in previously version showed correctly

**Comment by dprokop** [comment]
@deejayluk regarding the first issue you are reporting - do you mind sharing the data reponse for your query that throws an error? You can do it by using [Panel inspect](https://grafana.com/docs/grafana/latest/panels/inspect-panel/)

**Comment by dprokop** [comment]
damn - forget ^^ i see now the 4 rows of data in your screenshot that we can use

**Comment by deejayluk** [comment]
ok nie ma problemu :) jakbyś potrzebował więcej informacji daj znać Dominik :)

**Comment by nikki-kiga** [comment]
####  First Issue

Confirming that this behavior exists on main. 
<img width="1423" alt="data-barChart" src="https://user-images.githubusercontent.com/42276368/128567370-30d4ab53-2ab4-4e73-9c9f-d9045a65170b.png">
<img width="1427" alt="data-oldGraph" src="https://user-images.githubusercontent.com/42276368/128567373-f6a1e7b8-c005-47b8-aeb0-9e00aae1774d.png">
<img width="1424" alt="data-table" src="https://user-images.githubusercontent.com/42276368/128567374-bfb4d349-6a0c-4765-8a1f-1320d6ce088c.png">
<img width="1425" alt="data-timeSeries" src="https://user-images.githubusercontent.com/42276368/128567377-a3a6f33a-d2b5-4c23-9ad2-c2d3a4072682.png">

Also related to: https://community.grafana.com/t/time-format-issue/25052

#### Second Issue
It's possible that this is fixed by: https://github.com/grafana/grafana/pull/37615

**Comment by dprokop** [comment]
@deejayluk from what I see I can guess that date time returned by your query is not a unix timestamp, hence the time series won't work. Can you please share the data frame structure (available in the [Panel Inspect's JSON tab](https://grafana.com/docs/grafana/latest/panels/inspect-panel/)) so that we can confirm that? 

@nikki-kiga similar situation happens with the CSV Content scenario in test data. Even though the[ column is named `time`](https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/testdatasource/csv_data.go#L137) the [conversion to time field fails](https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/testdatasource/csv_data.go#L240), and the resulting data frame holds time as a `string` field:

![image](https://user-images.githubusercontent.com/2376619/130226396-15c59b90-5452-4c56-9594-c53f3d291d8e.png)

@nikki-kiga for the csv content test scenario the date needs to be in RFC3339 format as of [this line](https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/testdatasource/csv_data.go#L263)

**Comment by dprokop** [comment]
As of the original bug report - I don't think it occurs anymore on the main branch. I believe the actual issue here is not about the time series but about the data returned from the data source. Let's see what the data frame structure is and we can then decide what needs to be fixed :)

**Comment by dprokop** [comment]
@deejayluk did you have a chance to try out latest version of Grafana to see if you still encounter this issue?
