### ISSUE TITLE
`[date_formats].use_browser_locale` doesn't work; requires undocumented option `date_format_use_browser_locale`

### ISSUE THREAD

**Issue by theneva** [grafana/grafana#34748]
Hi! :wave:

**What happened**:

Grafana ignores the following configuration option:

``` ini
[date_formats]
use_browser_locale = true
```

This is also true if I set it using the environment variable `GF_DATE_FORMATS_USE_BROWSER_LOCALE=true`.

Instead, I'm forced to set an undocumented option `date_format_use_browser_locale` under the same `[date_formats]` header.

My locale is `en-GB-oxendict`, and https://www.localeplanet.com/support/browser.html says that a locale formatted date in my browser should be `DD/MM/YYYY`:

![image](https://user-images.githubusercontent.com/1404650/119671883-6e217880-be3a-11eb-89bf-11864e18871e.png)

Still, all graph panels format months in the en-US way, i.e., MM/DD:

![image](https://user-images.githubusercontent.com/1404650/119672015-87c2c000-be3a-11eb-99c3-7a8230a2404a.png)

The config list in the Server Admin settings view looks like this (note the additional `date_format_use_browser_locale` field at the top, which is missing an `s` at the end of `format`):

![image](https://user-images.githubusercontent.com/1404650/119672154-a7f27f00-be3a-11eb-8e42-d6bb5f0fb545.png)

I can't for the life of me figure out how to override the potentially-accidental `date_format_use_browser_locale` option using an environment variable – `GF_DATE_FORMATS_DATE_FORMAT_USE_BROWSER_LOCALE=true` doesn't work – but if I set it in `grafana.ini` like this:

```ini
[date_formats]
date_format_use_browser_locale = true
use_browser_locale = true
```

… I end up with this in the settings view:

![image](https://user-images.githubusercontent.com/1404650/119674164-40d5ca00-be3c-11eb-8108-119fba720e96.png)

… and the graph formats my months correctly, i.e., DD/MM:

![image](https://user-images.githubusercontent.com/1404650/119674432-7e3a5780-be3c-11eb-9dfc-9446e3d0f9a9.png)

**What you expected to happen**:

I expected two things to be different from the current behaviour:

1. Setting `use_browser_locale` to `true` should be enough to get the correct formatting.
2. The `date_format_use_browser_locale` should not exist at all, or at the very least be documented and configurable via an environment variable like the rest of the config options.

**How to reproduce it (as minimally and precisely as possible)**:

I used the `grafana/grafana:main` image to be sure I wasn't reporting an already-fixed bug, and it logs `version=8.1.0-23657pre commit=9dafd4f863`.

1. Start Grafana with `date_formats.use_browser_locale` set to `true`: `$ docker run --rm -it -e GF_SECURITY_ADMIN_USER=admin -e GF_SECURITY_ADMIN_PASSWORD=bananas -e GF_DATE_FORMATS_USE_BROWSER_LOCALE=true -p 3000:3000 grafana/grafana:main`
2. Log in (`admin`/`bananas`)
3. Create any graph in any dashboard and view `This year` using a browser with any European locale, such as `en-GB`, `en-GB-oxendict`, or `nb_NO` (which is my other use case)

I haven't tested setting _only_ the undocumented option because I believe it's there by mistake and this reproduction shows that it's wrong.

**Anything else we need to know?**:

I believe this line is the source of the bug: https://github.com/grafana/grafana/blob/ef0fab9aa5f86460306ccf271c3f3a16c0e3b2a4/pkg/setting/date_formats.go#L50

**Environment**:
- Grafana version: `version=8.1.0-23657pre` (it also happens in 7.5.3)
- Data source type & version: Doesn't matter; I used `-- Grafana --`'s random walk query
- OS Grafana is installed on: Doesn't matter, but I've tested the default `grafana/grafana` Docker image, which at the time of writing runs `Alpine Linux 3.13.5`
- User OS & Browser: `Chrome on Mac OS X 10.15` using any European locale
- Grafana plugins: None, and it doesn't matter
- Others: N/A

**Comment by Elfo404** [comment]
Thanks for reporting this!

https://grafana.com/docs/grafana/latest/administration/configuration/#use_browser_locale describes the same configuration option, so I would say `date_format_use_browser_locale` just happens to work as a side effect of this bug.

**Comment by Elfo404** [comment]
looping in @grafana/grafana-frontend-platform even though this should probably only be fixed on the backend

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/36428

**Comment by theneva** [comment]
Awesome, thank you! I love this project :smile:

**Comment by dalestev** [comment]
I'm still experiencing this issue on v12, without a solution I can find.

**Comment by mckn** [comment]
> I'm still experiencing this issue on v12, without a solution I can find.

Can you please provide some context (config, version etc) so we can try to reproduce the issue?
