### ISSUE TITLE
Unified alerting: Fix folder creation dropdown on alert rule page

### ISSUE THREAD

**Issue by oanamangiurea** [grafana/grafana#34796]
On alert rule creation - Grafana managed alerts, folder dropdown should display "+ Add new folder" as we do for Namespaces and Groups for Prometheus alerts. It's confusing for the user to think they have no way of creating a new folder, just typing the name is not that obvious. 

<img width="517" alt="Screenshot 2021-05-27 at 12 02 55" src="https://user-images.githubusercontent.com/5183519/119798698-0d4e7a80-bee4-11eb-900f-f659f04109f0.png">
<img width="809" alt="Screenshot 2021-05-27 at 12 04 22" src="https://user-images.githubusercontent.com/5183519/119798706-0e7fa780-bee4-11eb-8938-34b7f29caa0c.png">
rea

**Comment by peterholmberg** [comment]
This is a more general fix for the select component, I 100% support that we need this. Just keep it in mind.

**Comment by jvies** [comment]
I can confirm the problem on a dockerized installation of version 8.3.3.
The container was initialized on an older version. No alert was never defined.
Now I try to configure an alert, but I can't create a folder for my new alert.

**Comment by darklow** [comment]
Spent 15min to figure where can I create folder. Very much needed update. Or as a quickest fix using CSS only by changing cursor type to "text" would make it more obvious that you can actually write in the dropdown.

**Comment by predkambrij** [comment]
I didn't figured it out until I read darklow's comment :)

**Comment by tamaszl** [comment]
> Spent 15min to figure where can I create folder. Very much needed update. Or as a quickest fix using CSS only by changing cursor type to "text" would make it more obvious that you can actually write in the dropdown.

so where can we create the folder?

**Comment by soniaAguilarPeiron** [comment]
We've just merged the fix, so you will be able to see the `+Add new ` option in the drop-down, even if you don't have any values.

**Comment by lars-str** [comment]
I started using Grafana today and also encountered this problem. This means that the problem unfortunately still exists in the [latest Docker release](https://hub.docker.com/layers/grafana/grafana/latest/images/sha256-9a11066127b9e8582a270505e9ffc7687ae95bf98358542ced46eac17640ef50?context=explore). Is there any news about when the problem will be fixed? Can we possibly create a folder via a workaround?

Thank you very much!

**Comment by tamaszl** [comment]
> I started using Grafana today and also encountered this problem. This means that the problem unfortunately still exists in the [latest Docker release](https://hub.docker.com/layers/grafana/grafana/latest/images/sha256-9a11066127b9e8582a270505e9ffc7687ae95bf98358542ced46eac17640ef50?context=explore). Is there any news about when the problem will be fixed? Can we possibly create a folder via a workaround?
> 
> Thank you very much!

I figured it out. You just type the new folder name.

**Comment by lars-str** [comment]
I just took another look at the [PR](https://github.com/grafana/grafana/pull/54687) and noticed that the fix was merged into the main branch. And if I see it correctly, the fix is not yet available in the latest branch. The latest branch still uses Grafana V9.1.6. Main is already on V9.2. I have now just switched to the main branch and it actually works perfectly.

Thank you very much :-)!

**Comment by soniaAguilarPeiron** [comment]
Exactly, the fix is not released yet. Thank you for your feedback! :)

**Comment by bloodberrys** [comment]
> > I started using Grafana today and also encountered this problem. This means that the problem unfortunately still exists in the [latest Docker release](https://hub.docker.com/layers/grafana/grafana/latest/images/sha256-9a11066127b9e8582a270505e9ffc7687ae95bf98358542ced46eac17640ef50?context=explore). Is there any news about when the problem will be fixed? Can we possibly create a folder via a workaround?
> > Thank you very much!
> 
> I figured it out. You just type the new folder name.

Yeah, Just figure it out, thanks for this comment. Just type the folder name on the field.

**Comment by fredleger** [comment]
@soniaAguilarPeiron shouldn't the issue stay open until released ?
for me this is the difference between issue and merge request. The latest is closed as soon merged, but the issue is not resolved until deployed to production or released (in the github meaning of release)
