### ISSUE TITLE
Markdown support for Slack Notifier text

### ISSUE THREAD

**Issue by kenzhemir** [grafana/grafana#35057]
**What would you like to be added**:
Markdown support for the Slack alerts. 
Basically I want to add `"mrkdwn_in": ["text"],` next to this line
https://github.com/grafana/grafana/blob/d2649821d14f10edd5e79b57068b77c7a6ca79e4/pkg/services/alerting/notifiers/slack.go#L290

More info here: [Slack docs for attachments](https://api.slack.com/reference/messaging/attachments)

**Why is this needed**:
I would like to add long link (with query parameters) to grafana alert notifications and I want to format it. But since Slack Notifier does not enable `mrkdwn` in the webhook for the attachment text, I can't do that.

Examples:
What I currently have in the slack alert:
<https://www.google.com/search?q=Alert!+The+enemy+has+taken+our+intelligence!&oq=Alert!+The+enemy+has+taken+our+intelligence!&aqs=chrome..69i57.390j0j1&sourceid=chrome&ie=UTF-8 | alert link>

What I want to have in the slack alert:
[alert link](https://www.google.com/search?q=Alert!+The+enemy+has+taken+our+intelligence!&oq=Alert!+The+enemy+has+taken+our+intelligence!&aqs=chrome..69i57.390j0j1&sourceid=chrome&ie=UTF-8)

**Comment by kenzhemir** [comment]
actually, I think it is fixed in here:
https://github.com/grafana/grafana/pull/32861

**Comment by mhoyer** [comment]
🤔 I am not sure how that #32861 would help to fix this issue. I still can't use markdown in my notification templates for Slack. Also the most recent commit (as of now) does not set this `"mrkdwn_in": ["text"]` option: https://github.com/grafana/grafana/blob/31ecbf7/pkg/services/alerting/notifiers/slack.go#L279

I think about creating a new issue on this topic.
