### ISSUE TITLE
Graph options missing when many variables are in use

### ISSUE THREAD

**Issue by adam-nielsen** [grafana/grafana#35407]
If a dashboard has many variables, the "Display" section for the "Graph" panel type disappears.  In this screenshot there is no "Display" section before the "Links" section.

![grafana-panel-missing_display](https://user-images.githubusercontent.com/278772/121329019-2af5f800-c958-11eb-8514-9ccfcef7e522.png)

If I look in the DOM, there is an empty `<div></div>` where this section should be:

![grafana-panel-empty_div](https://user-images.githubusercontent.com/278772/121329016-29c4cb00-c958-11eb-8be5-12172602b4d5.png)

The problem is when there are so many variables that the graph is not drawn when editing the panel:

![grafana-panel-many_vars](https://user-images.githubusercontent.com/278772/121330349-47466480-c959-11eb-895e-0729eab6fcce.png)

If variables are removed so the panel is visible, or you are lucky enough to have a high enough resolution screen that you can resize the query section to make it smaller, as soon as the graph appears, the "Display" section suddenly renders.

**What happened**:

"Display" section is missing.

**What you expected to happen**:

"Display" section should be visible.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a text box variable and duplicate it approx 15 times.
2. Add a panel of type "Graph", and edit it.
3. Confirm you cannot see the graph as the space where it should be is occupied by the variables, as shown in the screenshot above.  If you can see the graph, add more variables (or resize until it disappears).
4. Observe that the 'Display' section is not visible in the sidebar on the right, until you delete some variables.

**Environment**:
- Grafana version: v7.3.4 (14c494085e)
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: Linux Firefox, Windows Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
Unable to replicate i v8, I think this must be fixed in v7.5 as well 
![Screenshot from 2021-06-09 13-55-24](https://user-images.githubusercontent.com/10999/121349989-65e13700-c92a-11eb-9f46-28be1f99c1c7.png)

**Comment by adam-nielsen** [comment]
I just upgraded to v8 and can confirm the problem still exists.  In your above example the graph is still visible as you're using a high resolution screen.  You will need to add many more variables to obscure the graph, or alternatively, resize the browser window or the graph so that the graph itself becomes so small it disappears.  Then reload the page and you will see the options missing:
![screenshot](https://user-images.githubusercontent.com/278772/121443576-17d33e80-c9d1-11eb-9e2b-642ee8711e53.png)

**Comment by adam-nielsen** [comment]
@torkelo Can this be reopened or should I open a new bug for it?

**Comment by torkelo** [comment]
duplicate (same root issue), https://github.com/grafana/grafana/issues/27403
