### ISSUE TITLE
Plugin: Stat shows wrong names

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#35472]
**What happened**:
Plugin show not correctly name value.

If enable table view then show name correctly: testa, testb, testc
![image](https://user-images.githubusercontent.com/73607094/121469010-0a5f8980-c9bc-11eb-8571-851029821911.png)
If disable table view all data have the same name testc
![image](https://user-images.githubusercontent.com/73607094/121469057-1d725980-c9bc-11eb-91a6-d81dabaea190.png)

**How to reproduce it (as minimally and precisely as possible)**:
Please add plugin and put code as MS SQL

```
select 'testa' customer, 0 'value'
union ALL
select 'testb' customer, 0 'value'
union ALL
select 'testc' customer, 0 'value'
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: MS SQL code
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome
- Grafana plugins: Stat
- Others: n/a

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/35368 will be part of 8.0.1

**Comment by deejayluk** [comment]
I updated to 8.0.1 and Time Series still show wrong values

![image](https://user-images.githubusercontent.com/73607094/121893858-c0a9d280-cd1e-11eb-8821-91e3ab309284.png)
