### ISSUE TITLE
Grafana proxy queries timeout after 30s with dataproxy.timeout and dataproxy.keep_alive_seconds to > 30s

### ISSUE THREAD

**Issue by morvencao** [grafana/grafana#35505]
**What happened**:

Relevant to https://github.com/grafana/grafana/issues/27839
Long running queries to thanos are failed after 30 seconds with a `504 Gateway timeout` issue despite `dataproxy.timeout` and `dataproxy.keep_alive_seconds` set to `>30s` when run behind a network proxy.

```
[dataproxy]
timeout = 300
keep_alive_seconds = 300
logging = true
```

<img width="1292" alt="grafana-timeout" src="https://user-images.githubusercontent.com/5468682/121521435-a2925880-ca26-11eb-9b9c-d3d54ba81b4f.png">

**What you expected to happen**:

Expect that queries should not appear to time out in less time than has been configured in the `dataproxy.timeout` and `dataproxy.keep_alive_seconds` setting.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: **v7.4.2**
- Data source type & version: prometheus
- OS Grafana is installed on: kubernetes
- User OS & Browser: macOS & chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Duplicate of #34177

**Comment by marefr** [comment]
Fixed and included in Grafana v8.0.0.

**Comment by morvencao** [comment]
@marefr 
I gave it a try with latest grafana(grafana/grafana:latest) image, but still have the issue, although I updated the `timeout` `dialTimeout` and `keep_alive_seconds` in grafana configuration to `120` seconds:
```
$ kc get secret grafana-config -o jsonpath="{.data.grafana\.ini}" | base64 -d | grep -A 10 dataproxy
[dataproxy]
timeout = 120
dialTimeout = 120
keep_alive_seconds = 120
logging = true
[log]
level = debug
```

The request to datasource will still be canceled in 30 seconds from debug logs:

<img width="902" alt="grafana-timeout-latest" src="https://user-images.githubusercontent.com/5468682/121664211-d2e6ff00-cad9-11eb-8054-55c63b43ebe4.png">

/cc @dsotirakis

**Comment by dsotirakis** [comment]
Hello @morvencao, I tried to reproduce on both `main` and `v8` and couldn't replicate your issue - seems to be working fine for me, by only setting `timeout` (which I guess it's what you are seeking for in this case).

Are you sure that you are tweaking the right configs and/or fields? Do you tweak them inside `defaults.ini`?

**Comment by morvencao** [comment]
I then update the configuration to only set `timeout`:
```
$ kc get secret grafana-config -o jsonpath="{.data.grafana\.ini}" | base64 -d | grep -C 5 dataproxy
http_port = 3001
root_url = %(protocol)s://%(domain)s/grafana/
domain = localhost
[users]
viewers_can_edit = true
[dataproxy]
timeout = 120
```

Still getting the "Gateway timeout!" after 30 seconds.

> Do you tweak them inside `defaults.ini`?

I created my own configuration in file called `grafana.ini`, I can confirm grafana is using my updated `grafana.ini`? 
For `dataproxy` part, I only add `timeout` to `120`

**Comment by marefr** [comment]
@morvencao to me it looks like your Prometheus times out after ~30 seconds. Have you tried to configure query timeout 
![image](https://user-images.githubusercontent.com/1668778/121858594-12d6fd80-ccf7-11eb-8170-8f5727465682.png)

If that doesn't make any difference it could also be limitations in your network stack.

**Comment by morvencao** [comment]
@marefr Yes, I did set the `queryTimeout` to 60 seconds in datasource configuration, it's still getting the same error after about 30 seconds:
```
$ kc get secret/grafana-datasources -o jsonpath="{.data.datasources\.yaml}" | base64 -d | grep queryTime
  queryTimeout: 60s
```

**Comment by marefr** [comment]
@morvencao please try with Grafana v8.0.2. If still the same problem I would believe something in your network stack is closing the TCP connection after 30 seconds.

**Comment by Raboo** [comment]
@morvencao The datasources configuration page usually has a timeout field that when left blank defaults to 30s. You can try to modify the timeout there.

**Comment by ibarryyan** [comment]
I know
