### ISSUE TITLE
Alert list plugin bug

### ISSUE THREAD

**Issue by Mixajlo14** [grafana/grafana#36165]
**What happened**:
State of alerts in alert list doesn't refresh when there is set auto refresh on dashboard.
When I reload whole page in browser, correct state of alerts shows up.

**What you expected to happen**:
Correct state of alerts after auto refresh of the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
- Create alert on some graph, with alerting state
- Create dashboard with alert list, and set auto refresh on that dashboard
- Leave alert list open in one tab 
- Fix alert state on graph in another tab 
- Check alert state in alert list (Status will remain Alerting, even if state of that alert is Ok)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Alert list
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 10 Firefox
- Grafana plugins: Alert list
- Others:

**Comment by zuchka** [comment]
Hi @Mixajlo14 

Are you using the new unified alerting system, which is opt-in and requires setting the `ngalert` feature toggle? OR are you using the legacy alerting system?

**Comment by Mixajlo14** [comment]
Hi @zuchka , I am using the legacy alerting system, just upgrade to the new version and that stoped working properly.

**Comment by zuchka** [comment]
Hi @Mixajlo14 

sorry, can you clarify for me? (long day!)

Are you reporting that your issue is now resolved, after upgrading to Unified Alerting? Or did upgrading break your alerts?

**Comment by Mixajlo14** [comment]
@zuchka No sorry, I just wanted to say that we created that alerts in earlier versions of Grafana, and that this was working before this new version. Sorry for the missunderstanding.

**Comment by Mixajlo14** [comment]
Hi @zuchka , here is video example of this problem, at the end of the video you will see that state of Panel Title alert is changed on graph, but it is still the same in alert list.
https://user-images.githubusercontent.com/24840317/123636478-36349900-d81d-11eb-8705-ee1c2a99fd13.mp4

**Comment by LiamLage** [comment]
Hi, I'm new to github so please excuse my inexperience. I have the same issue as @Mixajlo14 in Grafana V8.0.1, how do I follow this issue to keep up with how to resolve it?

**Comment by davidmparrott** [comment]
@Mixajlo14 more clarifying questions! It looks like you're not using the new alerting system in your video. Can you confirm that, please? Because alerting rules are not inherently tied to dashboards and panels in Grafana 8 alerts, you can't even edit the rules in the dashboard UI anymore. Here's an example of what that edit menu looks like in the new UI:

![annotation_test_-_Grafana](https://user-images.githubusercontent.com/4461026/124836957-c15a1100-df38-11eb-99b1-a42db3296845.png)

**Comment by Mixajlo14** [comment]
Hi @davidmparrott, I can confirm that we are using old alerting system. If you think that we will solve this problem with migration to new one, we will try that in next few days?

**Comment by erikoffereins** [comment]
We have the same issue as topicstart.
Is the legacy way of alert list going to be replaced with the other one?
If the answer is yes, is there a timeline to see the progress? Because we are using Influx and that isn't available in the new way according to the documentation [https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/](url)

But now we have a alert list which is not refreshing. And that's pretty annoying :D

**Comment by BenCastricum** [comment]
Same here, after a docker deploy we inadvertently upgraded to grafana 8. Now the (old) alert panel doesn't refresh anymore.

**Comment by ray-magini** [comment]
We face the same problem

**Comment by mojitaleghani** [comment]
hi, I also face the same problem. I am using grafana since version 6 (i think the version number is wrong but i use grafana since two version before what is have already. now it is 8.1.0).
in the version 6 I created alert list panel and it was working properly. since next version, the graph was changed in state and shows me problem but the alert list panel was not refresh until i refresh the page (use F5 or other refresh tool on the browser) and then the alert list panel shows the correct state to me.

I can confirm that I am using the legacy alert list panel since i can not see another alert list panel in the plugins.

**Comment by EmilionDK** [comment]
I have the same problem. ( Grafana 8.1.3 )

**Comment by mojitaleghani** [comment]
seems no one from Grafana sees this topic! :(

**Comment by Bukran** [comment]
Same problem here, we updated from 7.4.0 to 8.1.5 and the alerts panel is not getting refreshed.

**Comment by CB-IT-Chris** [comment]
same problem with Grafana v8.2.2 and alert List. no automatic refresh

**Comment by naiame-neltheri** [comment]
Is this fixed? I'm using `grafana:10.0.3` and the plugin is not updating alert states
