### ISSUE TITLE
WSS 403 error starts with version 8.0.4

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#36822]
WSS 403 error starts with version 8.0.4

Grafana 8.0.4 on Windows Server 2019
Tested Browsers: Firefox and Chrome

<img width="1787" alt="grafik" src="https://user-images.githubusercontent.com/79257887/125867353-baf27433-6234-4df6-ae48-5a86df58e4cb.png">

**Comment by FZambia** [comment]
@UlrichThiess hello, could you please send a WARN server log line from Gragana server logs which contains `Request Origin is not authorized` message when WebSocket connection is going to be established?

The reason here is that we check Origin request header before allowing WebSocket connection to be established with Grafana. See [in docs](https://grafana.com/docs/grafana/latest/live/configure-grafana-live/#request-origin-check). So you should configure `root_url` in `[server]` section or add `allowed_origins` into `[lve]` section.

Also an ongoing pr: https://github.com/grafana/grafana/pull/36661

**Comment by UlrichThiess** [comment]
log
```
t=2021-07-16T06:32:26+0200 lvl=warn msg="Request Origin is not authorized" logger=live origin=https://www.zoomsoft.de appUrl=https://www.zoomsoft.de:443/grafana/ allowedOrigins=
```

custom.ini
```
[server]
protocol = https
http_port = 443
domain = www.zoomsoft.de
enforce_domain = true
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

defaults.ini
```
[live]
max_connections = 100
allowed_origins =
```

I thought `allowed_origins =` doesn't have to be set.

With version 8.0.3 there was no browser error message.

**Comment by FZambia** [comment]
So the quick solution for your setup should be:

```
[live]
max_connections = 100
allowed_origins = https://www.zoomsoft.de
```

But in general situation looks like a bug in our origin check: just opened https://github.com/grafana/grafana/pull/36834

**Comment by UlrichThiess** [comment]
Thanks. Now it's working

**Comment by FZambia** [comment]
Should be fixed in Grafana v8.1.0, many thanks for a report!

**Comment by UlrichThiess** [comment]
Yes it works now after removing the `allowed_origins` entry.

**Comment by bmorashad** [comment]
Still doesn't work for me without allowed_origins entry \_(-_-)_/, after updating to 8.1

**Comment by FZambia** [comment]
@bmorashad hi, your root_url contains `http` scheme while request comes from `https` – I believe this is a reason, so changing `protocol` to `https` should help.

**Comment by bmorashad** [comment]
Alright it has been the issue, Thanks :)
But in my case since we were using https via reverse proxy there is no ssl-certificate, so changing the protocol results in error... Hence changing the protocol variable to https in root_url fixed the issue

**Comment by bmorashad** [comment]
Well actually it results in reverse proxy error, so I settled with same config where I set allowed_origins which works as expected

**Comment by nathanle** [comment]
@bmorashad, would you mind confirming what you have in allowed_origins. I am having the same issues you had. Thanks so much!
