### ISSUE TITLE
Mysql Variable & repeat panel

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#36880]
I have a master table from where, based on the field value, I need to choose the wanted table to use within the panel and with the repeat option. Basically I need to dynamically change the table where execute the query and show the result using the repeat panel option.
- I create a first multi-value variable "Company" with a query like:
SELECT Company FROM server (which is used as dropdown selection)
- I create a second single-value variable "Site_tbl" based on the first one in order to dynamically select the table I need, with a query like:
SELECT Site FROM server WHERE Company  = ${Company}
- I tried without success to repeat panel for several Site. It doesn't work even just trying to show the table name as a simple filed, putting for example within the panel the simple query like: SELECT ${Site_tbl} (with whatever other variable option)
- It's strange that with a simple single-value variable like: SELECT ${Company} it works as expected. The problem arises when I try to use the first variable within second one 
It's a full week I'm working on it, trying all combination, option, workaround coming in mind, but nothing.

**What happened**:
It seems that the possible variable values are passed join together as a string, even if the multi-value option is disabled and they are correctly shown separate as "Preview of values"

**What you expected to happen**:
the variable is recalculated for each single possible value and processed within the repeat panel option

**How to reproduce it (as minimally and precisely as possible)**:
just create a simple table like
ID           | Site | Company
1            |AAAA| aaaaaaa
2           |BBBBB| bbbbbb
the variable as described, and try to use the repeat panel option in order to simply show AAAA in one panel and BBBB in another one

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.0.6
- Data source type & version:  phpMyAdmin 5.1.0
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 - Crhome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@kaydelaney I'm reviewing older issues that still need to be investigated. Can you tell me if you're still having this problem with a newer version of Grafana? There were some bugs with repeating panels that have been addressed 

Can you share screenshots of what the panels are doing versus what you expect them to do.

**Comment by codeincarnate** [comment]
@zoltanbedi is going to take a look and see if this is MySql specific or if it's something that's happening more broadly

**Comment by zoltanbedi** [comment]
@DonatoD thanks for opening this issue. I was able to replicate this issue in 8.0.6 however this is fixed in the latest grafana so I'm going to close this issue.

**Comment by DonatoD** [comment]
Hi, yes it's still happening but I think is something more related the way variables work. And for what I've seen, you cannot use multi-value variable in this way for repeat panel.
Anyway, thanks for the support
