### ISSUE TITLE
repomd.xml signature could not be verified for grafana

### ISSUE THREAD

**Issue by BenoitKnecht** [grafana/grafana#36935]
**What happened**:

Using the following repository:

```ini
[grafana]
baseurl = https://packages.grafana.com/oss/rpm
gpgcheck = 1
gpgkey = https://packages.grafana.com/gpg.key
name = grafana
repo_gpgcheck = 1
```

I'm getting

```
https://packages.grafana.com/oss/rpm/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for grafana
```

whenever I run `yum check-update`.

It looks like a CDN caching issue, because it works fine on other machines and seems to depend on which A records are returned for `packages.grafana.com`. For instance:

```console
$ curl --connect-to packages.grafana.com:443:199.232.194.217:443 https://packages.grafana.com/oss/rpm/repodata/repomd.xml.asc
-----BEGIN PGP SIGNATURE-----

wsBcBAEBCAAQBQJg8FfbCRCMjDTFJAmMtgAA6nwIALwxU5B6lsy6OctZG5NpdFLX
EPKffce9LvWec39k7lVCspVP9xP1coPw1tzRyhV3VmazrJTclT850540a7k63UEO
owIL9zcD46WY2iFisezjBAQb0phYUHbikMPC+LdaIp21HQANIc9egTlV7GdbzCv9
E2mmdI/uhjZpcF5Ue+Tm8d9Ys7NWrriXePPp+NBPewuOVyrV0AwYNzk4rQB01WM0
f4o0QsYMdgqWjZeLqBLbDNiggUQZYfbrSkiLuLkoT2N/VqkV1pDrdr/2+Zp77Apn
KJ2cQvD8fsGd9ZrOYf7m2kjJ7S4usOADKRfQwMl8zE/6MomzbSbUSJYS2gUakWA=
=4GGo
-----END PGP SIGNATURE-----
$ curl --connect-to packages.grafana.com:443:151.101.114.217:443 https://packages.grafana.com/oss/rpm/repodata/repomd.xml.asc
-----BEGIN PGP SIGNATURE-----

wsBcBAEBCAAQBQJg5uXBCRCMjDTFJAmMtgAAGlsIAHGh6ATC31vGRBT3/o8owPGK
ayRgW4/2Y4NjBJDVQQDgPJwefJe8w90L8WlB7uQMnjRrWMW1yQnjNEpMQhKjG9B6
aRMBJPMRVLJ9Waq/bHacV2XFEWJv8+EIBkQLymhkzx+aq53+5XbaxHy9nCXSq+Zh
vyhbDry1EvThGsU7r5FN0mUIod/XO11F+9u7QKS+/iyiOAvwjYU2FjjkBTg4o7MO
cxmWAYBkd3bEn9ptor3sXiSIuUq3t4CFYHoiJsSGvp7LUUOEeRrmstkI9+5uAczj
h5fkD1fmIOBmFDgVTT8Q90B9qjTP7Mz5J9oPcbSw3TdMYNlS/f69R62jFe9WErw=
=WGvj
-----END PGP SIGNATURE-----
```

Both `curl` commands are being run from the same machine, but they return different content for `repomd.xml.asc`.

**What you expected to happen**:

I expect the `repomd.xml` signature to be valid every time.

**How to reproduce it (as minimally and precisely as possible)**:

See the two `curl` commands above.

**Comment by BenoitKnecht** [comment]
Looks like the CDN issue is more widespread than just the RPM repository:  #36902, #36906.

**Comment by wbrowne** [comment]
This should be fixed by now so I will close this issue. If there's still reports of problems, please let us know and we can re-open. Thank you 😄

**Comment by mkjpryor** [comment]
I am still hitting this issue on newly deployed machines.

**Comment by mkjpryor** [comment]
Even after removing the GPG check, I still get errors which look like they are related to the same issue:

```
$ sudo yum update
grafana                                                                                                                                                                                                                                        897  B/s | 544  B     00:00    
Errors during downloading metadata for repository 'grafana':
  - Status code: 404 for https://packages.grafana.com/oss/rpm/repodata/bae9dd764624ecd656892f9732b9e28b98d0f255214e0b136e3e0c38931f2784-filelists.xml.gz (IP: 199.232.198.217)
  - Status code: 404 for https://packages.grafana.com/oss/rpm/repodata/f783127625cab65f884ee5796db9df82569482717d8bdb9dc86659f3a758736f-primary.xml.gz (IP: 199.232.198.217)
Error: Failed to download metadata for repo 'grafana': Yum repo downloading error: Downloading error(s): repodata/f783127625cab65f884ee5796db9df82569482717d8bdb9dc86659f3a758736f-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/bae9dd764624ecd656892f9732b9e28b98d0f255214e0b136e3e0c38931f2784-filelists.xml.gz - Cannot download, all mirrors were already tried without success
```

```
$ curl https://packages.grafana.com/oss/rpm/repodata/bae9dd764624ecd656892f9732b9e28b98d0f255214e0b136e3e0c38931f2784-filelists.xml.gz
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: grafana-repo/oss/rpm/repodata/bae9dd764624ecd656892f9732b9e28b98d0f255214e0b136e3e0c38931f2784-filelists.xml.gz</Details></Error>
```

**Comment by thebeanogamer** [comment]
Still running into this.
