### ISSUE TITLE
CDN Caching inconsistencies cause yum failures

### ISSUE THREAD

**Issue by jarretlavallee** [grafana/grafana#37274]
**What happened**:
Intermittently we see yum failures in downloading the metadata from packages.grafana.com. There is an issue with the CDN where we get different results depending on which server handles the request. 

`151.101.50.217` returns an out-of-date `repomd.xml` from `1626348337`
```
# curl --resolve 'packages.grafana.com:443:151.101.50.217' https://packages.grafana.com/oss/rpm/repodata/repomd.xml
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
  <revision>1626348337</revision>
```

`151.101.186.217` returns the current `repomd.xml` from `1626363867`
```
# curl --resolve 'packages.grafana.com:443:151.101.186.217' https://packages.grafana.com/oss/rpm/repodata/repomd.xml
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
  <revision>1626363867</revision>
```

The headers from the requests above show that the cache should already be invalid and should have been refreshed, but the issue persists. 

Nonworking server
```
# curl -I --resolve 'packages.grafana.com:443:151.101.50.217' https://packages.grafana.com/oss/rpm/repodata/repomd.xml
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 3097
Expires: Thu, 22 Jul 2021 13:08:06 GMT
Last-Modified: Thu, 15 Jul 2021 15:44:31 GMT
ETag: "207f99902bd98226a55fbfeea057cc67"
x-goog-generation: 1626348344750214
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 3097
x-goog-meta-goog-reserved-file-mtime: 1626348337
Content-Type: application/xml
x-goog-hash: crc32c=BJWVqg==
x-goog-hash: md5=IH+ZkCvZgialX7/uoFfMZw==
x-goog-storage-class: MULTI_REGIONAL
Server: UploadServer
Cache-Control: public, max-age=3600
Accept-Ranges: bytes
Date: Tue, 27 Jul 2021 16:41:07 GMT
Via: 1.1 varnish
Age: 1661
X-Served-By: cache-dfw18654-DFW
X-Cache: HIT
X-Cache-Hits: 3
X-Timer: S1627404067.063041,VS0,VE0
```

Working server
```
# curl -I --resolve 'packages.grafana.com:443:151.101.186.217' https://packages.grafana.com/oss/rpm/repodata/repomd.xml
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 3097
Expires: Thu, 22 Jul 2021 13:44:07 GMT
Cache-Control: public, max-age=3600
Last-Modified: Thu, 15 Jul 2021 15:44:31 GMT
ETag: "94ddd475547063860bdfdbeb5301943a"
x-goog-generation: 1626363871834973
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 3097
x-goog-meta-goog-reserved-file-mtime: 1626363867
Content-Type: application/xml
x-goog-hash: crc32c=8T2YEg==
x-goog-hash: md5=lN3UdVRwY4YL39vrUwGUOg==
x-goog-storage-class: MULTI_REGIONAL
Server: UploadServer
Accept-Ranges: bytes
Date: Tue, 27 Jul 2021 16:41:44 GMT
Via: 1.1 varnish
Age: 1825
X-Served-By: cache-mdw17334-MDW
X-Cache: HIT
X-Cache-Hits: 2
X-Timer: S1627404105.548132,VS0,VE0
```

This is likely related to the same underlying issue as #35273, #36935, and #36902. I have opened this issue as it is an issue with the rpm repos instead of the apt repos and the rpm ones are closed.

**What you expected to happen**:

All requests to `https://packages.grafana.com` should return current data.

**How to reproduce it (as minimally and precisely as possible)**:

Run `curl --resolve 'packages.grafana.com:443:151.101.50.217' https://packages.grafana.com/oss/rpm/repodata/repomd.xml` to get an out of date `repomd.xml`

**Comment by zuchka** [comment]
Hi @jarretlavallee 

Thanks for starting a new issue. The team is currently tackling the root issue with our CDN caching, which causes these intermittent errors

**Comment by si458** [comment]
not sure if it helps but this issue seems to of happened around 19/20th of July as our plesk servers started complaining and showing these errors with yum updates
```
Reason: 2021-07-20 01:36:25 INFO: pum is called with arguments: ['--list', '--repo-info', '--json']
2021-07-20 01:36:28 ERROR: failure: repodata/1bd6d997144be85b1615c3bbe900db24c836f77d9897fe71632442e24f9a1d76-primary.sqlite.bz2 from plesk-ext-grafana: [Errno 256] No more mirrors to try.
https://packages.grafana.com/oss/rpm/repodata/1bd6d997144be85b1615c3bbe900db24c836f77d9897fe71632442e24f9a1d76-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
2021-07-20 01:36:28 ERROR: Exited with returncode 1.
```

**Comment by mariodieck** [comment]
Beim Beheben eines Problems mit der Installation ist ein Fehler aufgetreten: Execution extension has failed with exit code 1, stdout: , stderr: [2021-07-31 20:02:44.026] 8864:61059044064e5 ERR [extension/grafana] Fixing the Grafana service failed: Execution package has failed with exit code 1, stdout: , stderr: ERROR:__main__:Command '['apt-get', '-qq', 'update', '--allow-releaseinfo-change']' returned non-zero exit status 100 stdout: stderr:E: Failed to fetch https://packages.grafana.com/oss/deb/dists/stable/main/binary-amd64/Packages.bz2 File has unexpected size (23789 != 23822). Mirror sync in progress? [IP: 151.101.242.217 443] Hashes of expected file: - Filesize:23822 [weak] - SHA512:5b6cd10741a28c89a2b26daf1273a3f4dfefd119590693be94e1fd20aa6e6507b25616b82d95091441989318d2beabf2f3dd7b5a3c1c9b2e4c5a843fb4419218 - SHA256:5d3f4da864e87839b07991508c0ca2f253b0c4f67e70cfe6b8ce9f5f9d301764 - SHA1:97365a8503847f9f33129f59d2a2af86c80f93c1 [weak] - MD5Sum:2a5bf5f98a045b84476d76fcc0cda658 [weak] Release file created at: Thu, 29 Jul 2021 10:11:04 +0000 E: Some index files failed to download. They have been ignored, or old ones used instead. Execution package has failed with exit code 1, stdout: , stderr: ERROR:__main__:Command '['apt-get', '-qq', 'update', '--allow-releaseinfo-change']' returned non-zero exit status 100 stdout: stderr:E: Failed to fetch https://packages.grafana.com/oss/deb/dists/stable/main/binary-amd64/Packages.bz2 File has unexpected size (23789 != 23822). Mirror sync in progress? [IP: 151.101.242.217 443] Hashes of expected file: - Filesize:23822 [weak] - SHA512:5b6cd10741a28c89a2b26daf1273a3f4dfefd119590693be94e1fd20aa6e6507b25616b82d95091441989318d2beabf2f3dd7b5a3c1c9b2e4c5a843fb4419218 - SHA256:5d3f4da864e87839b07991508c0ca2f253b0c4f67e70cfe6b8ce9f5f9d301764 - SHA1:97365a8503847f9f33129f59d2a2af86c80f93c1 [weak] - MD5Sum:2a5bf5f98a045b84476d76fcc0cda658 [weak] Release file created at: Thu, 29 Jul 2021 10:11:04 +0000 E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by wbrowne** [comment]
Is this issue still occurring for you @mariodieck?

**Comment by si458** [comment]
@wbrowne i think this issue has been fixed, our plesk servers havent complained for a few days now! 👍

**Comment by mariodieck** [comment]
> Is this issue still occurring for you @mariodieck?

yes it still occurs.  I had uninstalled it and then wanted to reinstall it, but that also fails now.

**Comment by wbrowne** [comment]
Great stuff. I'll close the issue in that case. Can re-open if more discussion is required! Thanks a lot 👍
