### ISSUE TITLE
Grafana fails to start on CentOS 7

### ISSUE THREAD

**Issue by igorhrq** [grafana/grafana#40583]
**What happened**:
Grafana daemon is not starting after upgrade to 8.2.1-1 still, was necessary rollback to 8.1.7-1 again

**What you expected to happen**:
after the upgrade the Unit cannot start and gives the error below:
` Process: 32656 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=rpm cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.plugins=${PLUGINS_DIR} cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR} (code=exited, status=1/FAILURE)
 Main PID: 32656 (code=exited, status=1/FAILURE)
`
**How to reproduce it (as minimally and precisely as possible)**:
yum update and wait to upgrade for the 8.2.1-1, after it grafana will back with status failed for unit grafana-server.service

**Anything else we need to know?**:
none

**Environment**:
- Grafana old version: 8.1.7-1 --> 8.2.1-1
- Data source type & version:
- OS Grafana is installed on: CentOS Linux release 7.9.2009 (Core)
- User OS & Browser: chrome
- Grafana plugins: zabbix 
- Others: none

**Comment by igorhrq** [comment]
An comment reference with logs:
https://github.com/grafana/grafana/issues/40162#issuecomment-945849438

**Comment by igorhrq** [comment]
any news here @kminehart  ? Sorry disturb

**Comment by kminehart** [comment]
As far as I can tell most systemd issues are resolved in 8.2.2, which I believe includes that PR.

**Comment by ducttapecoder-vt** [comment]
> As far as I can tell most systemd issues are resolved in 8.2.2, which I believe includes that PR.

I just went from 7.3.0 to 8.2.3 and ran into this issue. I'm getting a slew of 'Unknown lvalue' lines with `journalctl -u grafana-server`. I use 443 but have run the setcap command. Logs are not getting written to /var/log/grafana but were before running the setcap.

I performed the steps here: https://github.com/grafana/grafana/issues/40162#issuecomment-946909948

In /lib/systemd/system/grafana-server.service:
- 'PrivateUsers' from 'true' to 'false
- CapabilityBoundingSet=CAP_NET_BIND_SERVICE
- AmbientCapabilities=CAP_NET_BIND_SERVICE

reload systemctl daemon and restart service and voila.

**Comment by igorhrq** [comment]
Hello @kminehart  i am still having problems here to start after upgrade, i will attach the logs:

`t=2021-11-08T14:56:58-0300 lvl=info msg="[SQL] SELECT org_id, plugin_id, enabled, pinned, plugin_version\n\t\t\t\t\tFROM plugin_setting WHERE org_id=? []interface {}{5} - took: 32.408µs" logger=sqlstore.xorm
t=2021-11-08T14:57:06-0300 lvl=info msg="Shutdown started" logger=server reason="System signal: terminated"
t=2021-11-08T14:57:06-0300 lvl=info msg=Profiler logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource enabled=false
t=2021-11-08T14:57:07-0300 lvl=info msg=Profiler logger=plugins.backend pluginId=grafana-googlesheets-datasource enabled=false
t=2021-11-08T14:57:12-0300 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." logger=settings
t=2021-11-08T14:57:12-0300 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." logger=settings
t=2021-11-08T14:57:12-0300 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2021-11-08T14:57:12-0300 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2021-11-08T14:57:12-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2021-11-08T14:57:12-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2021-11-08T14:57:12-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2021-11-08T14:57:12-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2021-11-08T14:57:12-0300 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2021-11-08T14:57:12-0300 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2021-11-08T14:57:12-0300 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2021-11-08T14:57:12-0300 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2021-11-08T14:57:12-0300 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2021-11-08T14:57:12-0300 lvl=info msg="App mode production" logger=settings
t=2021-11-08T14:57:12-0300 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-11-08T14:57:12-0300 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
t=2021-11-08T14:57:12-0300 lvl=eror msg=ShowSQL logger=sqlstore.xorm show=show
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 2.219241ms" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 36.714µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 31.063µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 19.65µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 25.976µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 17.696µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="Starting DB migrations" logger=migrator
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 62.299µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 20.378µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=346 duration=1.713908ms
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table'" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="[SQL] SELECT COUNT(id) AS Count FROM `user` - took: 84.369µs" logger=sqlstore.xorm
t=2021-11-08T14:57:12-0300 lvl=info msg="Starting plugin search" logger=plugins
t=2021-11-08T14:57:12-0300 lvl=info msg="Registering plugin" logger=plugins id=input
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-triggers-panel
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=jether-html-panel pluginDir=/var/lib/grafana/plugins/grafana-html-panel-master/dist
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=jether-html-panel
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=worldping-endpoint-nav pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/panels/nav-panel
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=worldping-endpoint-nav
t=2021-11-08T14:57:13-0300 lvl=info msg=Profiler logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource enabled=false
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-datasource
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=blackmirror1-statusbygroup-panel pluginDir=/var/lib/grafana/plugins/blackmirror1-statusbygroup-panel/dist
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=blackmirror1-statusbygroup-panel
t=2021-11-08T14:57:13-0300 lvl=info msg=Profiler logger=plugins.backend pluginId=grafana-googlesheets-datasource enabled=false
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-googlesheets-datasource
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=worldping-cta pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/panels/call-to-action
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=worldping-cta
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=vonage-status-panel pluginDir=/var/lib/grafana/plugins/vonage-status-panel/dist
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=vonage-status-panel
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-app
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=worldping-endpoint-list pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/panels/endpoint-list
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=worldping-endpoint-list
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=ryantxu-ajax-panel pluginDir=/var/lib/grafana/plugins/ryantxu-ajax-panel/dist
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=ryantxu-ajax-panel
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=grafana-piechart-panel pluginDir=/var/lib/grafana/plugins/grafana-piechart-panel/dist
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-piechart-panel
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=grafana-simple-json-datasource pluginDir=/var/lib/grafana/plugins/grafana-simple-json-datasource/dist
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-simple-json-datasource
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=grafana-worldmap-panel pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/grafana-worldmap-panel
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-worldmap-panel
t=2021-11-08T14:57:13-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=raintank-worldping-app pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist
t=2021-11-08T14:57:13-0300 lvl=info msg="Registering plugin" logger=plugins id=raintank-worldping-app
t=2021-11-08T14:57:13-0300 lvl=info msg="Live Push Gateway initialization" logger=live.push_http
t=2021-11-08T14:57:13-0300 lvl=info msg="[SQL] SELECT org_id, plugin_id, enabled, pinned, plugin_version\n\t\t\t\t\tFROM plugin_setting  - took: 88.843µs" logger=sqlstore.xorm
t=2021-11-08T14:57:13-0300 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=14019
t=2021-11-08T14:57:13-0300 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
t=2021-11-08T14:57:13-0300 lvl=info msg="[SQL] \nSELECT role AS bitrole, active, COUNT(role) AS count FROM\n  (SELECT last_seen_at>? AS active, last_seen_at>? AS daily_active, SUM(role) AS role\n   FROM (SELECT\n      u.id,\n      CASE org_user.role\n        WHEN 'Admin' THEN 4\n        WHEN 'Editor' THEN 2\n        ELSE 1\n      END AS role,\n      u.last_seen_at\n    FROM `user` AS u INNER JOIN org_user ON org_user.user_id = u.id\n    GROUP BY u.id, u.last_seen_at, org_user.role) AS t2\n  GROUP BY id, last_seen_at) AS t1\nGROUP BY active, daily_active, role; []interface {}{time.Date(2021, time.October, 9, 14, 57, 13, 646481802, time.Local), time.Date(2021, time.November, 7, 14, 57, 13, 646481999, time.Local)} - took: 258.075µs" logger=sqlstore.xorm
t=2021-11-08T14:57:13-0300 lvl=info msg="[SQL] SELECT `id`, `operation_uid`, `last_execution`, `version` FROM `server_lock` WHERE (operation_uid = ?) []interface {}{\"cleanup expired auth tokens\"} - took: 35.581µs" logger=sqlstore.xorm
t=2021-11-08T14:57:13-0300 lvl=info msg="[SQL] SELECT `id`, `dashboard_id`, `name`, `external_id`, `check_sum`, `updated` FROM `dashboard_provisioning` - took: 4.815185ms" logger=sqlstore.xorm
t=2021-11-08T14:57:13-0300 lvl=info msg="[SQL] SELECT (SELECT COUNT(*) FROM `user`) AS users,(SELECT COUNT(*) FROM `org`) AS orgs,(SELECT COUNT(*) FROM `data_source`) AS datasources,(SELECT COUNT(*) FROM `star`) AS stars,(SELECT COUNT(*) FROM `playlist`) AS playlists,(SELECT COUNT(*) FROM `alert`) AS alerts,(SELECT COUNT(*) FROM `user` WHERE last_seen_at > ?) AS active_users,(SELECT COUNT(*) FROM `user` WHERE last_seen_at > ?) AS daily_active_users,(SELECT COUNT(id) FROM `dashboard` WHERE is_folder = ?) AS dashboards,(SELECT COUNT(id) FROM `dashboard` WHERE is_folder = ?) AS folders,(\n\t\tSELECT COUNT(acl.id)\n\t\tFROM `dashboard_acl` AS acl\n\t\t\tINNER JOIN `dashboard` AS d\n\t\t\tON d.id = acl.dashboard_id\n\t\tWHERE d.is_folder = ?\n\t) AS dashboard_permissions,(\n\t\tSELECT COUNT(acl.id)\n\t\tFROM `dashboard_acl` AS acl\n\t\t\tINNER JOIN `dashboard` AS d\n\t\t\tON d.id = acl.dashboard_id\n\t\tWHERE d.is_folder = ?\n\t) AS folder_permissions,(\n\t\tSELECT COUNT(*)\n\t\tFROM `dashboard_acl` AS acl\n\t\t\tINNER JOIN `dashboard` AS d\n\t\t\tON d.id = acl.dashboard_id\n\t\tWHERE acl.role = 'Viewer'\n\t\t\tAND d.is_folder = 0\n\t\t\tAND acl.permission = 2\n\t) AS dashboards_viewers_can_edit, (\n\t\tSELECT COUNT(*)\n\t\tFROM `dashboard_acl` AS acl\n\t\t\tINNER JOIN `dashboard` AS d\n\t\t\tON d.id = acl.dashboard_id\n\t\tWHERE acl.role = 'Viewer'\n\t\t\tAND d.is_folder = 0\n\t\t\tAND acl.permission = 4\n\t) AS dashboards_viewers_can_admin, (\n\t\tSELECT COUNT(*)\n\t\tFROM `dashboard_acl` AS acl\n\t\t\tINNER JOIN `dashboard` AS d\n\t\t\tON d.id = acl.dashboard_id\n\t\tWHERE acl.role = 'Viewer'\n\t\t\tAND d.is_folder = 1\n\t\t\tAND acl.permission = 2\n\t) AS folders_viewers_can_edit, (\n\t\tSELECT COUNT(*)\n\t\tFROM `dashboard_acl` AS acl\n\t\t\tINNER JOIN `dashboard` AS d\n\t\t\tON d.id = acl.dashboard_id\n\t\tWHERE acl.role = 'Viewer'\n\t\t\tAND d.is_folder = 1\n\t\t\tAND acl.permission = 4\n\t) AS folders_viewers_can_admin, (SELECT COUNT(id) FROM `dashboard_provisioning`) AS provisioned_dashboards,(SELECT COUNT(id) FROM `dashboard_snapshot`) AS snapshots,(SELECT COUNT(id) FROM `dashboard_version`) AS dashboard_versions,(SELECT COUNT(id) FROM `annotation`) AS annotations,(SELECT COUNT(id) FROM `team`) AS teams,(SELECT COUNT(id) FROM `user_auth_token`) AS auth_tokens,(SELECT COUNT(id) FROM `alert_rule`) AS alert_rules,(SELECT COUNT(id) FROM `library_element` WHERE kind = ?) AS library_panels,(SELECT COUNT(id) FROM `library_element` WHERE kind = ?) AS library_variables,12 AS admins, 39 AS editors, 60 AS viewers, 6 AS active_admins, 11 AS active_editors, 7 AS active_viewers, 0 AS daily_active_admins, 0 AS daily_active_editors, 0 AS daily_active_viewers []interface {}{time.Date(2021, time.October, 9, 14, 57, 13, 646431309, time.Local), time.Date(2021, time.November, 7, 14, 57, 13, 646432709, time.Local), \"0\", \"1\", \"0\", \"1\", 1, 2} - took: 6.401543ms" logger=sqlstore.xorm
t=2021-11-08T14:57:13-0300 lvl=info msg="HTTP Server Listen" logger=http.server address=MYIP:3000 protocol=https subUrl= socket=
t=2021-11-08T14:57:13-0300 lvl=eror msg="Stopped background service *api.HTTPServer" logger=server reason="open /home/grafana/certs/cert.pem: permission denied"
t=2021-11-08T14:57:13-0300 lvl=info msg="[SQL] SELECT COUNT(*) AS count, type FROM `data_source` GROUP BY type - took: 33.215µs" logger=sqlstore.xorm
t=2021-11-08T14:57:13-0300 lvl=info msg="[SQL] SELECT `id`, `org_id`, `namespace`, `key`, `value`, `created`, `updated` FROM `kv_store` WHERE `org_id`=? AND `namespace`=? AND `key`=? LIMIT 1 []interface {}{0, \"infra.usagestats\", \"last_sent\"} - took: 2.035µs" logger=sqlstore.xorm
t=2021-11-08T14:57:13-0300 lvl=eror msg="Failed to get last sent time" logger=infra.usagestats error="context canceled"
t=2021-11-08T14:57:13-0300 lvl=eror msg="Server shutdown" logger=server error="*api.HTTPServer run error: open /home/grafana/certs/cert.pem: permission denied"
t=2021-11-08T14:57:14-0300 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." logger=settings
t=2021-11-08T14:57:14-0300 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." logger=settings
t=2021-11-08T14:57:14-0300 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2021-11-08T14:57:14-0300 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2021-11-08T14:57:14-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2021-11-08T14:57:14-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2021-11-08T14:57:14-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2021-11-08T14:57:14-0300 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2021-11-08T14:57:14-0300 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2021-11-08T14:57:14-0300 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2021-11-08T14:57:14-0300 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2021-11-08T14:57:14-0300 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2021-11-08T14:57:14-0300 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2021-11-08T14:57:14-0300 lvl=info msg="App mode production" logger=settings
t=2021-11-08T14:57:14-0300 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-11-08T14:57:14-0300 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
t=2021-11-08T14:57:14-0300 lvl=eror msg=ShowSQL logger=sqlstore.xorm show=show
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 1.664025ms" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 24.19µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 25.763µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 21.747µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 26.982µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 19.194µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="Starting DB migrations" logger=migrator
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table' and name = ? []interface {}{\"migration_log\"} - took: 30.326µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT `id`, `migration_id`, `sql`, `success`, `error`, `timestamp` FROM `migration_log` - took: 26.197µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=346 duration=1.955532ms
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT name FROM sqlite_master WHERE type='table'" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT COUNT(id) AS Count FROM `user` - took: 57.227µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="Starting plugin search" logger=plugins
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=input
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=worldping-endpoint-nav pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/panels/nav-panel
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=worldping-endpoint-nav
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=ryantxu-ajax-panel pluginDir=/var/lib/grafana/plugins/ryantxu-ajax-panel/dist
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=ryantxu-ajax-panel
t=2021-11-08T14:57:14-0300 lvl=info msg=Profiler logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource enabled=false
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-datasource
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=grafana-worldmap-panel pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/grafana-worldmap-panel
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-worldmap-panel
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=worldping-cta pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/panels/call-to-action
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=worldping-cta
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=worldping-endpoint-list pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist/panels/endpoint-list
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=worldping-endpoint-list
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=vonage-status-panel pluginDir=/var/lib/grafana/plugins/vonage-status-panel/dist
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=vonage-status-panel
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=jether-html-panel pluginDir=/var/lib/grafana/plugins/grafana-html-panel-master/dist
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=jether-html-panel
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=grafana-piechart-panel pluginDir=/var/lib/grafana/plugins/grafana-piechart-panel/dist
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-piechart-panel
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=grafana-simple-json-datasource pluginDir=/var/lib/grafana/plugins/grafana-simple-json-datasource/dist
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-simple-json-datasource
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=raintank-worldping-app pluginDir=/var/lib/grafana/plugins/raintank-worldping-app/dist
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=raintank-worldping-app
t=2021-11-08T14:57:14-0300 lvl=warn msg="Running an unsigned plugin" logger=plugins pluginID=blackmirror1-statusbygroup-panel pluginDir=/var/lib/grafana/plugins/blackmirror1-statusbygroup-panel/dist
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=blackmirror1-statusbygroup-panel
t=2021-11-08T14:57:14-0300 lvl=info msg=Profiler logger=plugins.backend pluginId=grafana-googlesheets-datasource enabled=false
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-googlesheets-datasource
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-triggers-panel
t=2021-11-08T14:57:14-0300 lvl=info msg="Registering plugin" logger=plugins id=alexanderzobnin-zabbix-app
t=2021-11-08T14:57:14-0300 lvl=info msg="Live Push Gateway initialization" logger=live.push_http
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT org_id, plugin_id, enabled, pinned, plugin_version\n\t\t\t\t\tFROM plugin_setting  - took: 100.456µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=14049
t=2021-11-08T14:57:14-0300 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT `id`, `dashboard_id`, `name`, `external_id`, `check_sum`, `updated` FROM `dashboard_provisioning` - took: 1.31788ms" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="HTTP Server Listen" logger=http.server address=162.241.203.2:3000 protocol=https subUrl= socket=
t=2021-11-08T14:57:14-0300 lvl=eror msg="Stopped background service *api.HTTPServer" logger=server reason="open /home/grafana/certs/cert.pem: permission denied"
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] SELECT `id`, `operation_uid`, `last_execution`, `version` FROM `server_lock` WHERE (operation_uid = ?) []interface {}{\"cleanup expired auth tokens\"} - took: 1.526µs" logger=sqlstore.xorm
t=2021-11-08T14:57:14-0300 lvl=info msg="[SQL] \nSELECT role AS bitrole, active, COUNT(role) AS count FROM\n  (SELECT last_seen_at>? AS active, last_seen_at>? AS daily_active, SUM(role) AS role\n   FROM (SELECT\n      u.id,\n     `

as you can see, the server received some errors of permissions, i dont know if this is the main cause, so i come here to ask, for example:
`t=2021-11-08T14:57:13-0300 lvl=eror msg="Stopped background service *api.HTTPServer" logger=server reason="open /home/grafana/certs/cert.pem: permission denied"
`

This can be the main reason of the error? Just an fix permissions for it?

**Comment by igorhrq** [comment]
Also, i have set cert.pem to grafana user, but it didnt work:
`
drwxr-xr-x 2 root    root      80 Nov 25  2020 .
drwxr-xr-x 3 root    root      19 Out  2  2019 ..
-rw-r--r-- 1 grafana grafana 6184 Nov 25  2020 cert.pem
-rw-r--r-- 1 grafana grafana 1704 Nov 25  2020 key.pem
`

permissions:
`
[root@vps-grafana home]# namei -m grafana/certs/
f: grafana/certs/
 drwxr-xr-x grafana
 drwxr-xr-x certs
`

**Comment by kminehart** [comment]
No the reason you'd likely see that error is because it's in a `/home` directory. It is not recommended to use `/home` as a home directory for application users (like `grafana`).

You can override this setting by using

```
systemctl edit grafana-server
```

and placing this setting in there, ensuring that the `[Service]` header is there.

```
[Service]
ProtectHome=false
```

**Comment by igorhrq** [comment]
Hello, i was removed that line and it was worked, before i saw your comment i have added it to false and reload. Everything is fine now.

**Comment by kminehart** [comment]
I'd super highly recommend not removing the line in the systemd file as it will be overwritten if a new change is added to it in the future causing your installation to break in the same way again.

Instead, you should use the override file I described above.

**Comment by igorhrq** [comment]
@kminehart ya buddy, i was followed your advice, right now the var is there with false value. Thanks for the advice for not remove. :D
