### ISSUE TITLE
Clock drift in Grafana managed alerts

### ISSUE THREAD

**Issue by Yogu** [grafana/grafana#43031]
**What happened**:

I created a Grafana managed alert. It seems to work fine in all the preview panels, even in "Query results" on the "View rule" page. However, to evaluate the rule in the background, Grafana seems to use a different clock time than the system clock. This is evident in two ways:

- Alerts (like Slack webhooks) trigger delayed by a specific time offset
- The "Created" timestamp if the "Matching instances" in the view rule page is delayed by the same offset, for all states (Normal, Pending, Firing).

Other places where Grafana logs timestamps (e.g. the dashboard history) use the correct clock time. Running the "date" command in the grafana container yields the correct date.

The first time, we noticed this issue on Grafana 8.2.1 (with a delay of ~5h 30min). Then, we updated to 8.3.1, which temporarily fixed the problem. After the weekend, we now again have a drift (delay) of around 15 minutes.

**What you expected to happen**:

The alerts should use the regular system clock and not have a clock drift.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure. For our Grafana instance, just leave Grafana running for a few days and then create an alert.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.1 (b9eacd93e9); go1.14
- Data source type & version: happens with elasticsearch and for prometheus
- OS Grafana is installed on: 4.19.0-16-amd64 # 1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: piechart-panel
- Others: podman 3.0.1

**Comment by gerobinson** [comment]
Would it be possible to add a screenshot of some alert instances with incorrect timestamps? It sounds like the first issue could be related to the `group_wait` time in Alertmanager which has a default value of 30 seconds, but that would not have affected the created timestamps in the Matching instances.

I would like to better understand what the expected timestamps were and then see how the actual timestamps differ.

**Comment by gerobinson** [comment]
Would it be possible to add a screenshot of some alert instances with incorrect timestamps? It sounds like the first issue could be related to the group_wait time in Alertmanager which has a default value of 30 seconds, but that would not have affected the created timestamps in the Matching instances.

I would like to better understand what the expected timestamps were and then see how the actual timestamps differ.

**Comment by Yogu** [comment]
Thank you for your reply!

Here is a dummy alert I just created which just checks if there are any logs, so it should constantly fire. I just created it, now it's 2022-01-10T15:41:00UTC+01:00. The "Created" timestamp is a cropped UTC string (found that out by looking at the source), so the clock is currently running behind by 2 hours and 15 minutes. That's definitely not group wait time or something similar (those are at the defaults). The drift also is accumulating progressively when the server runs for a few days or weeks.

![image](https://user-images.githubusercontent.com/395810/148784212-5e4fc1a4-b6c5-41ad-b19b-18e9b42a8652.png)

Does that help?

**Comment by gerobinson** [comment]
Hi,

Thanks for the screenshot! Would it be possible to check if the date and time on the server that is running Grafana is correct? I just ask because the times that we see in the query results (`15:39:20`, `15:39:25`, etc) are the Unix timestamps for each metric value in Prometheus, where as the `Created` timestamp for the alert instance is the time that the scheduler in Grafana scheduled an evaluation of the alert rule.

**Comment by Yogu** [comment]
Yes, the clock on the system is correct. Other Grafana components see the correct date and time, e.g. if I save a dashboard and look into the versions, the "date" column shows the correct date.

It's pretty strange.

When I browsed through the Grafana source, I noticed that the whole alerting code uses the package `github.com/benbjohnson/`, which supports mocking the date/time. I didn't spot anything suspicious, but maybe that's somehow related?

**Comment by gerobinson** [comment]
Thanks for checking this! What is the evaluation interval for this rule (i.e. how often is it evaluated), and are the queries for this rule are fast or quite slow? What can happen sometimes is that if the alert rule takes longer to evaluate than its interval then the scheduler can fall behind as experienced here.

**Comment by Yogu** [comment]
> What is the evaluation interval for this rule (i.e. how often is it evaluated)

That one I set to 10s, then I added another one with 60s. The timestamps for those both are wong by the same amount.

> and are the queries for this rule are fast or quite slow? 

The queries in question are fast (milliseconds). There are sometimes slow queries, probably even for alerts, but that should not lead to permanent clock drift, right? :D

>  What can happen sometimes is that if the alert rule takes longer to evaluate than its interval then the scheduler can fall behind as experienced here.

It does not really look like it falls behind. I create a new alert rule, it is executed properly, goes to "pending" and then "firing" just fine, but immediately has those wrong timestamps. This also is global for all alerts. Only restarting the server fixes it for all of them, until they are skewed again after a few days.

**Comment by gerobinson** [comment]
> The queries in question are fast (milliseconds). There are sometimes slow queries, probably even for alerts, but that should not lead to permanent clock drift, right? :D

Thanks for checking! If an alert rule takes longer to evaluate than its interval (i.e. it takes 15 seconds to evaluate an alert rule, but the alert rule is scheduled to run at a 10 second interval) then it can result in inconsistent and even late timestamps, but I don't think this is what's happening here.

> It does not really look like it falls behind. I create a new alert rule, it is executed properly, goes to "pending" and then "firing" just fine, but immediately has those wrong timestamps. This also is global for all alerts. Only restarting the server fixes it for all of them

Is this restarting Grafana server or restarting the actual server?

**Comment by Yogu** [comment]
We run Grafana within a podman container, so we can't restart only Grafana but always the whole container including Grafana. Don't know if this makes a difference.

The last restart actually was a Grafana update, and we (most probably) only restarted the Grafana container, not the server.

We just restarted Grafana again (and definitely not the server) to test it, and that also reset the clock drift.

**Comment by gerobinson** [comment]
I am quite interested to know if the scheduler ticker starts to fall behind real time. This is the code in the scheduler that receives the timestamp of the next tick [`Line 359`](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/schedule/schedule.go#L359) which is a `time.Time`. I think logging both the timestamp in the tick and the current time will help us understand what is happening here, something like:

```
sch.log.Log("current time is", time.Now(), "tick is", tick)
```

**Comment by gerobinson** [comment]
I am quite interested to know if the scheduler ticker starts to fall behind real time. This is the code in the scheduler that receives the timestamp of the next tick Line 359 which is a time.Time. I think logging both the timestamp in the tick and the current time will help us understand what is happening here, something like:

```
sch.log.Debug("current time is", time.Now(), "tick is", tick)
```

**Comment by gerobinson** [comment]
I am quite interested to know if the scheduler ticker starts to fall behind real time. This is the code in the scheduler that receives the timestamp of the next tick Line 359 which is a time.Time. I think logging both the timestamp in the tick and the current time will help us understand what is happening here, something like:

```
sch.log.Debug("tick is", tick)
````

**Comment by gerobinson** [comment]
I am quite interested to know if the scheduler ticker starts to fall behind real time. This is the code in the scheduler that receives the timestamp of the next tick [`Line 359`](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/schedule/schedule.go#L359) which is a `time.Time`. I think logging both the timestamp in the tick and the current time will help us understand what is happening here, something like:

```
sch.log.Debug("scheduler tick", "current_time", time.Now(), "tick", tick)
```

**Comment by Yogu** [comment]
Ok, we deployed a test installation with this change and get the log messages. I'll get back to you in a few days then.

**Comment by Yogu** [comment]
We already got some clock drift

```
DBUG[01-18|09:39:00] scheduler tick                           logger=ngalert current_time=2022-01-18T09:39:00+0000 tick=2022-01-18T09:39:00+0000
DBUG[01-18|09:39:10] scheduler tick                           logger=ngalert current_time=2022-01-18T09:39:10+0000 tick=2022-01-18T09:39:10+0000
DBUG[01-18|09:39:20] scheduler tick                           logger=ngalert current_time=2022-01-18T09:39:20+0000 tick=2022-01-18T09:39:20+0000
DBUG[01-18|09:39:30] scheduler tick                           logger=ngalert current_time=2022-01-18T09:39:30+0000 tick=2022-01-18T09:39:30+0000
DBUG[01-18|09:39:40] scheduler tick                           logger=ngalert current_time=2022-01-18T09:39:40+0000 tick=2022-01-18T09:39:40+0000
DBUG[01-18|09:39:50] scheduler tick                           logger=ngalert current_time=2022-01-18T09:39:50+0000 tick=2022-01-18T09:39:50+0000
DBUG[01-18|09:40:00] scheduler tick                           logger=ngalert current_time=2022-01-18T09:40:00+0000 tick=2022-01-18T09:40:00+0000
DBUG[01-18|09:40:10] scheduler tick                           logger=ngalert current_time=2022-01-18T09:40:10+0000 tick=2022-01-18T09:40:10+0000
DBUG[01-18|09:40:20] scheduler tick                           logger=ngalert current_time=2022-01-18T09:40:20+0000 tick=2022-01-18T09:40:20+0000
DBUG[01-18|09:40:30] scheduler tick                           logger=ngalert current_time=2022-01-18T09:40:30+0000 tick=2022-01-18T09:40:30+0000
DBUG[01-18|09:40:40] scheduler tick                           logger=ngalert current_time=2022-01-18T09:40:40+0000 tick=2022-01-18T09:40:40+0000
DBUG[01-18|09:40:50] scheduler tick                           logger=ngalert current_time=2022-01-18T09:40:50+0000 tick=2022-01-18T09:40:50+0000
DBUG[01-18|09:41:00] scheduler tick                           logger=ngalert current_time=2022-01-18T09:41:00+0000 tick=2022-01-18T09:41:00+0000
DBUG[01-18|09:41:10] scheduler tick                           logger=ngalert current_time=2022-01-18T09:41:10+0000 tick=2022-01-18T09:41:10+0000
DBUG[01-18|09:41:20] scheduler tick                           logger=ngalert current_time=2022-01-18T09:41:20+0000 tick=2022-01-18T09:41:20+0000
DBUG[01-18|09:41:30] scheduler tick                           logger=ngalert current_time=2022-01-18T09:41:30+0000 tick=2022-01-18T09:41:30+0000
DBUG[01-18|09:41:40] scheduler tick                           logger=ngalert current_time=2022-01-18T09:41:40+0000 tick=2022-01-18T09:41:40+0000
DBUG[01-18|09:41:51] scheduler tick                           logger=ngalert current_time=2022-01-18T09:41:51+0000 tick=2022-01-18T09:41:50+0000
DBUG[01-18|09:42:01] scheduler tick                           logger=ngalert current_time=2022-01-18T09:42:01+0000 tick=2022-01-18T09:42:00+0000
DBUG[01-18|09:42:11] scheduler tick                           logger=ngalert current_time=2022-01-18T09:42:11+0000 tick=2022-01-18T09:42:10+0000
DBUG[01-18|09:42:21] scheduler tick                           logger=ngalert current_time=2022-01-18T09:42:21+0000 tick=2022-01-18T09:42:20+0000

….

DBUG[01-18|12:31:37] scheduler tick                           logger=ngalert current_time=2022-01-18T12:31:37+0000 tick=2022-01-18T12:31:10+0000
DBUG[01-18|12:31:47] scheduler tick                           logger=ngalert current_time=2022-01-18T12:31:47+0000 tick=2022-01-18T12:31:20+0000
DBUG[01-18|12:31:57] scheduler tick                           logger=ngalert current_time=2022-01-18T12:31:57+0000 tick=2022-01-18T12:31:30+0000
DBUG[01-18|12:32:07] scheduler tick                           logger=ngalert current_time=2022-01-18T12:32:07+0000 tick=2022-01-18T12:31:40+0000
```

**Comment by gerobinson** [comment]
Hi @Yogu, this is interesting! What do the logs show 24 hours later?

**Comment by Yogu** [comment]
Here are some recent log entries:

```
DBUG[01-19|14:37:35] scheduler tick logger=ngalert current_time=2022-01-19T14:37:35+0000 tick=2022-01-19T14:33:00+0000
DBUG[01-19|14:37:45] scheduler tick logger=ngalert current_time=2022-01-19T14:37:45+0000 tick=2022-01-19T14:33:10+0000
DBUG[01-19|14:37:55] scheduler tick logger=ngalert current_time=2022-01-19T14:37:55+0000 tick=2022-01-19T14:33:20+0000
DBUG[01-19|14:38:05] scheduler tick logger=ngalert current_time=2022-01-19T14:38:05+0000 tick=2022-01-19T14:33:30+0000
DBUG[01-19|14:38:15] scheduler tick logger=ngalert current_time=2022-01-19T14:38:15+0000 tick=2022-01-19T14:33:40+0000
DBUG[01-19|14:38:25] scheduler tick logger=ngalert current_time=2022-01-19T14:38:25+0000 tick=2022-01-19T14:33:50+0000
DBUG[01-19|14:38:35] scheduler tick logger=ngalert current_time=2022-01-19T14:38:35+0000 tick=2022-01-19T14:34:00+0000
DBUG[01-19|14:38:45] scheduler tick logger=ngalert current_time=2022-01-19T14:38:45+0000 tick=2022-01-19T14:34:10+0000
```

**Comment by gerobinson** [comment]
I think what is happening here is that the scheduler is taking on average more than ~10 seconds to run (which is the tick interval) such that over time the scheduler cannot keep up with the rate of ticks and starts to fall behind. The question is what is taking 10 seconds? It could be [`Line 365`](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/schedule/schedule.go#L365). Would it be possible to add a log line before it and then we can look at the time taken to get the alert rules from the database?

**Comment by gerobinson** [comment]
I think what is happening here is that the scheduler is taking on average more than ~10 seconds to run (which is the tick interval) such that over time the scheduler cannot keep up with the rate of ticks and starts to fall behind. The question is what is taking 10 seconds? It could be [`Line 365`](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/schedule/schedule.go#L365). Would it be possible to add a log line before it and then we can look at the time taken to get the alert rules from the database?

**Comment by Yogu** [comment]
> The question is what is taking 10 seconds?

Hm that's a question. My first question would be why the scheduler's clock falls behind if it takes longer to exist instead of just skipping ticks or performing the ticks late, but with the correct timestamp. Does Grafana really keep track of the time by adding 10 seconds to a timestamp each tick? In my opinion, that's bound to cause problems, e.g. if a single tick takes longer than expected (which could happen for any number of reasons) or even if the system clock is changed. Would it be possible to change the logic so that the ticks determine the real clock time?

> It could be Line 365. Would it be possible to add a log line before it and then we can look at the time taken to get the alert rules from the database?

Wouldn't we need a log line before and after it, and maybe at other places that could take longer than 10s?

**Comment by gerobinson** [comment]
> Does Grafana really keep track of the time by adding 10 seconds to a timestamp each tick?

Yes! I'm not sure what the justification for doing this is though. I also think we should drop ticks for slow receivers (i.e. use `time.Ticker`) but I am working to understand if there is some other reason that we do not use it.

> Wouldn't we need a log line before and after it, and maybe at other places that could take longer than 10s?

There is a log line after it, so we just need one before it too!

```
364: alertRules := sch.fetchAllDetails(disabledOrgs)
365: sch.log.Debug("alert rules fetched", "count", len(alertRules), "disabled_orgs", disabledOrgs)
```

You are welcome to add as much logging as required, but from what I understand of this code there isn't much else in that function that could take a long time. If we find that it's not `Line 364` then we can add logs elsewhere?

**Comment by gerobinson** [comment]
Hi @Yogu, having discussed this with the team we want to first add some metrics (https://github.com/grafana/grafana/pull/44602) to the scheduler to better understand this issue before deciding on a fix.

**Comment by gerobinson** [comment]
Hi @Yogu, I've just merged it so please feel welcome to build the `v8.3.x` branch or wait for the next 8.3.x release!

**Comment by Yogu** [comment]
Hi, we built the 8.3.x branch (0ac23b0446), and I re-added the log line:

```
diff --git a/pkg/services/ngalert/schedule/schedule.go b/pkg/services/ngalert/schedule/schedule.go
index 4f57cd0982..18b94e80e8 100644
--- a/pkg/services/ngalert/schedule/schedule.go
+++ b/pkg/services/ngalert/schedule/schedule.go
@@ -324,6 +324,7 @@ func (sch *schedule) schedulePeriodic(ctx context.Context) error {
        for {
                select {
                case tick := <-sch.heartbeat.C:
+                       sch.log.Debug("scheduler tick", "current_time", time.Now(), "tick", tick)
                        start := time.Now()
                        sch.metrics.BehindSeconds.Set(start.Sub(tick).Seconds())
```

The log still suggests a lagging scheduler clock:

```
DBUG[02-11|14:05:09] scheduler tick logger=ngalert current_time=2022-02-11T14:05:09+0000 tick=2022-02-11T13:56:48+0000
DBUG[02-11|14:05:18] scheduler tick logger=ngalert current_time=2022-02-11T14:05:18+0000 tick=2022-02-11T13:56:58+0000
```

but the metrics look fine:

```
# HELP grafana_alerting_scheduler_behind_seconds The total number of seconds the scheduler is behind.
# TYPE grafana_alerting_scheduler_behind_seconds gauge
grafana_alerting_scheduler_behind_seconds 0.000588845

# HELP grafana_alerting_get_alert_rules_duration_seconds The time taken to get all alert rules.
# TYPE grafana_alerting_get_alert_rules_duration_seconds histogram
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="0.1"} 19191
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="0.25"} 19191
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="0.5"} 19191
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="1"} 19191
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="2"} 19191
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="5"} 19191
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="10"} 19191
grafana_alerting_get_alert_rules_duration_seconds_bucket{le="+Inf"} 19191
grafana_alerting_get_alert_rules_duration_seconds_sum 9.149743971000012
grafana_alerting_get_alert_rules_duration_seconds_count 19191

# HELP grafana_alerting_schedule_periodic_duration_seconds The time taken to run the scheduler.
# TYPE grafana_alerting_schedule_periodic_duration_seconds histogram
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="0.1"} 19191
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="0.25"} 19191
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="0.5"} 19191
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="1"} 19191
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="2"} 19191
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="5"} 19191
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="10"} 19191
grafana_alerting_schedule_periodic_duration_seconds_bucket{le="+Inf"} 19191
grafana_alerting_schedule_periodic_duration_seconds_sum 10.446386867000061
grafana_alerting_schedule_periodic_duration_seconds_count 19191
```

I especially wonder why the metric `grafana_alerting_scheduler_behind_seconds ` suggests there is no time lag, while the log output shows a ~8 minutes difference. From looking at the code, I don't see any difference in how the values are calculated. Can you think of a reason why they would differ?

**Comment by grobinson-grafana** [comment]
Hi @Yogu, I found a small bug in how we calculate the value for this metric! This should be released in 8.4.3.

**Comment by grobinson-grafana** [comment]
Hi @Yogu, I found a bug in how we calculate the value for this metric. This should be fixed in 8.4.3!

**Comment by Yogu** [comment]
Thanks for fixing the bug. Is there a specific reason you closed this issue? The problem is not solved by introducing metrics, it just helps to investigate further.

In the meantime, we have identified a problem with a NTP server that reported inaccurate times. With Grafana 8.4.3, we could litereally watch the metric grafana_alerting_scheduler_behind_seconds count up. When we switched to a more accurate NTP server, the metric stopped growing at that pace.

We will further monitor the metric and see how it develops now.

However, I would still argue strongly that this bug should be fixed, even if normally does not occur, or at least is not that noticable as it was for us. Both the code and the behavior suggest to me that Grafana does not handle changing clocks in an eventually-consistent way. If the clock has been wrong at some point and is corrected afterwards, the alert scheduler will forever use a wrong clock. That's not a behavior one would expect from a monitoring application.

**Comment by grobinson-grafana** [comment]
Hi @Yogu,

Apologies for the confusion here! GitHub will close an issue when there are no more open pull requests referencing the issue. It wasn't closed because we consider the issue fixed!

You make an interesting observation about what should happen when the system synchronizes with an NTP server, causing the system clock to either move back or forward in time. The current ticker ignores such synchronizations as the time of the initial tick, upon which all subsequent ticks are derived, is taken when Grafana starts. If the ticker uses the current time for each tick it is possible to have missing ticks, something which the current ticker avoids. That said, other rulers such as Cortex use the current time and accept missing ticks.

I intend to raise this issue with the team this week!

**Comment by Yogu** [comment]
Ah I think I now understand the reason for the tick behavior better. I usually use a much larger time range in the logs then the evaluation interval (e.g. check if there have been error logs within the last 10 minutes, and do this check every minute). Then, missing ticks would not be that big of a deal. But if you want to be sure that nothing is missed even if you don't have a margin of error like this, I see that missing ticks would be a concern, and it gets more complicated than just using the real clock time.

Some ideas (assuming a tick interval of 1 minute):
- Schedule a tick for a specific time (e.g. if it's currently 23:59:31, use 0:00 as next tick time).
- At the beginning of the tick, look at the system clock again.
- Did we miss a tick? Execute the missed tick before continuing. (Do this for up to n missed ticks, e.g. for 10 ticks).
- Did we miss so much tickets that we don't want to execute them? Skip those ticks, but log a warning.
- Are we too early for the next tick, by a small margin (< tick interval)? Reschedule the tick, and don't continue.
- So we're on time for the current tick. Execute the tick.
- Store the tick as the "last executed tick"
- Schedule the next tick (would be 0:01)

I probably missed some cases and I have no idea about the code base or about other requirements, so forgive me that, but I think that could be an approach for a system that does not miss ticks (unless you skip so much time that you actually would *want* to skip ticks), and still executes all ticks exactly on time when possible.

**Comment by yuri-tceretian** [comment]
The implementation of the ticker https://github.com/grafana/grafana/blob/main/pkg/services/alerting/ticker.go#L44-L46
does use the current time to determine whether to wait or put the tick to the channel. Ticker does not miss ticks. 
For example, if the ticker is on hold waiting for the current tick X to be consumed, and the current time changes, then as long as the tick is consumed it will calculate `diff = Now - (X + interval)`. If `diff` is non-negative, then it will put the next tick to the channel. Therefore, the ticker will be catching up if it is falling behind the current time. 
The ticker will start catching up in two cases: clock advance, and slow client (scheduler). In the case of the slow scheduler, there can be many reasons: slow database responses, an enormous number of alert rules (like 100k), and a slow CPU.
