### ISSUE TITLE
Adhoc filters cannot reference a data source variable

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#43472]
**What happened**:

We have dashboards with a single data source and an ad hoc filter variable. The data source is picked using a single valued data source variable.

This used to work fine until 8.3. Since 8.3, ad hoc filters must point to a specific data sources. However, the drop down doesn't allow me to select the variable. 

**What you expected to happen**:

Data source drop down should allow me to select a data source variable. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a new dashboard.

Create a data source variable

![image](https://user-images.githubusercontent.com/1764725/147126897-6c0fd43b-0a6d-4a9b-bede-4efde5f2eff0.png)

Create ah ad hoc filter

![image](https://user-images.githubusercontent.com/1764725/147126985-c4ab2370-a607-45b1-b9da-c0d4801cb328.png)

Observe you cannot pick `$ds` from the drop down.
 
**Anything else we need to know?**:

While this might sound like a feature request, I think it's a regression. What used to be possible with 8.2 is no longer possible with 8.3 and I don't think this request conflict with the requirement of ad hoc filters having to be tied to a specific data source. 

Also dashboard migration from 8.2 to 8.3 seems broken. ad hoc filters just disappeared from dashboards and I had to re-add the variable. I can fill another issue if that is useful.  

**Environment**:

- Grafana version: 8.3.3
- Data source type & version: Elasticsearch (but should apply to any data source)
- User OS & Browser: Firefix 94
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
> I can fill another issue if that is useful.

please do! it is super helpful for us to break out every problem into its own issue.

**Comment by parnigot** [comment]
> Since 8.3, ad hoc filters must point to a specific data sources

Do you have any link to documentation on this?

I'm also impacted by this issue since upgrading from 8.1 to 8.3.
In the old version I had ~30 dashboards with a Datasource variable `$ds` (with values like `ds prod`, `ds dev`, ...) and an Adhoc filter that pointed to the `$ds` variable. Since I've upgraded to 8.3 all the Ad hoc filters disappeared from the dashboards and I can't no longer re-create them, like stated in the issue I no longer can select the `$ds` variable from the drop down menu.

**Comment by cykl** [comment]
> Do you have any link to documentation on this?

No. I can remember reading this was a deliberate choice to support mixed data sources but I'm unable to find relevant issue / PR right now.

**Comment by hugohaggmark** [comment]
Should be solved by https://github.com/grafana/grafana/pull/43263 that will be released in 8.3.4

**Comment by parnigot** [comment]
Noob question (kinda new on the release process here): is the issue #43263 included in nightly builds?
I've just tried with a fresh install of `grafana-8.4.0-47248pre` and the issue is still there.

**Comment by hugohaggmark** [comment]
> Noob question (kinda new on the release process here): is #43263 included in nightly builds? I've just tried with a fresh install of `grafana-8.4.0-47248pre` and the issue is still there.

Sorry my bad, #43263 fixes the issue with migrating adhoc variables in dashboards from older versions to newer. @grafana/user-essentials we need to look into why we `$ds` doesn't appear in the list of viable data sources.

**Comment by hugohaggmark** [comment]
@parnigot @cykl opened a fix for this here #43881, will hopefully make it into the 8.3.4 release.
