### ISSUE TITLE
$__rate_interval problem breaks Node Exporter Full, second most popular dashboard

### ISSUE THREAD

**Issue by 2-5** [grafana/grafana#44381]
**What happened**:
The very popular Node Exporter Full dashboard was broken by a recent Grafana upgrade (last month)
https://grafana.com/grafana/dashboards/1860

**How to reproduce it (as minimally and precisely as possible)**:
Import the 1860 dashboard and you'll see errors

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: Prometheus 2.15.2
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10, Chrome

![1](https://user-images.githubusercontent.com/3753822/150796557-5166c4b3-487d-4a36-8038-5f47579be0f6.png)
![2](https://user-images.githubusercontent.com/3753822/150796574-e95ce042-ca8a-47a1-bcc3-78ebf5398cba.png)

**Comment by 2-5** [comment]
https://github.com/rfrail3/grafana-dashboards/issues/95

**Comment by gabor** [comment]
@2-5 a `rate_interval` issue was identified in https://github.com/grafana/grafana/issues/44251, this issue is fixed in Prometheus-2.22.0 or later, could you try updating prometheus and checking if it helps?

**Comment by JacobWarners** [comment]
Hi gabor,

I'm using the newest version of arm : 
[prometheus-2.33.1.linux-armv7.tar.gz](https://github.com/prometheus/prometheus/releases/download/v2.33.1/prometheus-2.33.1.linux-armv7.tar.gz)

And still have the issue. Let me know if you need any more information!

**Comment by gabor** [comment]
hi @JacobWarners , thanks for the info. too bad that does not fix it. this might be the same issue as https://github.com/grafana/grafana/issues/43002

**Comment by 2-5** [comment]
Fixed by upgrading to latest Prometheus.

**Comment by Nikhils09** [comment]
Hi @gabor, I'm using Prometheus 2.38.0, still getting this rate_interval issue

**Comment by gabor** [comment]
hi @Nikhils09 , thanks for the info, pinging @grafana/observability-metrics .

**Comment by gtk-grafana** [comment]
@Nikhils09 I'm unable to reproduce this when importing that dashboard into grafana 9.3.x with a prometheus 2.38 datasource, everything is working fine for me. What version of Grafana are you running?

**Comment by Nikhils09** [comment]
Hi, I'm using Grafana version 8.1.2, could that be a issue with Grafana version?

**Comment by Nikhils09** [comment]
Could the error be a result of the Grafana version?

**Comment by gtk-grafana** [comment]
@Nikhils09  It's possible, are you able to reproduce this issue with a recent version of Grafana?

**Comment by gtk-grafana** [comment]
That [dashboard](https://grafana.com/grafana/dashboards/1860-node-exporter-full/) says it requires Grafana 9.2.3 or higher, so I would guess that this dashboard won't work with your version of Grafana. You might be able to modify that dashboard to work with an older version of Grafana, or find a dashboard that supports your current version of Grafana.

**Comment by Nikhils09** [comment]
It appears there is a problem with the $__rate_interval as it is not functioning properly and consistently returns a value of 60 seconds. Not sure if it works with version 8.1.2.

**Comment by gtk-grafana** [comment]
Yeah, you might be able to get that working by removing the $__rate_interval function in that dashboard, but you might find it easier to find a public dashboard that supports your version of Grafana

**Comment by Nikhils09** [comment]
Is there any other variable that can work instead of rate_interval?
