### ISSUE TITLE
Unable to create alert query for a Azure Monitor metric dimension

### ISSUE THREAD

**Issue by cheekp** [grafana/grafana#44918]
**What happened**:
Testing unified alerting on 8.4.0-beta1

Alerting -> Alert Rules -> New Alert 

Rule type: Grafana managed alert
Create query on Azure Monitoring datasource with metric service and attempt to add a dimension to the query:

<img width="642" alt="Screenshot 2022-02-04 at 14 16 19" src="https://user-images.githubusercontent.com/39499749/152544565-e8e889fe-323d-4fcd-90f4-1c7a40197ffa.png">

Error:
`{"message":"Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: request failed, status: 400 Received invalid query parameter: [$filter, +eq+%27%2A%27],[aggregation, Average],[api-version, 2018-01-01],[interval, PT1M],[metricnames, IncomingMessages],[metricnamespace, Microsoft.EventHub%2Fnamespaces],[timespan, 2022-02-04T13%3A01%3A55Z%2F2022-02-04T14%3A01%3A55Z],[top, ], TraceId: {d5a67685-0fc4-4972-bc14-f437a9109399} for request: subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.EventHub/namespaces/xxxx/provider"}`

Alert can be saved but is left in error state.
<img width="671" alt="Screenshot 2022-02-04 at 14 22 10" src="https://user-images.githubusercontent.com/39499749/152545018-59b690c5-0bf0-4889-b212-5a25ef39ef08.png">

**What you expected to happen**:
Alert queries on azure metric dimension predicates should not fail evaluation. Dashboard panels with the equivalent query function correctly.

**How to reproduce it (as minimally and precisely as possible)**:
It appears this can be reproduced when adding a dimension query against any azure resource. I found the same problem on Event Hubs Namespaces and Service Bus Namespaces, against various metrics.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.0-beta1
- Data source type & version: Builtin Azure Monitor data source, 0.3.0
- OS Grafana is installed on: ubuntu 
- User OS & Browser: MacOS 11.6, Edge 95.0.1020.30 
- Grafana plugins: Builtin Azure Monitor data source, 0.3.0
- Others:

**Comment by yaelleC** [comment]
Hi @cheekp , thanks for raising the issue!

I have not been able to repro this issue consistently, could you check one thing for me: 
if you create the alert from the query made in a dashboard panel do you still see the same error?

_I mean by using this button:_
![Screenshot 2022-02-07 at 15 30 33](https://user-images.githubusercontent.com/42030685/152834163-f02160b3-ef8c-41ad-9a9e-45206a412bde.png)

**Comment by yaelleC** [comment]
After investigation , I seem to be able to reproduce in some cases but the alerts work in some others:

1. If I make a dashboard and create the alert from it -> it works fine
2. If I make a dashboard with no dimensions, create an alert from it and add the dimension in alert page -> it works fine
3. If I create the alert from the alert page -> I see the error described in this issue and the error state for the alert

![Screenshot 2022-02-08 at 10 53 06](https://user-images.githubusercontent.com/42030685/152962624-0ecef58e-c5e4-4314-b48d-3ab59f5c832a.png)

**Comment by cheekp** [comment]
I get the same. It's a problem when creating the alert rule directly (Alerting -> Alert Rules -> New Alert). If it's created from a dashboard it persists and functions correctly. Once the alert rule is created via dashboard, it's available in the list of  alert rules, you can query the source etc. However, if you then attempt to modify the dimension attributes on the query it errors as before.  At least there is a partial workaround and seems to be UI related, thanks @yaelleC!

**Comment by yaelleC** [comment]
It looks like it could have more to do with the `alert` page than the `azure` datasource, I'll move this issue to the alert team, let see if they can pin point the cause of the issue 😃

**Comment by jstaffans** [comment]
I experience the same issue on 8.3.5.

**Comment by andresmgot** [comment]
Hi, this was fixed in https://github.com/grafana/grafana/pull/47010 and released in 8.4.5. Please let us know if you still find the issue using that version!

**Comment by Chandra2614** [comment]
I am still facing this issue, Azure monitor works fine but not working in Azure managed grafana alerts
