### ISSUE TITLE
[Bug] load plugins error

### ISSUE THREAD

**Issue by majj** [grafana/grafana#4524]
grafana 3.0.0 beta
CentOS 5.11

[root@site bin]# ./grafana-cli plugins install grafana-simple-json-datasource
installing grafana-simple-json-datasource @ 1.0.0
from url: https://grafana.net/api/plugins/grafana-simple-json-datasource/versions/1.0.0/download
into: /var/lib/grafana/plugins

✔ Installed grafana-simple-json-datasource successfully

Restart grafana after installing plugins . <service grafana-server restart>

after restart grafana-server:

Plugin Error
Error: XHR error (404 Not Found) loading http://...site.io/monitor/public/app/plugins/datasource/grafana-simple-json-datasource/module.js?bust=1459496168101 Error loading http://...site.io/monitor/public/app/plugins/datasource/grafana-simple-json-datasource/module.js

2016/04/01 16:27:12 [I] Database: sqlite3
2016/04/01 16:27:12 [I] Migrator: Starting DB migration
2016/04/01 16:27:12 [I] Plugins: Scan starting
2016/04/01 16:27:12 [I] Listen: http://0.0.0.0:3000/monitor

It's seemed grafana--server can't find the plugins and didn't adding route.

**Comment by torkelo** [comment]
how are you starting grafana-server ?

**Comment by majj** [comment]
cd /opt/grafana-3.0.0b/bin

nohup ./grafana-server  &

defaults.ini:

# Directory where grafana will automatically scan and look for plugins
#
plugins = /opt/grafana-3.0.0b/public/plugins

**Comment by torkelo** [comment]
Ok, move the plugin intl your custom plugin dir and it should work. As you saw whe you ran the grafana-cli command it put the plugin in the default plugins dir /var/lib/grafana/plugins

**Comment by majj** [comment]
I run grafana-cli properly with --pluginsDir, but it works well on Windows, not CentOS.

**Comment by jessetan** [comment]
@majj Is the plugin actually installed in your plugin directory? Might be a permissions error on installation, see #4562.

**Comment by majj** [comment]
@jessetan  installation is ok

**Comment by majorcorn** [comment]
@majj Did you ever solve this?  I am having the same issue with a kairosDB plugin.

**Comment by meng-tian** [comment]
Encountered very similar error here, anyone managed to solve this issue?

**Comment by daniellee** [comment]
@meng-tian what error are you getting exactly? Are you also using a custom directory for your plugins?

**Comment by meng-tian** [comment]
Hi @daniellee , I installed plugin through Docker environment variables:
```
docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,vonage-status-panel" grafana/grafana
```
clock and simple json plugin both work fine. It's only the status panel plugin not working. When I trying to add a status panel in dashboard, it complains:
```
Plugin Error
Fetch error: 404 Not Found Instantiating
http://127.0.0.1:3000/public/app/plugins/panel/graph/legend Loading
http://127.0.0.1:3000/public/plugins/vonage-status-panel/stauts_ctrl.js Loading
plugins/voage-status-panel/model
```

**Comment by meng-tian** [comment]
Thanks @daniellee , using the stable version of Grafana image works 👍

**Comment by pmoranga** [comment]
Hi @meng-tian,
I still see the issue on latest (4.6.1) and master (5b38c23). On 4.5.2 it works as confirmed by @daniellee.

**Comment by daniellee** [comment]
@meng-tian @pmoranga a new version of the vonage status panel plugin has been published so this should work now on 4.6.1.

**Comment by mrcaron** [comment]
I'm running grafana 4.6.2 and still see the bug in version 1.0.7 of the plugin.

**Comment by daniellee** [comment]
@mrcaron just tested on the 4.6.2 docker image:

`docker run -d -p 3000:3000 -e "GF_INSTALL_PLUGINS=vonage-status-panel" --name=grafana  grafana/grafana:4.6.2`

and it seems to work. Are you sure you are getting the same error ("Fetch error: 404 Not Found Instantiating")?

**Comment by meng-tian** [comment]
@daniellee Thanks for the update.
