### ISSUE TITLE
Cannot run grafana with mysql configured as group replication cluster

### ISSUE THREAD

**Issue by yasharne** [grafana/grafana#45639]
**What happened**:
I have a MySQL cluster with group replication, when I start the grafana with the `primary` MySQL server as the backend, I get the below error:
```
logger=migrator t=2022-02-19T15:05:09.95+0000 lvl=eror msg="Executing migration failed" id="copy alert_rule_tag v1 to v2" error="Error 3098: The table does not comply with the requirements by an external plugin."
logger=migrator t=2022-02-19T15:05:09.95+0000 lvl=eror msg="Exec failed" error="Error 3098: The table does not comply with the requirements by an external plugin." sql="INSERT INTO `alert_rule_tag` (`alert_id`\n, `tag_id`) SELECT `alert_id`\n, `tag_id` FROM `alert_rule_tag_v1`"
Failed to start grafana. error: migration failed (id = copy alert_rule_tag v1 to v2): Error 3098: The table does not comply with the requirements by an external plugin.
migration failed (id = copy alert_rule_tag v1 to v2): Error 3098: The table does not comply with the requirements by an external plugin.
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create MySQL group replication
2. use the cluster as grafana backend

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.1-ubuntu
- Data source type & version:
- OS Grafana is installed on: kubernetes
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @yasharne 

> ....id="copy alert_rule_tag v1 to v2"...

looks like your server is trying to migrate legacy alerting rules into the newer unified alerting `v2` platform. Is this a brand new grafana instance? Or were you running an earlier version of Grafana and upgrading to `8.4.1` caused this? If your db has old alerting rules, is there a way where you can test if your backend setup works with a fresh Grafana instance?

I would just like to pin this specifically to an alerting migration issue if possible. thanks! 👍

**Comment by zuchka** [comment]
Also, if this is an existing setup, the following chart can help understand how various alerting configurations in the Grafana ini can interact with eachother:

https://github.com/grafana/grafana/pull/42200#issue-1062269188

**Comment by yasharne** [comment]
Hi @zuchka it was a brand new installation without any previous databases

**Comment by yuri-tceretian** [comment]
@armandgrillet this seems to be an important enough to warrant a fix for 9.0 (i.e. asap)

**Comment by jodrell2000** [comment]
FYI, there's a 2nd 'migration' query from an empty install that causes the same error (I skipped the first by manually adding a row to the migration_log table)
`INSERT INTO `annotation_tag` (`annotation_id`\n, `tag_id`) SELECT `annotation_id`\n, `tag_id` FROM `annotation_tag_v2``

**Comment by JokerDevops** [comment]
Hi, this problem doesn't seem to be fixed in version 9.0, because I still have this problem after using version 9.3.2. Although I solved this problem by manually adjusting the database table field index, it should automatically adapt to MySQL MGR Cluster

**Comment by grobinson-grafana** [comment]
Hi @JokerDevops, can you share what you changed to the index to fix the issue? Any additional information would help us understand the issue better and might help other users fix the issue too! Thank you!

**Comment by armandgrillet** [comment]
The issue mentions `alert_rule_tag` but is a Grafana migration issue that does not specifically relate to Alerting, labeled it for the Grafana backend team.

**Comment by mygrsun** [comment]
> 

I find that table 'alert_rule_tag_v1 ' have not a primary key.mysql mgr must have a primary key.

**Comment by JokerDevops** [comment]
> 

```sql

alter table alert_rule_tag_v1
    add constraint alert_rule_tag_v1_pk
        primary key (tag_id, alert_id);
```

**Comment by JokerDevops** [comment]
```sql
alter table annotation_tag_v2
    add constraint annotation_tag_v2_pk
        primary key (tag_id, annotation_id);
```

**Comment by JokerDevops** [comment]
Add primary keys to the alert_rule_tag_v1 and annotation_tag_v2 temporary tables.

**Comment by iivanov9** [comment]
Very annoying bug. Got this on fresh install in docker with our MySQL cluster.
[JokerDevops](https://github.com/JokerDevops) Thank you for a quick fix!

**Comment by JokerDevops** [comment]
So the issue is already fixed? In which version was it fixed?
@tolzhabayev

**Comment by scottsananderson** [comment]
Any news regarding this issue ?

**Comment by Veidit** [comment]
This is still a problem with Grafana 10.4.2, thanks to @JokerDevops I got this working.

**Comment by jammiemil** [comment]
Having the same issue with a fresh V11.1.3 instance.

To work around it i first had to add PK to alert_rule_tag_v1

```
alter table alert_rule_tag_v1
add constraint alert_tag_v1_pk
primary key (tag_id, alert_id);
```

Then let the pod run forwards till it hit the same issue for annotation_tag_v2 so i created the pk for that also:

```
alter table annotation_tag_v2
add constraint annotation_tag_v2_pk
primary key (tag_id, annotation_id);
```

After which it was able to complete the 'Migration'

**Comment by W1zzardTPU** [comment]
> Having the same issue with a fresh V11.1.3 instance.
> 
> To work around it i first had to add PK to alert_rule_tag_v1
> 
> ```
> alter table alert_rule_tag_v1
> add constraint alert_tag_v1_pk
> primary key (tag_id, alert_id);
> ```
> 
> Then let the pod run forwards till it hit the same issue for annotation_tag_v2 so i created the pk for that also:
> 
> ```
> alter table annotation_tag_v2
> add constraint annotation_tag_v2_pk
> primary key (tag_id, annotation_id);
> ```
> 
> After which it was able to complete the 'Migration'

Same issue, thanks for the fix. I wonder why this is taking so long to solve

**Comment by utdrmac** [comment]
You can fix this on the MySQL side, by using the automatic primary key feature. Execute this on all GR member nodes:

`SET PERSIST sql_generate_invisible_primary_key=1;`

Now, when you create a table, if there is no Primary Key (a GR requirement), one will automatically be created, and it will be marked invisible.

**Comment by JokerDevops** [comment]
Is this PR the solution to this problem? I don't think he did the merger?  https://github.com/grafana/grafana/pull/81724

**Comment by chenyw11** [comment]
> **What happened**: I have a MySQL cluster with group replication, when I start the grafana with the `primary` MySQL server as the backend, I get the below error:
> 
> ```
> logger=migrator t=2022-02-19T15:05:09.95+0000 lvl=eror msg="Executing migration failed" id="copy alert_rule_tag v1 to v2" error="Error 3098: The table does not comply with the requirements by an external plugin."
> logger=migrator t=2022-02-19T15:05:09.95+0000 lvl=eror msg="Exec failed" error="Error 3098: The table does not comply with the requirements by an external plugin." sql="INSERT INTO `alert_rule_tag` (`alert_id`\n, `tag_id`) SELECT `alert_id`\n, `tag_id` FROM `alert_rule_tag_v1`"
> Failed to start grafana. error: migration failed (id = copy alert_rule_tag v1 to v2): Error 3098: The table does not comply with the requirements by an external plugin.
> migration failed (id = copy alert_rule_tag v1 to v2): Error 3098: The table does not comply with the requirements by an external plugin.
> ```
> 
> **What you expected to happen**:
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Create MySQL group replication
> 2. use the cluster as grafana backend
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Grafana version: 8.4.1-ubuntu
> * Data source type & version:
> * OS Grafana is installed on: kubernetes
> * User OS & Browser:
> * Grafana plugins:
> * Others:

I have the same problem in v10.4.8. Is there have a new version to reslove this problem now? I shoundn't execute the command `SET PERSIST sql_generate_invisible_primary_key=1;` everytime when I install a brand new grafana instance.

**Comment by dstathis** [comment]
Running in to this issue as well. Are there any plans to get this working?

**Comment by utdrmac** [comment]
@dstathis did you try the invisible PK trick above?

**Comment by dstathis** [comment]
@utdrmac

Unfortunately no, when I set that I see this instead:

```
2025-10-21T15:37:24.384Z [grafana] logger=migrator t=2025-10-21T15:37:24.384030695Z level=info msg="Executing migration" id="add primary key to seed_assigment"
2025-10-21T15:37:24.384Z [grafana] logger=migrator t=2025-10-21T15:37:24.384496136Z level=error msg="Executing migration failed" id="add primary key to seed_assigment" error="Error 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key" duration=464.52µs
2025-10-21T15:37:24.384Z [grafana] logger=migrator t=2025-10-21T15:37:24.3845299Z level=error msg="Exec failed" error="Error 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key" sql="code migration"
2025-10-21T15:37:24.399Z [grafana] logger=migrator t=2025-10-21T15:37:24.39960098Z level=info msg="Unlocking database"
2025-10-21T15:37:24.400Z [grafana] Error: ✗ migration failed (id = add primary key to seed_assigment): Error 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key
2025-10-21T15:37:24.407Z [pebble] Service "grafana" stopped unexpectedly with code 1
```
