### ISSUE TITLE
Unable to install plugins when running in docker

### ISSUE THREAD

**Issue by xo4n** [grafana/grafana#4569]
Running 
```
docker run -d -p 3000:3000 --name=grafana --volumes-from grafana-storage grafana/grafana:master
```
will set plugins directory to data/plugins instead of /var/lib/grafana/plugins and will fail to install any plugin 

```
2016/04/05 15:13:20 [I] Version: 3.0.0-beta2, Commit: v3.0-beta2+6-g676e950, Build date: 2016-04-05 13:37:09 +0000 UTC
2016/04/05 15:13:20 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana
  plugins: data/plugins

2016/04/05 15:13:20 [I] Database: sqlite3
2016/04/05 15:13:20 [I] Migrator: Starting DB migration
2016/04/05 15:13:20 [I] Plugins: Scan starting
2016/04/05 15:13:20 [W] Plugins: Plugin dir data/plugins does not exist
2016/04/05 15:13:20 [W] Plugins: Failed to create plugin dir: data/plugins, error: mkdir data: permission denied
2016/04/05 15:13:20 [I] Listen: http://0.0.0.0:3000
´´´

**Comment by torkelo** [comment]
thanks for reporting this, will fix.

**Comment by bergquist** [comment]
This should be fixed by https://github.com/grafana/grafana-docker/commit/256b449171924510e46f68ff486ad86da252c3e7

A little bit confusing that we use gosu for starting grafana in docker instead of starting it as a service and get the package configuration. But it should be working now! :)

**Comment by infinitydon** [comment]
I am still getting the same error with the latest build:

2016/05/12 14:44:57 [I] Created default admin user: admin
2016/05/12 14:44:57 [I] Plugins: Scan starting
2016/05/12 14:44:57 [W] Plugins: Plugin dir data/plugins does not exist
2016/05/12 14:44:57 [W] Plugins: Failed to create plugin dir: data/plugins, error: mkdir data: permission denied
2016/05/12 14:44:57 [T] Checking for updates
2016/05/12 14:44:57 [I] Listen: http://0.0.0.0:3000

**Comment by bergquist** [comment]
@infinitydon have you configure an custom plugin directory for docker? If so does it have write permissions?

**Comment by torkelo** [comment]
@infinitydon pushed updated docker containers to docker hub, hope that fixes it :)

**Comment by xo4n** [comment]
yes  it fixes it 

```
grafana         | 2016/05/13 09:32:31 [I] Version: 3.0.1, Commit: v3.0.1+2-g549eb15, Build date: 2016-05-11 08:37:21 +0000 UTC
grafana         | 2016/05/13 09:32:31 [I] Configuration Info
grafana         | Config files:
grafana         |   [0]: /usr/share/grafana/conf/defaults.ini
grafana         |   [1]: /etc/grafana/grafana.ini
grafana         | Command lines overrides:
grafana         |   [0]: default.paths.data=/var/lib/grafana
grafana         |   [1]: default.paths.logs=/var/log/grafana
grafana         |   [2]: default.paths.plugins=/var/lib/grafana/plugins
grafana         | Paths:
grafana         |   home: /usr/share/grafana
grafana         |   data: /var/lib/grafana
grafana         |   logs: /var/log/grafana
grafana         |   plugins: /var/lib/grafana/plugins
grafana         |
grafana         | 2016/05/13 09:32:31 [I] Database: sqlite3
grafana         | 2016/05/13 09:32:31 [I] Migrator: Starting DB migration
grafana         | 2016/05/13 09:32:36 [I] Plugins: Scan starting
grafana         | 2016/05/13 09:32:36 [I] Listen: http://0.0.0.0:3000
grafana         | 2016/05/13 09:32:36 [T] Checking for updates

```

**Comment by bergquist** [comment]
@xo4n thank you for the followup :)

**Comment by infinitydon** [comment]
Yes.. I have pulled the latest image..

But I noticed even if I do "service grafana-server restart" after plugin installation, the new plugin does not show up in the GUI until I restart the container.
