### ISSUE TITLE
Modal scrollbar click bug

### ISSUE THREAD

**Issue by DislayPS** [grafana/grafana#45994]
**What happened**:
Modal with scrollbar has "click" issue and resets the scrollbar to weird positions without allowing users to click on other areas.

**What you expected to happen**:
Users should be able to click the area they want, when scrolled back where they want.

**How to reproduce it (as minimally and precisely as possible)**:
General description: Have a Modal with long content, for the scrollbar to appear. Scroll down, click a button, or some interactive element inside the content at the bottom. Scroll back up, click anywhere, the scrollbar will reset at the bottom of the modal
[Apologies, tried to do a video recording, but gif was too big]
Step 1: Open in a browser https://developers.grafana.com/ui/latest/index.html?path=/story/overlays-modal--basic
Step 2: Inspect Element inside the modal
Step 3: Copy the "lorem ipsum" text and paste it several times so the content grows and the modal will show a scrollbar
Step 4: Scroll down to the bottom, click the button "Button 1"
Step 5: Scroll back up all the way up and click the text -> The scrollbar goes back at the bottom (I can't click the text, nor select the text at the top)

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version:  Mine is Grafana UI 8.2.2 but I think the bug still exist in newer version, from the Storybook page: https://developers.grafana.com/ui/latest/index.html?path=/story/docs-overview-intro--page
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Bug found in both Chrome & Firefox browsers (Haven't tested others)
- Grafana plugins: N/A
- Others: N/A

**Comment by ashharrison90** [comment]
hi @DislayPS 👋 

thanks for raising this! this bug was fixed in v8.4.0 by https://github.com/grafana/grafana/pull/44770

the public storybook is currently a few versions behind, we're investigating that as part of https://github.com/grafana/grafana/issues/45203

hope that helps! 😄

**Comment by DislayPS** [comment]
Hi @ashharrison90, thank you for looking into this quickly.

I have just tested with @grafana/ui 8.4.0 as well as 8.4.2 and the issue remains, I would like to re-open this ticket if possible.

Here are my grafana dependencies list:
`"@grafana/data": "^8.4.2",
    "@grafana/eslint-config": "^2.5.2",
    "@grafana/runtime": "^8.4.2",
    "@grafana/toolkit": "^8.4.2",
    "@grafana/ui": "^8.4.2",
`

**Comment by DislayPS** [comment]
Hi @ashharrison90,  

I'm testing on my local machine with those packages installed.
I don't recognize my issue being the one you mentioned in [#44770](https://github.com/grafana/grafana/pull/44770) though.
My issue is the scrollbar resets at weird positions on click.

**Comment by ashharrison90** [comment]
maybe if you can give the exact steps you're taking to repro that would help? 🤔

the scrollbar moving is a symptom of the issue linked above. because there's nothing to focus on, focus jumps back down to the button you originally clicked causing the button to scroll into view.

**Comment by DislayPS** [comment]
Hi @ashharrison90, Thank you for working so hard at night.

I initially thought that the bug was fixed on @grafana/ui package, it turns out the grafana platform also needs to be upgraded to 8.4.x. 
So thank you, I was able to see the fix by upgrading my local grafana platform to 8.4.x in addition to my package.json dependencies =)

Cheers,
Dislay

**Comment by ashharrison90** [comment]
no worries, don't worry I'm not working hard just replying whilst watching twitch streams 😂

glad it's working for you!
