### ISSUE TITLE
Grafana Service not starting on Ubuntu 20.04.4

### ISSUE THREAD

**Issue by amit-thakur-S** [grafana/grafana#46404]
Grafana Service stopped working after update.
Ubuntu 20.04.4 LTS
Grafana 8.4.3

```
ubuntu@ip-XXXXXXXXX:/etc$ sudo systemctl status grafana-server
● grafana-server.service - Grafana instance
     Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-03-10 12:09:38 UTC; 9s ago
       Docs: http://docs.grafana.org
    Process: 1274 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR>
   Main PID: 1274 (code=exited, status=203/EXEC)

Mar 10 12:09:38 ip-xxx-xx-xx-xxx systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Mar 10 12:09:38 ip-xxx-xx-xx-xxx systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Mar 10 12:09:38 ip-xxx-xx-xx-xxx systemd[1]: Stopped Grafana instance.
Mar 10 12:09:38 ip-xxx-xx-xx-xxx systemd[1]: grafana-server.service: Start request repeated too quickly.
Mar 10 12:09:38 ip-xxx-xx-xx-xxx systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Mar 10 12:09:38 ip-xxx-xx-xx-xxx systemd[1]: Failed to start Grafana instance.
```

Output of Grafana Log File:
```
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Starting Grafana" version=8.4.3 commit=b7d2911cac branch=HEAD compiled=2022-03-02T13:01:27Z
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations"
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled."
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2022-03-10T10:24:28.71+0000 lvl=info msg="App mode production"
logger=sqlstore t=2022-03-10T10:24:28.71+0000 lvl=info msg="Connecting to DB" dbtype=sqlite3
logger=migrator t=2022-03-10T10:24:28.73+0000 lvl=info msg="Starting DB migrations"
logger=migrator t=2022-03-10T10:24:28.74+0000 lvl=info msg="migrations completed" performed=0 skipped=381 duration=1.146569ms
logger=plugin.manager t=2022-03-10T10:24:28.77+0000 lvl=info msg="Plugin registered" pluginId=input
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=worldping-endpoint-list status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=grafana-worldmap-panel status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=jdbranham-diagram-panel status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=worldping-cta status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=grafana-clock-panel status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=grafana-worldmap-panel status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=worldping-endpoint-nav status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=raintank-worldping-app status=unsigned
logger=plugin.loader t=2022-03-10T10:24:28.77+0000 lvl=warn msg="Skipping loading plugin due to problem with signature" pluginID=grafana-piechart-panel status=unsigned
logger=query_data t=2022-03-10T10:24:28.77+0000 lvl=info msg="Query Service initialization"
logger=live.push_http t=2022-03-10T10:24:28.78+0000 lvl=info msg="Live Push Gateway initialization"
logger=server t=2022-03-10T10:24:28.86+0000 lvl=info msg="Writing PID file" path=/run/grafana/grafana-server.pid pid=1269
logger=server t=2022-03-10T10:24:28.87+0000 lvl=eror msg="Stopped background service" service=*api.HTTPServer reason="failed to open listener on address 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: permission denied"
logger=infra.usagestats t=2022-03-10T10:24:28.87+0000 lvl=eror msg="Failed to get last sent time" error="context canceled"
logger=server t=2022-03-10T10:24:29+0000 lvl=eror msg="Server shutdown" error="*api.HTTPServer run error: failed to open listener on address 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: permission denied" 
```

Is this an issue with the HTTP Port? If so, how can I enable that. Thanks in advance.

**Comment by geomtech** [comment]
Hello

You have to follow the documentation here : https://grafana.com/docs/grafana/latest/installation/rpm/
At this part : 
![image](https://user-images.githubusercontent.com/5628290/157710160-2f7d0d9e-28fb-4504-915b-5418887d2f94.png)

**Comment by amit-thakur-S** [comment]
Hi @geomtech 

This setting is for RPM Based Linux. My EC2 Instance is an Ubuntu machine. Will this work?

**Comment by geomtech** [comment]
I think yes ! Try 😉

**Comment by amit-thakur-S** [comment]
Updated the file and restarted Grafana Server.

```
● grafana-server.service - Grafana instance
     Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/grafana-server.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Fri 2022-03-11 07:25:43 UTC; 6s ago
       Docs: http://docs.grafana.org
    Process: 9832 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR>
   Main PID: 9832 (code=exited, status=1/FAILURE)

Mar 11 07:25:43 ip-172-31-35-217 systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Mar 11 07:25:43 ip-172-31-35-217 systemd[1]: Stopped Grafana instance.
Mar 11 07:25:43 ip-172-31-35-217 systemd[1]: grafana-server.service: Start request repeated too quickly.
Mar 11 07:25:43 ip-172-31-35-217 systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Mar 11 07:25:43 ip-172-31-35-217 systemd[1]: Failed to start Grafana instance.
```

**Comment by geomtech** [comment]
`chmod 640 /var/lib/grafana/grafana.db`

**Comment by amit-thakur-S** [comment]
Thanks @geomtech

The issue is now resolved. Grafana is running as expected.

**Comment by 23ewrdtf** [comment]
I'm still having these issues and the solution https://github.com/grafana/grafana/issues/46404#issuecomment-1064262581 from [geomtech](https://github.com/geomtech) is still valid. The archived copy of the solution is here https://web.archive.org/web/20220126111457/https://grafana.com/docs/grafana/latest/installation/rpm/

I'm on Ubuntu 23.04 and tried everything. For me this is temporary solution as I will move grafana behind a load balancer.

```
Serving Grafana on a port < 1024
If you are using systemd and want to start Grafana on a port that is less than 1024, then you must add a systemd unit override.

The following command creates an override file in your configured editor:
# Alternatively, create a file in /etc/systemd/system/grafana-server.service.d/override.conf
systemctl edit grafana-server.service
1 Add these additional settings to grant the CAP_NET_BIND_SERVICE capability. To read more about capabilities, see [the manual page on capabilities.](https://web.archive.org/web/20220126111457/https://man7.org/linux/man-pages/man7/capabilities.7.html)

[Service]
# Give the CAP_NET_BIND_SERVICE capability
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE

# A private user cannot have process capabilities on the host's user
# namespace and thus CAP_NET_BIND_SERVICE has no effect.
PrivateUsers=false
```
