### ISSUE TITLE
Respect Ctrl-clicking sidebar pop-up elements to open link in new tab

### ISSUE THREAD

**Issue by glindstedt** [grafana/grafana#47514]
There's inconsistency in behavior for the sidebar links depending on if you click the sidebar or the box that pops up with the extra items. The links on the actual sidebar respects Ctrl-clicks for opening the link in a new tab, but the menu with the extra items does not and just navigates within the current tab. It's quite frustrating if you have a metric query in the current tab that you want to keep and come back to, but want to open another tab to check another metric/dashboard, and suddenly have your current tab replaced just because the link doesn't respect Ctrl-clicks.

Ctrl-click in this area, it will successfully open a new tab:

![image](https://user-images.githubusercontent.com/1015224/162441969-5a2480ff-3984-474e-9523-894b5c5687d8.png)

Ctrl-click in this area instead, it will not open a new tab but will use the current tab instead:

![image](https://user-images.githubusercontent.com/1015224/162442028-6e73cd62-4a3b-4efc-849e-942612c8bd57.png)

**What you expected to happen**:

Ctrl-clicks should always open the link in a new tab.

**Environment**:
- Grafana version: 8.4.2
- User OS & Browser: Linux, Chrome

**Comment by JoaoSilvaGrafana** [comment]
Hey 👋  Thank you for raising this!

For the navigation we are using a library called `react-aria` from Adobe's `react-spectrum` collection of libraries and they do have an issue with having links as menu items that someone has raised previously: https://github.com/adobe/react-spectrum/issues/1244#issuecomment-1097715407

Their current work around would require a refactor of how we have structured the navigation, so we might wait and see if they provide a better work around that we can apply.

**Comment by ashharrison90** [comment]
currently implementing some new navigation designs - plan to look at this as part of that 👍

**Comment by ashharrison90** [comment]
so as mentioned this is fixed as part of the new navigation experience we're implementing. you can check out these changes via the `topnav` feature toggle - there's still some bugs to fix, etc. as such, i'm going to close this as completed, and look out for the new navigation release soon™️ 🥳

**Comment by wiardvanrij** [comment]
@ashharrison90 

Could we leave this open because it's not fixed. Anyone not using a feature flag still has this. So unless it becomes the de facto standard, it's still very much so not solved?

**Comment by ashharrison90** [comment]
@wiardvanrij it will become the standard soon 🙂 keep an eye out 👍

**Comment by ericmustin** [comment]
@ashharrison90 any update or roadmap guidance you can provide on this, specifically around when the `topnav` feature will be standard?

**Comment by ashharrison90** [comment]
@ericmustin sure 👍

due to the scale of these changes, we're being extra cautious and adopting an incremental release process. the plan is:

with the release of v9.4.0 this month we will begin gradually enabling the feature in our cloud environments. assuming no show-stopping bugs, it will become the default navigation experience in v9.5.0. as with anything in software, **please do not take any of these release numbers as firm commitments**. 🙏

if you're running grafana yourself, from v9.4.0 i would encourage you to enable both the `topnav` and `topNavCommandPalette` feature toggles. we've had this enabled on some of our internal environments for a couple of months now so it's definitely stable, and any feedback (either positive or negative) would be super valuable. you can do that [here](https://github.com/grafana/grafana/discussions/58910).

hope that helps! 🙌

**Comment by ericmustin** [comment]
@ashharrison90 Thanks yea we’re in the process of bumping from 9.3.6 to 9.4.0-beta1 internally atm. The ff was causing some complications with our app plugin nav when we first migrated to 9.3, and led us to have to disable it. I can document those complications on the attached issue thanks. Appreciate the additional context, won’t take anything as firm commitment

**Comment by ashharrison90** [comment]
@ericmustin is this a plugin provided by grafana, a community plugin available through the catalog or a private custom plugin? 🤔 

afaik all grafana plugins have now been updated. if one of the latter, some changes to the plugin may be required. we'll be posting a plugin upgrade guide shortly which should help guide through the changes. the plugin should still functionally work without these changes, but some features of the new navigation (breadcrumbs/section nav mostly) may not.

providing information in the attached discussion sounds perfect, thank you! 🙏
