### ISSUE TITLE
Loki: Ad-hoc filter is inadvertently added between the regex parser/line_format curly braces.

### ISSUE THREAD

**Issue by SSvilen** [grafana/grafana#47701]
**What happened**:

When having a regex parser/line_format with curly braces the ad-hoc filter is getting addeded there too (in addition to the stream selectors).

**What you expected to happen**:

The ad-hoc filter should be added between the first curly braces.

**How to reproduce it (as minimally and precisely as possible)**:

Following example query
```
topk(10,sum by (api) (count_over_time({instance="server:443",responsecode=~"500" } |= "/api"| regexp "\\/api\\d{0,1}(?P<api>[\\/a-zA-Z\\-\\.]+)" [$__interval])))
```
is converted to the following:

```
topk(10,sum by (api) (count_over_time({api="_MY_ADHOC_QUERY",instance="server:443",responsecode=~"500"} |= "/api"| regexp "\\/api\\d{api="_MY_ADHOC_QUERY"}(?P<api>[\\/a-zA-Z\\-\\.]+)" [1h])))&time=1649855273000000000&limit=1
```
**Anything else we need to know?**:

The same happens when 
```
line_format {{ .label }} 
```
is used.

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: Loki 2.4
- OS Grafana is installed on: Kubernetes

**Comment by mellieA** [comment]
sounds similar to https://github.com/grafana/grafana/pull/38542 fixed in 8.1.3

**Comment by joey-grafana** [comment]
Could you please take a look at this when you get a chance, @ivanahuckova :)

**Comment by ivanahuckova** [comment]
Yes, our handling of ad hoc filters needs to be improved for complex metrics queries. It currently works for log queries and then metrics queries without parsing. I am going to turn this into feature request as this use case is currently not handled. We should definitely add this to our backlog!

**Comment by ivanahuckova** [comment]
@SSvilen can you confirm that this happens only for metrics queries.

**Comment by daper** [comment]
@ivanahuckova It also happens for log queries when using line_format. The following query:
```
{container="controller",job="ingress-nginx"} | json | __error__ != "JSONParserErr" | status!=200 | line_format "➡️ {{ .status }} {{ .method }} {{ .path }} {{ .host }} {{ .ip }} {{ .upstream_name }}" | ip!~"10\\.42\\.0\\."
```
gets converted into:
```
{container="controller",geoip_country_code="CH",job="ingress-nginx"} | json | __error__ != "JSONParserErr" | status!=200 | line_format "➡️ {{geoip_country_code="CH"} {{geoip_country_code="CH"} {{geoip_country_code="CH"} {{geoip_country_code="CH"} {{geoip_country_code="CH"} {{geoip_country_code="CH"}" | ip!~"10\\.42\\.0\\."
```

**Comment by ivanahuckova** [comment]
Thank you! @gabor we should probably change how we add new labels to loki queries now when we have parser and we could use that instead of complex regexp.

**Comment by SSvilen** [comment]
@ivanahuckova  - in my use case I only have metric queries.

**Comment by ivanahuckova** [comment]
@daper What version of Grafana are you using as this should have been fixed in v8.3.3 https://github.com/grafana/grafana/pull/42590

**Comment by daper** [comment]
@ivanahuckova I am using the `v8.5.3 (409e9bc9a5)` version. I double checked it 😅 just in case, but still happens.

**Comment by ivanahuckova** [comment]
@daper I see where the issue is. For templating, we expect pattern `{{.test` but you use `{{test`. We should update it to consider this usecase as well.

**Comment by xdom** [comment]
@ivanahuckova This affects also queries which contain variables with format options (e.g. `${filter:regex}`).

Query
```
{hostname=~"$hostname"} |= "$search" !~ "${antisearch:regex}|THIS_VALUE_IS_NEVER_PRESENT" | json | line_format "{{.message}}\n{{.stackTrace}}"
```

With ad-hoc filter **not present** is rendered into:
```
{hostname=~".+",error=~".*"} |= "" !~ "|THIS_VALUE_IS_NEVER_PRESENT" | json | line_format "{{.message}}\n{{.stackTrace}}"
```

The same query with ad-hoc filter **present**:
```
{app="mws",hostname=~".+"} |= "" !~ "}|THIS_VALUE_IS_NEVER_PRESENT" | json | line_format "{{.message}}\n{{.stackTrace}}"
```

A dangling right curly brace is present in resulting query: `"➡️}⬅️|THIS_VALUE_IS_NEVER_PRESENT"`.
