### ISSUE TITLE
[BUG] Particular plugin menu should not be displayed to unauthenticated users

### ISSUE THREAD

**Issue by phutchins** [grafana/grafana#4784]
This issue was initially opened in the grafana-zabbix repo's issues but @alexanderzobnin mentioned that it was an issue with Grafana and not the plugin.

* I'm currently running out of the develop branch at commit 163b45cf37ec077e018ff2b9fe03fb0be36e0a80
* Plugin that is showing up is the grafana-zabbix plugin menu
* This is running on Ubuntu 14.04

When sharing a dashboard in grafana, an unauthenticated user can click the grafana menu button in the top left and will see a Zabbix menu item. It says permission denied when it is clicked but it should not be displayed.

The Zabbix plugin's menu should not be displayed unless the user is authenticated.

Authenticated:
![](https://cloud.githubusercontent.com/assets/1074345/14707380/8f921736-0792-11e6-913c-4f12c24eee5c.png)

Unauthenticated
![](https://cloud.githubusercontent.com/assets/1074345/14707383/92acf4f4-0792-11e6-8ee0-d1c850ea6459.png)

Please let me know if there is any additional information that I can provide that would be helpful.

Honestly, I'd love it if we had the ability to share a dashboard which did not display the menu bar at the top at all. I don't want the user to be able to change anything so I don't care about them not being able to see the time configuration.

**Comment by torkelo** [comment]
Fixed so that the nav will not include the app if there are no subnavs that the user has access to. 

This will not solve your case because Zabbix has 2 dashboard links where addToNav is set to true, which no Role assigned (defaults to Viewer). So Zabbix link will still be shown for anonymous users. 

https://github.com/alexanderzobnin/grafana-zabbix/blob/master/src/plugin.json#L48

**Comment by phutchins** [comment]
@torkelo awesome! Thank you so much! I'll work with the zabbix plugin developer to get this fixed the rest of the way. Thanks again for such an awesome dashboard and all of your work on this!

I've been watching the project for a year or two now and I'm very excited to have started using it...

**Comment by phutchins** [comment]
I've added the 'Editor' role to the includes and removed addToNav and have managed to get the sub menus to disappear from the menu but the Zabbix menu still appears. Could you point me in the right direction for adding a required role to the root level of the menu? A similar example might be good enough if you know of one.

**Comment by phutchins** [comment]
Well, I take it back. Removing addToNav completely removes it from the nav and I then can't see the menu item when logged in... When addToNav exists, but I have "role": "Editor" I can still see the menu item when logged out :-\.

**Comment by torkelo** [comment]
whats your anonymous user role? (specified in config file in the anonymous section )

**Comment by phutchins** [comment]
It's all pretty much default. org_role = Viewer for auth.anonymous

**Comment by torkelo** [comment]
@phutchins strange, works here, when I set role: "Editor" to one of the dashboards or pages, (in the includes section), I cannot see the main app link in nav when I am anonymous. Did you restart grafana-server ? it needs restart to reread plugin.json (also if you are modifying a plugin that has a dist folder modify the plugin json in the dist folder)

**Comment by phutchins** [comment]
@torkelo odd. I'm editing the plugin.json in /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/ and when I made changes (and restart) I do see changes on the front end to the sub menus but the main menu is still not going away. I'm 2 days behind on the zabbix plugin so maybe I can pull updates and see if that helps... 

Does this look like what you're doing?

```
  "includes": [
    {
      "type": "datasource",
      "name": "Zabbix Datasource",
      "role": "Editor"
    },
    {
      "type": "panel",
      "name": "Triggers Panel",
      "role": "Editor",
      "addToNav": true
    },
    {
      "type": "dashboard",
      "name": "Zabbix Server Dashboard",
      "path": "dashboards/zabbix_server_dashboard.json",
      "role": "Editor",
      "addToNav": true
    }
  ],
```

**Comment by torkelo** [comment]
A panel should not have addToNav

**Comment by phutchins** [comment]
I removed the addToNav as I had before and still the same outcome... 

<img width="816" alt="screen shot 2016-04-27 at 7 22 18 am" src="https://cloud.githubusercontent.com/assets/1074345/14850743/1f45b7ec-0c49-11e6-9acd-73071c7fdac3.png">

Then when I log in, those two menus are missing...

<img width="700" alt="screen shot 2016-04-27 at 7 25 20 am" src="https://cloud.githubusercontent.com/assets/1074345/14850761/3befba14-0c49-11e6-8588-a07a38d41bb6.png">

Any thoughts? Maybe @alexanderzobnin has an idea?

**Comment by tammytankian** [comment]
I dont know if you guys already found a solution for this, but I could solve only deleting the includes of the dashboards in

/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/dist/plugin.json /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/src/plugin.json

And that is it 

Only every update of it, you have to do the procedure again


Is going to be like this the file:

  "includes": [
    {
      "type": "datasource",
      "name": "Zabbix Datasource"
    },
    {
      "type": "panel",
      "name": "Triggers Panel"
    }
  ],

  "dependencies": {
    "grafanaVersion": "3.x 4.x",
    "plugins": []
  }
}

After that, restart grafana, and you remove the menu, wito=hout losing access to the config in "plugins" menu.

![image](https://user-images.githubusercontent.com/27218076/32459301-eeee6a3a-c30d-11e7-9e11-9acaa2d6ec8d.png)

Hope I could help (:

**Comment by alexanderzobnin** [comment]
@phutchins I'll take a look at this issue again.
