### ISSUE TITLE
Node graph context menu doesn't appear

### ISSUE THREAD

**Issue by hoptical** [grafana/grafana#51410]
**What happened**:
Context menu doesn't appear while clicking on a node in the _graph_ layout. However, it's ok in the _grid_ layout.

![screen-capture](https://user-images.githubusercontent.com/30399989/175772941-ba082a1b-a043-47b1-b8a7-1c4a231b01db.gif)

**What you expected to happen**:
A context menu must appear according to the [Gif ](https://grafana.com/static/img/docs/node-graph/node-graph-navigation-7-4.gif) of nodegraph in the [nodes ](https://grafana.com/docs/grafana/latest/visualizations/node-graph/#nodes)section of documentation.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install [node graph data source API plugin](https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/). This plugin is just a middleware to provide graph data via API and visualize it by [node graph panel](https://grafana.com/docs/grafana/latest/visualizations/node-graph/).
2. Use the [API example ](https://github.com/hoptical/nodegraph-api-plugin#api-example) to set up a simple API server with Flask.
3. [Configure ](https://github.com/hoptical/nodegraph-api-plugin#plugin-configuration)the plugin with the address of API server
4. Create a node graph panel in a dashboard. You should now see a simple graph.
5. Click on a node in the graph layout.

**Anything else we need to know?**:
As I mentioned in previous section, you should use [node graph API](https://github.com/hoptical/nodegraph-api-plugin) plugin as the data source.

**Environment**:
- Grafana version: 7.5+
- Data source type & version: [node graph API plugin](https://github.com/hoptical/nodegraph-api-plugin) v1.0.0
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome
- Grafana plugins: [Node graph Panel](https://grafana.com/docs/grafana/latest/visualizations/node-graph/)
- Others:

**Comment by ivanahuckova** [comment]
@hoptical This issue is fixed in Grafana v9.0.0.

**Comment by hoptical** [comment]
@ivanahuckova But the issue is still there even for Grafana v9.0.1. The [gif](https://user-images.githubusercontent.com/30399989/175772941-ba082a1b-a043-47b1-b8a7-1c4a231b01db.gif) that I'd attached before is related to this version.
This issue has been also reported in hoptical/nodegraph-api-plugin#17 by another user who used Grafana v9.0.1.

**Comment by alex-necula** [comment]
I'm experiencing the same issue on Grafana v9.0.6

**Comment by perotta** [comment]
@ivanahuckova me too. I'm also experiencing the exact same problem on 9.1.6. Is is because of the data format? 

Using Node Graph API plugin and my data looks like this:

{"nodes":[{"id":"1247414","title":"V3D00011","subtitle":"11151","mainstat":"V3D00011","secondarystat":"11151","detail__dashboard":"http:\/\/localhost:8000\/ui\/contact\/11151\/general"},{"id":"1248629","title":"V3P00015","subtitle":"15406","mainstat":"V3P00015","secondarystat":"15406","detail__dashboard":"http:\/\/localhost:8000\/ui\/contact\/15406\/general"}],"edges":[{"id":"154","source":"1247414","target":"1248629"}]}

**Comment by lmangani** [comment]
> @hoptical This issue is fixed in Grafana v9.0.0.

@ivanahuckova the issue persists and closing it without any referenced PR makes it quite hard to understand what the supposed cause might have been either.

**Comment by ivanahuckova** [comment]
For issues related to Node Graph API, please open the issue in its plugin repository: https://github.com/hoptical/nodegraph-api-plugin

**Comment by perotta** [comment]
It doesn't look like the issue is with Node Graph API. I'm seeing the same problem using TestData DB (see screenshot below). When I click on any node, no Context Menu appears (except when on Grid Layout)

![image](https://user-images.githubusercontent.com/45238586/192270498-b1b0698d-bb9e-4ec1-8cc5-e79de1ad7e93.png)

**Comment by ivanahuckova** [comment]
@perotta Could you please create a new issue as this one was closed and has some mixed responses related to Node graph and Node Graph API plugin. Thank you so much! 🙏

**Comment by perotta** [comment]
@ivanahuckova sure

Here it is 
https://github.com/grafana/grafana/issues/55838

Thank you! :)
