### ISSUE TITLE
[Bug] unload prompt displays even when there are no unsaved changes

### ISSUE THREAD

**Issue by arodland** [grafana/grafana#5145]
Since upgrading to 3.0.1, I get the "changes you made may not be saved" on closing or reloading the tab, even if I didn't made any changes — even if I do it immediately after opening the tab. Same behavior in 3.0.3. Grafana is running on Linux, browser is Chrome 51 on Linux. Many data sources in use, but primarily graphite.

![unsaved](https://cloud.githubusercontent.com/assets/6380/15486011/abab1f66-2110-11e6-8df3-8a339e796329.png)

**Comment by utkarshcmu** [comment]
+1 to this bug

**Comment by torkelo** [comment]
cannot replicate this. Can you show me your dashboard json?

**Comment by torkelo** [comment]
closing this due to lack of more detail

**Comment by bobrik** [comment]
This is fixed in 3.0.4.

**Comment by olegmayko** [comment]
Hi, it is still happening on grafana 4.0.2 and Chrome browser (windows 10) , my teammates also reported it occurred on Safari. What kind of details do you need to investigate it ?

**Comment by StianOvrevage** [comment]
We are having the same problems. Noone is touching grafana interactively but it is reloaded on a status monitor every 10 minutes and multiple times a day the onbeforeunload popup prevents automatic reload. Looked into it a year ago without any luck, and still a huge PITA.

Can we have a setting that disables check for unsaved changes, since it appears not to detect 100% correctly?

**Comment by torkelo** [comment]
@StianOvrevage have you tried saving the dashboard? Maybe it's an old dashboard that just needs a resave to persist the schema upgrade

**Comment by StianOvrevage** [comment]
I have re-saved now, looks good so far, gonna observe for the rest of the day.

How often are there schema upgrades? Every new major/minor version? We have some dashboards saved as json on the backend and managed with SaltStack making re-saving a bit tedious right now. Is there a tool to batch upgrade dashboards based on json for example?

**Comment by StianOvrevage** [comment]
I have now pinned the grafana container to use 4.3.2 to avoid upgrading grafana unintentionally and having schema migration issues.

I have also re-saved the offending dashboard (saved in db). However, when I load for example /grafana/dashboard-solo/db/favorite-panels?panelId=2&theme=light&refresh=5m&orgId=1 even with no changes, no clicks, no interaction whatsoever, it will still prompt for unsaved changes after a few minutes.

**Comment by daniellee** [comment]
In the next version of Grafana (v4.4.0 or with one of the recent nightly builds), we will be releasing the version history feature that allows you to do json diffs between saved versions. With this feature we will be able to track the causes of any strange behavior with unsaved changes.

**Comment by StianOvrevage** [comment]
Awesome stuff @daniellee! Looking forward to it!
