### ISSUE TITLE
Grafana loki search tab stopped working properly for typing queries starting from chrome Version 105.0.5195.52 

### ISSUE THREAD

**Issue by y0zg** [grafana/grafana#54602]
When you type in Grafana Loki query `{app="something"}` it will show you in chrome as `{a}pp`
Not sure whether this is Grafana / Loki or chrome (most probably) issue (it is not reproducable with Prometheus queries)

Issue is reproducible in chrome Version 105.0.5195.52 , but isn't reproducible in lower versions
<img width="734" alt="Screenshot 2022-09-01 at 16 45 10" src="https://user-images.githubusercontent.com/6439757/187930652-ebc96a90-c029-442a-9330-c04b654d843a.png">

**Comment by dannykopping** [comment]
I've transferred this issue because it relates to the plugin not the Loki database itself

**Comment by Bassardes** [comment]
Same. Reproducible only on chrome Version 105.0.5195.52

**Comment by glebsam** [comment]
Yep, since I've been on Chrome 105 (beta), I had to use builder-mode for queries

**Comment by mellieA** [comment]
👋 This issue is fixed [here](https://github.com/grafana/grafana/issues/54535)

**Comment by gururajumoe** [comment]
same here. 
still seeing this issue with - 
Version 106.0.5249.119 (Official Build) (arm64)

**Comment by DinithKumudika** [comment]
still the issue persist in the chrome

i am using grafana 8.2.5 and chrome 136.0.7103.93 (Official Build) (64-bit)
