### ISSUE TITLE
Loki Query Editor is no longer usable

### ISSUE THREAD

**Issue by r0fls** [grafana/grafana#55521]
**Describe the bug**
This is an issue with Grafana and the Loki Datasource in Grafana 9.1.1 The Loki query editor is no longer useable, as the combination of auto complete and query builder features are causing some bugs where typing out the query no longer works.

**Expected behavior**
The Grafana Loki query editor should be a first class citizen.

**Environment:**
 - Infrastructure: (NA)
 - Deployment tool: (NA)

**Screenshots, Promtail config, or terminal output**
I would need to do a screen recorded capture to display the issue here, but it is really bad... 😢

**Comment by yongzhang** [comment]
I think you're hitting this: https://github.com/grafana/grafana/issues/54535, this was fixed in v9.1.5+

**Comment by r0fls** [comment]
Thanks @yongzhang, that sounds like it. I’ll get this upgraded and see if it’s fixed. Feel free to close this out, or wait to hear back from me, up to you.

**Comment by victorolinasc** [comment]
I still have issues with a keyboard input that uses punctuation (pt-BR) on an international layout (en-US).

https://user-images.githubusercontent.com/376386/191562071-8d0dba57-4f8e-4b26-af5b-f7f4586eefd5.mp4

**Comment by natellium** [comment]
Hey @victorolinasc I believe your issue may be solved with this fix https://github.com/grafana/grafana/pull/55576

I'll be closing this one as a duplicate of https://github.com/grafana/grafana/issues/54535

**Comment by r0fls** [comment]
confirmed this was the issue we were facing, thanks a ton 🙏
