### ISSUE TITLE
expression when data mixed

### ISSUE THREAD

**Issue by frezeen** [grafana/grafana#58937]
**What happened**:
expression when data source is mixed dont work

**What you expected to happen**:
expression result
**How to reproduce it (as minimally and precisely as possible)**:
create a mixed datasource , add expression
**Anything else we need to know?**:
error is: message:"The request headers point to a different plugin than is defined in the request body"
**Environment**:
- Grafana version: 9.3.0.beta 1
- Data source type & version: 
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @frezeen 

I believe this was spotted by some of our devs and they are looking into it already ❤️

**Comment by ryantxu** [comment]
Is fixed in main, and will be in the next release

**Comment by maurerle** [comment]
I still get a 500 in the latest docker-container (f925787d0f79) when using an expression and mixed data.
This worked just fine in previous versions.

**Comment by itsmylife** [comment]
I tested and saw it is working. However, there was a small UI issue (See: https://github.com/grafana/grafana/issues/64890). And that was addressed here: https://github.com/grafana/grafana/pull/65006

Please let me know if you still experiencing problems.
