### ISSUE TITLE
Dashboard Variables with Azure Data Explorer Datasource Don't Honor Time Parameters 

### ISSUE THREAD

**Issue by tommo-ms** [grafana/grafana#61509]
**What happened**:

> My dashboard has an Azure Data Explorer (ADX) data-source with a query that returns a list of values used to filter various panels. When I use the built in parameters for the time-selector in a WHERE clause of the ADX query they aren't honored.  It appears the parameter values set by the time range selector can't accessed in an ADX data-source for dashboard parameter. 
> 
> This is a usability issue since users expect their changes to time filter to affect this list of values in the variable.  Since I can't access the parameters for their time selection, I have to either bring back all values in the ADX database (which is way too many) or introduce an arbitrary look back (e.g. - 7 days) which is only accurate if the user selects the same lookback time.  Therefore, my reports are inaccurate from a user perspective, and it reduces the trust in the Grafana reports we are trying to get our organization to adopt. 

**What you expected to happen**:

> I expect any variable query to have access to the dashboard time selection parameters enabling report designers to filter the results in based on the user's time selection. 

**How to reproduce it (as minimally and precisely as possible)**:

> 1. Create and dashboard and set the time using the time drop-down selector: 
>    * Start Time: '2023-01-13 00:00' 
>    * End Time: '2023-01-13 06:00'
> 2. Create a dashboard variable called mySeries that has an Azure Data Explorer data-source and uses this query:  
> ```
>    let seriesFilter = datatable(Timestamp:datetime, seriesName:string )[
>     '2023-01-13 00:00', "A", 
>     '2023-01-13 01:00', "B", 
>     '2023-01-13 02:00', "C", 
>     '2023-01-13 03:00', "D", 
>     '2023-01-13 04:00', "E", 
>     '2023-01-13 05:00', "F", 
>     '2023-01-13 06:00', "G" 
>     ];
>    seriesFilter
>    | where Timestamp > $__timeFrom() and Timestamp <= $__timeTo()
> ```
> 3. Press the"Run Query" button and under "Preview of Values" you should see a single result of "None" which is improper
> 4. Next, comment out the where clause in the query to exclude the time filter: 
> ```
>    let seriesFilter = datatable(Timestamp:datetime, seriesName:string )[
>     '2023-01-13 00:00', "A", 
>     '2023-01-13 01:00', "B", 
>     '2023-01-13 02:00', "C", 
>     '2023-01-13 03:00', "D", 
>     '2023-01-13 04:00', "E", 
>     '2023-01-13 05:00', "F", 
>     '2023-01-13 06:00', "G" 
>     ];
>    seriesFilter
>    //| where Timestamp > $__timeFrom() and Timestamp <= $__timeTo()
> ```
> 5. Press the "Run Query" again and you'll see the expected results of: A, B, C, D, E, F, G
> 6. You can also create a table panel in the report using the same query and you'll see that it properly processes the time parameters. 

**Repro Demo**

> [Here ](https://1drv.ms/u/s!Ahi4riCD6b4OiIMyeAkdIL_3xR2uVA?e=VhX41e) is an animated gif that shows a repro of the issue.  The animation first shows the a table panel, with the query in step-2 above, works as expected and filters the rows based on the time selection.  The second part of the demo shows how the same query doesn't work as expected in the variable. 

**Anything else we need to know?**:

**Environment**:
- Grafana version:  9.2.7.1
- Data source type & version:  Azure Data Explorer 4.1.6
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment]
:wave: Thanks for creating this issue and for including such detailed repro steps 👍 , @tommo-ms 

i am forwarding this issue to the Dashboard squad for review

**Comment by axelavargas** [comment]
Hey @tommo-ms 👋🏾 , thanks for reporting this issue and for the gif (it made it easier to understand the problem)  :).  In order to hook a template variable with the time range from the dashboards, there is a couple of things you need to configure:

1. Select "refresh -> On time range change" 

![image](https://user-images.githubusercontent.com/239999/214055848-716f75f4-4408-4419-8b4a-dc30ec8ec3f2.png)

2. Use a global variable in the azure template variable query. Reading from the documentation it seems that for azure you can use $__timeFilter global variable, you can find more information here https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#timefilter-or-__timefilter 

Let me know if these suggestions solve the problem :). 

Thank you 🙏🏾

**Comment by kayodeprinceMS** [comment]
The problem is the global variables/macros suggested in option 2. are not being honored in variable queries. Similar to #36944

**Comment by axelavargas** [comment]
Hey, @kayodeprinceMS, thanks for letting us know 😄. I am redirecting to @grafana/partner-plugins as this seems related to Azure monitor and they have more context.

Thank you 🙏🏾

**Comment by kayodeprinceMS** [comment]
Hi, this problem is already fixed in Azure Monitor plugin, the request to also fix in the ADX plugin. ADX variables queries should support the time macros just as in panels.

**Comment by kate-jq** [comment]
$__timeFilter global variable do not work for variables from ADX queries, it's still a problem

**Comment by maybrittstoen** [comment]
When creating a variable in Grafana cloud it is not possible to limit the search range with a time filter.
Variables as global filters.
This makes the variable potensially search large amount of data. We need a fix for this or the use of global varables will not be posible to use.

**Comment by asimpson** [comment]
This is logged over in the ADX repo
- https://github.com/grafana/azure-data-explorer-datasource/issues/546

**Comment by maybrittstoen** [comment]
Thanks 😀
