### ISSUE TITLE
Grafana.org & docs site update

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#6170]
Some tech & design updates are needed
- [x] Migrate grafana.org from ruby middleman to hugo and normal sass/html templates
- [x] Sass -> Scss migrated
- [x] Layouts migrated
- [x] Landning page migrated
- [x] JS bundling & minification
- [x] content reving
- [x] Blog is working with old & new urls
- [x] migrate all pages
- [x] Migrate grafana.org publish from github page to s3
- [x] Add fastly cdn for new grafana.org s3 page
- [x] New design for download page and maybe other minor design changes
- [ ] Update docs site to new hugo based docs-base 
- [ ] New design for docs site
- [ ] Use Algolia search in docs 
  
  cc @mattttt @bulletfactory

**Comment by TerraTech** [comment]
Will these updates fix the anchor problem?

I'm using Chrome (Version 54.0.2840.87 m (64-bit)), and while viewing:
http://docs.grafana.org/installation/configuration/

and I click on any side navigation link e.g. _http_addr_ (http://docs.grafana.org/#http-addr), it sends me back to the base URL with that anchor.

**Comment by torkelo** [comment]
fixed that issue now

**Comment by TerraTech** [comment]
@torkelo Thank you!

**Comment by TerraTech** [comment]
@torkelo the anchor problem is back.
Clicking on "type", the anchor link is:
http://docs.grafana.org/v3.1/#type
instead of
http://docs.grafana.org/v3.1/installation/configuration/#type

**Comment by torkelo** [comment]
Have no updated any old version docs, use latest (root)

**Comment by TerraTech** [comment]
Ah, my bad, the _/v3.1/_ was the problem, I must have followed a versioned link into that path.
http://docs.grafana.org/installation/configuration/#type
^^ the anchors work fine
