### ISSUE TITLE
CloudWatch Logs: queries returning multiple time series cannot be used in alert rules

### ISSUE THREAD

**Issue by DColadas** [grafana/grafana#63388]
**What happened**:
CloudWatch Logs returning multiple time series cannot be used in alert rules. I can see this problem was reported in another issue's comment in the past (https://github.com/grafana/grafana/issues/46429#issuecomment-1185375094).

**What you expected to happen**:
Each time series returned in a CloudWatch logs query should be evaluated individually in an alert rule. 

**How to reproduce it (as minimally and precisely as possible)**:
Select the CloudWatch Logs data source and write a query returning multiple time series, like the following (if more than one log group is selected):
```
stats count(*) by bin(1h), @log
```
Each individual time series is shown correctly in a time series panel:
<img width=70% src="https://user-images.githubusercontent.com/48674466/219354373-e7f43c5d-056f-4a3b-808f-983a300e68d9.png"/>

If the query above is used in an alert rule instead, the error `Failed to evaluate queries and expressions: input data must be a wide series but got type long (input refid)` pops up:

<img width=70% src="https://user-images.githubusercontent.com/48674466/219356384-afa5753d-ff40-4340-91aa-4c15ccfa99b5.png"/>

The alert rule works if the query returns a single time series:
```
stats count(*) by bin(1h)
```

**Anything else we need to know?**:
I have not been able to apply panel expressions (like `Reduce`) to CloudWatch Logs queries either: I always get an error. Maybe the issue is related?
Also, in case it's useful: I've checked the Query Inspector for the query above. No `labels` are populated, and `@log` is a textual field. 
```
{
  "response": {
    "results": {
      "A": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "name": "/loggroup1",
              "refId": "A",
              "meta": {...}
              "fields": [
                {
                  "name": "bin(1h)",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time",
                    "nullable": true
                  },
                  "labels": {}
                },
                {
                  "name": "@log",
                  "type": "string",
                  "typeInfo": {
                    "frame": "string",
                    "nullable": true
                  },
                  "labels": {}
                },
                {
                  "name": "count(*)",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {}
                }
              ]
            },
...
```

**Environment**:
- Grafana version: tested in 9.3.1, 9.3.2, 9.3.6
- Data source type & version: Cloudwatch 5.0.0
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04, Firefox 109
- Grafana plugins:
- Others:

**Comment by fridgepoet** [comment]
Hi @DColadas thanks for reporting this issue.
I was able to reproduce it exactly as you described.
(Notes: on our external dev account, /ecs/PetSearch and /ecs/PayForAdoption log groups)

> I have not been able to apply panel expressions (like Reduce) to CloudWatch Logs queries either: I always get an error.

I was also able to reproduce this issue and am continuing to investigate.

**Comment by DColadas** [comment]
Hi @fridgepoet @iwysiu ,
As of Grafana 10.1.2, I am not sure the issue is fixed. See the image below:

<img width=70% src="https://github.com/grafana/grafana/assets/48674466/a4b846b1-2596-4ce7-9aa9-d7b8f0dab998" />

While we no longer get the `input data must be a wide series` error and we can now apply expressions on the query result, each time series doesn't retain any labels: they are just called `Series 1` and `Series 2` instead. In this case, I would expect each time series to have their own `@log` label.

Essentially, we cannot yet evaluate Cloudwatch Logs queries returning multiple series in alert rules, as we just get the following error: `invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}`.

Am I missing something? Can we reopen this issue?

**Comment by iwysiu** [comment]
Hi @DColadas ! Sorry to hear you're still having issues. I reproduced it and it looks like we're not setting the labels for CloudWatch logs queries. We've reopened the issue.
