### ISSUE TITLE
From 9.3.8 onwards, existing math expressions are not included in queries

### ISSUE THREAD

**Issue by t517435** [grafana/grafana#64121]
There is very often trouble with the math functions during upgrades, especially between major releases. However, this is a bug in between minor releases. This issue happens when upgrading from 9.3.6 to 9.3.8 and newer. Rolling back to 9.3.6 fixes the issue.

**What happened**:
![bilde](https://user-images.githubusercontent.com/52272022/222700424-27f81f61-0731-4132-a56a-17c534ff695a.png)
The expression is empty. Should include math expression below.

**What you expected to happen**:
![bilde](https://user-images.githubusercontent.com/52272022/222700613-564da3af-2345-4fe9-89f7-6937f7d400c8.png)

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade from 9.3.6 to any newer release

**Anything else we need to know?**:
Possible to fix the problem by manually entering all math-functions over again. This is tedious.

**Environment**:
- Grafana version: >9.3.8
- Data source type & version:
- OS Grafana is installed on: RHEL9.1
- User OS & Browser: Windows 10 Chrome/Firefox
- Grafana plugins:
- Others:

**Comment by itsmylife** [comment]
It is not related to #62510 
I checked out 9.3.6 and created an alert rule and went back to the main and checked it. It works. 

When I check out 9.3.6 I cannot even create an expression for a dashboard panel because of [this issue](https://github.com/grafana/grafana/issues/62259) 

So I checked out 9.3.4 and created an expression and then switched back to the main branch and I was still able to see and edit the expression.

**Comment by t517435** [comment]
Grafana JSON 9.3.6

{
  "id": 2,
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "gauge",
  "title": "Nokia CMM 4G Attach",
  "datasource": {
    "type": "influxdb",
    "uid": "${DataSource}"
  },
  "pluginVersion": "9.3.6",
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "red",
            "value": null
          },
          {
            "color": "yellow",
            "value": 50
          },
          {
            "color": "green",
            "value": 70
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "links": [],
      "max": 100,
      "min": 0,
      "unit": "percent"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "D no-c-epcsrv-3"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "displayName",
            "value": "2G attach successrate no-c-epcsrv-3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F no-c-epcsrv-3"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "4G attach successrate no-c-epcsrv-3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F no-c-epcsrv-1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "4G attach successrate no-c-epcsrv-1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D no-c-epcsrv-1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "2G attach successrate no-c-epcsrv-1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D no-c-epcsrv-7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "2G attach successrate no-c-epcsrv-7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D no-c-epcsrv-9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "2G attach successrate no-c-epcsrv-9"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F no-c-epcsrv-7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "4G attach successrate no-c-epcsrv-7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F no-c-epcsrv-9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "4G attach successrate no-c-epcsrv-9"
          }
        ]
      }
    ]
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "showThresholdLabels": true,
    "showThresholdMarkers": true,
    "text": {}
  },
  "targets": [
    {
      "alias": "4G $col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "${DataSource}"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "CMM_EPS_CPPS_Mobility_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "E",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.NbrFailedAttachRequests_sum"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Failed Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "alias": "4G $col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "${DataSource}"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "CMM_EPS_CPPS_Mobility_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "B",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.NbrSuccessAttachRequests"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Successfull Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "datasource": {
        "name": "Expression",
        "type": "__expr__",
        "uid": "__expr__"
      },
      "expression": "100*(($B)/($B+$E))",
      "hide": false,
      "refId": "F",
      "type": "math"
    }
  ]
}

**Comment by t517435** [comment]
Grafana 9.3.6 JSON panel

{
  "id": 2,
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "gauge",
  "title": "Attach",
  "datasource": {
    "type": "influxdb",
    "uid": "${DataSource}"
  },
  "pluginVersion": "9.3.6",
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "red",
            "value": null
          },
          {
            "color": "yellow",
            "value": 50
          },
          {
            "color": "green",
            "value": 70
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "links": [],
      "max": 100,
      "min": 0,
      "unit": "percent"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "D 3"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "displayName",
            "value": "Attach 3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 3"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 9"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 9"
          }
        ]
      }
    ]
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "showThresholdLabels": true,
    "showThresholdMarkers": true,
    "text": {}
  },
  "targets": [
    {
      "alias": "4G $col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "${DataSource}"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "Mobility_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "E",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.NbrFailedAttachRequests_sum"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Failed Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "alias": "4G $col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "${DataSource}"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "Mobility_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "B",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.NbrSuccessAttachRequests"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Successfull Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "datasource": {
        "name": "Expression",
        "type": "__expr__",
        "uid": "__expr__"
      },
      "expression": "100*(($B)/($B+$E))",
      "hide": false,
      "refId": "F",
      "type": "math"
    }
  ]
}

**Comment by t517435** [comment]
Grafana 9.4.3 JSON Panel

{
  "datasource": {
    "type": "influxdb",
    "uid": "${DataSource}"
  },
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "red",
            "value": null
          },
          {
            "color": "yellow",
            "value": 50
          },
          {
            "color": "green",
            "value": 70
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "links": [],
      "max": 100,
      "min": 0,
      "unit": "percent"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "D 3"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "displayName",
            "value": "Atatch 3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 3"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 9"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 9"
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 9
  },
  "id": 36,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "showThresholdLabels": true,
    "showThresholdMarkers": true,
    "text": {}
  },
  "pluginVersion": "9.4.3",
  "targets": [
    {
      "alias": "$col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "k6D7ah8Mk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "CMM ",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.SuccGprsAttach"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "alias": "$col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "k6D7ah8Mk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "CMM_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.FailGprsAttachGen"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Failed Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "datasource": {
        "type": "__expr__",
        "uid": "-100"
      },
      "expression": "100*($A/($C+$A))",
      "hide": false,
      "refId": "D",
      "type": "math"
    }
  ],
  "title": "Attach",
  "type": "gauge"
}

**Comment by t517435** [comment]
Grafana 9.3.6 JSON Panel

{
  "id": 36,
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 9
  },
  "type": "gauge",
  "title": "Attach",
  "datasource": {
    "type": "influxdb",
    "uid": "${DataSource}"
  },
  "pluginVersion": "9.3.6",
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "red",
            "value": null
          },
          {
            "color": "yellow",
            "value": 50
          },
          {
            "color": "green",
            "value": 70
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "links": [],
      "max": 100,
      "min": 0,
      "unit": "percent"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "D 3"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "displayName",
            "value": "Attach 3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 3"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "D 9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 9"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "F 9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Attach 9"
          }
        ]
      }
    ]
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "showThresholdLabels": true,
    "showThresholdMarkers": true,
    "text": {}
  },
  "targets": [
    {
      "alias": "$col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "k6D7ah8Mk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "CMM_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.SuccGprsAttach"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "alias": "$col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "k6D7ah8Mk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "CMM_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.FailGprsAttachGen"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Failed Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/epcsrv/"
        }
      ]
    },
    {
      "datasource": {
        "type": "__expr__",
        "uid": "-100"
      },
      "expression": "100*($A/($C+$A))",
      "hide": false,
      "refId": "D",
      "type": "math"
    }
  ]
}

**Comment by t517435** [comment]
> It is not related to #62510 I checked out 9.3.6 and created an alert rule and went back to the main and checked it. It works.
> 
> When I check out 9.3.6 I cannot even create an expression for a dashboard panel because of [this issue](https://github.com/grafana/grafana/issues/62259)
> 
> So I checked out 9.3.4 and created an expression and then switched back to the main branch and I was still able to see and edit the expression.
> 
> @t517435 Could you please provide dashboard json or panel json?

See JSON Panel above. The same panel. It's working in 9.3.6, but fails in 9.4.3

**Comment by itsmylife** [comment]
@t517435 Thank you for bearing with me for such a long time. After carefully checking things, I realized that @yuri-tceretian was right and I missed something to diagnose the issue. Yes, it was related to #62510 
We fixed this issue in the latest release of `9.3.x` and `9.4.x`. Could you please upgrade and try again? 
If you don't want to upgrade I can suggest a workaround: 
Changing the expression uid from `-100` to `__expr__` should resolve the issue.

**Comment by t517435** [comment]
Hi!

Thank you for your response.
I have just upgraded and testet, but, unfortunately, it is still not working. The expression content is missing.

Now we can see the Expressions panel, but it contains the following: (${DataSource})

![datasource](https://user-images.githubusercontent.com/52272022/229057042-e8b79a89-8893-4cd2-a641-e1bfbb9cf556.png)

**Comment by t517435** [comment]
Here is the 9.4.7 json-file:

{
  "datasource": {
    "type": "influxdb",
    "uid": "${DataSource}"
  },
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "red",
            "value": null
          },
          {
            "color": "yellow",
            "value": 50
          },
          {
            "color": "green",
            "value": 70
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "links": [],
      "max": 100,
      "min": 0,
      "unit": "percent"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "no-3"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "displayName",
            "value": "no-3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "no-3"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "no-3"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "no-1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "no-1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "no-1"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "no-1"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "no-7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "no-7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "no-9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "no-9"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "no-7"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "no-7"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "no-9"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "no-9"
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 9
  },
  "id": 36,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "showThresholdLabels": true,
    "showThresholdMarkers": true,
    "text": {}
  },
  "pluginVersion": "9.4.7",
  "targets": [
    {
      "alias": "$col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "k6D7ah8Mk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "CMM_GPRS_Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "VS.Attach"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/srv/"
        }
      ]
    },
    {
      "alias": "$col $tag_host",
      "datasource": {
        "type": "influxdb",
        "uid": "k6D7ah8Mk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "host"
          ],
          "type": "tag"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": true,
      "measurement": "Management",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"VS.*attachFail*\") FROM \"cmm\" WHERE (\"host\" =~ /^$Hostname$/) AND $timeFilter GROUP BY time($__interval), \"Machine\" fill(null)",
      "rawQuery": false,
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "AttachGen"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          },
          {
            "params": [
              "Attach"
            ],
            "type": "alias"
          }
        ]
      ],
      "tags": [
        {
          "key": "host",
          "operator": "=~",
          "value": "/srv/"
        }
      ]
    },
    {
      "datasource": {
        "type": "__expr__",
        "uid": "-100"
      },
      "expression": "100*($A/($C+$A))",
      "hide": false,
      "refId": "D",
      "type": "math"
    }
  ],
  "title": "Attach",
  "type": "gauge"
}

**Comment by t517435** [comment]
Result
![error](https://user-images.githubusercontent.com/52272022/229061316-20322ef8-b100-421a-a965-ddbd11a909ce.png)

**Comment by t517435** [comment]
Expected result
![correct](https://user-images.githubusercontent.com/52272022/229061627-af199a14-8889-4d6f-b1d7-4fc0c1b3d9a6.png)

**Comment by itsmylife** [comment]
@t517435 I see the problem and reproduced it on my end too. I have the fix ready. Before creating a PR I will test it a bit more. Thanks for the JSONs and screenshots. Those were quite helpful.

**Comment by itsmylife** [comment]
@t517435 This PR https://github.com/grafana/grafana/pull/65950 is going to fix the problem.

**Comment by t517435** [comment]
Hi!

Thank you very much for your prompt response. I really appreciate your efforts.

Have a great Easter.

Regards,
Frode Per Marøy

4. apr. 2023 kl. 16:59 skrev ismail simsek ***@***.***>:

﻿

@t517435<https://github.com/t517435> I see the problem and reproduced it on my end too. I have the fix ready. Before creating a PR I will test it a bit more. Thanks for the JSONs and screenshots. Those were quite helpful.
