### ISSUE TITLE
Error type for locked database points to datasource as the problem

### ISSUE THREAD

**Issue by mbrancato** [grafana/grafana#64692]
**What happened**:

Getting datasource error alerts:
![image](https://user-images.githubusercontent.com/8493275/224737570-071d5cdc-ec8f-4c28-a5b6-133cf9426a21.png)

**What you expected to happen**:

The issue here is this shows a `DatasourceError` error type, but it is not a data source error. Please create a new exception type that implies the Grafana database and not the data source. Maybe a new error type like `GrafanaDatabaseLockedError` or something as it points people in the direction of a data source as the problem.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: Victoria Metrics / Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by usmangt** [comment]
:Hi @mbrancato,

Thanks for opening this issue. For this we would like to see the backend logs.

Could you please change the default log level to debug mode. To do this go to the server where grafana is installed and edit the configuration file (/etc/grafana//grafana.ini)
There you will this section;

```
#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
;level = info
```
Set the parameter level to debug and remove the colon in the beginning i.e.

`level = debug`

Then restart the grafana service and resent the logs once the issue occurs again.

Also, 

Can you please provide the steps of reproduction so that the community can also try to reproduce it on a test machine? 

Just try to provide the easiest and simplest steps possible.

Thanks.

**Comment by mbrancato** [comment]
I can help dig into this - I figured I would open a separate issue if I cannot figure out what causes the lock. 

I've enabled debugging, I'll need to wait for it to generate. we're not doing anything to cause this, it seemingly happens at random. And it seems related to alerts- we have notifications setup, and this seems to happen more often when alerts are firing.

logs before enabling debug: 

```
logger=ngalert.sender.router rule_uid=F7Z9-cS4k org_id=1 t=2023-03-14T13:16:14.406625818Z level=info msg="Sending alerts to local notifier" count=1
logger=ngalert.scheduler rule_uid=F7Z9-cS4k org_id=1 version=169 attempt=0 now=2023-03-14T13:16:00Z t=2023-03-14T13:16:13.834452833Z level=error msg="Failed to build rule evaluator" error="failed to build query 'A': database is locked"
logger=datasources t=2023-03-14T13:16:13.834364167Z level=error msg="Failed getting data source" err="database is locked" uid=PBFA97CFB590B2093 id=0 name= orgId=1
logger=ngalert.scheduler rule_uid=VnZr-cI4z org_id=1 version=171 attempt=0 now=2023-03-14T13:16:00Z t=2023-03-14T13:16:12.656148467Z level=error msg="Failed to build rule evaluator" error="failed to build query 'A': database is locked"
logger=datasources t=2023-03-14T13:16:12.656040843Z level=error msg="Failed getting data source" err="database is locked" uid=PBFA97CFB590B2093 id=0 name= orgId=1
logger=cleanup t=2023-03-14T13:15:39.172781795Z level=info msg="Completed cleanup jobs" duration=90.217943ms
```

**Comment by mbrancato** [comment]
that didn't take long, here are debug logs around when the error is being raised and sent as a notification:

```
logger=ngalert.state.historian rule_uid=wP__Bl14z org_id=1 t=2023-03-14T14:07:07.129476488Z level=debug msg="Done saving alert annotation batch"
logger=datasources rule_uid=VnZr-cI4z org_id=1 t=2023-03-14T14:07:07.062274586Z level=debug msg="Querying for data source via SQL store" uid=PBFA97CFB590B2093 orgId=1
logger=ngalert.state.manager rule_uid=jmZ9-5SVk org_id=1 t=2023-03-14T14:07:06.777132848Z level=debug msg="Saving alert states" count=1
logger=ngalert.state.manager rule_uid=jmZ9-5SVk org_id=1 t=2023-03-14T14:07:06.777092173Z level=debug msg="Setting alert state"
logger=ngalert.state.manager rule_uid=jmZ9-5SVk org_id=1 t=2023-03-14T14:07:06.776322218Z level=debug msg="State manager processing evaluation results" resultCount=1
logger=ngalert.scheduler rule_uid=jmZ9-5SVk org_id=1 version=173 attempt=0 now=2023-03-14T14:07:00Z t=2023-03-14T14:07:06.776276878Z level=error msg="Failed to build rule evaluator" error="failed to build query 'A': database is locked"
logger=datasources t=2023-03-14T14:07:06.776193788Z level=error msg="Failed getting data source" err="database is locked" uid=PBFA97CFB590B2093 id=0 name= orgId=1
logger=datasources rule_uid=MnZracIVk org_id=1 t=2023-03-14T14:07:06.47415228Z level=debug msg="Querying for data source via SQL store" uid=PBFA97CFB590B2093 orgId=1
logger=datasources rule_uid=eMZr-cIVz org_id=1 t=2023-03-14T14:07:05.88509294Z level=debug msg="Querying for data source via SQL store" uid=PBFA97CFB590B2093 orgId=1
logger=datasources rule_uid=j4hVJDJVk org_id=1 t=2023-03-14T14:07:05.296802945Z level=debug msg="Querying for data source via SQL store" uid=PBFA97CFB590B2093 orgId=1
logger=ngalert.state.manager rule_uid=dURgGa5Vz org_id=1 t=2023-03-14T14:07:04.841880505Z level=debug msg="Saving alert states" count=1
logger=ngalert.state.manager rule_uid=dURgGa5Vz org_id=1 t=2023-03-14T14:07:04.841839061Z level=debug msg="Setting alert state"
logger=ngalert.state.manager rule_uid=dURgGa5Vz org_id=1 t=2023-03-14T14:07:04.841431165Z level=debug msg="State manager processing evaluation results" resultCount=1
logger=ngalert.scheduler rule_uid=dURgGa5Vz org_id=1 version=13 attempt=0 now=2023-03-14T14:07:00Z t=2023-03-14T14:07:04.841375641Z level=debug msg="Alert rule evaluated" results="[{Instance: State:Normal Error:<nil> Results:map[] Values:map[] EvaluatedAt:2023-03-14 14:07:00 +0000 UTC EvaluationDuration:4.841367629s EvaluationString:}]" duration=132.62135ms
logger=expr rule_uid=dURgGa5Vz org_id=1 datasourceType=prometheus t=2023-03-14T14:07:04.841283359Z level=debug msg="expression datasource query (seriesSet)" query=A
logger=tsdb.prometheus rule_uid=dURgGa5Vz org_id=1 t=2023-03-14T14:07:04.814229862Z level=debug msg="Sending query" start=2023-03-14T14:02:00Z end=2023-03-14T14:07:00Z step=15s query="max(\n sum(vm_data_size_bytes{job=~\"(vminsert-vmcluster|vmselect-vmcluster|vmstorage-vmcluster)\", instance=~\".*\"}) by(job, instance) /\n (\n sum(vm_free_disk_space_bytes{job=~\"(vminsert-vmcluster|vmselect-vmcluster|vmstorage-vmcluster)\", instance=~\".*\"}) by(job, instance) +\n sum(vm_data_size_bytes{job=~\"(vminsert-vmcluster|vmselect-vmcluster|vmstorage-vmcluster)\", instance=~\".*\"}) by(job, instance)\n ) \n)"
logger=secrets.kvstore t=2023-03-14T14:07:04.814025702Z level=debug msg="got secret value from cache" orgId=1 type=datasource namespace=Prometheus
```

**Comment by usmangt** [comment]
Thanks,

What is the default Grafana-backed database on your machine?

By default, if you do not define any then SQLite get installed as the default one.

The error in the logs is related to the backend db which says that it is in a locked state. I search more for this error and it seems to be related to SQLite as it is good if you are using it to monitor only a few amounts of the Dashboard n Panels but not recommended if you are monitoring a lot of things.

I found this [post](https://community.grafana.com/t/database-is-locked-unable-to-use-grafana-anymore/16557) at our community forums so might be good if you check it out.

Also, there is this [script](https://github.com/grafana/database-migrator) to migrate the existing SQLite DB to MySQL.

Please check and I hope it does help.

**Comment by mbrancato** [comment]
does Grafana expose metrics for that DB usage and can you define a "few" versus "a lot"? 

I only have 17 alerting rules.

Regardless, my issue was opened because of the error type returned. It implies there is a datasource error, but this appears to be a backend database issue, not from a "data source".

**Comment by mbrancato** [comment]
@usmangt 
I believe the issue here is that the alert state is never inspected.

There is a static alert name defined here:
https://github.com/grafana/grafana/blob/ae07bf7ce5792f6f7107e2602e20147f0f0ff7ec/pkg/services/ngalert/schedule/compat.go#L26

When the `errorAlert` function is called, the alert state `state.State` is never inspected to check the type of error that was returned. Regardless of what kind of error actually caused this, the error is set to a static `DatasourceError` string:
https://github.com/grafana/grafana/blob/ae07bf7ce5792f6f7107e2602e20147f0f0ff7ec/pkg/services/ngalert/schedule/compat.go#L121

**Comment by armandgrillet** [comment]
Even if the bug does not exist following Grafana 10, the fact that we are reporting an alert with `DatasourceError` instead of only a message displayed somewhere in the interface with a more detailed message is a bug.

**Comment by mbrancato** [comment]
Regarding the locking support on EFS. I do think that is an edge case, but in general, vfs locking likely needs to be exposed as a configurable option in the `grafana.ini`. Currently the vfs locking is not specified. 

https://sqlite.org/vfs.html

**Comment by santigijon** [comment]
I don't think the issue was resolved so writing this comment so that the issue does not close. I agree with @armandgrillet this should not trigger an alert. I am having the same issue, from time to time, I get this "level=error msg="Failed getting data source" err="database is locked"

**Comment by Dunge** [comment]
Using AWS EFS as the storage here. Still getting this error as of Grafana v11.3.0. I thought #91778 enabling WAL would fix it, but no it didn't!

Increasing the EFS throughput rate made it slightly better (it only happens every few weeks instead of every day days), but it's not a real solution. Switching it to a EBS (local) volume prevent Grafana from being highly available, so that's not a solution either.

But the most annoying thing, and what I assume is a bug here:

- Every single alarms configured trigger at once as a `DatasourceError` type
- It does NOT respect the `group_wait` and `group_interval` settings on the receiver policies. It triggers instantly.
