### ISSUE TITLE
postgres: tls-mode `verify-ca` does not work correctly (behaves like `verify-full`)

### ISSUE THREAD

**Issue by tomcastro89** [grafana/grafana#65816]
summary by @gabor  : the postgres TLS mode `verify-ca` does not work correctly, and behaves the same as `verify-full`. to reproduce:  try this scenario: https://github.com/grafana/oss-big-tent-tools/tree/main/tls-setups/postgres#verify-server-cert-ignore-host . it should work, but it does not.

---

**What happened**:
Grafana Versions >= 9.4.0 cause the following issues in Panels that use an PostgreSQL (AWS RDS) as Datasource and
the following TLS settings:

**Issues**

```
db query error: x509: certificate is valid for <DB instance url>, not <route53 url to db>
```
```
db query error: x509: certificate is not valid for any ....
```

**Settings**

Host: "insert AWS RDS Postgres Host route53"
Database: "insert DB name"
User+Password
TLS/SSL Mode: *verify-ca*
TLS/SSL Method: *Certificate content*
TLS/SSL Root Certificate: "insert official aws rds certificate"

PostgreSQL details
Version: *11*

*One*(the first) certificate out of the official AWS RDS root certificates eu-central-1 bundle is used:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
*[eu-central-1-bundle.pem](https://truststore.pki.rds.amazonaws.com/eu-central-1/eu-central-1-bundle.pem)*

**What you expected to happen**:
The panels should work in the same way they do in Grafana v9.3.8

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Grafana v9.3.8
2. Add an AWS RDS Postgres Database as Datasource incl. the TLS settings above
3. use a route53 to access the AWS RDS
4. it should work
5. upgrade Grafana to a Version >=9.4.0
6. the issues mentioned above should appear and the panels dont work

**Anything else we need to know?**:

**Environment**:
- Grafana version: >= 9.4.0
- Data source type & version: PostgreSQL
- OS Grafana is installed on: [Grafana official image](https://hub.docker.com/r/grafana/grafana) deployed as Stateful Set in Openshift

**Comment by idastambuk** [comment]
I think this is a ticket for the @grafana/grafana-bi-squad, as it’s a PostgreSQL datasource

**Comment by tomcastro89** [comment]
Hi,

the same issue appears now when updating grafana from 10.1.5 to 10.2.0.

Please look into it. Thanks!

**Comment by zoltanbedi** [comment]
Thanks for letting us know @tomcastro89. I'm going to reopen this issue.

**Comment by gabor** [comment]
fixed in https://github.com/grafana/grafana/pull/81353

**Comment by gabor** [comment]
unfortunately we had to revert the fix, has problems in certain corner-cases, so i'll reopen this one too. we'll adjust our fix and do it again.

**Comment by zoltanbedi** [comment]
We also fixed it for the Postgres datasource in https://github.com/grafana/grafana/pull/83768

**Comment by gabor** [comment]
fixed again in https://github.com/grafana/grafana/pull/85530 ( we had to roll back the previous fix)

**Comment by Vineetkhadloya** [comment]
@zoltanbedi @gabor I still see this issue when upgradind from v9.3.0 to v9.4.17. 
Was the fix backported to 9.4.x ?

**Comment by zoltanbedi** [comment]
@Vineetkhadloya it was not and it won't be. Sorry.

**Comment by erandu** [comment]
Hello,
We are facing this issue when upgrading from 9.5.14 to 11.4.0. This is curious because this should be fixed with https://github.com/grafana/grafana/pull/85530 ?
A fix that we found is to add `ssl_sni = 0` into grafana.ini
