### ISSUE TITLE
Dashboards: Parent folder link does not work when grafana is served from sub path

### ISSUE THREAD

**Issue by MiggL** [grafana/grafana#70047]
### 
# What went wrong?

**What happened**:
When viewing a dashboard, I tried to open the parent folder from the top left breadcrumb navigation in a new tab.
The opened page starts with url `https://<domain>/dashboards...` instead of `https://<domain>/<subpath>/dashboards...` and thus was a 404 page.

It actually works if you just left-click the button to open it in the same tab, but if you do anything else with the link (middle-click, right-click, copy link) it gets the wrong url.

**What did you expect to happen**:
That the correct page `https://<domain>/<subpath>/dashboards...` opens.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana served from sub path.

**Step 2**:

- Create a folder. (The General folder is not included in the breadcrumb navigation)

**Step 3**:

- Create a dashboard in this folder, save it.

**Step 4**:

- From the dashboard page, try to open the parent folder in a new tab from the breadcrumb navigation.
- Or, try to copy the link.
- Or, just look at the link url at the bottom of your browser while hovering the parent folder link.

### 
# What Grafana version are you using?

v9.5.3

### 
### Is the bug inside a Dashboard Panel?

No

### Grafana Platform?

Kubernetes

### User's OS?

Windows 10

### User's Browser?

Tested with Firefox ESR and a Chromium-based browser (Edge)

### Is this a Regression?

Yes

### Anything else to add?

This worked in Grafana 9.4 when the dashboard page breadcrumb navigation was a bit different.

**Comment by vsile** [comment]
The same issue

**Comment by ashharrison90** [comment]
hi @MiggL @vsile 👋 

this was fixed with https://github.com/grafana/grafana/pull/68308 and will be available in the next patch release of grafana 10

thanks for raising 🙌

**Comment by MiggL** [comment]
Hi @ashharrison90 
Thanks for the update. Shouldn't this be backported to Grafana 9? I assume many users, like me, will still use Grafana 9 during the next few months, and this is still an issue in the lastest patch version of Grafana 9.5

**Comment by MiggL** [comment]
All right, thanks.

**Comment by vsile** [comment]
Hello, @ashharrison90.
It still doesn't work with Grafana 10.2.3 on Dashboard pages.
![изображение](https://github.com/grafana/grafana/assets/9244347/0e98d837-5880-4a3d-9c4d-59a219115ba4)

It works with breadcrumb though
![изображение](https://github.com/grafana/grafana/assets/9244347/688717da-7559-48ec-a3fe-89b8833394b3)

**Comment by ashharrison90** [comment]
hi @vsile 👋 

i can't repro that locally, links work correctly for me. here i'm serving grafana under a `/grafana` subpath. note the link in the bottom left is correct:
![image](https://github.com/grafana/grafana/assets/20999846/991563df-7552-4500-9e5d-24fa1349ebeb)

what does your grafana config look like? you'll need something like:
```ini
[server]
root_url = <baseUrl>/<subPath>
serve_from_sub_path = true
```
