### ISSUE TITLE
Feature toggle removal: toggleLabelsInLogsUI

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#72437]
Added in https://github.com/grafana/grafana/pull/70328, on July 24, 2022. Consider whether we should release, including steps needed to validate readiness, or remove.

Enable toggleable filters in log details view.
Once we’re able to tell which query produced what log line we can fully release this feature.

**Comment by matyax** [comment]
Done in https://github.com/grafana/grafana/pull/74342

**Comment by ivanahuckova** [comment]
@matyax I'll reopened to have an issue that keeps track of  `toggleLabelsInLogsUI ` - so we have a reminder to remove the toggle (currently it still exists and defaults to `true`)

**Comment by matyax** [comment]
Good catch! I had a false memory that I actually removed it 🤦‍♂️
