### ISSUE TITLE
searchbox unable to input Chinese correctly

### ISSUE THREAD

**Issue by halleystar** [grafana/grafana#72864]
### What happened?

searchbox unable to input Chinese correctly Figure 1:

![image](https://github.com/grafana/grafana/assets/5334156/a2fe3ec1-35ab-472c-a144-1e393fcce72d)

when After input, it will look like Figure 2:

![image](https://github.com/grafana/grafana/assets/5334156/01ef157b-64f4-4166-9a21-36ffd7926532)

### What did you expect to happen?

able to input Chinese correctly

### Did this work before?

i dont know

### How do we reproduce it?

input Chinese in the searchbox

### Environment (with versions)?

Grafana: 10.0.1
OS: windows 11
Browser: chrome 115.0.5790.102

### Grafana platform?

Other

**Comment by JoaoSilvaGrafana** [comment]
Hi @halleystar ! Thanks for raising this! As I do not use Chinese characters, I am struggling a bit to be able to figure out what the issue is 😅  Could you give us an example of what you would expect to happen and what is wrong in your figures 1 and 2? Thank you!

**Comment by halleystar** [comment]
This is a bug in kbar. I only wanted to input the Chinese characters '你好'. but kbar also included the Pinyin input I used to spell '你好'.  The correct look should only contain "你好" and not contain any characters in front of "你好"

**Comment by JoaoSilvaGrafana** [comment]
Ah yes I see you raised an [issue](https://github.com/timc1/kbar/issues/327) on kbar , it does seem like something that needs to be fixed on that side so I will be closing this issue in favor of that one 👍

**Comment by timc1** [comment]
Hey all! This has been fixed in an earlier version of `kbar` already – make sure you use the latest release.

**Comment by halleystar** [comment]
Hey all! This is the version i reference:   "kbar": "^0.1.0-beta.41".  But the issue still exists
![动画](https://github.com/grafana/grafana/assets/5334156/2d4aa8c3-e103-4bdf-818c-f4dcd195dffa)

**Comment by ashharrison90** [comment]
dupe of https://github.com/grafana/grafana/issues/70883
