### ISSUE TITLE
Test user mapping for LDAP not visible- Grafana 10.1.0

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#73884]
### What happened?

Test user mapping for LDAP not visible in Grafana 10.1.0. Menu Authentication is missing
See: https://github.com/grafana/grafana/pull/71285

![Grafana 10 1 0 no menu Authentication](https://github.com/grafana/grafana/assets/56024424/2dbf5be6-6a5c-41a2-ba81-b74e15d5f545)

### What did you expect to happen?

"Test user mapping" for LDAP is visible in Grafana 10.1.0

### Did this work before?

Grafana 10.0.3

![Test user mapping Grafana 10 0 3](https://github.com/grafana/grafana/assets/56024424/84453237-c10d-49ec-b244-d999cedc3ffc)

### How do we reproduce it?

1. Install Grafana with Docker Image: docker pull grafana/grafana:10.1.0
2. Have a look at: Auth: Move LDAP debug to Authentication menu.
3. But: Authentication menu is not visible

### Is the bug inside a dashboard panel?

The bug is inside the menu structure I think.

### Environment (with versions)?

Grafana: 10.1.0
OS:          docker Image: docker pull grafana/grafana:10.1.0
Browser:  Chrome 116.0.5845.97 (Offizieller Build) (64-Bit)

### Grafana platform?

Docker

### Datasource(s)?

no

**Comment by mhollstein** [comment]
Where to find "Test user mapping" in Grafana 10.1.0 and above?

**Comment by eleijonmarck** [comment]
this should now be fixed and out with 10.1.1 - #73941

**Comment by mhollstein** [comment]
I still can't see the LDAP menu in Grafana 10.1.1  Please check.

![2023-09-13 07_27_20-Grafana](https://github.com/grafana/grafana/assets/56024424/9f864f95-571c-4aeb-ba4e-21f6f5f5685f)

**Comment by eleijonmarck** [comment]
@mhollstein could you help me identify a could of things?

What role is user you are using?

What are the configuration settings in your ini file?
- Do you have LDAP enabled for instance?
```ini
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
skip_org_role_sync = false
```

I have tried with a new installation of Grafana where I login as an admin.

Without LDAP enabled, the authentication tab is not going to be visable.

You need to have LDAP enabled for the authentication tab to be shown.

If you set the 
```
[auth.ldap]
enabled=true
```

It should show up, let me know if this is not the case

**Comment by mv-fachilles** [comment]
Having the same issue with v10.1.1 and LDAP is enabled:
![image](https://github.com/grafana/grafana/assets/30074528/763285e3-a5e2-4359-b6e9-9ba29120557e)

**Comment by This-is-me-now** [comment]
We have the same problem... also no improvement with updating to 10.1.1. As one of my colleagues pointed out, fix is also not described in 10.1.1 change log so I asume this will be included in the next release at the earliest.

**Comment by mhollstein** [comment]
In 10.1.1 it is not visible with active LDAP.

**Comment by a1ea321** [comment]
Same here. I used `grafana/grafana:10.1.1` (docker). LDAP was working fine. I synced the users. Logged in with them. After a while (after I restarted the OpenLDAP server?) it stopped working. When a user tries log in, the account gets disabled.

**Comment by kiper-prog** [comment]
In 10.1.2 it is also not visible when LDAP is active.

**Comment by eleijonmarck** [comment]
@mv-fachilles could you let me know which user role you login as? ServerAdmin, or do you login as a orgadmin?

**Comment by eleijonmarck** [comment]
I see no issues from the current setup. The following is a clean grafana setup from scratch from main where we have not changed any of the settings.

My initial thoughts was:
- perhaps the authentication page is not shown, due to the LDAP server not responding, however even with a failed configuration the page is loading.

https://github.com/grafana/grafana/assets/7727602/4274da47-4b2d-4049-ae3e-f014e0eee803


Next steps are to check this with a docker container

**Comment by eleijonmarck** [comment]
@kiper-prog What basic role are you within the org?

**Comment by mhollstein** [comment]
Hello Eric, 
I am a ServerAdmin. I've done an update from 10.1.2 to 10.1.5 and now I can see the "Authentication" inside the Administration menu. Here are the screenshots: https://github.com/grafana/grafana/issues/75364

**Comment by mv-fachilles** [comment]
@eleijonmarck my user is server admin 
![image](https://github.com/grafana/grafana/assets/30074528/1d0a2079-89b5-47f4-837c-5dba62d1c71d)

But same as @mhollstein the issue is solved for me with upgrading to v10.1.5

**Comment by eleijonmarck** [comment]
thank you all for confirming. The fix is to upgrade to version v10.1.5
