### ISSUE TITLE
Alerting: oldest alert configuration is returned instead of latest

### ISSUE THREAD

**Issue by glc-froussel** [grafana/grafana#74690]
### What happened?

Since v9.4.0, when you add a contact point in the alerting dashboard, the operation is successful but UI does not display the new contact point. Same behavior if you update an existing contact point.

This seems to be related to this commit : https://github.com/grafana/grafana/commit/0e7640475fccfcc74bfe7909b5cd963e83775705

Before :
```go
func (st *DBstore) GetLatestAlertmanagerConfiguration(ctx context.Context, query *models.GetLatestAlertmanagerConfigurationQuery) error {
        ...
	// The ID is already an auto incremental column, using the ID as an order should guarantee the latest.
	ok, err := sess.Desc("id").Where("org_id = ?", query.OrgID).Limit(1).Get(c)
```
After :
```go
func (st *DBstore) GetLatestAlertmanagerConfiguration(ctx context.Context, query *models.GetLatestAlertmanagerConfigurationQuery) error {
        ...
	// The ID is already an auto incremental column, using the ID as an order should guarantee the latest.
	ok, err := sess.Table("alert_configuration").Where("org_id = ?", query.OrgID).Get(c)
```

`Desc("id)` has been removed and the query seems to return the oldest row instead of the latest.

### What did you expect to happen?

`GetLatestAlertmanagerConfiguration` method should return latest row instead of oldest.

### Did this work before?

Before 9.4.0 yes.

### How do we reproduce it?

1.Go to Alerting Dashboard
2.Add or update a contact point

### Environment (with versions)?

Grafana:>=9.4.0

### Grafana platform?

Other

**Comment by mellieA** [comment]
@glc-froussel which contact point are you trying to configure? I was able to add a new contact point and see it immediately with grafana 10.2.x

One thing to check is that you're adding the contact point to the correct alertmanager. There's a drop down in the top right corner: 

![Screenshot 2023-09-11 at 4 45 22 PM](https://github.com/grafana/grafana/assets/18175287/c63f357d-1353-48b0-b429-76a7c3919712)

**Comment by glc-froussel** [comment]
@mellieA I am using the internal Grafana alertmanager.

I also tried to upgrade to Grafana 10.1.x and same behavior.

One thing to note is that I have upgraded from 8.4.x following the migration guide. Everthing worked fine except this behavior on alerting configuration.

**Comment by rwwiv** [comment]
This was a frontend bug that was fixed with this PR: https://github.com/grafana/grafana/pull/73162 and is in v10.1.1

---

Regarding the backend query, this table was split into 2: one contains the history and one contains the current configuration. The change you're seeing was to support that split, and there should only ever be one row in the table this function is querying.

**Comment by glc-froussel** [comment]
@rwwiv I still have the issue on 10.1.1
 
> Regarding the backend query, this table was split into 2: one contains the history and one contains the current configuration. The change you're seeing was to support that split, and there should only ever be one row in the table this function is querying.

The fact is I see multiple rows in the table `alert_configuration`. Maybe I am missing something ?

**Comment by JacobsonMT** [comment]
@glc-froussel There will be one row per org, are the rows you're seeing from different orgs?
