### ISSUE TITLE
ServiceAccounts: db unique constraint violation when creating many concurrent serviceaccount permissions

### ISSUE THREAD

**Issue by mhulscher** [grafana/grafana#77462]
### What happened?

I am using the grafana terraform provider (2.4.0) to create a lot (>= 100) of serviceaccounts and assign each a serviceaccount permission of "Edit" on a team. This is using grafana enterprise 10.1.2.

I run my terraform apply with `-paralellism=25` . I frequently run into this error from grafana:

```
pq: duplicate key value violates unique constraint \"UQE_role_org_id_name\"
```

```
grafana-8c48d85b8-5hvqk grafana logger=context userId=1 orgId=1 uname=admin t=2023-10-31T17:10:01.662108993Z level=error msg="failed to set permissions" error="pq: duplicate key value violates unique constraint \"UQE_role_org_id_name\"" remote_addr=127.0.0.1 traceID=
grafana-8c48d85b8-5hvqk grafana logger=context userId=1 orgId=1 uname=admin t=2023-10-31T17:10:01.662154817Z level=info msg="Request Completed" method=POST path=/api/access-control/serviceaccounts/167 status=400 remote_addr=127.0.0.1 time_ms=104 duration=104.299496ms size=52 referer= handler=/api/access-control/serviceaccounts/:resourceID
```

![image](https://github.com/grafana/grafana/assets/18721288/3545d209-1d5d-44a9-9562-1683f23b4878)

Maybe important to mention; we only create serviceaccounts in the main org, not in other orgs (although those do exist).

Please let me know if you require more information.

### What did you expect to happen?

No errors.

### Did this work before?

This works sometimes.

### How do we reproduce it?

1. Use automation (ie terraform) to create over 100 teams, 100 serviceaccounts and 100 serviceaccount permissions

### Is the bug inside a dashboard panel?

N/A

### Environment (with versions)?

Grafana: 10.1.2 **enterprise**
OS: Ubuntu
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
hi @mhulscher 
I understand that this was solved in https://github.com/grafana/terraform-provider-grafana/pull/1130
Can you please confirm if the issue can be closed? thank you !

**Comment by mhulscher** [comment]
Hi @tonypowa , unfortunately the PR you mentioned does not solve this issue. It adds retries for 401s, but not 400s like what is happening here.

**Comment by julienduchesne** [comment]
Hey, the SA API has concurrency issues that result in both 400s and 500s. 

Both are problematic in their own way, the 500s are more so because sometimes SAs will be created through a 500 and the retry causes an unresolvable failure from TF's point of view (conflict)

I don't think retrying is the solution here, 400s shouldn't be retried by definition (401s neither but they're less problematic to retry). This requires a fix on the API side. For now, I've added a mutex on the TF side here: https://github.com/grafana/terraform-provider-grafana/pull/1161, so regardless of the parallelism, SAs should always be created one by one and that fixes the issue. Hopefully this shouldn't cause too much of a slow down since the API is pretty quick

**Comment by mhulscher** [comment]
@julienduchesne thanks for the update. The problem that I am describing here is with the grafana_service_account_permission resource. Is that also protected by this same mutex?

**Comment by julienduchesne** [comment]
I think so. Since it's a one-to-one relation between the SA and SA permissions, they should be created roughly one by one as well (permissions will be scheduled after SAs are created)

**Comment by gelicia** [comment]
This seems to have been resolved. Closing the issue.
