### ISSUE TITLE
Bug: Dashboard Imports - Variable datasources are lost on import when using "Export for sharing externally"

### ISSUE THREAD

**Issue by beeradb** [grafana/grafana#77961]
### What happened?

I created a dashboard where all panels use a datasource variable. When I export this "normally" it works as expected. When I export this for "Sharing externally" it overwrites my default panel datasources with a default I don't seem to be able to set.

### What did you expect to happen?

I expect that when I have a datasource query result set as the data sources that it works as expected.

### Did this work before?

I'm not sure.

### How do we reproduce it?

1. create a new dashboard.
2. Create a $DATASOURCE variable and ensure it gets a default value set via regex or some other method.
3. Create a panel using that $DATASOURCE.
4. Export the dashboard using "Export for sharing externally"
5. Import the dashboard.
6. Observe that all datasources have reset.

Concrete Example:

I created a single pane dashboard using as $DATASOURCE variable:

![Screenshot 2023-11-09 at 13 35 35](https://github.com/grafana/grafana/assets/294617/191df8bf-635d-4b71-be72-6cff89178e20)

Here's the dashboard json via the "JSON Model" page in dashboard settings:

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 100,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${DATASOURCE}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DATASOURCE}"
          },
          "editorMode": "code",
          "expr": "1",
          "instant": false,
          "legendFormat": "__auto",
          "range": true,
          "refId": "A"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": "grafanacloud-someorg-prom",
          "value": "grafanacloud-prom"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "DATASOURCE",
        "options": [],
        "query": "prometheus",
        "queryValue": "",
        "refresh": 1,
        "regex": "/.*-prom/",
        "skipUrlSync": false,
        "type": "datasource"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Datasource is lost",
  "uid": "c1a785fe-3632-475a-9ea2-48249c3452fe",
  "version": 2,
  "weekStart": ""
}
```

The same dashboard exported via the export tab with "Export for sharing externally" set:

```
{
  "__inputs": [
    {
      "name": "DS_GRAFANACLOUD-SOMEORG-PROM",
      "label": "grafanacloud-someorg-prom",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "10.3.0-63137"
    },
    {
      "type": "datasource",
      "id": "prometheus",
      "name": "Prometheus",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${DS_GRAFANACLOUD-SOMEORG-PROM}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_GRAFANACLOUD-SOMEORG-PROM}"
          },
          "editorMode": "code",
          "expr": "1",
          "instant": false,
          "legendFormat": "__auto",
          "range": true,
          "refId": "A"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": "grafanacloud-swirldslabsdev-prom",
          "value": "grafanacloud-prom"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "DATASOURCE",
        "options": [],
        "query": "prometheus",
        "queryValue": "",
        "refresh": 1,
        "regex": "/.*-prom/",
        "skipUrlSync": false,
        "type": "datasource"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Datasource is lost",
  "uid": "c1a785fe-3632-475a-9ea2-48249c3452fe",
  "version": 2,
  "weekStart": ""
}
```

Here's the result after importing the  "sharing externally" version:

![Screenshot 2023-11-09 at 13 40 10](https://github.com/grafana/grafana/assets/294617/08054b1a-04be-42ae-a7ab-08248e4a0b7c)

This is only somewhat problematic when importing via the UI because you can select the default datasource to use for the imported dashboard. However, as far as I can tell this is **completely broken** with no workaround if you import dashboards via terraform on the API, as I do not see a way via either of those methods to set the default datasource used for the dashboard.

### Environment (with versions)?

Grafana: Grafana v10.3.0-63137 (ffcaef9c17f55ad98690d70bb5953e1131361729)

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
Hi @beeradb 

Thank you for creating this issue

I can't reproduce it since, as you pointed out, you are asked to choose the panel's data source when importing the dashboard.

![image](https://github.com/grafana/grafana/assets/45235678/27015b1e-8794-4275-9375-736bcffcb1d4)

IMHO, this works as intended, but I will pass the issue to the Dashboard squad to double check.

**Comment by beeradb** [comment]
It doesn't seem this could be working as intended, as to me it provides a very inconsistent importing experience.

1. There's no "select datasource" option when importing [via terraform](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/dashboard) or [via the HTTP API](https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/). How can I replicate this behavior there? Should the same export behave differently depending on which API/method is used to import?

2. Does importing via the UI just now allow for variable datasources at all? I can understand (optionally) overwriting any static datasources, but if I've already set my datasource as a variable, shouldn't that be respected? Why am I forced to select here but not in other importing contexts?

**Comment by lucychen-grafana** [comment]
Hi @beeradb,

Thanks for submitting the issue. I was able to replicate the issue you are experiencing and can confirm that this is a bug. All template variables imported (both externally and internally) should be respected in the new dashboard including datasource as a variable. I will add this issue to our backlog to be fixed.

In regards to importing via terraform and HTTP API, that method is recommended for importing internally rather than externally because uid of datasource is used. External export/import does not use uid because different instances will have different datasources. It instead requires an input from user to select the datasource in the new instance that corresponds to the datasource from originating instance; hence I recommend using the UI for that. Let me know if you have any other questions/concerns

**Comment by beeradb** [comment]
I'm just checking in here - I know this is an open source project, and progress comes at its own pace, but is there any hope of getting this into an upcoming sprint?

As-is the dashboard import experience feels completely broken when trying to move dashboards between instances. Even though we could handle this with the tools provided by Grafana, such as standardizing our datasource UIDs and/or using variable selection, when we attempt to import dashboards with shared panes using terraform, all visualizations just show up blank. The only way we've found to make it work is manually importing via the UI and selecting the data source from the dropdown. This is workable for a single dashboard but as complexity grows, so does the cost of all this manual importing.

Respecting the datasource settings in the dashboard export when importing via the API would be a very welcomed fix.

**Comment by lucychen-grafana** [comment]
Closing this as there is a fix in place here https://github.com/grafana/support-escalations/issues/10104

**Comment by R-Studio** [comment]
> Closing this as there is a fix in place here https://github.com/grafana/support-escalations/issues/10104

I can't access the url.

**Comment by beeradb** [comment]
nor can I - could we get info on how this was fixed?

**Comment by evictorero** [comment]
This is the [PR](https://github.com/grafana/grafana/pull/86273) @lucychen-grafana mentioned. 
Can you confirm the issue is fixed?
I was able to import an external dashboard but I think there is still an issue with exported JSON, there is no need to create an input for the current DS if all DSs of the dashboard panels are managed by a ${datasource} variable.
I mean, in this particular case: 
```  "__inputs": [
    {
      "name": "DS_GRAFANACLOUD-SOMEORG-PROM",
      "label": "grafanacloud-someorg-prom",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ```

  Shouldn't be part of the JSON.

**Comment by chcatf** [comment]
@evictorero following the same reproduction steps listed in the post on Grafana 11, I am seeing that this is still an issue.
After importing a dashboard with a panel that originally used a variable data source, the data source was set to a default instead of ${dataSource}

**Comment by lucychen-grafana** [comment]
Hi @chcatf, this fix will be publicly available in the next minor release Grafana 11.1 schedule for 2024-06-25

**Comment by chcatf** [comment]
I've upgraded to v11.1.0 and dashboards imported from that version using "export for sharing externally" now use the same variables - thanks for the fix!

Is it expected that importing from a previous versions' dashboards exported using the sharing externally option will have the issue? i.e. exporting a dashboard with variables from grafana v9 and importing it to v11.1.0 will replace the variable.

**Comment by evictorero** [comment]
Yes, the fix was applied to the exported JSON, so it won't be compatible with previous versions.

**Comment by PabloEForgeFlow** [comment]
I am not sure this has been fixed entirely, as exporting a dashboard with a variable datasource (`prometheus_datasource`), still ends up with a datasource in the `__inputs` list (`DS_GRAFANACLOUD-INSTANCE-PROM`).

Within the json file, however, both `"uid": "${DS_GRAFANACLOUD-INSTANCE-PROM}" ` and  `"uid": "${prometheus_datasource}" ` can be found, without any apparent criterion. In the sections `templating.list[].datasource` and `panels[].targets[].datasource` both forms appear interspersed.

Additionally, a datasource of type `__expr__` also gets placed in the `__inputs` list as `DS_EXPRESSION`, which appears fairly pointless, but I guess this does not belong to the same issue.

The export was done from a Grafana Cloud instance in the free tier.

**Comment by notjames** [comment]
I believe that I'm also running into the same issue, but my use-case is a bit different.

I'm migrating from grafana running in a legacy virtual machine/baremetal machine environment into grafana running in EKS as grafana operator. I'm pulling the rules et al directly from grafana.db and generating grafana CR manifests.

The imports of the manifests work great! The variables exist! The issue is the variables are empty. If one goes into an established variable, everything in the variable is "empty." Everything else works great! I haven't important notification polices or contact policies yet.

**Comment by evictorero** [comment]
Thanks for reporting this. I could reproduce the issue. 
It might be related to an outdated exported JSON, but we need a way to update the dashboard JSON in the library or support the JSON generated before the fix when importing.
I'm reopening this issue to track it.

**Comment by hexxone** [comment]
Thank you for the fast reply!

> It might be related to an outdated exported JSON, but we need a way to update the dashboard JSON in the library or support the JSON generated before the fix when importing.

Yes indeed, it seems like most of the exported Dashboards are still targeting version 11.x - like the Node Exporter as well.

As a fix, It would be really nice if you can just select the existing `${dataSource}` variable in the dropdown for the DS-select in the UI - and maybe if the Dasboard does NOT have a DS-variable, even the possibility to create a new data source variable?

Then its no problem if it gets replaced in the whole Dashboard.

I think that would greatly benefit the usability. Especially for systems which always use multiple data sources and older dashboards, like in my case.

**Comment by juanicabanas** [comment]
@grafana/dashboards-squad  @grafana/grafana-dashboards-core I think this is related to the dashboard's team.
I took a look at the issue and the problem the following:
When importing the dashboard (previously exported to use in another instance), a datasource input is rendered when it shouldn't, because the panels are linked to a datasource template variable (where the type of datasource matters, not the instance of the datasource).
Although the input is rendered, @kaydelaney fixed part of this issue and the selection doesn't affect the result.
However
1. We should get rid of that input
2. The dashboard JSONs in the Grafana catalog are not updated with the latest change of @kaydelaney . Example: https://grafana.com/grafana/dashboards/1860-node-exporter-full/ still links the panels to the datasource input
 
I'm also not sure how much of this will change with schema v2

**Comment by crabique** [comment]
Reading the entire issue, it's still not clear: Is that an intended flow that it replaces my `${CLUSTER}` dataset variable in all instances by stuff like `${DS_SOME-CLUSTER}` which is just a `DS_` prefix + uppercased _alphabetically first_ item in the datasource selector at the time of export? 

Why can't it just remain `${CLUSTER}` in both the panels and the `__inputs`? The name of the selector variable remains `${CLUSTER}`, so it stops being used by anything else, and I don't quite understand the logic here.

**Comment by harisrozajac** [comment]
The PR above will address this issue. I'm hoping it provides some clarity.
