### ISSUE TITLE
Alerting: Failed to build evaluator for queries and expressions after adding and removing a node

### ISSUE THREAD

**Issue by elibroftw** [grafana/grafana#78333]
### What happened?

When I click preview, I get Failed to build evaluator for queries and expressions: unable to find dependent node 'D'. This happens after I add a new query node and then delete the query node.

### What did you expect to happen?

Preview should just work.

### Did this work before?

Before I added the query node yes,

### How do we reproduce it?

1. Copy an alert
2. Create a new query node
3. Delete query node
4. Click preview

### Is the bug inside a dashboard panel?

![image](https://github.com/grafana/grafana/assets/21298211/b17598a5-6dd6-403a-967d-0de356f284e1)

### Environment (with versions)?

Grafana: Grafana v9.4.7
OS: Windows 10
Browser: Firefox

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
hi @elibroftw 

>Delete query node

Do you mean to delete the query that was already there (the alert was copied), or to delete the new query you just created?

I can reproduce the error, but only if I delete the query that came with the copied alert. This is expected, because the query id (query name A) gets deleted while it is still used in the Reduce expression.

**Comment by elibroftw** [comment]
Means delete the new query node.

**Comment by tonypowa** [comment]
I'm afraid I still cannot reproduce it. Even when I delete the new query, the expressions' input update accordingly.
Could you please record a gif to make sure that I am not missing anything?

Thank you

**Comment by elibroftw** [comment]
https://github.com/grafana/grafana/assets/21298211/31d9bc6e-6696-4de1-9553-55f3293a77fa

**Comment by tonypowa** [comment]
thank you for providing the recording
one last question,: is this issue also reproducible with other data sources besides your AWS data source ?

**Comment by elibroftw** [comment]
Should be as the node auto changes its input

**Comment by tonypowa** [comment]
@elibroftw Could you please try to reproduce it with a different data source? This will help me to route the issue to the appropriate team. Thank you

**Comment by chilsenb** [comment]
@tonypowa I encountered a possibly related problem upgrading from 10.1.5 to 10.2.3.

Existing AWS timestream alerts break with this error, but for node A, the timestream query. Grafana retries the query dozens of times a second.

I deleted the alerts and the system stabilized. I created a new alert from an existing timestream query panel, and the same thing happened.

Next, I created a blank alert, with the timestream datasource. After selecting a database and table, but before I can select a metric, the same thing happens. "Failed to build evaluator for queries and expressions," dozens of errors / timestream requests per second -- with a completely blank query.

In all three cases, the preview button is flickering between "Preview" and "Cancel" -- suggesting something has broken with the preview logic / timing.

This only happens for AWS timestream. Rolling back to 10.1.5 resolved the problem.
Note that the repeated requests generate timestream expenses, so testing this should be done with care.

Grafana version: 10.2.3, running on Amazon Linux 2023
timestream plugin version: 2.8.0

**Comment by idastambuk** [comment]
I can confirm this is an issue caused by Timestream query running. Working on getting a fix out!

**Comment by idastambuk** [comment]
Hi @chilsenb, @tonypowa, we just released Timestream@2.9.0 with the fix

**Comment by bemorr** [comment]
This does not appear to be fixed - I'm still experiencing the same issue - Timeseries plugin 2.9.0 is installed - in fact, it's a fresh upgrade of Grafana (9->10) so have only ever had 2.9.0 this issue with this release

**Comment by chilsenb** [comment]
Timestream plugin 2.9.0 did fix the issue I described above on my installation.

**Comment by idastambuk** [comment]
Hi @bemorr, can you describe exactly what is happening with your alerts? Im unable to reproduce the bug in 2.9.0 as described in the original post
