### ISSUE TITLE
Issue Adding Users to an Organization as Grafana Admin in Grafana OSS 10.2.0

### ISSUE THREAD

**Issue by ceccillia** [grafana/grafana#79062]
### What happened?

Hello,

I am experiencing an issue with Grafana OSS version 10.2.0 where I, as a Grafana Admin, am unable to add users to an organization created by another user.

As an admin user (let's call this user admin), I am trying to add a user (user2) who is not part of any organization into an organization (org1) created by another user (user1). However, when attempting to do this, I encounter an error message stating: "You'll need additional permissions to perform this action. Permissions needed: org.users: add".
I have the following permissions set:

'org.users:add': ['users:*', 'users:*']
'org.users:read': ['users:*', 'users:*', 'users:*', 'users:*', 'users:*']
'org.users:remove': ['users:*', 'users:*']
'org.users:write': ['users:*', 'users:*']

### What did you expect to happen?

As an admin, I should have the necessary permissions to add users to any organization.

### Did this work before?

This worked on 10.1.5

### How do we reproduce it?

1.  Log in as admin.
2. Try to add user2 to org1.
3. Encounter the permission error.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: OSS 10.2.0
OS: Centos 7
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by ccataha** [comment]
This issue is also reproducible in 10.2.1, 10.2.2 in docker and service-based environments.

**Comment by WeetA34** [comment]
Hello,
same issue here.
It seems only Grafana Admin + destination organization admin can add users for this destination organization.

**Comment by iXingo** [comment]
same here

**Comment by tonypowa** [comment]
hi @ccataha 

I reproduced the issue in Grafana v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)

Note for the reviewer:

*Updated repro steps:*

1. Log in with any admin
1. Create a new user and remove the default org it is assigned to
1. Create another user and give it server admin permission 
1. Log out
1. Log in with this new admin user 
1. Create a new org
1. Log out
1. Log in with the admin of step 1.
1. Fnally, try to assign the user created in step 2 to the new org

**Comment by tonypowa** [comment]
Uncaught (in promise) 
Object { status: 403, statusText: "Forbidden", data: {…}, config: {…}, traceId: undefined }
actions.ts:127
![image](https://github.com/grafana/grafana/assets/45235678/6b6ef57b-3a26-4e7e-ae6f-96d5ad915480)

**Comment by iXingo** [comment]
any updates on this bug?

**Comment by fabioasdias** [comment]
so just we are clear:
- grafana system admin user can't add themselves to an existing org they are not part of
- admin special user works.

So this "security" patch is forcing me to use the admin user and share that password across different people? That's unfortunate...

**Comment by gamab** [comment]
Hey :wave: 
Thanks for the report! We fixed this issue with: https://github.com/grafana/grafana/pull/81552 this will be available in `10.4` :pray:

**Comment by MrXo** [comment]
I'm still experiencing this issue in Grafana v11.1.0 (5b85c4c2fc).

As a Grafana admin I can see the organization I want to add myself to, but I get the same error: "You'll need additional permissions to perform this action. Permissions needed: org.users: add".

Additionally when I want to open the Org's settings I get:
"You'll need additional permissions to perform this action. Permissions needed: org.users: read"
"You'll need additional permissions to perform this action. Permissions needed: orgs: read"

**Comment by marcanio** [comment]
Also seeing this Grafana v11.1.0 and was not seeing it on V11.0.0. 

Same as @MrXo, but as Grafana admin I can not add myself to other orgs but yet I can go to other users and add them to other organizations just fine. Getting the same errors as listed above when I try to make any edits to my user in Grafana though.

**Comment by Cimbel** [comment]
I see issue happens on v11.1.3. I'm using Administrator user with GrafanaAdmin privileges and cannot assign neither myself nor other users to other orgs. I additionally disabled the following options:
```
permission_validation_enabled: false
permission_cache: false
```
I created a basic auth user with password and email by Grafana Administrator(default admin) and I was able only assign a role for main org. I wasn't able to assign role another org or add user to another org.
How to reproduce it
* Login to Grafana UI under Global admin@localhost.
* Create simple user with password and email in Main Org.
* Try to add this newly created user into some existing org, but Grafana admin user shouldn't be in that org

It's still sad because though I'm GrafanaAdmin I cannot add anyone to another org including myself. I'm using Enterprise edition.

**Comment by IevaVasiljeva** [comment]
Hi all! We have another fix on top of the previous fix - [this PR](https://github.com/grafana/grafana/pull/92024)  should allow server admins to add/remove users to orgs that server admin doesn't belong to. The fix will be released together with Grafana 11.3.0 and will try to backport it to patch versions of 11.1.x and 11.2.x as well (the issue was introduced in 11.0.4).

Also a heads up that in the long term we're planning to change server admin org memberships by assuming that all server admins are members of all organizations. Our thinking is that if server admins always have the permissions to be admins in all organizations, it feels like false security to not consider them as admins.

**Comment by IevaVasiljeva** [comment]
I've merged the fix and backported it to 11.1.x. So this issue should hopefully be fixed in 11.2.0 as well as the next patch of 11.1.x (should be 11.1.5). I'll close this issue for now, but please shout if you're still experiencing problems, in which case we will reopen the issue and keep investigating.

**Comment by TyIsI** [comment]
Commenting for posterity, with the added comment that I'm waiting for the Docker image for 11.1.5 to be released.

Ran into this on Docker grafana/grafana:11.1.4

**Comment by zktaiga** [comment]
> I've merged the fix and backported it to 11.1.x. So this issue should hopefully be fixed in 11.2.0 as well as the next patch of 11.1.x (should be 11.1.5). I'll close this issue for now, but please shout if you're still experiencing problems, in which case we will reopen the issue and keep investigating.

I think it's still broken in `11.1.5`. I don't get the error people are mentioning after the upgrade from 11.1.0, but I (as a server admin) don't have the ability to add a user to another org. I can look at the org and see the users in it, but I can't seem to go to a user profile and add them to it.

**Comment by IevaVasiljeva** [comment]
> Commenting for posterity, with the added comment that I'm waiting for the Docker image for 11.1.5 to be released.
> 
> Ran into this on Docker grafana/grafana:11.1.4

Looks like 11.1.5 is available ([here](https://hub.docker.com/r/grafana/grafana/tags?page=&page_size=&ordering=&name=11.1.5)). I can also see an Enterprise release for 11.1.4 ([here](https://hub.docker.com/r/grafana/grafana-enterprise/tags?page=&page_size=&ordering=&name=11.1.4)) which you can use without a license (enterprise features will be disabled, but it should work fine otherwise), but don't see it for OSS. I'll check if we're planning to publish 11.1.4 OSS image.

**Comment by zktaiga** [comment]
> > I think it's still broken in `11.1.5`. I don't get the error people are mentioning after the upgrade from 11.1.0, but I (as a server admin) don't have the ability to add a user to another org. I can look at the org and see the users in it, but I can't seem to go to a user profile and add them to it.
> 
> Could you please provide some more details about your issue? Are you using OSS Grafana or licensed Enterprise version? What do you see and what error are you getting when you try to navigate to a user's profile page?
> 
> I just tested on 11.1.5 locally and it worked for my test setup. This is what I used for testing:
> 
>     * Grafana OSS v11.1.5;
> 
>     * two orgs - org 1 and org 2;
> 
>     * user A who is Grafana Server Admin, and a Viewer of org 1 but doesn't belong to org 2;
> 
>     * user B who is a Viewer in org 1;
> 
>     * user A can add user B to org 2.

Grafana OSS.

Was on 11.0.0, went through the upgrade path of 11.0.0 -> 11.1.5 -> 11.2.0. Since 11.1.5 I could now see users in the new org (no error messages when browsing to `https://host/admin/orgs/edit/2` like was described in this Github issue. 

Following scenario is on 11.1.5/11.2.0.

- User A, synced via Generic OAuth, is a server admin and admin of org 1. Not part of org 2.
- User B, created manually, is a server admin and admin of org 2. Not part of org 1.

Behavior:
- User A can add User B into org 1.
- User B cannot add User A into org 2.
- User A cannot add itself into org 2 despite being server admin.

**Comment by IevaVasiljeva** [comment]
> Following scenario is on 11.1.5/11.2.0.
> 
> * User A, synced via Generic OAuth, is a server admin and admin of org 1. Not part of org 2.
> * User B, created manually, is a server admin and admin of org 2. Not part of org 1.
> 
> Behavior:
> 
> * User A can add User B into org 1.
> * User B cannot add User A into org 2.
> * User A cannot add itself into org 2 despite being server admin.

I think that might be because of the IdP role sync - we extended it to support multi-org mapping in 11.1.0 ([PR](https://github.com/grafana/grafana/pull/87394)). We expect each user's roles and org memberships to be either manually assigned or synced from the IdP provider but we don't allow the mix of both.

To check if this is the case, try setting `skip_org_role_sync` to `true` under `[auth.generic_oauth]` section in the config file and restart your instance. This should allow manually adding user A to orgs and setting user A's permissions.

In the long term, you could either keep automatic role sync disabled if you want to manually manage users' roles and org memberships, or configure `org_mapping` to map user to several orgs automatically. There's more info about it in [these docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configure-role-mapping).

**Comment by zktaiga** [comment]
> but we don't allow the mix of both.

TIL! That was it, thanks!

**Comment by IevaVasiljeva** [comment]
> TIL! That was it, thanks!

Nice! Glad that we got to the bottom of it :)

**Comment by TyIsI** [comment]
Can confirm that this is indeed fixed in grafana/grafana:11.1.5 image.

**Comment by jellyfish-headphones** [comment]
Still seeing this issue on Grafana 11.2.0.

I use organizations to give various teams their own dashboards. I created some organizations in the past (I think I was on some 10.x version) and added myself users to these orgs, but since upgrading, I, as a Grafana Admin, cannot add users to these organizations anymore. It seems like I am no longer a part of these organizations and I cannot even add myself to them. "You'll need additional permissions to perform the action (...)" etc.

I can create new orgs and add users to them, but orgs I made prior to the upgrade I cannot touch.

We use Generic OAuth to give ourselves as admins the admin role, and we don't give end users any role in the OAuth token so that they initially sign into the Main Org with a role of "None" and then we manually place them into their organization (could never get automatic org-mapping to work). Tried setting `skip_org_role_sync` to true but to no avail.

Can anyone relate? Am I missing some key point here?
