### ISSUE TITLE
Dashboard: TypeError: We.type is undefined, when entering a new metrics into visualization

### ISSUE THREAD

**Issue by bbqrob** [grafana/grafana#82873]
### What happened?

Hitting the "run queries" button while entering a new metric makes the metric unchangable and pops up the following error:

```
TypeError: We.type is undefined
```

![image](https://github.com/grafana/grafana/assets/1068861/31f1eb2d-233a-4fbc-8b16-316c6e23bf0d)
[full-log.txt](https://github.com/grafana/grafana/files/14307567/full-log.txt)

### What did you expect to happen?

I didn't expect an error popping up.

### Did this work before?

Yes.

### How do we reproduce it?

1. Created a fresh Visualization in an existing dashboard
2. Enter a random (non-empty) metric (completion is displayed correctly for existing types)
3. Click "run queries" button

### Environment (with versions)?

Grafana: v10.3.3 (252761264e)
OS: Ubuntu Linux 22.04.3 (grafana is running containerized)
Docker: v24.0.5, build 24.0.5-0ubuntu1~22.04.1
Browser: Firefox 122.0.1 (64-bit), Windows 11

### Grafana platform?

None

### Datasource(s)?

prometheus v2.50.0-rc.0

**Comment by bbqrob** [comment]
Just tried it out with prometheus v2.49.1 - same behaviour. So "maybe" not related to the datasource.

**Comment by plasmastorm** [comment]
Seeing the same with prometheus 2.50.0 datasource, full expanded error looks like this:

```
TypeError: We.type is undefined

N@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:5608:8893
WithTheme(undefined)
div
g@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:5818:3925
div
m@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:26:25714
u@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:26:23367
31697/je<@http://10.10.10.1:3000/public/build/1697.ba74e2de8c65e37f1de4.js:98:4764
Ta@http://10.10.10.1:3000/public/build/1697.ba74e2de8c65e37f1de4.js:98:6913
i@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:1:194
o@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:192:118841
g@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:192:119350
div
div
div
fs@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:124:25127
It@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:187:4993
za@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:124:29669
Rs@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:124:29787
E@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:425:57
div
K@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:4108:820
div
mu@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:124:30083
It@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:187:4993
y@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:187:2686
Xo@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:124:12769
ft@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:66:950
Oa@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:124:14520
g@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:4109:6041
div
div
div
div
div
q@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:124:36552
u@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:192:29680
H@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:4114:56
Hs@http://10.10.10.1:3000/public/build/DashboardPageProxy.309311965b4cd0612f76.js:315:9492
div
r@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:284:49410
div
56746/mn<@http://10.10.10.1:3000/public/build/DashboardPageProxy.309311965b4cd0612f76.js:315:10932
div
div
i@http://10.10.10.1:3000/public/build/8474.aca7493112eb29aea9e3.js:1:2302
div
i@http://10.10.10.1:3000/public/build/8474.aca7493112eb29aea9e3.js:1:4290
_@http://10.10.10.1:3000/public/build/8474.aca7493112eb29aea9e3.js:1:9608
div
i@http://10.10.10.1:3000/public/build/8474.aca7493112eb29aea9e3.js:1:2302
div
i@http://10.10.10.1:3000/public/build/8474.aca7493112eb29aea9e3.js:1:4290
_@http://10.10.10.1:3000/public/build/8474.aca7493112eb29aea9e3.js:1:9608
div
div
div
U@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:357:21339
Xs@http://10.10.10.1:3000/public/build/DashboardPageProxy.309311965b4cd0612f76.js:332:526
Ut@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:183:66326
WithTheme(Connect(Xs))
vn@http://10.10.10.1:3000/public/build/DashboardPageProxy.309311965b4cd0612f76.js:407:474
DashboardPage
Ut@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:183:66326
So@http://10.10.10.1:3000/public/build/DashboardPageProxy.309311965b4cd0612f76.js:407:6555
Suspense
o@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:192:118841
Gc@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:5420:9842
ve@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:228:23578
la@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:209:4753
Zn@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:209:10235
el@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:228:11785
ve@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:228:25773
div
div
main
div
ag@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:5420:2396
la@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:209:4753
Zn@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:209:10235
_n@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:209:9695
Il@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:228:12076
ve@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:228:19749
div
i@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:212:13888
v@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:41:14038
p@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:662:233839
c@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:566:21337
o@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:192:118841
g@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:192:119350
Re@http://10.10.10.1:3000/public/build/9733.976a8afd1c8ec137399a.js:187:521
Eu@http://10.10.10.1:3000/public/build/8378.36d9cd16557e09d3c339.js:5431:122

**Comment by jbaiter** [comment]
Going back to Prometheus 2.45.0 fixes it for me, so this seems to be a problem with newer Prometheus versions.

**Comment by WolleTD** [comment]
> Going back to Prometheus 2.45.0 fixes it for me, so this seems to be a problem with newer Prometheus versions.

Weirdly, can't confirm, although I'm certain this issue started when prometheus got updated yesterday on my server. I'm running `latest` docker container, just tried `v2.45.0` and issue persists, even after restarting Grafana for good measure.

**Comment by salmaan25** [comment]
As @jbaiter pointed out the issue is with type and help in metrics metadata. 
Going back to Prometheus 2.45.3 fixed it for me.

**Comment by NETertainer** [comment]
Fix coming (https://github.com/prometheus/prometheus/pull/13633).

**Comment by itsmylife** [comment]
Thank you for reporting this. It was an issue with Prometheus `v2.50.0` and was fixed.
The new version of Prometheus `v2.50.1` is coming up https://github.com/prometheus/prometheus/pull/13641
This will fix the issue. Closing the fix in place and the new version will soon be in the market.

**Comment by tunix** [comment]
I still have this issue with prometheus-server `v2.50.1` and Grafana `10.3.3`

**Comment by itsmylife** [comment]
@tunix Could you please clear the browser cache and try again? With Prometheus `v2.50.1` this was resolved.

**Comment by tunix** [comment]
@itsmylife yes it seems to be gone now. Thanks!
