### ISSUE TITLE
[BUG?] MySQL Query: Result of 0 shows as undefined.

### ISSUE THREAD

**Issue by MartynKeigher** [grafana/grafana#8531]
Hey all, 

While I know and appreciate its still in Alpha, has anyone seen/experienced, or even better... fixed this yet?? 

![image](https://cloud.githubusercontent.com/assets/3298134/26755158/6185db32-484d-11e7-8dcb-1a577a7717b3.png)
_as expected._

![image](https://cloud.githubusercontent.com/assets/3298134/26755161/721c3824-484d-11e7-9bba-d2b03cef7c29.png)
_undefined, when it should be 0_

Thanks.

_More Info_
- What Grafana version are you using? v4.3.2 (commit: ed4d170)
- What datasource are you using? MySQL
- What OS are you running grafana on? Ubuntu 16.04.1
- What did you do? Ran a SQL query with a _known result_ of 0, in a singlestat tile.
- What was the expected result? 0
- What happened instead? undefined

**Comment by torkelo** [comment]
What format are you returning, time series or table format? Time series require value column and time_sec column

**Comment by MartynKeigher** [comment]
**Table** format.

Time_series gives me an 'expected' error: `Found row with no time value`

Here is the 'literal' result...
![image](https://cloud.githubusercontent.com/assets/3298134/26755944/74287078-485d-11e7-8f61-96b3365c1050.png)

**Comment by daniellee** [comment]
Looks like a bug in the single stat panel rather than a bug in the MySQL data source. Will fix now.

**Comment by aehmge** [comment]
Ugly Workaround when you only got positive Integer values from mySQL:

Use the CASE Function in mySQL to MAP the 0 to -1:

SELECT 
CASE a.value
   WHEN 0 THEN -1
   ELSE a.value 
END as Anzahl 
FROM ( ...
) a

Revert this with the "value mapping" inside the singlestat widget:
![grafik](https://user-images.githubusercontent.com/3597383/26973745-2b11e184-4d18-11e7-97db-e63998795880.png)

So everything works now, 0 is displayed and value coloring works.
First i tried "WHEN 0 THEN '0'" this works only for displaying 0, but coloring didn't work with strings.

**Comment by daniellee** [comment]
It's fixed in the latest nightly build and the fix will be included in the coming 4.4.0 release.

**Comment by MartynKeigher** [comment]
Thank you so much guys for all of your efforts on this!! Much appreciated!

**Comment by ravinoz** [comment]
I know this issue is marked "Closed" but I'm still experiencing the exact problem under Grafana v4.5.2 (commit: ec2b0fe)

I've checked "public/app/plugins/panel/singlestat/module.ts" and public/app/plugins/panel/singlestat/specs/singlestat_specs.ts and @daniellee 's changes in f7c48c5  are there. 

anything I'm missing or is anyone else still experiencing this issue?

Thanks.

**Comment by daniellee** [comment]
@ravinoz what problem are you seeing exactly? Seems to work for me - I tested with a mysql query that returns nothing and the value mapping worked:

![image](https://user-images.githubusercontent.com/434655/33933605-8cb369d2-dff6-11e7-9e0b-4246542ba896.png)

**Comment by ravinoz** [comment]
Thanks @daniellee,

Unfortunately I wasn't able to simplify the query for generic repro my SQL query looks like below, and when I'm running it in the sql console I get "empty set"
```
mysql> SELECT Count(JOB_TICKET.JOB_TICKET_ID) AS CountOfJOB_TICKET_ID FROM JOB_TICKET WHERE (((JOB_TICKET.ASSIGNED_TECH_ID) Is Null) AND ((JOB_TICKET.REPORT_DATE) Is Not Null) AND ((JOB_TICKET.CLOSE_DATE) Is Null) AND ((JOB_TICKET.STATUS_TYPE_ID) Not In (3,4,5)) AND ((JOB_TICKET.TECH_GROUP_LEVEL_ID) In (7)) AND ((JOB_TICKET.DELETED)=1)) GROUP BY JOB_TICKET.LOCATION_ID HAVING (((JOB_TICKET.LOCATION_ID)=13))
    -> ;
Empty set (0.01 sec)
```
I can't paste a screenshot here (can only paste text) for some reason, but the panel JSON is this one (sorry for the long text)
```
{
  "cacheTimeout": null,
  "colorBackground": false,
  "colorValue": true,
  "colors": [
    "rgba(7, 177, 0, 0.7)",
    "rgba(237, 129, 40, 0.89)",
    "rgba(245, 54, 54, 0.9)"
  ],
  "datasource": "webhelpdesk",
  "format": "none",
  "gauge": {
    "maxValue": 100,
    "minValue": 0,
    "show": false,
    "thresholdLabels": false,
    "thresholdMarkers": true
  },
  "height": "",
  "hideTimeOverride": false,
  "id": 4,
  "interval": null,
  "links": [
    {
      "dashUri": "db/helpdesk-syseng",
      "dashboard": "Helpdesk - SysEng",
      "title": "Helpdesk - SysEng",
      "type": "dashboard"
    }
  ],
  "mappingType": 1,
  "mappingTypes": [
    {
      "name": "value to text",
      "value": 1
    },
    {
      "name": "range to text",
      "value": 2
    }
  ],
  "maxDataPoints": 100,
  "nullPointMode": "connected",
  "nullText": null,
  "postfix": "",
  "postfixFontSize": "50%",
  "prefix": "",
  "prefixFontSize": "50%",
  "rangeMaps": [],
  "span": 3,
  "sparkline": {
    "fillColor": "rgba(31, 118, 189, 0.18)",
    "full": false,
    "lineColor": "rgb(31, 120, 193)",
    "show": false
  },
  "tableColumn": "CountOfJOB_TICKET_ID",
  "targets": [
    {
      "alias": "",
      "format": "table",
      "rawSql": "SELECT Count(JOB_TICKET.JOB_TICKET_ID) AS CountOfJOB_TICKET_ID\nFROM JOB_TICKET\nWHERE (((JOB_TICKET.ASSIGNED_TECH_ID) Is Null) AND ((JOB_TICKET.REPORT_DATE) Is Not Null) AND ((JOB_TICKET.CLOSE_DATE) Is Null) AND ((JOB_TICKET.STATUS_TYPE_ID) Not In (3,4,5)) AND ((JOB_TICKET.TECH_GROUP_LEVEL_ID) In (7)) AND ((JOB_TICKET.DELETED)=0))\nGROUP BY JOB_TICKET.LOCATION_ID\nHAVING (((JOB_TICKET.LOCATION_ID)=13));\n\n",
      "refId": "A"
    }
  ],
  "thresholds": "1,2",
  "timeFrom": null,
  "title": "Unassigned Tickets",
  "transparent": false,
  "type": "singlestat",
  "valueFontSize": "120%",
  "valueMaps": [
    {
      "value": "null",
      "op": "=",
      "text": "N/A"
    }
  ],
  "valueName": "avg"
}
```

Maybe a conflicting setting somewhere in my panel?

**Comment by meshfx** [comment]
Hey @daniellee are you able to show the mysql you used to test this one?

**Comment by meshfx** [comment]
@ravinoz @daniellee interestingly, if I purposely introduce an error into the code the mapping works?!?!

For example, I was messing around with the code and made a type.. 
"SELECT Count(JOB_TICKET_ID AS CountOfJOB......"  The closing bracket is missing..    sure enough the end result on screen is now N/A or any word I put in the mapping.  BUT obviously the mysql is broken so there is an error.  I fix the mistake and it goes back to displaying an error.

So it is a case that somewhere in this mysql;
SELECT Count(JOB_TICKET_ID) AS CountOfJOB_TICKET_ID, TECH.USER_NAME, TECH.SUPERVISOR_ID
FROM TECH INNER JOIN JOB_TICKET ON TECH.CLIENT_ID = ASSIGNED_TECH_ID
WHERE (((JOB_TICKET.REPORT_DATE) Is Not Null) AND ((JOB_TICKET.CLOSE_DATE) Is Null) AND ((JOB_TICKET.STATUS_TYPE_ID) Not In (4,5)) AND ((JOB_TICKET.TECH_GROUP_LEVEL_ID) In (5,7)) AND ((JOB_TICKET.DELETED)=0))
HAVING (((TECH.USER_NAME)='daniello') AND ((TECH.SUPERVISOR_ID)=3))

The panel loses the result?  but doesn't error out the mysql and when there is a value all the colour options work exactly how they should dependent on the number of tickets in a tech queue.

**Comment by meshfx** [comment]
Everyone stand down.. I think it was just clumsy SQL that was confusing Grafana.  When I looked at the code I realised I didn't actually need an inner join (I was leveraging the SQL from another query for this task).  When I stripped it all the way back to the bare bones.. it works now.  This can be considered CLOSED.  thanks

**Comment by ravinoz** [comment]
Thanks @meshfx. I was hopeful for a moment there, but I guess I'm yet to find the cause to my issue (still getting "undefined" in the panel)

**Comment by ravinoz** [comment]
@meshfx bang on. Working for me to.

@daniellee all good, thanks. Problem solved (by fixing the SQL query)
