### ISSUE TITLE
[Feature Request] support cockroachdb

### ISSUE THREAD

**Issue by JorritSalverda** [grafana/grafana#8900]
I tried running **Grafana 4.4.1** with **CockroachDB 1.0.3** but it failed during DB migration / schema creation. Although CockroachDB is mostly compatible with _Postgres_ not every ORM is because they use many exotic queries to inspect the schema. Running Grafana with CockroachDB only fails for the main database, the sessions database works fine on top of CockroachDB.

This page shows the ORMs that are compatible with CockroachDB:

- https://www.cockroachlabs.com/docs/stable/build-an-app-with-cockroachdb.html

And their roadmap for additional support:

- https://docs.google.com/spreadsheets/d/17A0EflPqI9yhargK0n4tSw2WogQuVc5YeK-VFmKvXHM/edit#gid=0

Which particular ORM are you using for Grafana's main database when setting database type to _postgres_?

And can I find the sql schema anywhere in the Github repository in order to try the manually create the schema to find out if things run fine after doing that?

**Comment by torkelo** [comment]
Grafana is using xorm.

There is no schema file but the schema is built as a series of migrations that are defined in the go code:

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/migrations.go

The easiest way to get the complete schema is to start grafana against a postgres database then extract the complete schema from that.

**Comment by JorritSalverda** [comment]
Thanks, I'll check with CockroachDB whether it's a lot of work to support xorm.

Btw, the error outputted by Grafana when trying to run it with CockroachDB is the following

```
t=2017-07-19T15:21:27+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=postgres
t=2017-07-19T15:21:27+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-07-19T15:21:27+0000 lvl=info msg="Executing migration" logger=migrator id="Update user table charset"
t=2017-07-19T15:21:27+0000 lvl=eror msg="Executing migration failed" logger=migrator id="Update user table charset" error="pq: unimplemented at or near \",\"\nALTER TABLE \"user\" ALTER \"login\" TYPE
 VARCHAR(190), ALTER \"email\" TYPE VARCHAR(190), ALTER \"name\" TYPE VARCHAR(255), ALTER \"password\" TYPE VARCHAR(255), ALTER \"salt\" TYPE VARCHAR(50), ALTER \"rands\" TYPE VARCHAR(50), ALTER \"com
pany\" TYPE VARCHAR(255), ALTER \"theme\" TYPE VARCHAR(255);\n                                                  ^\n"
t=2017-07-19T15:21:27+0000 lvl=eror msg="Exec failed" logger=migrator error="pq: unimplemented at or near \",\"\nALTER TABLE \"user\" ALTER \"login\" TYPE VARCHAR(190), ALTER \"email\" TYPE VARCHAR(19
0), ALTER \"name\" TYPE VARCHAR(255), ALTER \"password\" TYPE VARCHAR(255), ALTER \"salt\" TYPE VARCHAR(50), ALTER \"rands\" TYPE VARCHAR(50), ALTER \"company\" TYPE VARCHAR(255), ALTER \"theme\" TYPE
 VARCHAR(255);\n                                                  ^\n" sql="ALTER TABLE \"user\" ALTER \"login\" TYPE VARCHAR(190), ALTER \"email\" TYPE VARCHAR(190), ALTER \"name\" TYPE VARCHAR(255),
 ALTER \"password\" TYPE VARCHAR(255), ALTER \"salt\" TYPE VARCHAR(50), ALTER \"rands\" TYPE VARCHAR(50), ALTER \"company\" TYPE VARCHAR(255), ALTER \"theme\" TYPE VARCHAR(255);"
t=2017-07-19T15:21:27+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: pq: unimplemented at or near \",\"\nALTER TABLE \"user\" ALTER \"login\"
TYPE VARCHAR(190), ALTER \"email\" TYPE VARCHAR(190), ALTER \"name\" TYPE VARCHAR(255), ALTER \"password\" TYPE VARCHAR(255), ALTER \"salt\" TYPE VARCHAR(50), ALTER \"rands\" TYPE VARCHAR(50), ALTER \
"company\" TYPE VARCHAR(255), ALTER \"theme\" TYPE VARCHAR(255);\n                                                  ^\n\n"
```

**Comment by bedrin** [comment]
This is because CockroachDB doesn't support changing column types:
https://github.com/cockroachdb/cockroach/issues/5950

**Comment by bobvawter** [comment]
FYI: we're working on an RFC for changing column types for the 2.1 release: https://github.com/cockroachdb/cockroach/pull/24703

**Comment by rabun788** [comment]
I see that commit was merged into master... does that mean this has been fixed and should be closed?

**Comment by jdfalk** [comment]
No it still doesn't work. I attempted it about 3 weeks ago. Grafana later attempts to drop an index without cascading, and a few other issues. I spent about a day attempting to fix the Grafana code to use it correctly and just gave up and went back to mysql. I would LOVE to use cockroachdb for this though. Any work on getting this pushed forward as an additional DB would be greatly appreciated.

**Comment by Luit** [comment]
I've investigated the current state of this, and came to the following conclusion that there's currently three issues (of which one occurs multiple times):
* [ ] `DROP INDEX` on `UNIQUE` constraints doesn't work. I've locally mitigated those with the addition of `CASCADE` but it's probably nicer to explicitly drop the constraint before dropping the index to work around this. (occurs multiple times)
* [ ] A data migration in dashboard uses `'' || id`, which in postgres coerces the integer `id` to a string. On cockroach this didn't work without the explicit coercion to string (`'' || id::STRING`).

**Comment by cgebe** [comment]
Support for CockroachDB would be much appreciated. We are using it across all of our k8s clusters since postgres does not allow easy ha setups. Is there an update to the state of this request? Right now, we have to use the PostgresSQL datasource.

**Comment by acoshift** [comment]
Right now I use Grafana with CorkcoachDB, still not found any problems so far.
But It won't work out of the box.
I have to
1. Run Grafana with PostgreSQL
2. Stop Grafana
3. Dump Grafana database from PostgreSQL and import to CockroachDB
4. Start Grafana using CockroachDB

The problem is when upgrading Grafana, I have to check is there any database migration, and I might have to manually migrate the database.

**Comment by gargath** [comment]
Having CockroachDB support would be very much appreciated.
At the moment the only low-maintenance way to provide users with a HA Grafana instances with shared storage seems to be to use a cloud-provider SQL database.

**Comment by piotr1212** [comment]
There is also an issue in https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/datasource_mig.go#L139

```
EROR[05-20|12:06:35] Executing migration failed               logger=migrator id="Add uid column" error="pq: expected DEFAULT expression to have type varchar, but '0' has type int
"
EROR[05-20|12:06:35] Exec failed                              logger=migrator error="pq: expected DEFAULT expression to have type varchar, but '0' has type int" sql="alter table \
"data_source\" ADD COLUMN \"uid\" VARCHAR(40) NOT NULL DEFAULT 0 "
```

adding extra quotes fixes it:
` Name: "uid", Type: DB_NVarchar, Length: 40, Nullable: false, Default: "'0'",`

**Comment by sergeyshaykhullin** [comment]
Also got an error in 7.0.0 using cockroachdb as database
```
t=2020-05-29T21:07:46+0000 lvl=eror msg="Executing migration failed" logger=migrator id="Update dashboard title length" error="pq: unimplemented: type conversion not yet implemented"
t=2020-05-29T21:07:46+0000 lvl=eror msg="Exec failed" logger=migrator error="pq: unimplemented: type conversion not yet implemented" sql="ALTER TABLE \"dashboard\" ALTER \"title\" TYPE VARCHAR(189);"
```

**Comment by Luit** [comment]
>     * [x]  A data migration in dashboard uses `'' || id`, which in postgres coerces the integer `id` to a string. On cockroach this didn't work without the explicit coercion to string (`'' || id::STRING`). [cockroachdb/cockroach#34404](https://github.com/cockroachdb/cockroach/issues/34404)

This one's just been fixed as well. It'll take a minute to get to a release, but it's getting there!

**Comment by vy-ton** [comment]
@Luit Is this the remaining issue?

> DROP INDEX on UNIQUE constraints doesn't work. I've locally mitigated those with the addition of CASCADE but it's probably nicer to explicitly drop the constraint before dropping the index to work around this. (occurs multiple times)

**Comment by Luit** [comment]
AFAICT #16471 fixed that one.

**Comment by vy-ton** [comment]
@Luit To your knowledge, is anything else blocking Grafana from working with CockroachDB? As mentioned above, `alter table...alter type` will be available in v20.2.

**Comment by Luit** [comment]
@vy-ton It's been a while since I tried. The hurdles I faced back then were all in the way of getting Grafana working on CockroachDB. Manually working around them gave me a working Grafana. I'm not entirely sure all the migrations from the two years since that work on CRDB. Someone'd have to try. The `ALTER TABLE ... ALTER ... TYPE` was, after the workarounds in #16471 the only one I knew of back then.

**Comment by deniszh** [comment]
No, unfortunately `SET enable_experimental_alter_column_type_general = true;` didn't help. 
CockroachDB v20.2.0, one node, insecure.
Grafana 7.3.2
```
INFO[11-14|12:01:53] Executing migration                      logger=migrator id="Update dashboard title length"
INFO[11-14|12:01:53] [SQL] ALTER TABLE "dashboard" ALTER "title" TYPE VARCHAR(189); - took: 916.161µs logger=sqlstore.xorm
EROR[11-14|12:01:53] Executing migration failed               logger=migrator id="Update dashboard title length" error="pq: ALTER COLUMN TYPE from varchar to varchar is only supported experimentally"
EROR[11-14|12:01:53] Exec failed                              logger=migrator error="pq: ALTER COLUMN TYPE from varchar to varchar is only supported experimentally" sql="ALTER TABLE \"dashboard\" ALTER \"title\" TYPE VARCHAR(189);"
INFO[11-14|12:01:53] [SQL] INSERT INTO "migration_log" ("migration_id","sql","success","error","timestamp") VALUES ($1, $2, $3, $4, $5) RETURNING "id" []interface {}{"Update dashboard title length", "ALTER TABLE \"dashboard\" ALTER \"title\" TYPE (189);", false, "pq: ALTER COLUMN TYPE from varchar to varchar is only supported experimentally", "2020-11-14 12:01:53"} - took: 502.861µs logger=sqlstore.xorm
EROR[11-14|12:01:53] Server shutdown                          logger=server reason="Service init failed: migration failed: migration failed: Failed to roll back transaction due to error: %!s(<nil>): pq: current transaction is aborted, commands ignored until end of transaction block"
Service init failed: migration failed: migration failed: Failed to roll back transaction due to error: %!s(<nil>): pq: current transaction is aborted, commands ignored until end of transaction block
```

Maybe `ALTER TABLE ... ALTER TYPE VARCHAR TO VARCHAR" is not supported still, I see VARCHAR to STRING mentioned in https://github.com/cockroachdb/cockroach/issues/49329.

**Comment by deniszh** [comment]
Ah, `enable_experimental_alter_column_type_general` is _session_ variable, not a cluster setting. Well, I do not see how you can include session variable w/o changing Grafana sources.
/cc @rafiss

**Comment by rafiss** [comment]
Ah yeah that's a session variable. A workaround is to include that variable in your connection string. E.g. for a local insecure cluster you could connect like this: `'postgresql://root@localhost:26257?sslmode=disable&enable_experimental_alter_column_type_general=on'`

**Comment by deniszh** [comment]
@rafiss : Exactly, that's my point - that syntax is not working, as you can see e.g. in https://github.com/grafana/grafana/blob/v7.3.2/pkg/services/sqlstore/sqlstore.go
Even `sslmode=disable` working only through special parameter in `[database]` section.

**Comment by rafiss** [comment]
I see -- I agree with you, it looks like there would need to be some changes to Grafana sources. I think there should be a new CockroachDB type in https://github.com/grafana/grafana/blob/v7.3.2/pkg/services/sqlstore/migrator/types.go and the connection string should be constructed as I described for CockroachDB.

Making a CockroachDB `migrator` type (and also maybe a dialect) seems like a reasonable step for making Grafana have full support for CockroachDB, in my opinion. I am curious if that is a viable next step?

**Comment by abursavich** [comment]
@deniszh and @rafiss, if you look at the [readConfig](https://github.com/grafana/grafana/blob/v7.4.3/pkg/services/sqlstore/sqlstore.go#L355-L379) method you can either specify a `url` or the `type`, `host`, `name`, `user`, and `password`. If you use the `url`, then you can add extra query params. However, [some params](https://github.com/grafana/grafana/blob/v7.4.3/pkg/services/sqlstore/sqlstore.go#L381-L393) like `ssl_mode` must be specified separately.

Technically, it looks like you can simply specify the `type` and raw `connection_string` but the comments claim that's only for integration tests.

**Comment by Akhalaka** [comment]
In some quick testing with CockroachDB v21.1.1 and Grafana 7.5.7, I can get Grafana to correctly connect to cockroach using the URL of `postgres://roach@roach1:26257/grafana?sslmode=disable&enable_experimental_alter_column_type_general=true` (key difference here is `postgres` not `postgresql`)

However this is still not enough as we now get an error of
```
error="pg: unimplemented: ALTER COLUMN TYPE is not supported inside a tranaction" sql="ALTER TABLE \"dashboard\" ALTER \"title\" TYPE VARCHAR(189);"
```

This is compared to running grafana without the experimental support which gets the error message described above
```
error="pq: ALTER COLUMN TYPE from varchar to varchar is only supported experimentally"
```

All said however, the way that the statement is currently executed still appears unsupported on the cockroachdb side since the `ALTER COLUMN TYPE` statement is executed within a transaction in the grafana migration: https://www.cockroachlabs.com/docs/stable/alter-column.html#limitations-on-altering-data-types.

**Comment by vy-ton** [comment]
> error="pg: unimplemented: ALTER COLUMN TYPE is not supported inside a tranaction" sql="ALTER TABLE \"dashboard\" ALTER \"title\" TYPE VARCHAR(189);"

This error will be removed in the upcoming CockroachDB major release
```
demo@127.0.0.1:26257/movr> begin;
BEGIN


Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/movr  OPEN> alter table dashboard alter column title type VARCHAR(189);
ALTER TABLE


Time: 4ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/movr  OPEN> commit;
COMMIT


Time: 23ms total (execution 23ms / network 0ms)
```

**Comment by sergeyshaykhullin** [comment]
Does someone tested on latest v8.2.3?

**Comment by teutat3s** [comment]
Yeah, still the same error reported by @Akhalaka with cockroach v21.1.11 and grafana v8.2.3
This seems related:
https://github.com/cockroachdb/cockroach/issues/49351

@vy-ton do you mean the cockroach release v21.2.0?

**Comment by vy-ton** [comment]
Are you seeing the unimplemented or experimental error?

**Comment by UnacceptableUse** [comment]
I'm on cockroach v21.1.8 and I'm getting "pq: unimplemented: ALTER COLUMN TYPE is not supported inside a transaction"

**Comment by teutat3s** [comment]
With the versions mentioned above I get: 
```
pq: unimplemented: ALTER COLUMN TYPE is not supported inside a transaction" sql="ALTER TABLE \"dashboard\" ALTER \"title\" TYPE VARCHAR(189);"
```

**Comment by synchris** [comment]
> With the versions mentioned above I get:
> 
> ```
> pq: unimplemented: ALTER COLUMN TYPE is not supported inside a transaction" sql="ALTER TABLE \"dashboard\" ALTER \"title\" TYPE VARCHAR(189);"
> ```
> 
> EDIT: just tried with cockroachdb `v21.2.0-rc.3` and I see the same `unimplemented` error.
> 
> For others struggling to set the experimental session variable in grafana, you can also set it for the grafana role / user in cockroach like this:
> 
> ```
> CREATE DATABASE grafanadb;
> CREATE USER grafana WITH PASSWORD 'secret_password';
> GRANT ALL ON DATABASE grafanadb to grafana;
> ALTER ROLE grafana SET enable_experimental_alter_column_type_general=true;
> ```

The role altering does not seems to work.

**Comment by phin1x** [comment]
The experimental do not work with the latest grafana (v8.3) because cockroachdb has some [limitations](https://www.cockroachlabs.com/docs/v21.2/alter-column#limitations-on-altering-data-types) with altering columns.

I had some other errors where the default value was not compatible with the column type:
`vl=eror msg="Exec failed" logger=migrator error="pq: expected DEFAULT expression to have type varchar, but '0' has type int" sql="CREATE TABLE IF NOT EXISTS \"alert_rule\" (\n\"id\" SERIAL PRIMARY KEY  NOT NULL\n, \"org_id\" BIGINT NOT NULL\n, \"title\" VARCHAR(190) NOT NULL\n, \"condition\" VARCHAR(190) NOT NULL\n, \"data\" TEXT NOT NULL\n, \"updated\" TIMESTAMP NOT NULL\n, \"interval_seconds\" BIGINT NOT NULL DEFAULT 60\n, \"version\" INTEGER NOT NULL DEFAULT 0\n, \"uid\" VARCHAR(40) NOT NULL DEFAULT 0\n, \"namespace_uid\" VARCHAR(40) NOT NULL\n, \"rule_group\" VARCHAR(190) NOT NULL\n, \"no_data_state\" VARCHAR(15) NOT NULL DEFAULT 'NoData'\n, \"exec_err_state\" VARCHAR(15) NOT NULL DEFAULT 'Alerting'\n);"`

**Comment by vy-ton** [comment]
> I had some other errors where the default value was not compatible with the column type:

https://github.com/cockroachdb/cockroach/issues/74854 is the tracking issue for this error

**Comment by chenjpu** [comment]
CRDB:     22.1.1
grafana:  9.0.0

```
pq: unimplemented: ALTER COLUMN TYPE is not supported inside a transaction
```

**Comment by ZsBT** [comment]
Still having this issue (ALTER COLUMN TYPE is not supported inside a transaction).

```
# cockroach version
Build Tag:        v23.1.3
Build Time:       2023/06/08 22:36:13
Distribution:     CCL
Platform:         linux amd64 (x86_64-pc-linux-gnu)
Go Version:       go1.19.4
C Compiler:       gcc 6.5.0
Build Commit ID:  c663f843fa3e1a87855a18f9678291f35eeef394
Build Type:       release

```

**Comment by cornfeedhobo** [comment]
Everyone interested can track the progress at cockroachdb/cockroach#9851

**Comment by gelicia** [comment]
It looks like this is something that cockroachDB is implementing to be compatible with standard SQL functionality. I am closing this ticket as the work can be tracked on the cockroachdb repo.

**Comment by Darkness4** [comment]
Hi, I managed to "make it work" with cockroachdb with this "hack". Basically, by doing some migration manually:

```sql
-- (1) Do it outside of a transaction
ALTER TABLE "dashboard" ALTER "title" TYPE VARCHAR(189);

-- !!! EXECUTE MANUALLY and restart grafana until next crash !!!

-- (2) Skip COLLATE "C", not supported by Cockroachdb. Accepts to use the default collation.
INSERT INTO migration_log (migration_id, sql, success, error, timestamp) VALUES ('set path collation in file table', 'ALTER TABLE file ALTER COLUMN path TYPE VARCHAR(1024) COLLATE "C";', true, '', current_timestamp);

-- !!! EXECUTE MANUALLY and restart grafana until next crash !!!

-- (3) Replace rowid with id in seed_assignment
ALTER TABLE seed_assignment ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE seed_assignment ALTER PRIMARY KEY USING COLUMNS(id);
INSERT INTO migration_log (migration_id, sql, success, error, timestamp) VALUES ('add primary key to seed_assigment', 'ALTER TABLE seed_assignment ADD COLUMN id SERIAL PRIMARY KEY;', true, '', current_timestamp);

-- !!! EXECUTE MANUALLY and restart grafana until next crash !!!

-- (4) Do it outside of a transaction
ALTER TABLE "folder" ALTER "title" TYPE VARCHAR(189);

-- !!! EXECUTE MANUALLY and restart grafana until next crash !!!

-- Migrations should be complete.

-- (5) Create missing sequence (?!). Runtime issue caused by first org creation.
create sequence org_id_seq;

```

- `(1)` and `(4)` is covered by  https://github.com/cockroachdb/cockroach/issues/9851. Issue is still open because the statement doesn't work inside a transaction.
- `(2)` is the same issue as @ZsBT 
- `(3)`, CockroachDB's `rowid` column is conflicting with `id` (`multiple primary keys not allowed`). `rowid` is automatically added when the table has no primary key. Executing the two `ALTER TABLE` statements seem to automatically delete the `rowid` column.
- `(5)`, when initializing the first org, `SELECT setval('org_id_seq', (SELECT max(id) FROM org))` is failing with `relation "org_id_seq" does not exist`. The request: https://github.com/grafana/grafana/blob/b62f8c0f19b8b10a1de577e54510883423cf6ddd/pkg/services/sqlstore/migrator/postgres_dialect.go#L210 
  I don't really know the reason because I don't really know much about PostgreSQL and CockroachDB. I guess PostgreSQL is generating a sequence for each SERIAL PRIMARY KEY, whereas CockroachDB is calling `unique_rowid()`

**Comment by cottand** [comment]
Unfortunately, in https://github.com/grafana/grafana/commit/545b7bf8ff49ae1427cf24eeb38f599612299e8e grafana added another migration incompatible with CockroachDB (with id=`add primary key to file table (postgres and sqlite)`)

This will result in the following log line when first starting Grafana 12.3+:

```
level=error msg="Exec failed" error="pq: unimplemented: DROP INDEX usage inside a function definition is not supported" sql="..."
```

CRDB are tracking implementing this in https://github.com/cockroachdb/cockroach/issues/110080 but that's been open for a few years at the time of writing this 🥲

You can still progress by applying the changes from each failing migration manually and marking them as done in `migration_log`
