### ISSUE TITLE
InfluxDB client: Start / Stop times are ignored in FLUX queries on 11.0 and 11.1

### ISSUE THREAD

**Issue by PeterHasse** [grafana/grafana#89948]
### What happened?

All our FLUX dashboards stopped working when upgrading from the 11 preview release to 11.1. Downgrading to 10.4.5 resolved the issue. From the Grafana Log output it looks like Grafana is ignoring the selected start and stop time and uses 1970 instead, see log below:

`Jul 02 12:48:48 monitoring grafana[1411]: logger=tsdb.influx_flux endpoint=queryData pluginId=influxdb dsName=InfluxDB dsUID=Ckrwhbn4k uname=admin t=2024-07-02T12:48:48.002535688Z level=warn msg="Flux query failed" err="invalid: error in building plan while starting program: cannot query an empty range" query="customTagValues = (bucket, tag, predicate=(r) => true, start=1970-01-01T00:00:00Z, stop=1970-01-01T00:00:00Z) =>\n  from(bucket: bucket)\n    |> range(start: start, stop: stop)\n    |> filter(fn: predicate)\n    |> keep(columns: [tag])\n    |> group()\n    |> distinct(column: tag)\n\ncustomTagValues(bucket: \"Aladin_November\", tag: \"device\")"
Jul 02 12:48:48 monitoring grafana[1411]: logger=tsdb.influx_flux endpoint=queryData pluginId=influxdb dsName=InfluxDB dsUID=Ckrwhbn4k uname=admin t=2024-07-02T12:48:48.002687311Z level=warn msg="Flux query failed" err="invalid: error in building plan while starting program: cannot query an empty range" query="customTagValues = (bucket, tag, predicate=(r) => true, start=1970-01-01T00:00:00Z, stop=1970-01-01T00:00:00Z) =>\n  from(bucket: bucket)\n    |> range(start: start, stop: stop)\n    |> filter(fn: predicate)\n    |> keep(columns: [tag])\n    |> group()\n    |> distinct(column: tag)\n\ncustomTagValues(bucket: \"Aladin_November\", tag: \"measurement_name\")"`

It does not make a difference if a custom time frame is selected or e.g. last 5 min. Up / Downgrading reproducible triggers / solves the issue

### What did you expect to happen?

Successful data query

### Did this work before?

yes, with Grafana 10.4.5 it works as expected

### How do we reproduce it?

1.Add Flux data source
2. add a dashboard
3. add a query

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.1.0
OS: Ubuntu 22.04.4
Browser: Chromium 

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB Flux

**Comment by thepill** [comment]
I can confirm the issue - i do have the same problem after upgrading to 11.1

```
level=warn msg="Flux query failed" err="invalid: error in building plan while start   │
│   ing program: cannot query an empty range" query="from(bucket: \"proxmox\")\n  |> range(start: 1970-01-01T00:00:0   │
│   0Z, stop: 1970-01-01T00:00:00Z)\n  |> filter(fn: (r) => \n    r._measurement == \"system\" and\n    r.object ==    │
│   \"nodes\"\n  )\n  |> keyValues(keyColumns: [\"host\"])\n  |> group()\n  |> keep(columns: [\"host\"])\n  |> disti   │
│   nct(column: \"host\")\n\n"
```

**Comment by artstar-es** [comment]
Can confirm that I am experiencing the exact same issue, though mine is limited solely to 11.1.0. Rolling back to 11.0.1 results in my dashboards working again.

This query problem only seems to affect my Variables (Query-based). The Data Source variable is functioning normal. All panel queries within the dashboards work fine as well, if I manually populate the four query-based Variables I'm attempting to work with.

logger=context userId=1 orgId=1 uname=admin t=2024-07-03T01:14:02.103888812+10:00 level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=[redacted reverseproxyIP] time_ms=2 duration=2
.653936ms size=685 referer="https://grafana.redacted.url/d/RwSBnsS7z/apc-ups-detailed-summary?editIndex=1&editview=templating&from=now-30m&orgId=1&refresh=1m&to=now&var-currency=%24&var-kwhprice=.15&va
r-maxvoltamp=1000&var-maxwatt=800&var-powerfactor=0.8&var-upsdatasource=0Mo2emVnk&var-upsname=UPSTower" handler=/api/ds/query status_source=downstream
logger=tsdb.influx_flux endpoint=queryData pluginId=influxdb dsName=InfluxDB-Fluxed dsUID=0Mo2emVnk uname=admin t=2024-07-03T01:14:02.110247652+10:00 level=warn msg="Flux query failed" err="invalid: comp
ilation failed: error @5:45-5:46: missing property value\n\nerror @5:56-5:57: missing property value" query="from(bucket: \"telegraf\")\r\n  |> range(start: 1970-01-01T00:00:00Z, stop: 1970-01-01T00:00:0
0Z)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"\")\r\n  |> keep(columns: [\"_time\",\"ups_name\"])\r\n  |> map(fn: (r) => ({ r with _value: float(v: )/float(v: )}))\r\n
|> yield(name: \"last\")\r\n"

**Comment by SokoFromNZ** [comment]
Same issue after upgrading to v11.1:

My variables query is OK in Influx:
![image](https://github.com/grafana/grafana/assets/33326277/50e5c230-fe77-48aa-97e3-8ac52aa6b7c5)

But as a variable it delivers no values:
![image](https://github.com/grafana/grafana/assets/33326277/2b971b0a-4fbf-4567-a97f-748fd0b520ac)

**Comment by tt-kkaiser** [comment]
Same issue here. After upgrading Grafana from version 11.0 to 11.1, all dashboards using InfluxDB as a data source fail to load.

**Comment by PeterHasse** [comment]
@marefr thanks for looking at the ticket. Can we provide any further information to support grafana on fixing this?

**Comment by dataartisan** [comment]
Noticed the same thing. Was able to downgrade using:

 grafana:
    image: grafana/grafana:11.0.1
    container_name: grafana

Flux queries work well.

**Comment by jtp10181** [comment]
Had the same issue, all my dashboards stopped working with 11.1 and I tracked it back to the variables not populating any results. My variables use Flux queries like above examples. Was not sure of the exact cause but rolling back 11.0.1 fixed the issue so I am just waiting for the next release to see if its fixed.

**Comment by dc881927** [comment]
Same issue here.
grafana:11.1
All the variables searching using flux has been ​failed.

**Comment by jasuade** [comment]
I think this issue is repeated, see: https://github.com/grafana/grafana/issues/88983, a fix has been released and backported.

**Comment by jtp10181** [comment]
I updated to 11.1 again via apt using the official repo and all my dashboards and variables are still broken. 

How do you get the backported patch?

**Comment by derpeter** [comment]
[11.1.2 ](https://github.com/grafana/grafana/releases/tag/v11.1.2) release fixed the issue, at least for our dashboards.

**Comment by jtp10181** [comment]
Yes 11.1.2 looks to have fixed the issue for me as well. Updated vi apt.

**Comment by PeterHasse** [comment]
Fix confirmed, i close the ticket. Thank you all and the grafana team for the fix.
