### ISSUE TITLE
Tooltip font size causing scrollbar buttons to appear for every entry. 

### ISSUE THREAD

**Issue by bdoiron74** [grafana/grafana#90697]
### What happened?

updated from 10.4.5 to 11.1.0 and the tooltips are messed up

### What did you expect to happen?

tooltips not to have scrollbar buttons on each series name

### Did this work before?

was fine with 10.2.2, 10.4.5

### How do we reproduce it?

1. plot some data, time series panel
2. tooltip mode ALL
3. roll mouse over visualization

### Environment (with versions)?

Grafana: 11.1.0
OS: Windows 11 23H2 22631.3880
Browser: Chrome 126.0.6478.127 (Official Build) (64-bit)

### Grafana platform?

None

**Comment by leeoniya** [comment]
just to make sure, can you reproduce this behavior on play.grafana.org or in a nightly build?

https://grafana.com/grafana/download/nightly?edition=oss

**Comment by bdoiron74** [comment]
Here's what I'm seeing on my instance with dockerhub grafana/grafana:11.1.0 (arm64):
![image](https://github.com/user-attachments/assets/9523dab3-9dc8-45b4-8d88-1e360d707973)

and grafana/grafana:10.4.5 (arm64):
![image](https://github.com/user-attachments/assets/817d5f4a-82c2-46de-8e0f-27c1c355bee4)

play.grafana 11.2.0-73179 doesn't seem to be showing it
![image](https://github.com/user-attachments/assets/77f9908b-4bbe-4e56-a58f-ce118389b935)

**Comment by bdoiron74** [comment]
Even if the scroll buttons weren't appearing for me with 11.1.0, the tooltip font size seems to have grown and is too big IMO. Is there a way to change that?

**Comment by nicholas-a-guerra** [comment]
I agree the 11.1.x tooltip is looking very odd now. There is a blank scrollbar even if it's not needed and the font is so big now that many tooltips that never needed a scrollbar before now need one. Font size should be adjustable back to the original size at least and scrollbar should not always be seen. Every customer I've interacted with does not understand how to use a scrollbar in a tooltip. It is not intuitive to need to click specifically on the dot of data to be able to keep the tooltip in place, then hover over the tooltip to be able to scroll. I don't think users will ever be able to grasp that. The screenshots below should be true to size. Everything about 11.0.2 is better than 11.1.1. An option to keep the old style would be great.


v11.0.2

<img width="243" alt="image" src="https://github.com/user-attachments/assets/620b99c6-1d67-4905-857f-bc11b29175f7">\

<img width="237" alt="image" src="https://github.com/user-attachments/assets/58cfc0ec-8021-4cf0-8b7e-6f364b0419a7">


v11.1.1

<img width="276" alt="image" src="https://github.com/user-attachments/assets/9a272d01-7420-4d2f-a6c6-f91c124fe27b">\

<img width="308" alt="image" src="https://github.com/user-attachments/assets/b2597625-27e0-450d-9ebd-5489a5c79141">

**Comment by adela-almasan** [comment]
Fixed by https://github.com/grafana/grafana/pull/91547

**Comment by SwissPoPo** [comment]
There is still more line spacing than before. Apart from the scroll bar it is not fixed.
On small iframes the tooltip is not completely visible.

**Comment by leeoniya** [comment]
this issue was about scroll bars, which is fixed.

the increased font size was a design choice, and we've heard similar feedback about the decreased density being problematic, but it is not a bug per se. feel free to open another issue for this, though.
