### ISSUE TITLE
[11.2.2+security-01] logs : error="invalid user agent format"

### ISSUE THREAD

**Issue by Nemric** [grafana/grafana#95006]
### What happened?

Grafana seems to work fine, but I have too many logs like : `logger=base.plugin.context t=2024-10-18T21:12:10.07539877Z level=warn msg="Could not create user agent" error="invalid user agent format"`

### What did you expect to happen?

Using grafana as usual without error logs, and of course, logs are not the root cause ;)

### Did this work before?

Yes, it only appears on latest `11.2.2+security-01` release

### How do we reproduce it?

1. update to 11.2.2+security-01
2. login to grafana
3. check for logs (promtail ;) )

### Environment (with versions)?

Grafana: 11.2.2+security-01
OS: Fedora CoreOS 41.20241006.1.1 containerized grafana / fedora 40 workstation
Browser: Firefox 131.0.3

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by p-rott** [comment]
I've got the same issue, for me it's most noticeable when trying to save a dashboard. The logs show the following error message 3-5 times, with a timeout afterwards. 
`logger=base.plugin.context t=2024-10-19T14:26:45.962483694+02:00 level=warn msg="Could not create user agent" error="invalid user agent format"
logger=context userId=1 orgId=1 uname=admin t=2024-10-19T14:27:57.613402899+02:00 level=error msg="bad request data" error="read tcp 10.0.0.33:3000->10.0.0.2:61472: read: connection timed out" remote_addr=10.0.0.2 traceID=`

This also means that i can't save dashboards anymore and therefore can't create or change any current visualizations.

**Comment by derSascha** [comment]
Looks like the user-agent parser fails on the security version. Created a small pull-request to fix the parser regexp. A new release without the `+` in the version should fix this too.

**Comment by Nemric** [comment]
Solved in v11.3.0, thanks a lot :)

**Comment by logopk** [comment]
Still present in
    image: grafana/grafana:11.3.0-security-01


grafana       | logger=base.plugin.context t=2024-11-12T17:48:00.00349766Z level=warn msg="Could not create user agent" error="invalid user agent format"

**Comment by derSascha** [comment]
Dependency on `grafana-plugin-sdk-go` was already bumped on master, but not on the 11.3.x branch (was fixed in [v0.256.0](https://github.com/grafana/grafana-plugin-sdk-go/releases/tag/v0.256.0)).


> Solved in v11.3.0, thanks a lot :)

Bug was not fixed in this build. There was just a new version string, that does not contain special characters like a "+security"...

**Comment by Nemric** [comment]
sorry ^^

**Comment by celesteking** [comment]
`WARN [11-14|22:56:33] Could not create user agent              logger=base.plugin.context error="invalid user agent format"`
in `11.3.0+security-01`

**Comment by Nachtfalkeaw** [comment]
me2
Nov 15 00:04:00 ubiquiti grafana[44451]: logger=base.plugin.context t=2024-11-15T00:04:00.012759959+01:00 level=warn msg="Could not create user agent" error="invalid user agent format"

Version 11.3.0+security-01 (commit: 5ddc329279bb66e3fd584812b8a4e16751eeecd0, branch: HEAD)

**Comment by sfjhu** [comment]
Also encountering this bug on the Docker image of 11.3.0+security-01.

**Comment by vladyslav2** [comment]
following the issue

**Comment by AlTosterino** [comment]
Hey, I'm also experiencing this issue on my local Grafana (grafana version 11.2.2+security-01). I no longer can check logs from Loki under `Explore` (pre-configured dashboards shows Loki logs, clicking `Run Query` on `Explore` section does nothing)

Logs:
```
loguru-observability-example-grafana-1  | logger=tsdb.loki endpoint=queryData pluginId=loki dsName=Loki dsUID=ee19h0cttekg0b uname=admin fromAlert=false t=2024-11-20T09:03:11.895204876Z level=info msg="Response received from loki" duration=33.549166ms stage=databaseRequest statusCode=200 contentLength= start=2024-11-20T08:58:11.856Z end=2024-11-20T09:03:11.856Z step=200ms query="sum by (record_extra_action) (count_over_time({service_name=\"log-generator\"} | json | logfmt [300s]))" queryType=range direction=backward maxLines=1000 supportingQueryType=none lokiHost=loki:3100 lokiPath=/loki/api/v1/query_range status=ok
loguru-observability-example-grafana-1  | logger=tsdb.loki endpoint=queryData pluginId=loki dsName=Loki dsUID=ee19h0cttekg0b uname=admin fromAlert=false t=2024-11-20T09:03:11.898622168Z level=info msg="Response parsed from loki" duration=3.277291ms metricDataplane=true framesLength=9 stage=parseResponse
loguru-observability-example-grafana-1  | logger=tsdb.loki endpoint=queryData pluginId=loki dsName=Loki dsUID=ee19h0cttekg0b uname=admin fromAlert=false t=2024-11-20T09:03:11.903194084Z level=info msg="Response received from loki" duration=16.574375ms stage=databaseRequest statusCode=200 contentLength= start=2024-11-20T08:58:11.857Z end=2024-11-20T09:03:11.857Z step=200ms query="sum by (detected_level) (count_over_time({service_name=\"log-generator\"} | json | logfmt [300s]))" queryType=range direction=backward maxLines=1000 supportingQueryType=none lokiHost=loki:3100 lokiPath=/loki/api/v1/query_range status=ok
loguru-observability-example-grafana-1  | logger=tsdb.loki endpoint=queryData pluginId=loki dsName=Loki dsUID=ee19h0cttekg0b uname=admin fromAlert=false t=2024-11-20T09:03:11.904727793Z level=info msg="Response parsed from loki" duration=1.488ms metricDataplane=true framesLength=3 stage=parseResponse
loguru-observability-example-grafana-1  | logger=tsdb.loki endpoint=queryData pluginId=loki dsName=Loki dsUID=ee19h0cttekg0b uname=admin fromAlert=false t=2024-11-20T09:03:11.928720543Z level=info msg="Response received from loki" duration=42.454792ms stage=databaseRequest statusCode=200 contentLength= start=2024-11-20T08:58:11.856Z end=2024-11-20T09:03:11.856Z step=200ms query="{service_name=`log-generator`} | json | logfmt | drop __error__, __error_details__" queryType=range direction=backward maxLines=1000 supportingQueryType=none lokiHost=loki:3100 lokiPath=/loki/api/v1/query_range status=ok
loguru-observability-example-grafana-1  | logger=tsdb.loki endpoint=queryData pluginId=loki dsName=Loki dsUID=ee19h0cttekg0b uname=admin fromAlert=false t=2024-11-20T09:03:11.950857959Z level=info msg="Response parsed from loki" duration=22.04025ms metricDataplane=true framesLength=1 stage=parseResponse
loguru-observability-example-grafana-1  | logger=base.plugin.context t=2024-11-20T09:03:13.47816596Z level=warn msg="Could not create user agent" error="invalid user agent format"
loguru-observability-example-grafana-1  | logger=tsdb.loki endpoint=callResource pluginId=loki dsName=Loki dsUID=ee19h0cttekg0b uname=admin t=2024-11-20T09:03:13.494888085Z level=info msg="Response received from loki" status=ok statusCode=200 contentLength=45 duration=16.298333ms contentEncoding= stage=databaseRequest
```

**Comment by oscararmandolozano** [comment]
I have the same problem with 11.2.2.  A lot of these messages:

logger=base.plugin.context t=2024-12-04T09:35:10.003014645-05:00 level=warn msg="Could not create user agent" error="invalid user agent format"
logger=base.plugin.context t=2024-12-04T09:35:12.504541073-05:00 level=warn msg="Could not create user agent" error="invalid user agent format"
logger=base.plugin.context t=2024-12-04T09:35:15.002985863-05:00 level=warn msg="Could not create user agent" error="invalid user agent format"
logger=base.plugin.context t=2024-12-04T09:35:17.503451076-05:00 level=warn msg="Could not create user agent" error="invalid user agent format"

The problem is what is the detination IP, or which datasource, organization, etc...?

Thanks.

**Comment by langerma** [comment]
following, as it is also happening on our side

**Comment by 123456890987654321** [comment]
Happening also in v11.4.4+security-01 (7834551853)
