### ISSUE TITLE
Thresholds coloring in gauge with percents broken (when decimals set to 0 and unit set to percent 0.0 - 1.0)

### ISSUE THREAD

**Issue by wkruse** [grafana/grafana#9799]
In Grafana **4.6.1** a gauge for value `52` and unit `percent (0-100)`, thresholds `70,90`, gauge min `0`, gauge max `100` works as expected.

![52-works](https://user-images.githubusercontent.com/3473199/32455537-dcb3adf2-c322-11e7-800f-0491028125ae.png)

**But** for value `0.52` and unit `percent (0.0-1.0)`, thresholds `70,90`, gauge min `0`, gauge max `100` doesn't color the thresholds.

<img width="1350" alt="0_52-broken" src="https://user-images.githubusercontent.com/3473199/32455813-b5f82bce-c323-11e7-9d5d-5affdaf1ccdd.png">

I am expecting it to be the same.

**Comment by torkelo** [comment]
We fixed a bug in v4.6 which caused this behaviour to change. Thresholds and guage min/max or on your raw metric value not on the string formatted value. Your value is between 0-1 so your thresholds need to be between 0 - 1 as well. It's only the display unit that renders your value as percent but the underlying value is between 0-1

**Comment by wkruse** [comment]
@torkelo Thanks for a quick response and clarification. I did change the thresholds to `0.7,0.9` and max to `1`, still no luck.

<img width="1340" alt="0 52-still-broken" src="https://user-images.githubusercontent.com/3473199/32485320-54776e70-c3a3-11e7-94ea-517105bc36af.png">

**Comment by wkruse** [comment]
@torkelo @bergquist Am I doing it wrong or is it a bug?

**Comment by daniellee** [comment]
@wkruse it seems to work with decimals on the Grafana play site. Are you sure that your values are between 0 and 1? Also not sure what data source you are using but is it possible the values from your query are strings and not floats?

![image](https://user-images.githubusercontent.com/434655/33309222-a238c99e-d41d-11e7-9526-360b8b5d2fcf.png)

**Comment by wkruse** [comment]
@daniellee The `Decimals: 0` in combination with `percent (0.0-1.0)` and thresholds `0.7,0.9` is the problem. There seems to be no way to show percents without decimals for `percent (0.0-1.0)`. Not sure if it's a real bug or just something to be aware of.

**Comment by daniellee** [comment]
Confirmed. The decimals field is used both for the unit (percent) and the value. Tricky to solve though.

**Comment by santoshiyengar** [comment]
@daniellee,

I faced a similar problem, i see in the snapshot that you have set the Gauge min to 0 and Max to 100. It should be min to 0 and Max to 1.

It did work with me, hope it works for you.

Regds
Santosh Iyengar

**Comment by santoshiyengar** [comment]
@daniellee , please use min:0 and max:1 under Gauge in options. You have used min:0 and max:100

**Comment by markmnl** [comment]
I'm facing this issue with decimals used for thresholds and min max. (see first pic)

Seems be a rounding issue because same setup does work when value drops to e.g. 0.90 (see second pic)

![image](https://user-images.githubusercontent.com/2630321/60648368-633e5300-9e72-11e9-9fa7-08a830d9521d.png)

![image](https://user-images.githubusercontent.com/2630321/60648468-984aa580-9e72-11e9-82c0-966e52eafe47.png)

**Comment by torkelo** [comment]
Can you try the new Gauge panel ?

**Comment by markmnl** [comment]
> Can you try the new Gauge panel ?

I should have mentioned I'm using 5.1.1, there doesn't appear to be a Guage panel - I used Singlestat panel..

Do you mean this plugin: https://grafana.com/plugins/briangann-gauge-panel/installation ?

**Comment by torkelo** [comment]
no, a new panel introduced in v6, can you upgrade to v6.2

**Comment by markmnl** [comment]
Ah OK, I cannot upgrade at this time, but have switched to use background without guage as a workaround for now,

**Comment by effgee** [comment]
Looks like issue is still present with "percentage 0-100".
Workaround is to format as general, and just use % symbol as postfix.

**Comment by torkelo** [comment]
this should work in the new gauge panel

**Comment by kd3c** [comment]
The problem is still present in Grafana v7.5.1.
