### ISSUE TITLE
Custom namespaces in CloudWatch are not showing data points

### ISSUE THREAD

**Issue by andrey-sra** [grafana/grafana#9852]
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
- What Grafana version are you using?  4.6.1
- What datasource are you using? CloudWatch
- What OS are you running grafana on?  Ubuntu 16.04
- What did you do?  
Added metrics from several custom AWS namespaces (which I can see in AWS console).  Shows as no data points.   I can see stock AWS metrics displayed on the same dashboard.
- What was the expected result?
See data points.
- What happened instead?
No data points.
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
Request:
```
Request URL:http://localhost:3000/api/tsdb/query
Request Method:POST
Status Code:200 OK
Remote Address:[::1]:3000
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Content-Length:129
Content-Type:application/json
Date:Fri, 10 Nov 2017 21:21:12 GMT
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Connection:keep-alive
Content-Length:352
Content-Type:application/json;charset=UTF-8
Cookie:grafana_user=admin; grafana_remember=32982d6111583e72777f77dcdc5086a815ac5bfda1ec6e62ae4698618619575187; grafana_sess=61e39cb8a1ec7da8; toggles=%7B%22ui-wp-upgrade%22%3Atrue%7D
Host:localhost:3000
Origin:http://localhost:3000
Referer:http://localhost:3000/dashboard/db/test?panelId=1&fullscreen&edit&orgId=1
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
X-Grafana-Org-Id:1
Request Payload
view parsed
{"from":"1510300800000","to":"1510387199999","queries":[{"refId":"A","intervalMs":60000,"maxDataPoints":1294,"datasourceId":1,"type":"timeSeriesQuery","alias":"ttt","dimensions":{"InstanceID":"i-xxxxx"},"hide":false,"metricName":"RotationPutTime","namespace":"LogIngestion","period":"60","region":"us-east-2","statistics":["SampleCount"]}]}
```
Response:
```
{"results":{"A":{"refId":"A","series":[{"name":"ttt","points":null,"tags":{"InstanceID":"i-xxxxx"}}],"tables":null}}}
```
Log:
```
t=2017-11-09T19:17:08-0800 lvl=info msg="Starting Grafana" logger=server version=4.6.1 commit=cac8b97 compiled=2017-11-01T03:27:12-0700
t=2017-11-09T19:17:08-0800 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-11-09T19:17:08-0800 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-11-09T19:17:08-0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-11-09T19:17:08-0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-11-09T19:17:08-0800 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-11-09T19:17:08-0800 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-11-09T19:17:08-0800 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-11-09T19:17:08-0800 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-11-09T19:17:08-0800 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-11-09T19:17:08-0800 lvl=info msg="App mode production" logger=settings
t=2017-11-09T19:17:08-0800 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=7378
t=2017-11-09T19:17:08-0800 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-11-09T19:17:08-0800 lvl=info msg="Starting DB migration" logger=migrator
t=2017-11-09T19:17:08-0800 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-11-09T19:17:08-0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-11-09T19:17:08-0800 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-11-09T19:17:08-0800 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-11-09T19:17:08-0800 lvl=info msg="Starting plugin search" logger=plugins
t=2017-11-09T19:17:08-0800 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-11-09T19:17:08-0800 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-11-09T19:17:08-0800 lvl=info msg="Initializing Stream Manager"
t=2017-11-09T19:17:08-0800 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
```

**Comment by bergquist** [comment]
Should be fixed by https://github.com/grafana/grafana/pull/9856

**Comment by Valian** [comment]
Still not working for me. Version 4.6.2, exactly the same results as @andrey-sra. I have custom metrics from docker API, visible on CloudWatch dashboard, but can't make it using Grafana.

**Comment by mtanda** [comment]
The fix will be released in 5.0. Please try 5.0beta.
https://github.com/grafana/grafana/issues/10301#issuecomment-364023517

**Comment by alexsabau86** [comment]
This is still not fixed on version 5.0.1
https://github.com/grafana/grafana/issues/11676

**Comment by ab791520b4** [comment]
For me a custom namespace called CustomMetrics is working at least with Grafana 5.1.0. The CWAgent namespace is not working though. Both are specified as custom metrics for the Cloudwatch data source (and this string also contains no spaces around the comma separating the two namespaces). All graphs can be viewed in CloudWatch. There exist also other non-custom metrics that do not show up in Grafana for instance AWS/ElasticBeanstalk > LoadAverage1min and AWS/ElasticBeanstalk > CPUIdle even though they show up in CloudWatch. Could it be a upper- vs. lower-case problem? In some of my panels (e.g. the one for the CustomMetrics namespace) I had to replace the dimension string "InstanceId" by "InstanceID" in the panel JSON in order for points to show up.

**Comment by HSkogmo** [comment]
Grafana v5.1.3 (087143285)

Can confirm that this is an issue for the CWAgent namespace, but working as expected for the AWS default name space.

- I just attempted to change the default namespace for the agent from "CWAgent" to "CustomMetrics", like @ab791520b4 but it did not work for me. Perhaps there's something buggy that the CloudWatch Agent is doing?
- I also attempted to add a second namespace comma-separated-no-spaces to the Grafana data source config.
- I tried with and without IAM Administrator credentials to test if the IAM policies were too tight

I have made sure that I'm selecting an InstanceId and I've quadruple checked that it is correct. I've also tried selection dimensions based on InstanceType and ImageId, but no luck. I'm also certain that I'm selecting the same region as the one shown in the AWS console.

I don't know what to check next as I'm running out of permutations to try in the Graph Metrics tab 😅

**Comment by ab791520b4** [comment]
My CustomMetrics namespace was created using calls to "aws cloudwatch put-metric-data" not using the CWAgent:
`aws cloudwatch put-metric-data --namespace CustomMetrics --metric-name MyMetric --unit Kilobytes --value 42 --dimensions "InstanceId=i-abcdef"`
In fact I used InstanceID instead of InstanceId when I specified the dimensions argument which explains why I had to replace InstanceId by InstanceID in my panels.

Also it seems to me that it is not a Grafana problem. If I try to query using the aws cli then I also get no data points:
`$ aws cloudwatch list-metrics --namespace "CWAgent" --metric-name "mem_used_percent" --dimensions "Name=InstanceId,Value=i-abcdef"
{
    "Metrics": [
        {
            "Namespace": "CWAgent",
            "MetricName": "mem_used_percent",
            "Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "i-abcdef"
                },
                {
                    "Name": "AutoScalingGroupName",
                    "Value": "awseb-abcdef"
                },
                {
                    "Name": "ImageId",
                    "Value": "ami-abcdef"
                },
                {
                    "Name": "InstanceType",
                    "Value": "m4.xlarge"
                }
            ]
        }
    ]
}
$ aws cloudwatch get-metric-statistics --namespace "CWAgent" --metric-name "mem_used_percent" --dimensions "Name=InstanceId,Value=i-abcdef,Name=AutoScalingGroupName,Value=awseb-abcdef,Name=ImageId,Value=ami-abcdef,Name=InstanceType,Value=m4.xlarge" --statistics Average --period 60 --start-time 2018-06-05T08:00:00Z --end-time 2018-06-05T08:03:00Z
{
    "Label": "mem_used_percent",
    "Datapoints": []
}
`
Also this seems to be nothing specific to CWAgent. The aws cli also e.g. returns no data points for AWS/ElasticBeanstalk:CPUIdle but it does for example for AWS/ElasticBeanstalk:ApplicationRequestsTotal. It also does not seem to be an issue due to a specific dimension combination being required as far as I can tell (see for example https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Dimension for an explanation of dimension combinations) since I specified all dimensions in the example above.

**Comment by ab791520b4** [comment]
I did turn out to be a dimension combination problem: When specifying multiple dimensions when calling the aws cli, multiple parameters have to be specified (no surrounding quotation marks or comma in between). So the correct get-metric-statistics call for CWAgent:mem_used_percent is:
<pre><code>$ aws cloudwatch get-metric-statistics --namespace "CWAgent" --metric-name "mem_used_percent" --dimensions Name=InstanceId,Value=i-abcdef Name=AutoScalingGroupName,Value=awseb-abcdef Name=ImageId,Value=ami-abcdef Name=InstanceType,Value=m4.xlarge --statistics Average --period 60 --start-time 2018-06-05T08:00:00Z --end-time 2018-06-05T08:03:00Z</code></pre>

And then data points are returned. And that turns out to be the same problem in Grafana. As soon as one specifies all dimensions in Grafana then everything works like a charm. The required dimensions can e.g. be determined using `aws cloudwatch list-metrics` (see comment above). But also Grafana displays all available dimensions in the drop-down menu when adding a dimension. The only difference to non-custom metrics is as it is stated in the link provided in the last comment:

> For metrics produced by certain AWS services, such as Amazon EC2, CloudWatch can aggregate data across dimensions. For example, if you search for metrics in the AWS/EC2 namespace but do not specify any dimensions, CloudWatch aggregates all data for the specified metric to create the statistic that you requested. CloudWatch does not aggregate across dimensions for your custom metrics. 

And that also answers why it did not work for certain AWS metrics: Not all of them are aggregated automatically.

**Comment by mtanda** [comment]
I check the behavior and confirm Grafana works correctly.

![image](https://user-images.githubusercontent.com/224552/41037501-7e302f14-69ce-11e8-8baa-5210a91bda11.png)

**Comment by mtanda** [comment]
> When specifying multiple dimensions when calling the aws cli, multiple parameters have to be specified (no surrounding quotation marks or comma in between).

It is one of the trap of CloudWatch. Specify all dimension, you may get graph.

**Comment by HSkogmo** [comment]
@mtanda You the real MVP! My lizard brain must have just assumed that I was able to use any of the identifiers that were added, and it didn't occur to me to be that explicit and specify all of them.

Specifying InstanceId, ImageId and the InstanceType for Dimensions made the graphs appear. It is indeed a trap that CloudWatch's config wizard leads you into; it suggests you add multiple dimensions by default. If you were to modify the CloudWatch agent config to only add InstanceId as a dimension for the metrics, then I think the expected behaviour when only selecting a single dimension in Grafana would work.

Thanks again, I learned something new today :D

**Comment by mtanda** [comment]
I think this is a UI issue of query editor. So feel sorry about it...

**Comment by mtanda** [comment]
I'll make a PR to improve UI.

https://github.com/grafana/grafana/compare/master...mtanda:cw_metrics_confirm?expand=1

**Comment by alexsabau86** [comment]
I can confirm that all custom metrics from cloudwatch are working now in grafana. One must specify all dimensions that are present in the cloudwatch dashboard for a given metric.

**Comment by squib-zz** [comment]
Oddly, I'm still seeing this issue even when specifying all dimensions. I am able to see the metrics via the CLI. Any Ideas?

**Comment by sunker** [comment]
Closing this since I cannot reproduce it.

**Comment by pvpkiranbo1** [comment]
> For anyone landing here, uncheck `Match exact`:
> 
> ![image](https://user-images.githubusercontent.com/9471861/121550888-8621fc00-c9e5-11eb-9f63-6c4b88200904.png)

This saved me my day. Thanks a lot
