### ISSUE TITLE
Dashboards: "Query error: -1 Request was aborted" when an auto interval variable is involved

### ISSUE THREAD

**Issue by lilydjwg** [grafana/grafana#99057]
### What happened?

With an auto interval variable involved, when a refresh is ongoing, the graph disappears and a red icon appears at the left top of graph, tooltip says "Query error: -1 Request was aborted".

This happens with the Graphite source and I didn't test other sources.

### What did you expect to happen?

No error. Graph updates when refresh finishes and doesn't disappear before that.

### Did this work before?

grafana 11.0.0 doesn't have this issue

### How do we reproduce it?

1. Goto https://play.grafana.org/d/000000011/graphite-carbon-metrics
2. Add an interval variable with auto option (e.g. named `i`)
3. Change A series's query to `alias(summarize(carbon.agents.*.updateOperations, '$i', 'sum', false), 'Updates')`
4. Change the interval value to "Auto"
5. Press "Refresh"
6. Before the refresh finishes, the graph disappears and a red icon appears at the left top of graph, tooltip says "Query error: -1 Request was aborted". 
<details>
<summary>Devtools console error message</summary>

```
12:30:47.761 runRequest.catchError 
Object { type: "cancelled", cancelled: true, data: null, status: -1, statusText: "Request was aborted", config: {…} }
​
cancelled: true
​
config: Object { method: "POST", url: "api/datasources/proxy/uid/000000001/render", data: "target=alias(summarize(carbon.agents.*.updateOperations%2C%20'5min'%2C%20'sum'%2C%20false)%2C%20'Updates')&target=alias(sumSeries(carbon.agents.*.metricsReceived)%2C%20'Metrics%20Received')&target=alias(sumSeries(carbon.agents.*.committedPoints)%2C%20'Committed%20Points')&target=alias(sumSeries(carbon.agents.*.pointsPerUpdate)%2C%20'Points%20Per%20Update')&target=alias(averageSeries(carbon.agents.*.cpuUsage)%2C%20'CPU')&target=alias(sumSeries(carbon.agents.*.creates)%2C%20'Creates')&from=1736991046&until=1737001848&format=json&maxDataPoints=1198", … }
​
data: null
​
message: "Query error: -1 Request was aborted"
​
status: -1
​
statusText: "Request was aborted"
​
type: "cancelled"
​
<prototype>: Object { … }
instrumentation.js:30:49
    S instrumentation.js:30
    t instrumentation.js:30
    e instrumentation.js:23
    H runRequest.ts:167
    RxJS 27
    internalFetch backend_srv.ts:147
    Ae ResponseQueue.ts:32
    RxJS 6
    add ResponseQueue.ts:37
    De FetchQueueWorker.ts:56
    RxJS 21
    publishUpdate FetchQueue.ts:76
    ae FetchQueue.ts:55
    RxJS 6
    add FetchQueue.ts:59
    fetch backend_srv.ts:132
    RxJS 59
    ts registerQueryWithController.js:17
    RxJS 4
    runWithTimeRange SceneQueryRunner.js:313
```
</details>

### Environment (with versions)?

Grafana: 11.4.0
OS: Arch Linux
Browser: Firefox 136 or Google Chrome 131

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Graphite

**Comment by aangelisc** [comment]
Hi @lilydjwg, I'm going to close this out as I've attempted reproduction and this is fixed in Play following the steps that you've shared. Thanks!

**Comment by lilydjwg** [comment]
I can still reproduce this issue. The previous reproduction doesn't work as I can't add variables any more, but here's a new one:

1. Go to https://play.grafana.org/d/000000051/graphite-panel-repeats-copy?var-interval=$__auto&orgId=1&from=now-1h&to=now&timezone=browser&var-app=backend&var-app=fakesite&var-server=backend_01&var-server=web_server_03
2. Change query to `summarize(movingAverage(groupByNode(apps.$app.$server.counters.requests.count, 2, 'sum'), 5), '$interval', 'sum', false)`
3. Click `Refresh`

**Comment by aangelisc** [comment]
Thank you for the reproduction @lilydjwg - reopening this as I can see the issue.
